- doc/whats_new.rst
- nilearn/datasets/atlas.py
- nilearn/datasets/tests/test_utils.py
- nilearn/datasets/utils.py
Only targets the description. 
Related to #1635 and #1489
> change dataset description from bytes to str

- doc/whats_new.rst
Fix wrong links in the change log, introduced in #3126
> [FIX] Fix links in whats_new

- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/tests/test_matrix_plotting.py
This PR proposes to:
- refactor the code of the function `plot_matrix` which is too long with a hard-to-follow control flow.
- add more tests for `plot_matrix`
- refactor old test function for `plot_matrix` into multiple smaller tests
- improve the docstrings of the functions in the file `matrix_plotting.py`.
- adjust a little bit the space for the colorbar to avoid having the colorbar too close to the matrix (see a few examples like [this one](https://nilearn.github.io/auto_examples/03_connectivity/plot_signal_extraction.html#sphx-glr-auto-examples-03-connectivity-plot-signal-extraction-py))
> [ENH] Refactor `plot_matrix`

- doc/connectivity/parcellating.rst
- doc/modules/reference.rst
- doc/whats_new.rst
- examples/03_connectivity/plot_data_driven_parcellations.py
- nilearn/regions/__init__.py
- nilearn/regions/hierarchical_kmeans_clustering.py
- nilearn/regions/parcellations.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- nilearn/regions/tests/test_parcellations.py
Here is a pull-request  to include Hierarchical KMeans algorithm as an option in Parcellations object as discussed in #2134 .
The code is behaving as intended, the tests I added are passing. I tried to include this in one example and the user documentation, feedbacks are welcome !
> [MRG][ENH] Include Hierarchical KMeans in regions.Parcellations

- .github/workflows/testing.yml
- README.rst
- build_tools/github/dependencies.sh
Following #3143 this PR adds tests for minimum dependencies WITH min version of Matplotlib.
> [INFRA] Add tests min requirements with Matplotlib

- doc/decoding/decoding_intro.rst
Changed image labels to correspond with the images (could alternatively show images of faces and cats to match the original labels).
Closes #3154
> Fix image labels

- nilearn/image/image.py
Closes #3161  .
- Slightly modify wording of new_img_like docstring
> Adds a minor update to new_img_like docstring

- doc/changes/latest.rst
- nilearn/datasets/func.py
- nilearn/datasets/tests/test_func.py
> [FIX] Fix `fetch_abide_pcp`

- azure-pipelines.yml
> [MAINT] Bump python versions in azure pipelines

- .github/pull_request_template.md
- .github/workflows/auto-comment.yml
- doc/glossary.rst
- examples/02_decoding/plot_haxby_anova_svm.py
- nilearn/_utils/exceptions.py
- nilearn/_utils/niimg.py
- nilearn/_utils/niimg_conversions.py
- nilearn/masking.py
- nilearn/plotting/html_surface.py
> [DOC] Fix documentation links

- doc/building_blocks/manual_pipeline.rst
- examples/02_decoding/plot_haxby_full_analysis.py
- examples/02_decoding/plot_haxby_multiclass.py
- examples/02_decoding/plot_haxby_searchlight.py
- examples/02_decoding/plot_miyawaki_encoding.py
- examples/02_decoding/plot_miyawaki_reconstruction.py
- examples/02_decoding/plot_oasis_vbm.py
- examples/03_connectivity/plot_atlas_comparison.py
- examples/03_connectivity/plot_group_level_connectivity.py
- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_multi_subject_connectome.py
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
- examples/03_connectivity/plot_seed_to_voxel_correlation.py
- examples/03_connectivity/plot_signal_extraction.py
- examples/03_connectivity/plot_sphere_based_connectome.py
- examples/04_glm_first_level/plot_adhd_dmn.py
- examples/04_glm_first_level/plot_predictions_residuals.py
- examples/06_manipulating_images/plot_mask_computation.py
- examples/06_manipulating_images/plot_nifti_labels_simple.py
- examples/06_manipulating_images/plot_nifti_simple.py
- examples/06_manipulating_images/plot_roi_extraction.py
- examples/07_advanced/plot_advanced_decoding_scikit.py
- examples/07_advanced/plot_age_group_prediction_cross_val.py
- examples/07_advanced/plot_beta_series.py
- examples/07_advanced/plot_haxby_mass_univariate.py
- examples/07_advanced/plot_ica_neurovault.py
- examples/07_advanced/plot_ica_resting_state.py
- examples/07_advanced/plot_localizer_mass_univariate_methods.py
- examples/07_advanced/plot_localizer_simple_analysis.py
- examples/masker_note.rst
> [DOC] Add maskers note in examples

- doc/changes/0.9.1.rst
- doc/changes/whats_new.rst
- doc/themes/nilearn/layout.html
- nilearn/version.py
> Release `0.9.1`

- CONTRIBUTING.rst
Closes #1769.
- Recommend writing short, testable functions.
- Recommend against reorganizing existing functions for the sake of style.
- Point to test-driven development in testing section.
> [DOC] Add note about function size/scope to contributing guidelines

- examples/05_glm_second_level/plot_oasis.py
Closes #2393. I'm not sure if this merits a whatsnew entry, but I can add one if it does.
- Fix threshold description in `plot_oasis`.
- Improve formatting throughout `plot_oasis`.
> [DOC] Improve plot_oasis formatting and fix typo

- nilearn/decoding/tests/test_decoder.py
> [Fix] Fix test decoder

- doc/changes/latest.rst
- nilearn/datasets/atlas.py
- nilearn/datasets/func.py
- nilearn/interfaces/bids/glm.py
> [DOC] Fix doc building

- .github/workflows/testing.yml
- build_tools/github/dependencies.sh
- build_tools/github/install.sh
- nilearn/image/image.py
- nilearn/image/tests/test_resampling.py
- nilearn/maskers/nifti_labels_masker.py
- nilearn/regions/tests/test_signal_extraction.py
Redo of #2224, which seems to have gotten lost with the transition away from Travis.
> CI: Test pre-release versions of dependencies

- doc/changes/latest.rst
- doc/changes/names.rst
- nilearn/datasets/neurovault.py
- nilearn/datasets/tests/test_neurovault.py
Closes #3282
- change http into https in URL in neurovault.py
> [FIX] change http into https in neurovault URL

- nilearn/glm/second_level/second_level.py
- nilearn/reporting/html_report.py
Fixes documentation issues introduced in #3030 currently crashing the documentation build on main.
> [DOC] Fix documentation building

- doc/changes/latest.rst
- doc/changes/names.rst
- nilearn/glm/first_level/hemodynamic_models.py
Closes #3295.
Related to #2981.
- Fix the usage of `scipy.stats.gamma.pdf`
> [FIX] correct the usage of `scipy.stats.gamma.pdf`

- CONTRIBUTING.rst
> Quick fix for failed build after #3317 merge

- doc/decoding/frem.rst
- doc/decoding/searchlight.rst
- doc/decoding/space_net.rst
- doc/introduction.rst
- doc/references.bib
- examples/07_advanced/plot_beta_series.py
- nilearn/datasets/atlas.py
- nilearn/datasets/func.py
- nilearn/datasets/neurovault.py
- nilearn/datasets/struct.py
- nilearn/decoding/decoder.py
- nilearn/glm/regression.py
- nilearn/glm/second_level/second_level.py
- nilearn/glm/thresholding.py
- nilearn/image/image.py
- nilearn/interfaces/fmriprep/load_confounds.py
- nilearn/interfaces/fmriprep/load_confounds_strategy.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/plotting/img_plotting.py
- nilearn/regions/region_extractor.py
- nilearn/signal.py
Closes #3304.
- Alphabetize `references.bib`
> [MAINT] Put references in alphabetical order

- nilearn/maskers/multi_nifti_masker.py
> Quick fix for doc build fail after #3311 merge

- nilearn/surface/surface.py
- no more "experimental" warning
- add minimal example
- add advice to use depth strategy if possible
> update vol_to_surf docstring

- doc/manipulating_images/input_output.rst
- nilearn/_utils/__init__.py
- nilearn/_utils/cache_mixin.py
- nilearn/_utils/docs.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
- nilearn/image/image.py
- nilearn/image/resampling.py
- nilearn/maskers/base_masker.py
- nilearn/regions/parcellations.py
- nilearn/signal.py
- nilearn/surface/surface.py
- nilearn/tests/test_niimg.py
I realized after merging #3300 that I can improve some things and that I may have missed a couple of things.
- Expose `stringify_path` in `_utils.__init__`
- Missed one case where function should be used
- Docstrings were a bit inconsistent
- Failed to address https://github.com/nilearn/nilearn/pull/3300#discussion_r915643466
> [MAINT] Follow-up to pathlib support in #3300

- nilearn/signal.py
> Quick fix doc build fail for #3327

- doc/changes/latest.rst
- doc/changes/names.rst
- examples/04_glm_first_level/plot_adhd_dmn.py
Closes #3336.
- Changed a spelling error in the documentation in https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_adhd_dmn.html#sphx-glr-auto-examples-04-glm-first-level-plot-adhd-dmn-py
- I changed AHDH to ADHD
> [DOC] Changed AHDH to ADHD

- Makefile
- nilearn/_utils/docs.py
- nilearn/interfaces/fmriprep/load_confounds_strategy.py
- nilearn/plotting/data/html/stat_map_template.html
> [MAINT] Fix spelling errors causing codespell to fail

- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/html_surface.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_img_plotting/test_plot_markers.py
- nilearn/plotting/tests/test_surf_plotting.py
See https://matplotlib.org/devdocs/api/next_api_changes/deprecations/23668-TC.html
This PR should fix the test with Python 3.10 and pre-release deps.
> [MAINT] Fix Matplotlib Pending deprecations

- doc/changes/names.rst
- doc/glm/first_level_model.rst
- doc/glm/glm_intro.rst
- examples/03_connectivity/plot_compare_decomposition.py
- examples/07_advanced/plot_surface_bids_analysis.py
- nilearn/interfaces/fmriprep/tests/test_load_confounds_scrub.py
- nilearn/plotting/img_plotting.py
- Fixed some user-facing and non-user-facing typos
> [MAINT] fix various typos

- .github/workflows/codespell.yml
- .github/workflows/pep8.yml
- .github/workflows/testing.yml
- `python-version` should be a string, not a float
- update GitHub Actions to latest versions
- update Python to latest 3.10 in PEP8 checks
> [MAINT] Update CI workflow

- doc/introduction.rst
Closes #3376.
We have moved on from requirements files to `setup.cfg` and the documentation here needs an update!
> [FIX] update developer installation instruction

- nilearn/plotting/find_cuts.py
> [Fix]: inaccurate docstring of find_probabilistic_atlas_cut_coords

- nilearn/maskers/multi_nifti_labels_masker.py
- nilearn/maskers/multi_nifti_maps_masker.py
Partially addresses #3384 and resolves scikit-learn compatibility error: https://app.circleci.com/pipelines/github/nilearn/nilearn/5017/workflows/0899df21-383c-45ae-807a-f31f734907e8/jobs/10386
> [FIX] Write out full signature for multi-subject maskers

- doc/changes/0.9.0.rst
- nilearn/maskers/multi_nifti_labels_masker.py
- nilearn/maskers/multi_nifti_maps_masker.py
See Sphinx warnings under Build docs step here: https://github.com/nilearn/nilearn/actions/runs/3361958806/jobs/5573039460
> [FIX] Resolve Sphinx warnings causing full build to fail

- doc/sphinxext/gh_substitutions.py
- examples/02_decoding/plot_oasis_vbm.py
- examples/04_glm_first_level/plot_hrf.py
- nilearn/_utils/data_gen.py
- nilearn/connectome/connectivity_matrices.py
- nilearn/datasets/func.py
- nilearn/datasets/neurovault.py
- nilearn/datasets/struct.py
- nilearn/datasets/utils.py
- nilearn/decoding/space_net.py
- nilearn/externals/tempita/__init__.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/tests/test_dmtx.py
- nilearn/interfaces/bids/query.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/find_cuts.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
* [FURB108]: Use `x in (y, z)` instead of `x == y or x == z`
* [FURB124]: Use `x == y == z` instead of `x == y and x == z`
* [FURB110]: Use `x or y` instead of `x if x else y`
* [FURB105]: Use `print()` instead of `print("")`
* [FURB125]: Return is redundant here
* [FURB123]: Replace `float(x)` with `x`
* [FURB111]: Use `f` instead of `lambda x: f(x)`
* [FURB121]: Replace `isinstance(x, y) or isinstance(x, z)` with `isinstance(x, (y, z))`
> [MAINT] Apply refurb suggestions

- doc/changes/latest.rst
- nilearn/glm/__init__.py
> [MAINT] Remove warning that `nilearn.glm` module is experimental

- .github/ISSUE_TEMPLATE/bug_report.md
Just thought this is an important detail that should be here in addition to the contribution guide.
- Prompt people to submit a minimal runnable example with nilearn data.
> [MAINT] add reminder in bug report template

- doc/changes/latest.rst
- doc/maintenance.rst
Closes #3381 .
Adds additional instructions to https://nilearn.github.io/stable/maintenance.html#build-and-deploy-the-documentation to make sure that whoever is doing the release will have the dependencies to correctly render LaTeX
> [MAINT] Add instructions to release section of the maintenance page

- doc/changes/latest.rst
- nilearn/_utils/glm.py
- nilearn/signal.py
- nilearn/tests/test_signal.py
Closes #3204.
- Allow binary mask for `sample_mask`
- Change the doc string related to sample_mask to reflect the change
> [EHN] allow binary mask passed to `sample_mask`

- .github/workflows/auto-comment.yml
- CONTRIBUTING.rst
- doc/changes/latest.rst
- doc/changes/names.rst
Closes #3218 .
- Addition of a changelog/what's new line to the PR template
> [DOC]  Add "add changelog entry" to auto-comment PR template #3218 

- doc/changes/latest.rst
See https://github.com/nilearn/nilearn/actions/runs/3684801816/jobs/6234973880
> [DOC] Quick fix for failing doc build

- doc/changes/latest.rst
- doc/changes/names.rst
- nilearn/reporting/glm_reporter.py
- nilearn/reporting/tests/test_glm_reporter.py
Closes #3442 .
- add `cut_coords` parameter in `reporting.make_glm_report` method
- adapt pytest accordingly
I could not build the updated Sphinx documentation, so the docstrings changes should be carefully reviewed
> [ENH] add `cut_coords` parameter in `reporting.make_glm_report` method

- doc/changes/latest.rst
- nilearn/decomposition/tests/test_canica.py
Closes #3441 .
- Add and tweak noise parameter for making canica test data
> [FIX] Resolve CanICA test failures

- .github/workflows/README.md
- .github/workflows/pep8.yml
- .github/workflows/testing.yml
Closes #3448.
Remove deprecated job that is now automatically supported by GitHub Actions
> [INFRA] Remove deprecated check_skip job

- CONTRIBUTING.rst
- README.rst
- doc/introduction.rst
Closes # .
- Change office hours name
- Change office hours day
> [DOC] Change office hours name to "drop-in" hours

- CONTRIBUTING.rst
Closes #3468 .
- Clarify that any virtual environment tool can be used
- Add example of using Python module venv
> [DOC] Clarify recommendation for using a virtual environment

- doc/changes/latest.rst
- nilearn/image/image.py
Closes #2048
1. Clarify that voxels with values
- inferior to threshold are set to 0
- supeerior or equal to threshold are kept as is
2. Explain how percentiles are computed.
> [DOC] update doc threshold image

- .github/dependabot.yml
Closes #3488 .
- add a dependabot.yml file to make sure all github actions use their latest version
Dependabot opens PR that look like this:
https://github.com/bids-standard/bids-matlab/pull/511
> [INFRA] add dependabot to update github actions

- doc/changes/latest.rst
- nilearn/glm/second_level/second_level.py
- nilearn/glm/tests/test_second_level.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/mass_univariate/tests/test_permuted_least_squares.py
This PR addresses #3464 and adds covariates to non-parametric inference.
Edit: and some other intercept-stuff, lol
> [FIX] Add covariates to non-parametric inference

- doc/changes/latest.rst
- doc/changes/names.rst
- examples/00_tutorials/plot_single_subject_single_run.py
- examples/04_glm_first_level/plot_bids_features.py
- examples/04_glm_first_level/plot_predictions_residuals.py
- nilearn/reporting/_get_clusters_table.py
- nilearn/reporting/tests/test_reporting.py
Closes #3476 
- Add label maps output to `get_clusters_tables`
> [ENH] Add label maps as output to `get_clusters_tables`

- .github/workflows/auto-comment.yml
- CONTRIBUTING.rst
Closes #3486
- this updates the PR checklist with links to the relevant sections of the contributing doc to point new contributors to the relevant sections
- adds a new heading for changelog in the contributing doc
> [DOC] update PR checklist with links

- .github/workflows/auto-comment.yml
- .github/workflows/update_precommit_hooks.yml
- .pre-commit-config.yaml
> checklist_dummy

- .github/codespell_ignore_words.txt
- .github/workflows/flake8.yml
- .pre-commit-config.yaml
- nilearn/decoding/__init__.py
- nilearn/decoding/decoder.py
- nilearn/decoding/fista.py
- nilearn/decoding/objective_functions.py
- nilearn/decoding/proximal_operators.py
- nilearn/decoding/searchlight.py
- nilearn/decoding/space_net.py
- nilearn/decoding/space_net_solvers.py
- nilearn/decoding/tests/simulate_graph_net_data.py
- nilearn/decoding/tests/test_decoder.py
- nilearn/decoding/tests/test_fista.py
- nilearn/decoding/tests/test_graph_net.py
- nilearn/decoding/tests/test_objective_functions.py
- nilearn/decoding/tests/test_operators.py
- nilearn/decoding/tests/test_same_api.py
- nilearn/decoding/tests/test_searchlight.py
- nilearn/decoding/tests/test_sklearn_compatibility.py
- nilearn/decoding/tests/test_space_net.py
- nilearn/decoding/tests/test_tv.py
- nilearn/decomposition/_base.py
- nilearn/decomposition/_multi_pca.py
- nilearn/decomposition/canica.py
- nilearn/decomposition/dict_learning.py
- pyproject.toml
Relates to #2528
- Set up pre-commit hooks to also work on the `nilearn/decoding` module
- Update config and GH worflows accordingly
- run `pre-commit run -a` and manually fix or silence errors
- convert some "old strings" to f-strings using flynt
- remove some lambdas (PEP8 E731)
- add some explicit line breaks in doc
- fixes some headings underline length in doc strings
> [INFRA] apply black, flake8, pyupgrade to `nilearn/decoding`

- .github/workflows/auto-comment.yml
Supersedes #3516
Fixes https://github.com/nilearn/nilearn/pull/3511#issuecomment-1431861110
- implement proper formatting of the PR checklist
- example: https://github.com/Remi-Gau/nilearn/pull/10#issuecomment-1433774511
> [FIX] Fix PR checklist  line skip

- README.rst
> [MAINT] Update package versions in README to be consistent with actual requirements

- nilearn/_utils/niimg.py
- nilearn/decoding/decoder.py
- nilearn/decomposition/_base.py
- nilearn/decomposition/_multi_pca.py
- nilearn/image/resampling.py
- nilearn/masking.py
- nilearn/plotting/img_plotting.py
- nilearn/reporting/glm_reporter.py
Closes #3526 
- replaces links to output/input html page (dead or otherwise) with a `:ref:` where possible
- replaces with just the active link in other places
> [DOC] replace dead links with ref or with valid one

- .github/workflows/testing.yml
Closes #3522 .
Add Python 3.11 to testing matrix and use with pre-release job
> [INFRA] Add Python `3.11` to GitHub Actions testing workflow

- nilearn/_utils/data_gen.py
- nilearn/_utils/ndimage.py
- nilearn/_utils/niimg.py
- nilearn/connectome/group_sparse_cov.py
- nilearn/datasets/func.py
- nilearn/datasets/neurovault.py
- nilearn/datasets/utils.py
- nilearn/image/image.py
- nilearn/image/resampling.py
- nilearn/interfaces/fmriprep/load_confounds.py
- nilearn/interfaces/fmriprep/load_confounds_strategy.py
- nilearn/masking.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/edge_detect.py
- nilearn/plotting/find_cuts.py
- nilearn/plotting/img_plotting.py
- nilearn/surface/surface.py
Closes #3507
- match section underline length to section name length
> [MAINT] Fix section underline length in docstrings

- examples/00_tutorials/plot_3d_and_4d_niimg.py
- examples/00_tutorials/plot_decoding_tutorial.py
- examples/00_tutorials/plot_nilearn_101.py
- examples/00_tutorials/plot_python_101.py
- examples/00_tutorials/plot_single_subject_single_run.py
- examples/01_plotting/plot_carpet.py
- examples/01_plotting/plot_demo_plotting.py
- examples/01_plotting/plot_haxby_masks.py
- apply pre-commit hooks to example/00_tutorials
- 'examples/00_tutorials/plot_3d_and_4d_niimg.py',
> [FMT] format example/00_tutorials

- examples/06_manipulating_images/plot_affine_transformation.py
- examples/06_manipulating_images/plot_compare_mean_image.py
- examples/06_manipulating_images/plot_extract_regions_labels_image.py
- examples/06_manipulating_images/plot_extract_rois_smith_atlas.py
- examples/06_manipulating_images/plot_extract_rois_statistical_maps.py
- examples/06_manipulating_images/plot_mask_computation.py
- examples/06_manipulating_images/plot_negate_image.py
- examples/06_manipulating_images/plot_nifti_labels_simple.py
- examples/06_manipulating_images/plot_nifti_simple.py
- examples/06_manipulating_images/plot_resample_to_template.py
- examples/06_manipulating_images/plot_roi_extraction.py
- examples/06_manipulating_images/plot_smooth_mean_image.py
- apply pre-commit hooks to example/06_manipulating_images
- 'examples/06_manipulating_images/plot_negate_image.py',
- 'examples/06_manipulating_images/plot_resample_to_template.py'
> [FMT] format example/06_manipulating_images

- examples/05_glm_second_level/plot_oasis.py
- examples/05_glm_second_level/plot_proportion_activated_voxels.py
- examples/05_glm_second_level/plot_second_level_association_test.py
- examples/05_glm_second_level/plot_second_level_design_matrix.py
- examples/05_glm_second_level/plot_second_level_one_sample_test.py
- examples/05_glm_second_level/plot_second_level_two_sample_test.py
- examples/05_glm_second_level/plot_thresholding.py
- apply pre-commit hooks to example/05_glm_second_level
> [FMT] format example/05_glm_second_level

- .gitignore
Closes none
Related to https://github.com/nilearn/nilearn/pull/3559#discussion_r1125734722
- organize main gitignore into sections
> [MAINT] reorganize gitignore

- examples/03_connectivity/plot_atlas_comparison.py
- examples/03_connectivity/plot_compare_decomposition.py
- examples/03_connectivity/plot_data_driven_parcellations.py
- examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
- examples/03_connectivity/plot_group_level_connectivity.py
- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_multi_subject_connectome.py
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
- examples/03_connectivity/plot_seed_to_voxel_correlation.py
- examples/03_connectivity/plot_signal_extraction.py
- examples/03_connectivity/plot_simulated_connectome.py
- examples/03_connectivity/plot_sphere_based_connectome.py
- apply pre-commit hooks to example/03_connectivity
- 'examples/03_connectivity/plot_group_level_connectivity.py',
> [FMT] format example/03_connectivity

- nilearn/decoding/tests/test_decoder.py
- nilearn/decoding/tests/test_searchlight.py
Relates to #3570
- refactor tests of the decoding module to use setup functions and parametrize
> [MAINT] simplify tests decoding

- nilearn/datasets/description/basc_multiscale_2015.rst
- nilearn/datasets/func.py
- nilearn/image/resampling.py
Fix spelling errors to green the Codespell job (failed in #3498)
> [FIX] Fix spelling errors

- .circleci/README.md
- .github/workflows/README.md
Closes #3543.
Hopefully this makes it a bit easier to understand our CI infrastructure.
> [INFRA] Improve documentation of GitHub Actions workflows

- .github/workflows/flake8.yml
- .github/workflows/isort.yml
- .pre-commit-config.yaml
- nilearn/mass_univariate/__init__.py
- nilearn/mass_univariate/_utils.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/mass_univariate/tests/test__utils.py
- nilearn/mass_univariate/tests/test_permuted_least_squares.py
- nilearn/mass_univariate/tests/utils.py
- pyproject.toml
- setup.cfg
- apply black and isort
- fix remaining flake8 issues
- remove dead code flagged by vulture
- apply some refactoring from sourcery
- fix f strings
> [MAINT] Format mass univariate module

- nilearn/_utils/docs.py
- nilearn/datasets/tests/test_func.py
- nilearn/decomposition/canica.py
- nilearn/decomposition/dict_learning.py
- nilearn/glm/tests/test_first_level.py
- nilearn/image/tests/test_image.py
- nilearn/mass_univariate/tests/utils.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_html_document.py
- nilearn/plotting/tests/test_matplotlib_backend.py
- nilearn/regions/tests/test_parcellations.py
- nilearn/regions/tests/test_signal_extraction.py
- nilearn/tests/test_signal.py
- nilearn/version.py
- setup.cfg
This is just to try to get ahead of potential failures and useful if we want to implement #3541
> [MAINT] Handle deprecations in dependencies that raise warnings in pre-release CI test

- .github/ISSUE_TEMPLATE/bug.yml
Relates to https://github.com/nilearn/nilearn/pull/3610#discussion_r1147401239
- add latest version to the github form
> [MAINT] add recent versions to github bug form

- nilearn/conftest.py
Closes #3611 
- [remove skip doctest items for old numpy](https://github.com/nilearn/nilearn/commit/f597f2c72d649b421953bebc8acb3cb94698f89e)
> [MAINT] remove skip doctest items for old numpy

- doc/changes/latest.rst
- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
Closes #3636 .
@Remi-Gau is the loop under `_check_input_as_nifti_images` supposed to go in the if statement?
Might also warrant improving testing for new private second level model functions and also add docstrings
> [FIX] Fix `second_level_input` check function

- .github/workflows/flake8.yml
- .github/workflows/isort.yml
- .gitignore
- .pre-commit-config.yaml
- nilearn/input_data/__init__.py
- nilearn/input_data/base_masker.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/nifti_spheres_masker.py
- pyproject.toml
> [MAINT] Format nilearn/input_data

- AUTHORS.rst
> [MAINT] Add Remi to authors

- .github/workflows/flake8.yml
- .github/workflows/isort.yml
- nilearn/maskers/__init__.py
- nilearn/maskers/_masker_validation.py
- nilearn/maskers/base_masker.py
- nilearn/maskers/multi_nifti_labels_masker.py
- nilearn/maskers/multi_nifti_maps_masker.py
- nilearn/maskers/multi_nifti_masker.py
- nilearn/maskers/nifti_labels_masker.py
- nilearn/maskers/nifti_maps_masker.py
- nilearn/maskers/nifti_masker.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/maskers/tests/test_base_masker.py
- nilearn/maskers/tests/test_input_data.py
- nilearn/maskers/tests/test_masker_validation.py
- nilearn/maskers/tests/test_multi_nifti_labels_masker.py
- nilearn/maskers/tests/test_multi_nifti_maps_masker.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- nilearn/maskers/tests/test_nifti_maps_masker.py
- nilearn/maskers/tests/test_nifti_masker.py
- nilearn/maskers/tests/test_nifti_spheres_masker.py
- setup.cfg
> [MAINT] Format nilearn/maskers: apply isort and fix flake8 errors

- .github/workflows/flake8.yml
- .github/workflows/isort.yml
- .gitignore
- .pre-commit-config.yaml
- nilearn/glm/__init__.py
- nilearn/glm/_base.py
- nilearn/glm/contrasts.py
- nilearn/glm/first_level/__init__.py
- nilearn/glm/first_level/design_matrix.py
- nilearn/glm/first_level/experimental_paradigm.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/first_level/hemodynamic_models.py
- nilearn/glm/model.py
- nilearn/glm/regression.py
- nilearn/glm/second_level/__init__.py
- nilearn/glm/second_level/second_level.py
- nilearn/glm/tests/test_check_events_file_uses_tab_separators.py
- nilearn/glm/tests/test_contrasts.py
- nilearn/glm/tests/test_dmtx.py
- nilearn/glm/tests/test_first_level.py
- nilearn/glm/tests/test_hemodynamic_models.py
- nilearn/glm/tests/test_model.py
- nilearn/glm/tests/test_paradigm.py
- nilearn/glm/tests/test_regression.py
- nilearn/glm/tests/test_second_level.py
- nilearn/glm/tests/test_thresholding.py
- nilearn/glm/tests/test_utils.py
- nilearn/glm/thresholding.py
- setup.cfg
> [MAINT] Format nilearn/glm: apply isort and fix flake8 errors

- README.rst
Closes #3679  .
Updates made on the Discord, pinned issue, neurostars, and the arewemeetingyet link posted to twitter and mastodon.
Let me know if there are other places I missed.
> [MAINT] Change drop-in hour link to Jitsi

- nilearn/interfaces/bids/query.py
- nilearn/interfaces/fmriprep/load_confounds_compcor.py
- nilearn/interfaces/fmriprep/load_confounds_components.py
-   apply sourcery refactoring suggestions
-   use f strings everywhere
> [MAINT] refactor nilearn/interfaces (sourcery, f-strings)

- nilearn/surface/data/README.md
- nilearn/surface/surface.py
- nilearn/surface/tests/test_surface.py
- apply sourcery refactoring suggestions
- use f strings everywhere
> [MAINT] refactor nilearn/surface (sourcery, f-strings)

- nilearn/_utils/docs.py
Closes #3622 
- sort entries in docs.py in alphabetical order
> [MAINT] sort entries in docs.py in alphabetical order

- nilearn/_utils/numpy_conversions.py
Closes #3619
- convert "homemade" test in doc string to a proper doc test
> [DOC] Add doctest to as_ndarrays in numpy_conversions.py

- nilearn/datasets/tests/test_neurovault.py
> [MAINT] Format datasets tests func neurovault

- nilearn/datasets/tests/test_atlas.py
> [MAINT] Format datasets tests atlas

- nilearn/datasets/atlas.py
> [MAINT] Format datasets/atlas.py

- nilearn/datasets/tests/test_mocking_autoused.py
- nilearn/datasets/tests/test_struct.py
- nilearn/datasets/tests/test_testing.py
- nilearn/datasets/tests/test_utils.py
> [MAINT] Format datasets tests

- nilearn/reporting/glm_reporter.py
Closes #3620 
- remove workaround to avoid an old pandas bug that existed in a version of pandas that we no longer support
> [MAINT] remove comment relative to pandas precision bug

- nilearn/datasets/neurovault.py
> [MAINT] Format datasets/neurovault.py

- nilearn/datasets/func.py
> [MAINT] Format datasets/func.py

- nilearn/_utils/tests/test_cache_mixin.py
Relates to #3660
- add missing __init__.py in tests and tests/data folders
> [MAINT] add missing __init__.py in tests folders

- nilearn/datasets/tests/test_func.py
> [MAINT] Format datasets tests func

- nilearn/plotting/img_plotting.py
See error on main https://github.com/nilearn/nilearn/actions/runs/5071173662/jobs/9107231460
> [DOC] Fix broken doc build

- examples/04_glm_first_level/plot_adhd_dmn.py
Closes #3737 .
- add a plot of the signal extracted from the seed region
- add more explanation about what the example will show
> add more info to adhd example

- examples/01_plotting/plot_overlay.py
Relates to #3728
- fix rst heading
> [DOC] fix duplicate entry in examples dropdown

- .flake8
- examples/02_decoding/plot_oasis_vbm.py
- examples/02_decoding/plot_simulated_data.py
- examples/05_glm_second_level/plot_oasis.py
- examples/05_glm_second_level/plot_second_level_association_test.py
- examples/07_advanced/plot_haxby_mass_univariate.py
- examples/07_advanced/plot_ica_neurovault.py
- examples/07_advanced/plot_localizer_mass_univariate_methods.py
- examples/07_advanced/plot_localizer_simple_analysis.py
- examples/07_advanced/plot_neurovault_meta_analysis.py
Relates to #3728 
- remove mention of license in examples
- add authors by using rst comments
---
> [DOC] Remove license and hide authors in examples

- nilearn/plotting/cm.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/displays/_projectors.py
- nilearn/plotting/find_cuts.py
- nilearn/plotting/glass_brain.py
- nilearn/plotting/glass_brain_files/svg_to_json_converter.py
- nilearn/plotting/html_document.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/html_surface.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_find_cuts.py
- nilearn/plotting/tests/test_html_stat_map.py
Relates to #2528
- use fstrings in nilearn/plotting 
- search and replace `%` and `.format()` by fstrings
> [MAINT] refactor nilearn/plotting (f-strings)

- nilearn/plotting/tests/test_matrix_plotting.py
> [FIX] Fix test assertion to not always be true

- examples/00_tutorials/plot_single_subject_single_run.py
Relates to #3728 .
Better rendering of first output in example https://nilearn.github.io/dev/auto_examples/00_tutorials/plot_single_subject_single_run.html
> [DOC] Better print output in example output block 

- .pre-commit-config.yaml
- nilearn/plotting/cm.py
- nilearn/plotting/edge_detect.py
- nilearn/plotting/glass_brain_files/plot_align_svg.py
- nilearn/plotting/glass_brain_files/svg_to_json_converter.py
- nilearn/plotting/html_document.py
- nilearn/plotting/rm_file.py
- nilearn/plotting/tests/test_cm.py
- nilearn/plotting/tests/test_html_connectome.py
- nilearn/plotting/tests/test_html_document.py
- nilearn/plotting/tests/test_img_plotting/test_plot_anat.py
- nilearn/plotting/tests/test_img_plotting/test_plot_carpet.py
- nilearn/plotting/tests/test_img_plotting/test_plot_img.py
- nilearn/plotting/tests/test_img_plotting/test_plot_img_comparisons.py
- nilearn/plotting/tests/test_img_plotting/test_plot_prob_atlas.py
- nilearn/plotting/tests/test_img_plotting/test_plot_roi.py
- pyproject.toml
- update configs to start including nilearn/plotting
- apply black
> [FMT] apply black to plotting - part 1

- .pre-commit-config.yaml
- nilearn/_utils/tests/test_helpers.py
- nilearn/_utils/tests/test_niimg_conversions.py
- nilearn/conftest.py
- nilearn/datasets/atlas.py
- nilearn/image/tests/test_image.py
- nilearn/interfaces/tests/test_bids.py
- nilearn/plotting/find_cuts.py
- nilearn/plotting/html_connectome.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/tests/test_js_plotting_utils.py
- nilearn/plotting/tests/test_matplotlib_backend.py
- nilearn/plotting/tests/test_matrix_plotting.py
- pyproject.toml
- update configs to more from nilearn/plotting
- apply black
> [FMT] apply black to plotting - part 2

- .github/ISSUE_TEMPLATE/bug.yml
> [MAINT] Set nilearn version input in bug issue template to text area

- .pre-commit-config.yaml
- nilearn/maskers/nifti_maps_masker.py
- nilearn/plotting/tests/test_img_plotting/test_plot_connectome.py
- nilearn/plotting/tests/test_img_plotting/test_plot_markers.py
- nilearn/plotting/tests/test_img_plotting/test_plot_stat_map.py
- pyproject.toml
- update configs to format more from nilearn/plotting
- apply black
> [FMT] apply black to plotting - part 4

- .pre-commit-config.yaml
- nilearn/glm/tests/test_second_level.py
- nilearn/plotting/tests/test_img_plotting/test_img_plotting.py
- nilearn/plotting/tests/test_img_plotting/test_plot_glass_brain.py
- pyproject.toml
- update configs to format more from nilearn/plotting and to glm/tests/tests_second_level
- apply black
> [FMT] apply black

- nilearn/image/resampling.py
- nilearn/plotting/matrix_plotting.py
Closes #3829 
- remove old check for unsupported scipy versions
> [MAINT] remove old check for unsupported scipy versions

- CONTRIBUTING.rst
Closes #3850 
- add instruction on how to add upstream remote and fetch all the tags
> [DOC] update doc to mention how get all the tags from upstream to get the proper version displayed

- CITATION.cff
- doc/changes/latest.rst
- nilearn/plotting/html_surface.py
- nilearn/plotting/tests/test_html_surface.py
- nilearn/surface/surface.py
Closes #3500. Renamed files and also changed comment in one example, didn't seem to appear elsewhere.
- Rename `one_mesh_info` and `full_brain_info`
- Add first-time contributor info
> [REF] Rename html surface func to make them private

- nilearn/glm/tests/test_first_level.py
- nilearn/maskers/tests/test_masker_validation.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_html_surface.py
- nilearn/reporting/glm_reporter.py
fix flake8 errors appearng with the latest flake8 version
> [MAINT] fix flake8

- .github/pull_request_template.md
Closes None
more of cosmetic change but allows issue number AND name to be rendered directly when viewing the PR top message
also removes a space before the # that I am tired of deleting for every PR
> [INFRA] Update pull_request_template.md

- pyproject.toml
- Closes none
Required to help with linting / formatting locally
> [MAINT] add missing dev dependencies for linting

- doc/changes/0.2.6.rst
- doc/changes/0.3.1.rst
- doc/changes/0.4.0.rst
- doc/changes/0.5.0.rst
- doc/changes/0.6.2.rst
- doc/changes/0.7.0.rst
- doc/changes/0.8.0.rst
- Relates to https://github.com/nilearn/nilearn/issues/3578
> [DOC] add badge for deprecation

- nilearn/glm/second_level/second_level.py
- nilearn/glm/tests/test_second_level.py
- Closes #3298
- add test
- implement checks
> [ENH] check affine and shape of first level models when passed at the second level 

- nilearn/datasets/func.py
- nilearn/datasets/struct.py
> [MAINT] extract dataset ids and file lists

- nilearn/reporting/glm_reporter.py
- nilearn/reporting/tests/test_glm_reporter.py
- relates to https://github.com/nilearn/nilearn/issues/3726
- extracted from #3891
- ~~blocked by https://github.com/nilearn/nilearn/pull/3892&~~
> [MAINT] use tmp_path in glm reporter

- pyproject.toml
- relates to #3916 
- pin sphinx version to < 7.2 that does not play nice with sphinx gallery (waiting for a release)
> [FIX][DOC][MAINT] pin sphinx version

- .pre-commit-config.yaml
- nilearn/_utils/docs.py
- pyproject.toml
- Closes none
- as far as I can tell _utils.docs.py is not involved in any PR at the moment so we can let black loose on her.
> [MAINT] apply black to utils.doc

- .pre-commit-config.yaml
- examples/01_plotting/plot_demo_more_plotting.py
- examples/01_plotting/plot_demo_plotting.py
- nilearn/_utils/tests/test_data_gen.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/glass_brain.py
- nilearn/plotting/tests/test_html_stat_map.py
- pyproject.toml
> [MAINT] apply black and pre-commit hooks to files not in PRs

- .pre-commit-config.yaml
- nilearn/tests/test_masking.py
- pyproject.toml
> [MAINT] apply black to nilearn.masking.py

- .pre-commit-config.yaml
- nilearn/tests/test_signal.py
- pyproject.toml
> [MAINT] apply black to tests nilean.signal.py

- pyproject.toml
- Closes #3849
- Remove mkl doc dependency
-
> [MAINT] Remove MKL dependency for the documentation build dependencies

- .pre-commit-config.yaml
- nilearn/glm/first_level/first_level.py
- pyproject.toml
> [MAINT] apply black to glm.first_level.first_level

- nilearn/glm/tests/_utils.py
- nilearn/glm/tests/test_dmtx.py
- nilearn/glm/tests/test_paradigm.py
- Closes https://github.com/nilearn/nilearn/issues/3938
- refactor tests for design matrix and experimental paradigm
> [MAINT] refactor design matrix tests

- doc/changes/latest.rst
- examples/01_plotting/plot_prob_atlas.py
> [DOC] Plot only a few examples of probabilistic atlases

- .flake8
> [MAINT] simplify flake8 config

- doc/building_blocks/manual_pipeline.rst
- examples/00_tutorials/plot_3d_and_4d_niimg.py
- examples/00_tutorials/plot_decoding_tutorial.py
- examples/00_tutorials/plot_nilearn_101.py
- examples/00_tutorials/plot_python_101.py
- examples/00_tutorials/plot_single_subject_single_run.py
> [DOC] Use code cell syntax for splitting blocks in 00_tutorial examples

- doc/changes/latest.rst
- examples/00_tutorials/plot_3d_and_4d_niimg.py
- examples/01_plotting/plot_multiscale_parcellations.py
- examples/01_plotting/plot_prob_atlas.py
- examples/06_manipulating_images/plot_extract_rois_smith_atlas.py
- nilearn/datasets/atlas.py
- nilearn/datasets/tests/test_atlas.py
> [FIX] Use `maps` key for API consistency and improve deprecation for new behavior of some atlas fetchers

- nilearn/plotting/find_cuts.py
> [MAINT] Deal with Numpy `alltrue` deprecation

- doc/conf.py
> [DOC] Workaround for sphinx reference target not found for scikit-learn 1.31

- .github/workflows/black.yml
- pyproject.toml
- Closes none but mentioned in https://github.com/nilearn/nilearn/pull/3203#issuecomment-1732654867
- use --diff when running black in CI to show what changes would have been made
> [MAINT] Make black CI more verbose

- .pre-commit-config.yaml
- CONTRIBUTING.rst
- doc/building_blocks/manual_pipeline.rst
- doc/changes/0.10.1.rst
- doc/changes/0.7.0.rst
- doc/changes/0.8.0.rst
- doc/changes/0.8.1.rst
- doc/changes/0.9.1.rst
- doc/changes/0.9.2.rst
- doc/changes/latest.rst
- doc/connectivity/connectome_extraction.rst
- doc/connectivity/functional_connectomes.rst
- doc/connectivity/parcellating.rst
- doc/decoding/decoding_intro.rst
- doc/decoding/estimator_choice.rst
- doc/decoding/going_further.rst
- doc/decoding/searchlight.rst
- doc/decoding/space_net.rst
- doc/developers/group_sparse_covariance.rst
- doc/glm/first_level_model.rst
- doc/glm/glm_intro.rst
- doc/glm/second_level_model.rst
- doc/maintenance.rst
- doc/manipulating_images/input_output.rst
- doc/manipulating_images/manipulating_images.rst
- doc/manipulating_images/masker_objects.rst
- doc/plotting/index.rst
- nilearn/datasets/utils.py
- Closes none but relates to #4003 
- use double backtivks in rst files
- use [semantic line break](https://sembr.org/) in some places
> [DOC] use double backticks in rst files

- doc/maintenance.rst
- nilearn/_utils/docs.py
- Closes none
- update sphinx directives to use X.Y.Z format in view of next release
- update maintenance documentation
> [REL] remove `dev` in sphinx directives related to version

- .github/workflows/assign.yml
- .github/workflows/auto-comment.yml
- .github/workflows/black.yml
- .github/workflows/build-docs.yml
- .github/workflows/circle_artifacts.yml
- .github/workflows/codespell.yml
- .github/workflows/detect_test_pollution.yml
- .github/workflows/f_strings.yml
- .github/workflows/flake8.yml
- .github/workflows/isort.yml
- .github/workflows/testing.yml
- .github/workflows/testing_install.yml
- .github/workflows/update_authors.yml
- .github/workflows/update_precommit_hooks.yml
- Relates to #4003 
- make sure every step in all GHA has a name
> [MAINT] add names to all steps in all GHA workflows

- pyproject.toml
- Relates to #4003
- set xfail_strict to true as we do have a few xfail tests
- use --strict-config
- use --strict-markers
- use -ra
> [MAINT] update pytest config

- .gitignore
- doc/changes/latest.rst
- doc/changes/whats_new.rst
- Closes none
- reset latest.rst
> [MAINT] Post release 0.10.2

- doc/maintenance.rst
- Closes #4015
- link to issue label page
- remove obsolete labels
> [MAINT] Update issue labels

- Makefile
> [MAINT] Use correct target name for Makefile recipe

- nilearn/plotting/tests/test_img_plotting/test_plot_prob_atlas.py
- Closes none but should allow CI to be green in main
> [MAINT fix typo in fixture name

- doc/changes/latest.rst
> [DOC] Fix failing docs on main

- pyproject.toml
> [DOC][MAINT] Remove restriction on Sphinx version

- README.rst
> [MAINT] Fix Zenodo DOI badge

- examples/02_decoding/plot_haxby_glm_decoding.py
- examples/02_decoding/plot_haxby_multiclass.py
- examples/02_decoding/plot_miyawaki_encoding.py
- examples/02_decoding/plot_oasis_vbm.py
- examples/03_connectivity/plot_compare_decomposition.py
- examples/03_connectivity/plot_data_driven_parcellations.py
- examples/03_connectivity/plot_group_level_connectivity.py
- examples/03_connectivity/plot_signal_extraction.py
- examples/03_connectivity/plot_sphere_based_connectome.py
- examples/04_glm_first_level/plot_bids_features.py
- examples/04_glm_first_level/plot_localizer_surface_analysis.py
- examples/05_glm_second_level/plot_oasis.py
- examples/05_glm_second_level/plot_proportion_activated_voxels.py
- examples/05_glm_second_level/plot_second_level_association_test.py
- examples/05_glm_second_level/plot_second_level_one_sample_test.py
- examples/05_glm_second_level/plot_second_level_two_sample_test.py
- examples/06_manipulating_images/plot_compare_mean_image.py
- examples/06_manipulating_images/plot_extract_rois_smith_atlas.py
- examples/06_manipulating_images/plot_negate_image.py
- examples/06_manipulating_images/plot_resample_to_template.py
- examples/06_manipulating_images/plot_roi_extraction.py
- examples/07_advanced/plot_age_group_prediction_cross_val.py
- examples/07_advanced/plot_bids_analysis.py
- examples/07_advanced/plot_ica_neurovault.py
- examples/07_advanced/plot_surface_bids_analysis.py
- examples/08_experimental/plot_surface_image_and_maskers.py
Relates to https://github.com/nilearn/nilearn/pull/4031
which I did too quickly it seems
> [DOC] Remove extraneous hash symbols for examples' section splitters

- doc/Makefile
- doc/maintenance.rst
> [DOC] Add tagging of release version to stable doc build

- doc/changes/latest.rst
> [DOC] Fix label  in changelog

- nilearn/plotting/img_plotting.py
- Closes #2062, closes #911
- Document returns of functions in img_plotting
- Clarify plot_img is low level function
> [DOC] Clarify docstrings of plotting functions in `img_plotting`

- .pre-commit-config.yaml
- nilearn/maskers/nifti_labels_masker.py
- pyproject.toml
> [MAINT] Apply Black to nifti_labels_masker.py

- .pre-commit-config.yaml
- nilearn/reporting/html_report.py
- nilearn/reporting/tests/test_html_report.py
- pyproject.toml
> [MAINT] Apply Black to reporting files

- .pre-commit-config.yaml
- nilearn/plotting/img_plotting.py
- pyproject.toml
> [MAINT] Apply Black img_plotting.py

- .pre-commit-config.yaml
- nilearn/maskers/nifti_spheres_masker.py
- pyproject.toml
> [MAINT] Apply Black to nifti_spheres_masker.py

- .pre-commit-config.yaml
- nilearn/interfaces/fmriprep/load_confounds_compcor.py
- nilearn/interfaces/fmriprep/tests/_testing.py
- nilearn/interfaces/fmriprep/tests/test_load_confounds.py
- nilearn/interfaces/fmriprep/tests/test_load_confounds_strategy.py
- nilearn/interfaces/fmriprep/tests/test_load_confounds_utils.py
- pyproject.toml
- Closes none
- apply black to files no longer involved in other PRs
> [STY] run black on nilearn/interfaces/fmriprep

- nilearn/plotting/surf_plotting.py
> [FIX] Adjust figure size to display title for functions calling `plot_surf`

- .gitignore
- CITATION.cff
- doc/changes/latest.rst
- nilearn/datasets/func.py
- Closes #3307 
- The return value has been described in the fetch_abide_pcp docstring.
> Updated docs for fetch_abide_pcp

- .github/workflows/release-docs.yml
- doc/Makefile
- Closes None
Turning off automatic trigger for the moment as this will always run with merge on main. Will open another PR to fix
> [INFRA] Quick fix for automated stable doc build

- .github/workflows/release-docs.yml
> [INFRA] Fix auto trigger for release doc build in Actions workflow

- nilearn/plotting/html_document.py
- Closes none
- Follow up on https://github.com/nilearn/nilearn/pull/4180/files#r1442751278
- use dedicated helper decorator to deprecate parameter
> [FIX] use parameter deprecation decorator

- examples/04_glm_first_level/plot_bids_features.py
- nilearn/glm/tests/test_dmtx.py
- nilearn/reporting/_visual_testing/_glm_reporter_visual_inspection_suite_.py
- Closes none
- removes some left over mentions of nistats in documentation or variable names
> [MAINT] remove some old mention of nistats

- nilearn/_utils/tests/test_common.py
- nilearn/plotting/cm.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/edge_detect.py
- nilearn/plotting/glass_brain_files/plot_align_svg.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/html_surface.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_cm.py
- nilearn/plotting/tests/test_edge_detect.py
- nilearn/plotting/tests/test_html_surface.py
- nilearn/plotting/tests/test_img_plotting/test_get_colorbar_and_data_ranges.py
- relates to #3319
- make private functions in `nilearn.plotting` used outside of their module public
-
> [MAINT] make private functions in `nilearn.plotting` used outside of their module public

- nilearn/decoding/decoder.py
- nilearn/decoding/tests/test_decoder.py
> [FIX] Let decoder accept list of paths as input

- nilearn/datasets/func.py
- nilearn/glm/contrasts.py
- nilearn/glm/first_level/first_level.py
- nilearn/interfaces/fmriprep/load_confounds.py
- nilearn/interfaces/fmriprep/load_confounds_strategy.py
- nilearn/maskers/nifti_labels_masker.py
- nilearn/plotting/html_document.py
- Closes none
- change version 0.11.0 to 0.10.3 in sphinx directives
> [DOC] update version in sphinx directives

- nilearn/experimental/__init__.py
probably worth rebasing a lot of our PRs to avoid this
> [STY] re apply black

- doc/changes/latest.rst
- doc/changes/whats_new.rst
> [MAINT] Post release 0.10.3

- nilearn/reporting/tests/test_html_report.py
- nilearn/reporting/tests/test_reporting.py
- relates #3331 
- refactor tests nilearn reporting to use more fixture and parametrize where possible
> [MAINT] Refactor test reporting

- LICENSE
- doc/conf.py
- Closes none
- remove date mention in copyright and license
- won't have to update it every year
- hat tip to @effigies for pointing out why this is not necessary: https://hynek.me/til/copyright-years/
-
> [MAINT] remove date from copyright

- .github/workflows/numpy2_compatibility.yml
- nilearn/regions/region_extractor.py
- tox.ini
- Closes #4243
- fix issue with numpy array shape
- update tox recipe
- run numpy 2 ruff check in CI
> [FIX] numpy 2 compatibility 

- .github/workflows/numpy2_compatibility.yml
- nilearn/interfaces/fmriprep/tests/test_load_confounds.py
- Closes #4263 
- updates the way mock confounds are rearranged during testing
> [FIX] read only problem with numpy 2

- doc/changes/latest.rst
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_surf_plotting.py
- Closes #4127 
- mention where kwargs are passed to in the plotting subpackage
> [DOC] add documentation about kwargs in nilearn.plotting

- doc/changes/latest.rst
- nilearn/maskers/nifti_maps_masker.py
- Closes #4303
- fix position of cuts on nifti maps maskers
> [FIX] fix cut position in nifti maps maskers

- nilearn/externals/conftest.py
- pyproject.toml
- Closes #4305
- remove conftest for externals
- ignore collecting tests in tempita in pytest config in pyproject.toml
> [FIX] remove conftest for externals

- CONTRIBUTING.rst
- Closes #4317
- replace https://github.com/nilearn/nilearn/issues/2882 with [this link](https://tinyurl.com/nilearn-drop-in-hour).
- add a sentence mentioning the X posts.
> [DOC] Update drop-in hour information on contributing page

- CONTRIBUTING.rst
- Closes #4319
- refer to `nilearn.datasets` [documentation](https://nilearn.github.io/stable/modules/datasets.html)
> [DOC] Refer to nilearn datasets module 

- doc/visual_testing/reporter_visual_inspection_suite.py
- Closes #4351
- Change "grey" to "gray"
> [FIX] change "grey" to "gray" in `doc/visual_testing/reporter_visual_inspection_suite.py` for older Matplotlib versions

- doc/maintenance.rst
- Closes #4355
- Better explain what are the `deprecated`, `versionchanged` and `versionadded` directives
- point about having empty lines after every change log
- minor typo
> [DOC] Update release section of maintainence page

- doc/changes/latest.rst
- doc/changes/whats_new.rst
> [MAINT] Post release 0.10.4

- examples/06_manipulating_images/plot_compare_mean_image.py
- Closes #4363
- change "resting state" instances to "movie watching"
> Change "resting state" to "movie watching" in compare means example

- CONTRIBUTING.rst
- doc/Makefile
> [DOC] Mention in style guide the meaning of trailing underscore for attributes

- examples/01_plotting/plot_3d_map_to_surface_projection.py
skip plotting that makes doc build fails to not hold back other pull requests
> [FIX] skip problematic plotting in doc build

- .github/workflows/check_gha_workflow.yml
- .gitignore
- maint_tools/check_gha_workflow.py
- Closes #4385
- update script and GH workflow to plot duration of doc builds
> [MAINT] monitor duration of doc build

- .pre-commit-config.yaml
- examples/04_glm_first_level/plot_localizer_surface_analysis.py
- examples/07_advanced/plot_surface_bids_analysis.py
- nilearn/plotting/surf_plotting.py
- Closes none
- only exclude running black on subset of files to make sure other hooks are applied
- fix flake8 and pyugrade errors that this revelead
> [MAINT] update precommit configuration

- .github/workflows/test_with_tox.yml
- Closes none but relates to #4404
- test on macos 14 with latest dependencies to monitor failures seen in #4404
- test on macos 13 to make sure tests pass as usual
> [MAINT] test on several macos versions

- .github/codespell_ignore_words.txt
- .pre-commit-config.yaml
- Closes none
- update codespell version used by pre-commit and pacify the false positive it finds
> [MAINT] pacify codepspell

- .pre-commit-config.yaml
- examples/01_plotting/plot_surf_atlas.py
- examples/01_plotting/plot_surf_stat_map.py
- examples/01_plotting/plot_surface_projection_strategies.py
- examples/04_glm_first_level/plot_localizer_surface_analysis.py
- examples/07_advanced/plot_surface_bids_analysis.py
- nilearn/plotting/tests/test_html_surface.py
- pyproject.toml
- Closes none but relates to https://github.com/nilearn/nilearn/issues/3861
- apply black to several examples and one test file that are no longer involved in any other PR.
-
> [STY] apply black to files no longer invovled in other pull requests

- nilearn/decoding/tests/test_searchlight.py
- nilearn/surface/surface.py
- Closes none
- remove some try / except block that were there to check old versions of our dependencies we do not support anymore
> [MAINT] remove some try/except on imports

- nilearn/datasets/neurovault.py
- nilearn/datasets/struct.py
- nilearn/image/image.py
- nilearn/image/resampling.py
- nilearn/image/tests/test_image.py
- nilearn/maskers/nifti_labels_masker.py
- nilearn/maskers/nifti_maps_masker.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/plotting/tests/test_html_stat_map.py
- nilearn/regions/region_extractor.py
- Closes none but a follow up on #4412 
- explicitly pass the 'old' default to force_resample when resampling images
- add a TODO on each occurence to clean up when bumping to version > 0.13
> [MAINT] add force_resample where missing

- nilearn/maskers/multi_nifti_masker.py
- nilearn/maskers/nifti_maps_masker.py
- nilearn/maskers/nifti_masker.py
- nilearn/maskers/nifti_spheres_masker.py
- Closes none but follow up on #4441
- add explicit default of `force_resample` in cached calls to `resample_img`
> [REF] add force_resample default to cached calls

- examples/04_glm_first_level/plot_two_runs_model.py
- Closes none
- remove code that is duplicated in an example (creating output dir)
> [MAINT] remove duplicate code

- .circleci/config.yml
- .github/workflows/build-docs.yml
- .github/workflows/check_style_guide.yml
- Closes none but relates to #4401 
- let github push to the documentation repo when building the doc on main as we already do for the doc of the release
- circle CI is now only there for hosting the doc of the PRs (that deploy still needs fixing).
> [DOC] Fix deploy doc on main

- doc/changes/0.10.4.rst
- examples/01_plotting/plot_3d_map_to_surface_projection.py
- nilearn/plotting/cm.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_img_plotting/test_plot_roi.py
- Closes none but alternative to https://github.com/nilearn/nilearn/pull/4419
- keep the few refactors that could be salvaged from #4419
> [REF]  minor refactor of get_cmap and matplotlib version-handling

- nilearn/glm/first_level/first_level.py
- Closes none
- Extracted from #4112
- refactor fitting of first level models into several smaller functions
> [REF] refactor FLM fitting

- maint_tools/check_gha_workflow.py
- Closes none
relates to this workflow that monitor duration of test suite and doc build
- only keep the build of the doc on main branch (push only and not pull request)
previous figures showed a mix of full and partial builds:
new figure only shows full builds:
> [MAINT] for monitoring of duration of CI only plot doc build on main (full builds)

- nilearn/datasets/func.py
- nilearn/plotting/displays/_slicers.py
- nilearn/regions/region_extractor.py
- Closes none
- apply one of the numpy_2 related suggestion from ruff
see https://github.com/nilearn/nilearn/actions/runs/9699659906/job/26769169979?pr=4475#step:5:36
> [FIX] pacify ruff warning about numpy 2

- .github/workflows/build-docs.yml
- examples/01_plotting/plot_surf_stat_map.py
- examples/08_experimental/plot_surf_stat_map_experimental.py
- nilearn/datasets/func.py
- Closes #4474
- coerce dtype of nki dataset into float instead of object
> [FIX] coerce loaded data from NKI to float in examples

- .github/workflows/build-docs.yml
- .github/workflows/trigger_hosting_on_pr.yml
- Closes #4401 
- partly reverts https://github.com/nilearn/nilearn/pull/4402/files
> [FIX] host doc from PR on Circle-CI

- nilearn/decoding/decoder.py
- Closes #4490
- update both `Decoder` and `DecoderRegressor` docstring
> Explain Decoder's default cross-validation scheme

- CITATION.cff
- doc/changes/latest.rst
- examples/02_decoding/plot_miyawaki_encoding.py
- examples/04_glm_first_level/plot_design_matrix.py
- examples/05_glm_second_level/plot_oasis.py
- examples/05_glm_second_level/plot_second_level_design_matrix.py
- examples/05_glm_second_level/plot_second_level_two_sample_test.py
- examples/07_advanced/plot_beta_series.py
- nilearn/plotting/matrix_plotting.py
- Closes #4471
- Renames the all parameters names `ax` to axes.
- Changes the parameters wherever the functions are called.
> [API] renamed `ax` parameter for consistency

- AUTHORS.rst
- CITATION.cff
- doc/changes/latest.rst
- doc/changes/names.rst
- nilearn/_utils/data_gen.py
- nilearn/_utils/tests/test_data_gen.py
- Closes #2750
- Add tests for public data_gen functions
- Fix 2 data_gen functions to better match their doc
> [MAINT] Finish adding tests for `_utils.data_gen`

- nilearn/datasets/func.py
- Closes none but addresses https://github.com/nilearn/nilearn/pull/4506#issuecomment-2299636558
- use nibabel.save to to save to 'Analyze' format
> [FIX] revert save analyze for SPM auditory data

- .github/workflows/test_with_tox.yml
- .gitignore
- .pre-commit-config.yaml
- maint_tools/templates/index.html
- nilearn/_utils/tests/test_common.py
- pyproject.toml
- tox.ini
- Closes #4451
- add html report to testing suite
Merged #4444 prematurely so reverted it and opening this one that reimplements it so we can get other dev opinions on it.
> [MAINT] use pytest-reporter-html1 to create test reports

- .pre-commit-config.yaml
- examples/01_plotting/plot_3d_map_to_surface_projection.py
- examples/02_decoding/plot_oasis_vbm.py
- nilearn/experimental/plotting/tests/test_surface_plotting.py
- nilearn/glm/contrasts.py
- nilearn/reporting/html_report.py
- pyproject.toml
- Closes none but relates to #3861
> [STY] apply black to remaining example

- .pre-commit-config.yaml
- nilearn/plotting/html_surface.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_surf_plotting.py
- pyproject.toml
- Closes none but relates to #3861
> [STY] apply black to remaining files in plotting subpackage

- .pre-commit-config.yaml
- nilearn/surface/surface.py
- nilearn/surface/tests/test_surface.py
- pyproject.toml
- Closes none but relates to #3861
> [STY] apply black to surface subpackage

- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_simulated_connectome.py
- examples/03_connectivity/plot_sphere_based_connectome.py
- nilearn/regions/tests/test_rena_clustering.py
- Closes none
- removes try import that check an older version of scikit-learn
- remove a "futile" import check
> [REF] remove obsolete try import

- pyproject.toml
- Closes none
- Flynt (tool to ensure use of f-strings) is not used anymore but its configuration remained: this removes it
> [MAINT] remove flynt config

- pyproject.toml
- Closes none
- remove optional dependencies from pyproject.toml that will be installed by tox
> [MAINT] simplify dependencies of `dev` and `style` installs

- nilearn/decoding/decoder.py
- nilearn/decoding/tests/test_decoder.py
- nilearn/regions/rena_clustering.py
- nilearn/regions/tests/test_rena_clustering.py
- Closes #4533 
- adapt "_more_tags" methods and tests
- add TODOs to switch to the new `__sklearn_tags__` when dropping sklearn 1.5.1
> [FIX] update scikit-learn decoder tags

- examples/02_decoding/plot_haxby_glm_decoding.py
- examples/02_decoding/plot_miyawaki_encoding.py
- nilearn/interfaces/fmriprep/load_confounds_strategy.py
- nilearn/interfaces/fmriprep/tests/test_load_confounds.py
- nilearn/plotting/html_surface.py
- nilearn/reporting/glm_reporter.py
- Closes #4543
- fix some typos
> [FIX] remove several typos or double space

- nilearn/decoding/decoder.py
- nilearn/decoding/tests/test_decoder.py
- nilearn/regions/rena_clustering.py
- Closes none but relates to https://github.com/nilearn/nilearn/pull/4535#issuecomment-2348135156
> [FIX] fix version to check for scikit learn for new decoder tags

- maint_tools/citation_cff_maint.py
- nilearn/_utils/tests/test_data_gen.py
- nilearn/datasets/tests/test_func.py
- nilearn/decomposition/tests/test_multi_pca.py
- nilearn/experimental/surface/maskers.py
- nilearn/glm/_utils.py
- nilearn/glm/tests/test_dmtx.py
- nilearn/glm/tests/test_second_level.py
- nilearn/image/image.py
- nilearn/image/tests/test_image.py
- nilearn/interfaces/tests/test_bids.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- nilearn/plotting/displays/_projectors.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/tests/test_matrix_plotting.py
- nilearn/reporting/tests/test_reporting.py
> [MAINT] replace `nb` by `n`

- nilearn/decoding/decoder.py
- nilearn/decoding/tests/test_decoder.py
- nilearn/regions/rena_clustering.py
- Closes #4549
compare the minor version only to avoid the following 'problem':
```python
In [10]: compare_version("1.6.dev0", "<", "1.6")
Out[10]: True
```
> [FIX] fix sklearn version check

- .gitignore
- doc/changes/latest.rst
- nilearn/_utils/logger.py
- nilearn/_utils/tests/test_logger.py
- tox.ini
- Closes none
- use print from [rich](https://github.com/Textualize/rich) if users have it installed
- refactor tests for logger
This is just to try it out and see how the tests stdout look.
> [ENH] add optional pretty printing with rich for logging

- doc/changes/latest.rst
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/img_plotting.py
- Closes #4553
- make sure that radiological view is applied when requested
Before
After
> [FIX] fix radiological view

- nilearn/_utils/docs.py
- nilearn/datasets/neurovault.py
- pyproject.toml
- Closes none
- Relates to https://github.com/nilearn/nilearn/issues/4579
- Follow up on #4574
- most of the changes include formatting of
-  the keys in _utils/doc.py
-  the some double quotes in a long code example
> [STY] run ruff on extra files excluded from previous PR

- doc/conf.py
- Closes none
- make sure the Nilearn youtube channel is listed in the doc
> [DOC] add youtube channel in the doc footer

- CITATION.cff
- doc/changes/latest.rst
- nilearn/glm/first_level/first_level.py
- nilearn/glm/tests/test_first_level.py
> [FIX] `first_level_from_bids` will now return subjects in order

- nilearn/datasets/tests/test_neurovault.py
- nilearn/glm/first_level/experimental_paradigm.py
- nilearn/glm/tests/test_first_level.py
- nilearn/reporting/glm_reporter.py
- pyproject.toml
- Closes https://github.com/nilearn/nilearn/issues/4579
- fixes pandas 'error' flagged by ruff
- https://docs.astral.sh/ruff/rules/pandas-use-of-inplace-argument/
- https://docs.astral.sh/ruff/rules/pandas-use-of-dot-is-null/
> [STY] fix ruff pandas error

- examples/05_glm_second_level/plot_second_level_association_test.py
- examples/05_glm_second_level/plot_second_level_one_sample_test.py
- examples/08_experimental/plot_localizer_new_surface_analysis_experimental.py
- examples/08_experimental/plot_new_surface_bids_analysis_experimental.py
- maint_tools/check_gha_workflow.py
- maint_tools/show-python-packages-versions.py
- nilearn/__init__.py
- nilearn/_utils/docs.py
- nilearn/_utils/niimg.py
- nilearn/_utils/numpy_conversions.py
- nilearn/_utils/tests/test_niimg_conversions.py
- nilearn/conftest.py
- nilearn/datasets/atlas.py
- nilearn/datasets/func.py
- nilearn/datasets/tests/test_neurovault.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/model.py
- nilearn/glm/tests/test_contrasts.py
- nilearn/interfaces/bids/utils.py
- nilearn/interfaces/tests/test_bids.py
- nilearn/maskers/tests/test_input_data.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- nilearn/masking.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_img_plotting/test_img_plotting.py
- nilearn/plotting/tests/test_img_plotting/test_plot_stat_map.py
- nilearn/reporting/glm_reporter.py
- pyproject.toml
- Relates to #4579
- fix autofixable errors specific to ruff
> [REF] fix ruff 'errors' 

- examples/02_decoding/plot_miyawaki_reconstruction.py
- examples/03_connectivity/plot_seed_to_voxel_correlation.py
- examples/07_advanced/plot_advanced_decoding_scikit.py
- nilearn/_utils/niimg_conversions.py
- nilearn/_utils/testing.py
- nilearn/_utils/tests/test_niimg_conversions.py
- nilearn/datasets/func.py
- pyproject.toml
- Closes none but relates to #4579
- fixes errors for fly: https://docs.astral.sh/ruff/rules/#flynt-fly
- fixes errors for pyupgrade: https://docs.astral.sh/ruff/rules/#pyupgrade-up
> [STY] fix fly and up errors flagged by ruff

- nilearn/datasets/_utils.py
- nilearn/datasets/tests/test_utils.py
- pyproject.toml
- Closes  none but relates to #4327 
- fixes error: https://docs.astral.sh/ruff/rules/os-rmdir/
> [FIX] fix error PTH106 

- maint_tools/check_glossary_term.py
- nilearn/connectome/group_sparse_cov.py
- nilearn/datasets/_utils.py
- nilearn/datasets/tests/test_func.py
- nilearn/glm/first_level/first_level.py
- nilearn/maskers/base_masker.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/displays/_projectors.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/matrix_plotting.py
- pyproject.toml
- Closes none relates to #4579 
- fixes simplify errors: https://docs.astral.sh/ruff/rules/#flake8-simplify-sim
-
> [STY] fixes simplify error flagged by ruff

- nilearn/_utils/data_gen.py
- nilearn/glm/first_level/first_level.py
- nilearn/interfaces/bids/query.py
- Closes none
- fixes some doc build issue: see https://github.com/nilearn/nilearn/actions/runs/11270534259/job/31344536706#step:14:15603
> [FIX] Fix doc strings for path

- .github/workflows/testing_minimum.yml
- nilearn/experimental/surface/_io.py
- nilearn/experimental/surface/_surface_image.py
- nilearn/experimental/surface/tests/test_surface_image.py
- Closes #4565 
- add `to_filename` to PolyMesh and PolyData
> [ENH] Allow saving SurfaceImage data to Gifti files 

- nilearn/_utils/param_validation.py
- nilearn/_utils/tests/test_param_validation.py
- nilearn/decoding/tests/test_decoder.py
- Closes #4639
- rename `get_mask_volume` to `get_mask_extent`
- update function refs, and related variables similarly
> [REF] Rename `get_mask_volume`

- examples/04_glm_first_level/plot_design_matrix.py
- examples/07_advanced/plot_ica_neurovault.py
- nilearn/plotting/matrix_plotting.py
- nilearn/reporting/glm_reporter.py
- Closes none
- remove some now obsolete filter warnings
> [MAINT] remove some unecessary warning filters

- examples/02_decoding/plot_haxby_searchlight_surface.py
- examples/08_experimental/plot_surf_atlas_experimental.py
- Closes none
- make sure that thing like
```rst
:term:`foo`
```
render properly in the doc.
They should part of the block starting with `# %%`.
> [DOC] minor changes to examples for better rendering

- nilearn/datasets/_utils.py
- nilearn/datasets/tests/test_testing.py
- pyproject.toml
- Closes none but relates to #4579
- fix SIM117
- set upper bound for 'complexity' errors flagged by ruff.pylint so that our code does not get more complex than it is.
> [STY] fix SIM117 error

- nilearn/datasets/tests/test_neurovault.py
- Closes #4698 
- remove useless line in a test
> [MAINT] remove useles test line

- examples/01_plotting/plot_3d_map_to_surface_projection.py
- examples/01_plotting/plot_surf_atlas.py
- examples/01_plotting/plot_surf_stat_map.py
- nilearn/plotting/displays/_figures.py
- nilearn/plotting/tests/test_surf_plotting.py
- Closes #4691
- make sure that SurfaceImage can be used as input to plot contours
- clean up import to remove using `nilearn.experimental.plotting`
> [ENH] Add plotting contours using SurfaceImage with plotly

- examples/02_decoding/plot_haxby_searchlight.py
- examples/02_decoding/plot_haxby_searchlight_surface.py
- nilearn/decoding/searchlight.py
- Closes #4654
- adapt searchlight on surface example to use the SurfaceImage object
> [DOC] Use SurfaceImage object for the Searchlight surface example

- nilearn/decomposition/_base.py
- nilearn/decomposition/_multi_pca.py
- nilearn/decomposition/canica.py
- nilearn/decomposition/dict_learning.py
- nilearn/maskers/multi_nifti_masker.py
- nilearn/maskers/nifti_masker.py
- nilearn/regions/parcellations.py
- closes none
- adds some internal link to the doc for masking functions in the maskers doc strings
> [DOC] add link to masking functions

- nilearn/decoding/decoder.py
- nilearn/decoding/space_net.py
- Closes none
- mostly adds extra space before `:` to prevent render putting parameters types in bold
> [DOC] minor RST fixes to improve doc rendering

- nilearn/datasets/_utils.py
- nilearn/datasets/atlas.py
- nilearn/datasets/func.py
- nilearn/datasets/neurovault.py
- nilearn/datasets/struct.py
- nilearn/datasets/tests/test_func.py
- nilearn/datasets/tests/test_neurovault.py
- nilearn/datasets/tests/test_utils.py
- Closes none but relates to #4327 
- use pathlib.Path more systematically in nilearn.datasets
- still need to do fetch_files: in another PR
> [MAINT] use pathlib.Path more systematically in nilearn.datasets

- examples/01_plotting/plot_carpet.py
- examples/02_decoding/plot_haxby_searchlight_surface.py
- examples/03_connectivity/plot_atlas_comparison.py
- examples/03_connectivity/plot_sphere_based_connectome.py
- examples/04_glm_first_level/plot_bids_features.py
- examples/06_manipulating_images/plot_nifti_simple.py
- examples/07_advanced/plot_age_group_prediction_cross_val.py
- examples/07_advanced/plot_surface_image_and_maskers.py
- nilearn/datasets/atlas.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_surf_plotting.py
Not sure about the reimports under [`examples`](https://github.com/nilearn/nilearn/tree/main/examples). Were they added for didactic purposes?
> [STY] Multiple imports for an import name

- nilearn/tests/test_signal.py
For consistency with the rest of the tests. See also https://github.com/scipy/scipy/issues/8583.
> [STY] np.testing.assert_ → assert

- examples/01_plotting/plot_3d_map_to_surface_projection.py
- nilearn/datasets/func.py
- nilearn/datasets/struct.py
- nilearn/maskers/surface_labels_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- Closes none but should fix the dox build in main
- fix doc ref to scikit learn Bunch
- fix examples that failed to run  
- make label_names_ public in SurfaceLabelMaskers for compatibility with nilearn matrix plotting function
> [FIX][DOC] fix doc build

- nilearn/decoding/decoder.py
- Closes #4773
- Use `ClassifierMixin` and `RegressorMixin`
- set `estimator_type` tags
> Use the estimator type tags as required by scikit-learn 1.6.0 

- examples/02_decoding/plot_haxby_different_estimators.py
- examples/02_decoding/plot_haxby_searchlight_surface.py
- examples/05_glm_second_level/plot_second_level_association_test.py
- nilearn/datasets/func.py
- nilearn/datasets/struct.py
- nilearn/maskers/surface_labels_masker.py
- nilearn/maskers/surface_masker.py
- Closes none
- fix small issues with RST rendering
- add version added directives
> [FIX] add version added in the new classes and functions

- nilearn/datasets/atlas.py
> [MAINT] Sequence value overwritten unconditionally

- doc/modules/datasets.rst
- Closes #4277
- split atlases by deterministic and probabilistic
- some are mentioned twice as they can do both
> [DOC] split atlases section by probabilistic and deterministic

- nilearn/_utils/segmentation.py
- nilearn/datasets/func.py
- nilearn/regions/rena_clustering.py
Use `enumerate(...)` instead of `range(len(...))` where possible.
> [STY] Implicit enumerate calls

- nilearn/_utils/docs.py
- Closes none
- avoid the 'code block' look of the list
Before
> [DOC] fix rendering hrf list

- doc/glm/first_level_model.rst
- examples/04_glm_first_level/plot_design_matrix.py
- examples/04_glm_first_level/plot_write_events_file.py
- nilearn/glm/first_level/design_matrix.py
- nilearn/glm/first_level/experimental_paradigm.py
- nilearn/glm/first_level/first_level.py
- nilearn/plotting/matrix_plotting.py
- Closes #4562 
- update design matrix generation and plotting (and relevant examples) to mention how 0 duration events are handled
> [DOC] improve doc regarding events with 0 duration

- doc/Makefile
- Closes none but fixes doc build failure on main introduced by https://github.com/nilearn/nilearn/pull/4782
- make sure to create parent doc for  `.nojekyll`
> [FIX] create parent doc for  `.nojekyll`

- nilearn/_utils/docs.py
- nilearn/masking.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/surface/surface.py
- Closes none
- similar to https://github.com/nilearn/nilearn/pull/4784 but applies to all lists in the same module
> [DOC] Fix render of lists, notes and code blocks in 'template' parameters

- .github/workflows/test_with_tox.yml
- README.rst
- nilearn/connectome/tests/test_group_sparse_cov.py
- nilearn/mass_univariate/tests/test_permuted_least_squares.py
- nilearn/tests/test_masking.py
- Closes none
- adds some test for code uncovered according to https://app.codecov.io/gh/nilearn/nilearn/tree/main
- seems that our codecov reports are not uploaded properly because the codecov says: `No coverage reports found in this timespan.` over the last few months...
> [MAINT] increase coverage

- nilearn/decomposition/tests/test_base.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- Closes #4769
- add check_estimator_sparse_array to some estimators checks
> [MAINT] update checks scikit learn >= 1.7

- nilearn/glm/contrasts.py
- nilearn/glm/model.py
- nilearn/glm/regression.py
- nilearn/reporting/html_report.py
- Closes #4633
- move doc string for classes out of constuctor
> [DOC] move doc string for classes out of constructor

- doc/conf.py
- Closes none
- add link to bluesky account in footer
> [DOC] add bluesky to footer

- doc/changes/latest.rst
- nilearn/_utils/docs.py
- nilearn/glm/second_level/second_level.py
- nilearn/glm/tests/test_second_level.py
- Closes #3058
- Allow single 4D nifti as input for SecondLevelModel
> [FIX] Allow single 4D nifti as input for SecondLevelModel

- examples/01_plotting/plot_surf_atlas.py
- examples/01_plotting/plot_surf_stat_map.py
- examples/02_decoding/plot_haxby_searchlight_surface.py
- examples/07_advanced/plot_surface_image_and_maskers.py
- nilearn/datasets/func.py
- nilearn/glm/tests/test_first_level.py
- nilearn/maskers/_utils.py
- nilearn/maskers/surface_labels_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- nilearn/maskers/tests/test_utils.py
- nilearn/plotting/_utils.py
- nilearn/plotting/displays/_figures.py
- nilearn/plotting/tests/test_surf_plotting.py
- nilearn/regions/rena_clustering.py
- nilearn/surface/surface.py
- nilearn/surface/tests/test_surface.py
- Closes #4792
- remove squeeze on data
- add some tests for different shapes
- remove coercing surface data to 2D
- adapt other tests and examples
> [ENH] revert coercing surface data to 2D

- nilearn/datasets/func.py
- Closes none
- update number of participants loaded in load_nki
> [DOC][FIX] update number of participants loaded in load_nki

- examples/01_plotting/plot_surf_atlas.py
- Closes none
- make better use of SurfaceImage object abstraction
- use more meaningful variable names
- add more headings
> [FIX] rework plot_surf_atlas example

- examples/07_advanced/plot_surface_bids_analysis.py
> [FIX] update plot_surface_bids_analysis

- examples/01_plotting/plot_3d_map_to_surface_projection.py
- Closes none
- slight adaptation of the example to reference the right functions
- create a surface image for the signed curvature
> [FIX] update plot_3d_map_to_surface_projection

- examples/01_plotting/plot_surf_stat_map.py
- Closes none
- use SurfaceLabelMasker to compute seed timeseries
- create surface image of correlation
- avoid assigning data and events to new variables
> [FIX] update plot_surf_stat_map to properly use surface api

- examples/00_tutorials/plot_surface_101.py
- Closes none
- plotting can be done by passing directly a surface image: mesh is optional in that case
- styling to force "narrower" code (views better on smaller screens)
> [FIX] update plot_surface_101 example

- examples/07_advanced/plot_surface_image_and_maskers.py
- Closes none
- remove duplicate code
- add more explanations
- use more consistent code in the example
> [FIX] update plot_surface_image_and_maskers.py

- examples/04_glm_first_level/plot_localizer_surface_analysis.py
- Closes none
- use diverging map from white and not to white
- use shorten link to internal ref
- add some markup for strings
> [FIX] update plot_localizer_surface_analysis

- nilearn/plotting/tests/test_html_document.py
- Closes none
- use underscore for unused variable in loop
> [REF] use underscore for unused variable in loop

- nilearn/datasets/_utils.py
- nilearn/datasets/tests/test_utils.py
- Closes none
- [simplify empty collection comparison](https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/simplify-empty-collection-comparison/)
> [REF] simplify empty collection comparison

- nilearn/_utils/masker_validation.py
- Closes none
- use [join](https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/use-join/)
> [REF] use join

- nilearn/interfaces/tests/test_bids.py
- nilearn/plotting/displays/_figures.py
- Closes none
- apply [invert-any-all from sourcery](https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/invert-any-all/)
> [REF] avoid `not any()` or `not all()`

- nilearn/image/image.py
- Closes none
- fixes 'version changed' rendering to avoid this:
> [FIX] rendering version changed

- nilearn/glm/first_level/first_level.py
- nilearn/maskers/_utils.py
- nilearn/plotting/cm.py
- nilearn/plotting/find_cuts.py
- Closes none
- fixes [dict-comprehension](https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/dict-comprehension/)
> [REF] use dict comprehension

- nilearn/_utils/niimg.py
- nilearn/_utils/niimg_conversions.py
- nilearn/_utils/testing.py
- nilearn/conftest.py
- nilearn/datasets/tests/test_func.py
- nilearn/image/image.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/surf_plotting.py
- Closes none
implement the following rules from sourcery:
https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/
- remove-unnecessary-else
- swap-if-else-branches
> [REF] refactor unnecessary else block

- nilearn/_utils/niimg.py
- nilearn/_utils/testing.py
- nilearn/image/resampling.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/plotting/matrix_plotting.py
- Closes none
Apply the following rules from [sourcery](https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/):
- move-assign
- merge-list-append
- move-assign-in-block
> [REF] move assign variable within the if block where they are needed

- nilearn/decoding/space_net.py
- nilearn/image/resampling.py
- nilearn/plotting/displays/_figures.py
- nilearn/tests/test_signal.py
- Closes none
- https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/de-morgan/
> [REF] Apply de Morgan's law for conditional

- nilearn/plotting/tests/test_js_plotting_utils.py
- Closes none
- implements [default-get](https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/default-get/) fix from sourcery
> [REF] use get item where possible

- .github/workflows/nightly_dependencies.yml
- tox.ini
- Closes #4862 
- add pyarrow as dependency to nightly and pre-relese test build
- add pyarrow as dependency to doc build
Unrelated:
- upload test report for nightly test
> [MAINT] add pyarrow dependencies for some test and doc build 

- examples/01_plotting/plot_3d_map_to_surface_projection.py
- Closes none
- use ternary in example
> [REF] minor refactor of example

- nilearn/image/resampling.py
- Relates to https://github.com/nilearn/nilearn/issues/3655
- extract check inputs
- move assignement closer to their use
- remove unneeded else block
> [REF] Do simple refactor on resample_img

- maint_tools/check_gha_workflow.py
- Closes none
- apply sourcery refactoring to maint_tools
> [REF] refactor maint tools

- nilearn/_utils/docs.py
- nilearn/_utils/segmentation.py
- nilearn/_utils/tests/test_segmentation.py
- nilearn/decoding/space_net_solvers.py
- nilearn/glm/contrasts.py
- nilearn/interfaces/fmriprep/load_confounds_components.py
- nilearn/maskers/_utils.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/html_connectome.py
- nilearn/plotting/html_surface.py
- Closes none
apply the following rules from [sourcery](https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/)
- assign-if-exp              
- dict-assign-update-to-union 
- aug-assign                
- swap-if-expression         
- swap-nested-ifs             
- use-assigned-variable
> [REF] simplify assignement

- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/mass_univariate/tests/test_permuted_least_squares.py
- pyproject.toml
- Relates to #3655 
- extract input checks
- return early
- remove some else blocks
> [REF] Simple refactor of permuted_ols

- examples/03_connectivity/plot_group_level_connectivity.py
- Closes none
- ensure that all subplots have the same range
> [DOC] add min and max for plot_matrix in examples

- nilearn/glm/tests/test_second_level.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/mass_univariate/tests/test_permuted_least_squares.py
- pyproject.toml
- Closes none
- create functions:
- _compute_t_stat_threshold function
- _make_array_contiguous
- return early if not permutation needed
- only compute things needed for permutation
- ensures that n_perm is an int
> [REF] refactor permute_ols

- nilearn/connectome/group_sparse_cov.py
- Closes none but relates to #3655 
- refactor group_sparse_covariance
- extract several functions to make code more readable
> [REF] refactor group_sparse_covariance

- doc/conf.py
- Closes none
- ignore one link that gives `403 Client Error: Forbidden for url`
> [FIX] ignore link that gives `403 Client Error: Forbidden for url`

- nilearn/_utils/data_gen.py
- nilearn/_utils/glm.py
- nilearn/_utils/tests/test_data_gen.py
- nilearn/_utils/tests/test_glm.py
- nilearn/glm/tests/test_first_level.py
- nilearn/glm/tests/test_second_level.py
- nilearn/plotting/tests/test_matrix_plotting.py
- nilearn/reporting/tests/test_glm_reporter.py
- Closes #4894
- simplify table loading
- testing to see how many things actually break
> [FIX] simplify table loading

- nilearn/maskers/tests/test_base_masker.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- Closes #4888 
- update list of checks to ignore
> [FIX] update tag checks for sklearn 1.7

- nilearn/mass_univariate/permuted_least_squares.py
- pyproject.toml
- Closes none
- refactor output handling of permuted_ols
> [REF] further refactor of permuted_ols

- nilearn/_utils/logger.py
- nilearn/_utils/numpy_conversions.py
- nilearn/_utils/param_validation.py
- Closes none
apply following refactoring from sourcery
- lift-return-into-if
- last-if-guard
> [REF] fix last-if-guard and lift-return-into-if

- nilearn/_utils/tests/test_common.py
- nilearn/conftest.py
- nilearn/decoding/tests/test_decoder.py
- nilearn/decoding/tests/test_space_net.py
- nilearn/glm/tests/test_second_level.py
- nilearn/maskers/_utils.py
- nilearn/maskers/surface_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- nilearn/maskers/tests/test_surface_masker.py
- nilearn/maskers/tests/test_utils.py
- nilearn/plotting/tests/test_surf_plotting.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- nilearn/regions/tests/test_parcellations.py
- nilearn/regions/tests/test_rena_clustering.py
- nilearn/reporting/tests/test_glm_reporter.py
- nilearn/reporting/tests/test_html_report.py
- nilearn/surface/surface.py
- nilearn/surface/tests/test_surface.py
- relates to #4686
- closes https://github.com/nilearn/nilearn/issues/4904
- create a 1D surface fixture
- rename the old surf_img fixture surf_img_2d
> [REF] refactor 1D and 2D surface fixtures

- nilearn/decomposition/tests/test_base.py
- nilearn/maskers/tests/test_base_masker.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- Closes #4924 
- update list of estimator checks for sklearn 1.6
> [FIX] update estimator checks for sklearn 1.6

- nilearn/glm/first_level/first_level.py
- nilearn/masking.py
- Closes none
- apply merge duplicate blocks from sourcery
> [REF] merge duplicate blocks

- nilearn/connectome/connectivity_matrices.py
- nilearn/connectome/group_sparse_cov.py
- nilearn/connectome/tests/test_connectivity_matrices.py
- nilearn/connectome/tests/test_group_sparse_cov.py
- Closes none but relates to https://github.com/nilearn/nilearn/issues/4538#issuecomment-2527259857
- remove logic from constructor
- adds test for covarariance estimators
> [MAINT] update constructors of estimators in nilearn.connectome for sklearn compliance

- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
- nilearn/glm/tests/test_first_level.py
- Closes none but relates to https://github.com/nilearn/nilearn/issues/4538#issuecomment-2527259857
- check compatibility of FirstLevelModel with scikitlearn
- update FirstLevelModel constructor to avoid doing any logic in it: all checks are done at fit time
> [MAINT] check compatibility of FirstLevelModel with scikitlearn

- .github/workflows/build-docs.yml
- doc/conf.py
- examples/02_decoding/plot_oasis_vbm.py
- examples/05_glm_second_level/plot_second_level_association_test.py
- examples/07_advanced/plot_haxby_mass_univariate.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/mass_univariate/tests/test_permuted_least_squares.py
- pyproject.toml
- tox.ini
- Closes #4910
- revert one of the changes introduced by #4875
- add a regression test
- small changes in the failing examples so they are run in CI
- fixes linkchecks that's also failing on main
> [FIX] Properly set number fo permutation chunks when n_jobs > n_perm

- doc/conf.py
- doc/decoding/decoding_intro.rst
- doc/decoding/going_further.rst
> [FIX] fix dead link

- examples/01_plotting/plot_multiscale_parcellations.py
- nilearn/plotting/cm.py
- Closes #4934
- remove checks related to some old mpl versions
- modify an example to 'test'
> [MAINT] remove some checks for matplotlib we no longer support 

- nilearn/maskers/surface_masker.py
- nilearn/maskers/tests/test_surface_masker.py
- Closes none
- make name of parameter more consistent with that of other maskers
> [FIX] rename parameter for inverse_transform of SurfaceMasker

- nilearn/decomposition/tests/test_canica.py
- nilearn/interfaces/fmriprep/load_confounds_strategy.py
- apply US spelling
- fix a typo
> [STY] apply US spelling

- nilearn/glm/second_level/second_level.py
- nilearn/glm/tests/test_contrasts.py
- nilearn/image/tests/test_image.py
- nilearn/regions/tests/test_parcellations.py
- nilearn/tests/test_signal.py
- Apply a couple preview ruff rules that make real sense.
> [STY] Apply a couple preview ruff rules

- README.rst
- doc/conf.py
- Closes #4891
- add a badges in the README header
> [ENH] add bluesky and youtube badge to readme

- doc/changes/latest.rst
- nilearn/_utils/niimg_conversions.py
- nilearn/_utils/testing.py
- nilearn/_utils/tests/test_niimg_conversions.py
> [FIX] fix expand user path when passing niimg filename

- nilearn/maskers/base_masker.py
- nilearn/maskers/surface_labels_masker.py
- nilearn/maskers/surface_maps_masker.py
- nilearn/maskers/surface_masker.py
- Closes none
- create a _BaseSurfaceMasker from which all surface maskers inherit
- set the tags on the base masker
> [MAINT] Refactor tags surface masker

- .github/workflows/build-docs.yml
- .github/workflows/nightly_dependencies.yml
- .github/workflows/test_with_tox.yml
- doc/maintenance.rst
- tox.ini
- Closes none but relates to #4628 #4663
- use uv to run "pip install" in CI: https://docs.astral.sh/uv/
- allows to shave of precious time in CI
- unrelated: simplify the names of the tox "environments"
> [MAINT] use UV to install in CI

- .github/workflows/build-docs.yml
- .github/workflows/nightly_dependencies.yml
- .github/workflows/test_with_tox.yml
- doc/maintenance.rst
- tox.ini
> Revert "[MAINT] use UV to install in CI"

- doc/glossary.rst
- Closes none but should fix linkcheck (for now)
- The link https://benediktehinger.de/blog/science/threshold-free-cluster-enhancement-explained times out in CI (even though it does eventually succeed when I tried it)
- Replacing it with Jeanette Mumford's TFCE youtube video
> [FIX] Change link to TFCE tutorial

- doc/changes/0.11.1.rst
- doc/changes/whats_new.rst
- Closes none
- update changelog for release 0.11.1
> REL 0.11.1

- doc/changes/latest.rst
- doc/changes/whats_new.rst
Closes none
Reset changelog after release
> [MAINT] post release 0.11.1

- nilearn/glm/tests/test_first_level.py
- nilearn/maskers/tests/conftest.py
- nilearn/plotting/tests/test_html_document.py
- pyproject.toml
Closes none but fixes 2 doc errors flagged by ruff.
> [STY] add doc strings in classes in test

- nilearn/plotting/tests/conftest.py
- nilearn/plotting/tests/test_surf_plotting.py
- Closes none but relates to https://github.com/nilearn/nilearn/issues/3570 and https://github.com/nilearn/nilearn/issues/3331
- add a pyplot fixtures to set up and clean up figures on teardown
- add a plotly fixture to clean up figures on test teardown
- both fixtures also check if the matplotl or plotly are installed can allow to skip a test
- break long tests into smaller ones
> [REF] refactor test surface plotting

- doc/decoding/estimator_choice.rst
- doc/decoding/frem.rst
- doc/decoding/searchlight.rst
- doc/decoding/space_net.rst
- doc/introduction.rst
- nilearn/image/image.py
- Closes none
- put footcite between parenthesis not sqaure backets
- fix one typo in one directive
> [DOC] fix citations

- doc/Makefile
- doc/conf.py
- doc/make.bat
- Closes none
removes latex config as it seems not needed for a proper rendering of :math: directive content and we do not produce PDF of the doc anymore
example of :math: directive left unchanged in this PR.
https://output.circle-artifacts.com/output/job/63793075-cbf6-449b-a580-b4f060126c7e/artifacts/0/dev/glm/glm_intro.html#multiple-comparisons
> [TEST] do not install latex for doc build

- .gitignore
- doc/Makefile
> [MAINT] remove .nojekyll handling

- nilearn/plotting/tests/test_img_plotting/test_plot_carpet.py
- nilearn/plotting/tests/test_img_plotting/test_plot_glass_brain.py
- nilearn/plotting/tests/test_img_plotting/test_plot_img.py
- nilearn/plotting/tests/test_img_plotting/test_plot_img_comparisons.py
- nilearn/plotting/tests/test_img_plotting/test_plot_markers.py
- nilearn/plotting/tests/test_img_plotting/test_plot_prob_atlas.py
- nilearn/plotting/tests/test_img_plotting/test_plot_roi.py
- nilearn/plotting/tests/test_img_plotting/test_plot_stat_map.py
- Closes none
- refactor several tests for plotting to make them smaller
- use pyplot fixture to clean up figures on teardown
> [REF] refactor test plotting

- doc/conf.py
> [MAINT] fix dead link flagged by linkcheck 

- doc/building_blocks/neurovault.rst
- doc/references.bib
- nilearn/connectome/group_sparse_cov.py
- Closes none
- fix some links to arxiv
- use bibtex references rather than hard coded ones
> [DOC] fix references 

- examples/02_decoding/plot_haxby_frem.py
- examples/02_decoding/plot_mixed_gambles_frem.py
- examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
- nilearn/decomposition/_base.py
- Closes none
- see details below
> [FIX] minor fixes in examples

- nilearn/decomposition/dict_learning.py
- Closes none
- remove if block for unsupported sklearn version
> [MAINT] remove if block for unsupported sklearn version

- doc/visual_testing/reporter_visual_inspection_suite.py
- examples/01_plotting/plot_3d_map_to_surface_projection.py
- examples/01_plotting/plot_surf_atlas.py
- examples/01_plotting/plot_surf_stat_map.py
- examples/07_advanced/plot_surface_image_and_maskers.py
- nilearn/datasets/atlas.py
- nilearn/maskers/nifti_labels_masker.py
- nilearn/maskers/surface_labels_masker.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- Relates to https://github.com/nilearn/nilearn/issues/2263
- Relates https://github.com/nilearn/nilearn/issues/2660
- Closes #4661 
- convert labels to string in destrieux atlas
> [FIX] convert labels to string in labels in dataset fetchers

- examples/07_advanced/plot_surface_image_and_maskers.py
- Closes #4852
- only print every 3rd label to make legend easier to read
> [DOC] update labels in plot_surface_image_maskers

- nilearn/_utils/testing.py
- nilearn/_utils/tests/test_helpers.py
- nilearn/tests/test_package_import.py
- Closes none
- should 'fix' failing test on windows + matplotlib==3.3.0
- https://github.com/nilearn/nilearn/actions/runs/12556580073/job/35008021038#step:6:33671
> [FIX] skip failing tests on "windows & matplotlib==3.3.0"

- examples/01_plotting/plot_visualize_megatrawls_netmats.py
- examples/02_decoding/plot_mixed_gambles_frem.py
- examples/02_decoding/plot_oasis_vbm.py
- examples/02_decoding/plot_oasis_vbm_space_net.py
- examples/05_glm_second_level/plot_oasis.py
- nilearn/datasets/description/Megatrawls.rst
- nilearn/datasets/description/mixed_gambles.rst
- nilearn/datasets/description/oasis1.rst
- nilearn/datasets/func.py
- nilearn/datasets/struct.py
- Closes none but relates to #4218
- reorganizes description oasis, megatrawls, mixed gambles datasets
> [DOC] refactor description datasets functional derivatives

- README.rst
- Closes none
- update doc build status and test status badge in README
- should solve the broken link issue on main
> [MAINT] update badges 

- doc/versions.rst
- Closes none
- add links to doc for versions 0.7 - 0.8.1
-
> [DOC] add links to more older doc versions

- nilearn/__init__.py
- nilearn/_utils/docs.py
- nilearn/_utils/testing.py
- nilearn/conftest.py
- nilearn/glm/first_level/first_level.py
- nilearn/plotting/cm.py
- nilearn/plotting/displays/_projectors.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/html_document.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
- pyproject.toml
- Closes none
- minor changes to make sure that mypy does not raise any error on the code base even if it does not have any type annotation (yet)
> [MAINT] pacify mypy

- nilearn/__init__.py
- nilearn/_utils/docs.py
- nilearn/_utils/testing.py
- nilearn/conftest.py
- nilearn/glm/first_level/first_level.py
- nilearn/plotting/cm.py
- nilearn/plotting/displays/_projectors.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/html_document.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
- pyproject.toml
> Revert "[MAINT] pacify mypy"

- examples/00_tutorials/plot_single_subject_single_run.py
- nilearn/_utils/docs.py
- nilearn/datasets/description/fsaverage.rst
- nilearn/datasets/description/fsaverage3.rst
- nilearn/datasets/description/fsaverage4.rst
- nilearn/datasets/description/fsaverage5.rst
- nilearn/datasets/description/fsaverage6.rst
- nilearn/datasets/description/fsaverage_content.rst
- nilearn/datasets/description/icbm152_2009.rst
- nilearn/datasets/struct.py
- Closes none but relates to #4218 
- uniformize doc strings for templates
- centralizes information about templates in their description
> [DOC] refactor description templates

- .github/workflows/test_with_tox.yml
- nilearn/_utils/tests/test_common.py
- nilearn/datasets/tests/test_func.py
- nilearn/glm/tests/_testing.py
- nilearn/glm/tests/test_hemodynamic_models.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/tests/test_img_plotting/test_plot_connectome.py
- nilearn/reporting/utils.py
- Closes none
- remove or fix some of the dead code flagged by [vulture](https://github.com/jendrikseipp/vulture)
> [MAINT] remove dead code

- examples/01_plotting/plot_surf_stat_map.py
- examples/07_advanced/plot_surface_image_and_maskers.py
- nilearn/datasets/description/nki_enhanced_surface.rst
- nilearn/datasets/func.py
- Closes none but relates to #4218
- refactor documentation NKI dataset
> [DOC] update description nki

- doc/changes/latest.rst
- doc/visual_testing/reporter_visual_inspection_suite.py
- nilearn/_utils/docs.py
- nilearn/_utils/tests/test_common.py
- nilearn/datasets/atlas.py
- nilearn/datasets/tests/test_atlas.py
- Closes none
- Adds an Atlas class (inherit from sklearn Bunch) to help standardize atlases.
- Fixes doc build in main
> [REF] refactor atlas

- .github/workflows/update_authors.yml
- doc/conf.py
- Closes none
- fixes linkcheck
- make sure nilearn is installed for the check authors workflow
> [MAINT] fix doc build in main

- .github/workflows/update_authors.yml
- Closes none
- some dependencies were missing in ci
> [MAINT] fix check CFF workflows

- nilearn/maskers/nifti_labels_masker.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- Closes none
- check input type of label image before doing anything on it
> [REF] change order of input checks in fit of nifti label masker

- nilearn/_utils/class_inspect.py
- nilearn/maskers/multi_nifti_masker.py
- nilearn/maskers/nifti_maps_masker.py
- nilearn/maskers/nifti_masker.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/maskers/tests/test_base_masker.py
- nilearn/maskers/tests/test_multi_nifti_labels_masker.py
- nilearn/maskers/tests/test_multi_nifti_maps_masker.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- nilearn/maskers/tests/test_nifti_maps_masker.py
- nilearn/maskers/tests/test_nifti_masker.py
- Closes none
- add single tests for all maskers to standardize their behavior with maskers
> [REF] refactor test nifti maskers with masks

- nilearn/maskers/multi_nifti_labels_masker.py
- nilearn/maskers/multi_nifti_maps_masker.py
- nilearn/maskers/multi_nifti_masker.py
- nilearn/maskers/nifti_labels_masker.py
- nilearn/maskers/nifti_maps_masker.py
- nilearn/maskers/nifti_masker.py
- nilearn/maskers/nifti_spheres_masker.py
- Closes none
- avoid importing entire modules
> [MAINT] refactor import in maskers

- nilearn/decoding/decoder.py
- Closes none
- checking that using attributes for tags should not be necessary anymore
> [MAINT] remove old 'tags'  in nilearn/decoding

- nilearn/decoding/tests/test_searchlight.py
- nilearn/decomposition/tests/test_base.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/decomposition/tests/test_dict_learning.py
- nilearn/decomposition/tests/test_multi_pca.py
- nilearn/maskers/tests/test_multi_nifti_labels_masker.py
- nilearn/maskers/tests/test_multi_nifti_maps_masker.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/maskers/tests/test_nifti_masker.py
- nilearn/maskers/tests/test_nifti_spheres_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- nilearn/maskers/tests/test_surface_maps_masker.py
- Closes none but relates to #4538
- remove valid checks that are already listed as valid for all estimators in nilearn._utils.class_inpect
> [MAINT] remove valid checks duplicate

- nilearn/_utils/class_inspect.py
- nilearn/connectome/tests/test_connectivity_matrices.py
- nilearn/decoding/tests/test_searchlight.py
- nilearn/decomposition/tests/test_base.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/decomposition/tests/test_dict_learning.py
- nilearn/decomposition/tests/test_multi_pca.py
- nilearn/glm/tests/test_first_level.py
- nilearn/glm/tests/test_second_level.py
- nilearn/maskers/tests/test_multi_nifti_labels_masker.py
- nilearn/maskers/tests/test_multi_nifti_maps_masker.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- nilearn/maskers/tests/test_nifti_maps_masker.py
- nilearn/maskers/tests/test_nifti_masker.py
- nilearn/maskers/tests/test_nifti_spheres_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- nilearn/maskers/tests/test_surface_maps_masker.py
- nilearn/maskers/tests/test_surface_masker.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- nilearn/regions/tests/test_region_extractor.py
- nilearn/regions/tests/test_rena_clustering.py
- Closes none but relates to #4538
make sure all estimators comply with: 
-   "check_transformer_n_iter",
-    "check_transformers_unfitted",
> [MAINT] add transformer checks for all estimators

- nilearn/mass_univariate/permuted_least_squares.py
> [REF] refactor permuted_ols

- nilearn/conftest.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- nilearn/maskers/tests/test_surface_maps_masker.py
- nilearn/maskers/tests/test_surface_masker.py
- nilearn/plotting/tests/test_surf_plotting.py
- nilearn/regions/tests/test_rena_clustering.py
- nilearn/surface/tests/test_surface.py
- Closes none
- make sure surf_mesh fixture returns a polymesh and not a function
> [MAINT] make sure surf_mesh fixture returns a polymesh

- nilearn/plotting/_utils.py
- nilearn/plotting/html_surface.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_surf_plotting.py
- nilearn/surface/surface.py
> [REF] refactor plot_surf_contours

- nilearn/_utils/class_inspect.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/maskers/tests/test_nifti_masker.py
- Closes none
- extract dtype check from test_nifti_masker into a check to run on all nifti maskers
> [MAINT] add check dtype for all nifti maskers

- nilearn/_utils/param_validation.py
- nilearn/_utils/tests/test_param_validation.py
- Closes #5028 
- I wasn't sure where to place the new checks but chose where boolean inputs are converted into integers
> Check that sample_mask ends up as array of signed integers

- nilearn/maskers/tests/test_surface_maps_masker.py
- Closes #5096
- skip test on windows, old mpl, new np
-
> [TEST] skip test on windows, old mpl, new np

- doc/versions.rst
- doc/visual_testing/reporter_visual_inspection_suite.py
- examples/03_connectivity/plot_group_level_connectivity.py
- examples/07_advanced/plot_age_group_prediction_cross_val.py
- Closes none
- add links to doc 0.11.0 and 0.10.3
- minor changes in script to generate reports to avoid some warnings
- fixes in examples that failed on main because of change in datasets outputs type
> [DOC] Add link to older doc versions

- examples/05_glm_second_level/plot_second_level_two_sample_test.py
- Closes #5114
- update thresholding in example to show both activation and 'deactivation'
> [FIX] update thresolding in paired / unpaired t-test example

- nilearn/_utils/class_inspect.py
- Closes none
- remove obsolete check to skip
> [MAINT] remove obsolete check to skip

- doc/changes/latest.rst
- doc/modules/plotting.rst
- doc/references.bib
- examples/04_glm_first_level/plot_bids_features.py
- nilearn/_utils/tests/test_common.py
- nilearn/conftest.py
- nilearn/plotting/__init__.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting/test_plot_bland_altman.py
- Closes #4089 
- add a function to create a bland altman plot of 2 images
> [ENH] add plot_bland_altman function

- doc/changes/latest.rst
- examples/01_plotting/plot_surf_stat_map.py
- examples/07_advanced/plot_surface_image_and_maskers.py
- nilearn/maskers/surface_labels_masker.py
- Closes none but fixes some dtype edge cases for redution strategy in SurfaceLabelsMasker
- Specify output dtype of SurfaceLabelsMasker.transform
> [FIX] Specify output dtype of SurfaceLabelsMasker.transform

- nilearn/conftest.py
- nilearn/maskers/tests/test_multi_nifti_labels_masker.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- Closes none but relates to
- https://github.com/nilearn/nilearn/issues/3570
- https://github.com/nilearn/nilearn/issues/3331
> [REF] refactor test label maskers

- nilearn/datasets/tests/test_utils.py
- nilearn/decoding/tests/test_space_net.py
- nilearn/tests/test_init.py
- nilearn/tests/test_masking.py
- nilearn/tests/test_package_import.py
- pyproject.toml
- Closes none but relates to
- https://github.com/nilearn/nilearn/issues/3570
- https://github.com/nilearn/nilearn/issues/3331
> [REF] refactor test masking

- nilearn/_utils/docs.py
- nilearn/_utils/param_validation.py
- nilearn/typing.py
- Closes none
- check type of more parameters defined in _utils.doc
> [ENH] extend type checking at run time

- nilearn/_utils/docs.py
- nilearn/plotting/_utils.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/find_cuts.py
- nilearn/plotting/img_comparison.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_img_plotting/test_plot_roi.py
- pyproject.toml
- Closes none
- Initally related to https://github.com/nilearn/nilearn/issues/3655 but realized this could lead to a refactor across several plotting functions
- create a single function to handle figure saving independently of we are dealing with a figure, class, display...
- rename a function that had a leading underscore eventhough it was used outside of its module
> [REF] extract function to save figure

- nilearn/signal.py
- nilearn/tests/test_signal.py
- pyproject.toml
- Closes none but relates to
- https://github.com/nilearn/nilearn/issues/3570
- https://github.com/nilearn/nilearn/issues/3331
---
- make tests shorter
- add docstring to each test
- extract test for errors into separate tests with a check on the error message
> [REF] refactor tests signals

- examples/00_tutorials/plot_single_subject_single_run.py
- examples/04_glm_first_level/plot_bids_features.py
- nilearn/reporting/get_clusters_table.py
- Closes #3940
- mention atlasreader package to locate clusters
> [DOC] mention atlasreader package to locate clusters

- nilearn/decomposition/_base.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
- nilearn/maskers/nifti_labels_masker.py
- nilearn/maskers/nifti_maps_masker.py
- nilearn/maskers/nifti_masker.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/maskers/surface_labels_masker.py
- nilearn/maskers/surface_maps_masker.py
- nilearn/maskers/surface_masker.py
- Closes none
Remove Memory 'handling' that are handling as all classes where they occur inherit from 
nilearn._utils.cache_mixin.CacheMixin that handles a proper initialization with check_memory.
> [REF] remove unnecessary memory handling

- nilearn/image/resampling.py
- pyproject.toml
- Related to [#3655](https://github.com/nilearn/nilearn/issues/3655)
- extract checks if resamping is needed
> [REF] refactor resampling

- nilearn/interfaces/fmriprep/tests/test_load_confounds.py
- nilearn/interfaces/fmriprep/tests/test_load_confounds_components.py
- nilearn/interfaces/fmriprep/tests/test_load_confounds_scrub.py
- nilearn/interfaces/tests/test_bids.py
- nilearn/interfaces/tests/test_fsl.py
- pyproject.toml
- Relates to [#3570](https://github.com/nilearn/nilearn/issues/3570)
- simplify long tests
- add doc strings to some tests
- use pyplot fixture
> [REF] refactor test interfaces

- .pre-commit-config.yaml
- nilearn/_utils/bids.py
- nilearn/_utils/data_gen.py
- nilearn/_utils/niimg.py
- nilearn/_utils/param_validation.py
- nilearn/_utils/tags.py
- nilearn/conftest.py
- nilearn/datasets/func.py
- nilearn/datasets/neurovault.py
- nilearn/datasets/tests/test_atlas.py
- nilearn/datasets/tests/test_utils.py
- nilearn/decoding/tests/test_same_api.py
- nilearn/interfaces/bids/query.py
- nilearn/maskers/_utils.py
- nilearn/maskers/multi_nifti_masker.py
- nilearn/maskers/surface_maps_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- nilearn/maskers/tests/test_surface_maps_masker.py
- nilearn/mass_univariate/tests/test_permuted_least_squares.py
- nilearn/plotting/cm.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/glass_brain_files/svg_to_json_converter.py
- nilearn/plotting/html_connectome.py
- nilearn/plotting/img_comparison.py
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/tests/test_displays.py
- nilearn/plotting/tests/test_surf_plotting.py
- nilearn/reporting/glm_reporter.py
- nilearn/reporting/html_report.py
- nilearn/surface/surface.py
- Closes none
Fix the following issues flagged by Sourcery: https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/ :
- yield-from
- inline-immediately-yielded-variable
- move-assign   
- remove-str-from-print   
- collection-into-set
- merge-comparisons
- use-next
- skip-sorted-list-construction
- merge-duplicate-blocks 
- lift-duplicated-conditional 
- invert-any-all
- comprehension-to-generator
> [REF] fix simple issues flagged by sourcery

- .github/workflows/testing_minimum.yml
- Closes none
- skip tests for: windows + matplotlib 3.3.0 + latest version of all other dependencies
- should fix failures on main like this one: https://github.com/nilearn/nilearn/actions/runs/13518511334/job/37837983433
> [MAINT] skip compare figures tests for windows + matplotlib 3.3.0

- .coveragerc
- Closes none
- include tests in coverage
- just to make sure we run all of them
- h/t @effigies
- refs:
- https://nedbatchelder.com/blog/201908/dont_omit_tests_from_coverage.html)
- https://www.youtube.com/watch?v=70T6OxKwxm0
> [MAINT] check coverage of tests file

- nilearn/conftest.py
- nilearn/regions/tests/test_region_extractor.py
- nilearn/reporting/tests/test_html_report.py
- Closes none but relates to https://github.com/nilearn/nilearn/issues/3331
- better reuse some test fixtures
> [REF] refactor fixtures

- doc/changes/latest.rst
- nilearn/datasets/description/yeo_2011.rst
- Closes #5183
- Add license information for Yeo 2011 Atlas
> [DOC] Add license for Yeo 2011 Atlas

- nilearn/_utils/tests/test_common.py
- nilearn/interfaces/bids/glm.py
- nilearn/plotting/_utils.py
- nilearn/plotting/cm.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/displays/_projectors.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/displays/_utils.py
- nilearn/plotting/edge_detect.py
- nilearn/plotting/find_cuts.py
- nilearn/plotting/html_connectome.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/html_surface.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_baseline_comparisons.py
- nilearn/plotting/tests/test_displays.py
- nilearn/plotting/tests/test_html_connectome.py
- nilearn/plotting/tests/test_html_stat_map.py
- nilearn/plotting/tests/test_html_surface.py
- nilearn/plotting/tests/test_img_comparisons.py
- nilearn/plotting/tests/test_matrix_plotting.py
- nilearn/plotting/tests/test_surf_plotting.py
- nilearn/plotting/tests/test_utils.py
- Closes None
- Update imports to use absolute paths
- Update imports to use package level paths where possible:
eg. `from nilearn.plotting import plot_design_matrix` instead of `from nilearn.plotting.matrix_plotting import plot_design_matrix`
- move utility functions to `_utils` module
> [ENH] Refactor plotting imports

- doc/modules/index.rst
- Closes none
- aims to avoid having an empty API landing page (particularly obvious on modile)
> [DOC] show API main modules in doc

- nilearn/__init__.py
- nilearn/maskers/surface_labels_masker.py
- nilearn/maskers/surface_maps_masker.py
- nilearn/maskers/surface_masker.py
- nilearn/plotting/cm.py
- nilearn/plotting/displays/_projectors.py
- nilearn/plotting/html_connectome.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/html_surface.py
- nilearn/plotting/img_comparison.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/surf_plotting.py
- nilearn/reporting/glm_reporter.py
- Closes none
- Should make it easier to ensure consistency in terms of plotting
> [REF] Create single variable to set default colormaps

- doc/modules/plotting.rst
- Closes none
-  fix headings in plotting API page
> [FIX] fix headings in plotting API page

- nilearn/_utils/estimator_checks.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/maskers/surface_maps_masker.py
- Closes #5091
- add masker check to make sure they can be refitted with different attributes to give different results
> [FIX] ensure maskers can be refitted

- nilearn/_utils/estimator_checks.py
- nilearn/connectome/tests/test_connectivity_matrices.py
- nilearn/connectome/tests/test_group_sparse_cov.py
- nilearn/decoding/tests/test_decoder.py
- nilearn/decoding/tests/test_searchlight.py
- nilearn/decomposition/tests/test_base.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/decomposition/tests/test_dict_learning.py
- nilearn/decomposition/tests/test_multi_pca.py
- nilearn/glm/tests/test_first_level.py
- nilearn/glm/tests/test_second_level.py
- nilearn/maskers/tests/conftest.py
- nilearn/maskers/tests/test_multi_nifti_labels_masker.py
- nilearn/maskers/tests/test_multi_nifti_maps_masker.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- nilearn/maskers/tests/test_nifti_maps_masker.py
- nilearn/maskers/tests/test_nifti_masker.py
- nilearn/maskers/tests/test_nifti_spheres_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- nilearn/maskers/tests/test_surface_maps_masker.py
- nilearn/maskers/tests/test_surface_masker.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- nilearn/regions/tests/test_region_extractor.py
- nilearn/regions/tests/test_rena_clustering.py
- relates to https://github.com/nilearn/nilearn/issues/4538
- make all estimators pass
- "check_do_not_raise_errors_in_init_or_set_params",
- "check_estimators_fit_returns_self"
- use expected_failed_checks for the maskers that do not yet pass those checks
> [REF] refactor valid check_estimators 

- doc/connectivity/connectome_extraction.rst
- doc/connectivity/parcellating.rst
- doc/connectivity/region_extraction.rst
- doc/manipulating_images/manipulating_images.rst
- doc/manipulating_images/masker_objects.rst
- doc/plotting/index.rst
- Closes https://github.com/nilearn/nilearn/issues/4275
- do not use scale to let image adapt to div width
> [STY] fix some image resizing on mobile

- .prettierignore
- examples/02_decoding/plot_haxby_glm_decoding.py
- nilearn/glm/_base.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
- nilearn/reporting/data/html/glm_report.html
- nilearn/reporting/data/html/method_section.html
- nilearn/reporting/glm_reporter.py
- Closes #4493
- generate a method section for GLM reports
> [ENH] generate method section in GLM reports

- nilearn/_utils/estimator_checks.py
- nilearn/_utils/tags.py
- nilearn/conftest.py
- nilearn/glm/_base.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
- relates to https://github.com/nilearn/nilearn/issues/4538
- add 2 checks to replace the sklearn ones that cannot be run on GLM estimators
> [MAINT] add glm estimator checks

- nilearn/_utils/estimator_checks.py
- nilearn/connectome/tests/test_connectivity_matrices.py
- nilearn/connectome/tests/test_group_sparse_cov.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- nilearn/regions/tests/test_rena_clustering.py
- Relates to #4538
- further refactor of 'valid' sklearn checks
- expand list of of valid sklearn checks but specify explicitly why some tests need to be skipped
> [REF] refactor more extra_valid_checks into expected_failed_checks

- nilearn/_utils/helpers.py
- nilearn/glm/_utils.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/first_level/hemodynamic_models.py
- Closes none
- hoist some import outside of function bodies
> [REF] hoist imports

- examples/02_decoding/plot_haxby_searchlight.py
- nilearn/decoding/searchlight.py
- Closes #4668 
- move the warning filter to be in the jolib call and not out of it
> [FIX] reduce number of warning during searchligh

- nilearn/glm/_base.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
- nilearn/glm/tests/test_first_level.py
- nilearn/glm/tests/test_second_level.py
> [REF] rename _get_voxelwise_model_attribute

- examples/07_advanced/plot_surface_image_and_maskers.py
> [FIX][DOC] make sure figure in plot_surface_image_and_maskers is created and shown in same cell

- nilearn/_utils/estimator_checks.py
- nilearn/maskers/surface_labels_masker.py
- nilearn/maskers/surface_maps_masker.py
- nilearn/maskers/surface_masker.py
- nilearn/regions/region_extractor.py
- Closes none
- make sure that maskers fit and transform throw a type error if mask and images to fit / transform are of incompatible types.
> [ENH] check compatibily of inputs to fit and transform for maskers

- nilearn/_utils/bids.py
- nilearn/_utils/masker_validation.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
- nilearn/plotting/displays/_slicers.py
- Closes none
- vaguely relates to https://github.com/nilearn/nilearn/issues/3469 and what kind of images we accept as inputNiimgLike
- reuse a NiimgLike 'type' where possible
> [REF] use NiimgLike typing where possible

- nilearn/image/image.py
- relates to #5272
- fixes some mention of nilearn surface in the doc strings
> [DOC] improve doc nilearn.image

- nilearn/connectome/connectivity_matrices.py
- nilearn/connectome/group_sparse_cov.py
- nilearn/decomposition/_base.py
- nilearn/decomposition/canica.py
- nilearn/glm/_base.py
- nilearn/glm/_utils.py
- nilearn/glm/contrasts.py
- nilearn/glm/first_level/design_matrix.py
- nilearn/glm/first_level/experimental_paradigm.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/first_level/hemodynamic_models.py
- nilearn/glm/second_level/second_level.py
- nilearn/glm/thresholding.py
- nilearn/image/image.py
- nilearn/image/resampling.py
- nilearn/input_data/__init__.py
- nilearn/interfaces/bids/glm.py
- nilearn/interfaces/bids/query.py
- nilearn/interfaces/fmriprep/load_confounds.py
- nilearn/interfaces/fmriprep/load_confounds_scrub.py
- nilearn/interfaces/fmriprep/load_confounds_strategy.py
- nilearn/regions/hierarchical_kmeans_clustering.py
- nilearn/regions/parcellations.py
- nilearn/regions/rena_clustering.py
- nilearn/regions/signal_extraction.py
- nilearn/reporting/get_clusters_table.py
- nilearn/reporting/glm_reporter.py
- nilearn/reporting/html_report.py
- nilearn/surface/surface.py
- Closes none but relates to https://github.com/nilearn/nilearn/issues/4797
- use dynamic stacklevel finding rather hard coded ones
> [ENH] use dynamic stacklevel finding for warnings

- .github/workflows/build-docs.yml
- maint_tools/check_docstrings.py
- maint_tools/missing_default_in_docstring.py
- maint_tools/show-python-packages-versions.py
- tox.ini
- Closes none
- make sure that the couple of doc quality control script we have are run in CI to flag doc strings with missing default and mostly with fixable problems
> [MAINT] run doc qc scripts in CI 

- doc/changes/latest.rst
- nilearn/image/image.py
- nilearn/image/tests/test_image.py
- Closes #5288
- ensure mean_img can work on iterable of surface images
> [ENH] compute mean of means for list of surface images

- doc/changes/latest.rst
- Closes none but fixes the doc build failure because of a changelog entry eg: https://github.com/nilearn/nilearn/actions/runs/14218571913/job/39840967107?pr=5280#step:13:1538
- remove the s from nilearn.image.iter_img in changelog entry
> [FIX] changelog entry

- .github/workflows/testing_minimum.yml
- Closes none
- generate a report.html for tests run with minimum dependencies to [avoid these warnings in CI](https://github.com/nilearn/nilearn/actions/runs/14227950144)
> [FIX] create report html for tests with minimum dependencies

- examples/05_glm_second_level/plot_oasis.py
- nilearn/glm/_base.py
- Closes but should fix doc build on main
- filenames for nifti / gifti was not properly generated (ended in .json)
> [FIX] fix filenames when saving GLM to BIDS

- .github/workflows/test_with_tox.yml
- tox.ini
- Closes none
- generate HTML report of code coverage and upload them after running tests
> [ENH] upload HTML report of code coverage

- .github/workflows/benchmark.yml
- Closes none but fixes the benchmarks action: https://github.com/nilearn/nilearn/actions/runs/14433876048/job/40471964529#step:7:10
- need to cd into asv_benchmarks and then run everything
- also allow running via github UI rather than a commit on the main
> [FIX] Github action for running benchmarks

- .github/workflows/benchmark.yml
- build_tools/github/set_machine_name.py
- Closes none but the benchmarking action is still failing: https://github.com/nilearn/nilearn/actions/runs/14464873362/job/40564812919 
- will try running and debuggin via my fork
-
> [FIX] failing benchmark github action attempt 2

- .github/workflows/benchmark.yml
- Closes none but fixes new failure errors: https://github.com/nilearn/nilearn/actions/runs/14468490841/job/40576313354#step:11:22 and https://github.com/nilearn/nilearn/actions/runs/14468490841/job/40576313354#step:12:24
- correct path to find artifacts to be uploaded
- use the correct tmp ssh sock
> [FIX] failing benchmark github action attempt 3

- nilearn/glm/_base.py
- nilearn/glm/first_level/first_level.py
- follow up to #5320
- use legacy=False to parse FLM filenames inputs as bids files
> [FIX] use legacy=False to parse FLM filenames inputs as bids files

- README.rst
- doc/index.rst
- nilearn/image/image.py
- Closes none
- improve doc nilearn.image
> [DOC] misc doc improvements related to handling surface

- .github/workflows/test_atlases.yml
- maint_tools/check_atlas.py
- nilearn/_utils/bids.py
- nilearn/maskers/nifti_labels_masker.py
- Closes #4331 
- minor changes to make sure all nilearn atlases are usable
- allow look up tables to not contain all values present in an atlas (most often missing the background label)
> [ENH] ensure that all atlases are usable

- examples/07_advanced/plot_mask_large_fmri.py
- Closes none but revisits example [plot_mask_large_fmri](https://nilearn.github.io/dev/auto_examples/07_advanced/plot_mask_large_fmri.html) after the findings in https://github.com/nilearn/nilearn/pull/5128#discussion_r2021726878
- I think the issues seen due to numpy mmap'ed arrays in [comment](https://github.com/nilearn/nilearn/pull/5128#discussion_r2021726878) do not show up here because we are doing (almost) everything inside functions
- the only exception here is the initial loading of images, which I have now moved under a function
- Additionally, I confirm that by profiling each case separately in a script via the command line `mprof`. This gives us timeseries of memory usage. These timeseries show two things:
- each "child" process shows up …
> [ENH] Revisit example plot_mask_large_fmri

- maint_tools/plot_test_timing.py
- Closes none but fixes failing script on python 3.10 on windows https://github.com/nilearn/nilearn/actions/runs/14832742581/job/41637374790#step:7:15792
- convert int to str
-
> [FIX] Failing script for plotting test timing on windows python 3.10

- nilearn/_utils/estimator_checks.py
- nilearn/conftest.py
- nilearn/maskers/tests/conftest.py
- nilearn/maskers/tests/test_multi_nifti_maps_masker.py
- nilearn/maskers/tests/test_nifti_maps_masker.py
- nilearn/regions/tests/test_region_extractor.py
- Closes none
- create a new fixture for tests that require larger 3D images
> [REF] create large 3D shape fixture

- .github/workflows/test_atlases.yml
- Closes none
- only test label maskers on real atlases on main to minimize CI runs (and also failures when atlases cannot be fetched)
> [MAINT] only test label maskers on real atlases on main

- pyproject.toml
- tox.ini
- Closes https://github.com/nilearn/nilearn/issues/5384
- skip version 6.1.0 of plotly
> [FIX] skip plotly 6.1.0

- nilearn/plotting/_utils.py
- nilearn/plotting/displays/_axes.py
- nilearn/plotting/displays/_figures.py
- nilearn/plotting/displays/_projectors.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/find_cuts.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/img_comparison.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/plotting/matrix/matrix_plotting.py
- nilearn/plotting/surface/_backend.py
- nilearn/plotting/surface/_matplotlib_backend.py
- nilearn/plotting/surface/_utils.py
- nilearn/plotting/surface/html_surface.py
- nilearn/plotting/surface/surf_plotting.py
- pyproject.toml
- Closes #4797
- add stacklevel to all warnings in plotting
> [FIX] add stacklevel to warnings in plotting

- doc/changes/latest.rst
- nilearn/glm/first_level/first_level.py
- nilearn/glm/tests/test_first_level.py
- Relates to #5380 
- change default of slice_time_ref in first_level_from_bids
- update tests and doc string
> [DEP] change default of slice_time_ref in first_level_from_bids

- nilearn/plotting/surface/_backend.py
- nilearn/plotting/surface/_matplotlib_backend.py
- nilearn/plotting/surface/_plotly_backend.py
- nilearn/plotting/surface/surf_plotting.py
- nilearn/plotting/surface/tests/test_surf_plotting.py
- Closes None, but relates to:
- #5234 
- #5253 
- #5276
- #5282 
- #5322
- #5349
- #5389
-  Refactor `plotting.surface.surf_plotting.plot_surf_roi` to separate matplotlib code to `_matplotlib_backend` and plotly code to `_plotly_backend` and common parts to `backend`
- Add/update missing docstrings for tests in `test_surf_plotting` for `plot_surf_roi`
> [ENH] Refactor to separate backends for plot_surf_roi

- nilearn/_utils/estimator_checks.py
- Closes none
- reorder estimator checks alphabetically
> [REF] sort estimator checks

- nilearn/image/image.py
- nilearn/image/tests/test_image.py
- nilearn/surface/utils.py
- Closes #5289 
- Relates to #5272
- add surface support to math_img and binarize_img
- add tests
- fix some other doc strings in nilearn.image
> [ENH] add surface support to math_img and binarize_img

- nilearn/_utils/estimator_checks.py
- nilearn/connectome/tests/test_group_sparse_cov.py
- nilearn/decoding/tests/test_decoder.py
- nilearn/decomposition/tests/test_base.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/decomposition/tests/test_dict_learning.py
- nilearn/decomposition/tests/test_multi_pca.py
- nilearn/glm/tests/test_first_level.py
- nilearn/glm/tests/test_second_level.py
- nilearn/maskers/tests/test_multi_nifti_labels_masker.py
- nilearn/maskers/tests/test_multi_nifti_maps_masker.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/maskers/tests/test_nifti_labels_masker.py
- nilearn/maskers/tests/test_nifti_maps_masker.py
- nilearn/maskers/tests/test_nifti_masker.py
- nilearn/maskers/tests/test_nifti_spheres_masker.py
- nilearn/maskers/tests/test_surface_labels_masker.py
- nilearn/maskers/tests/test_surface_maps_masker.py
- nilearn/maskers/tests/test_surface_masker.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- nilearn/regions/tests/test_region_extractor.py
- nilearn/regions/tests/test_rena_clustering.py
- Closes none
- refactor estimator checks to run the nilearn ones and the sklearn ones separately
> [REF] extract nilearn check_estimators

- AUTHORS.rst
- CITATION.cff
- Closes none
- update list of core devs
> [MAINT] update list of core devs

- nilearn/_utils/estimator_checks.py
- nilearn/regions/tests/test_region_extractor.py
- Avoid multiple imports of the same name
> [MAINT] Multiple imports for an import name

- nilearn/surface/surface.py
- use `enumerate()` instead of `range(len())`
> [MAINT] Implicit enumerate call

- .github/workflows/testing_minimum.yml
- Closes none
- revert a change from a PR that should not have made it in main
> [MAINT] do not test all minimum dependencies on PR

- nilearn/_utils/estimator_checks.py
- nilearn/_utils/niimg_conversions.py
- nilearn/_utils/plotting.py
- nilearn/_utils/tests/test_estimator_checks.py
- nilearn/_utils/tests/test_helpers.py
- nilearn/conftest.py
- nilearn/datasets/func.py
- nilearn/decoding/searchlight.py
- nilearn/decomposition/dict_learning.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/glm/_utils.py
- nilearn/glm/contrasts.py
- nilearn/glm/first_level/design_matrix.py
- nilearn/glm/first_level/experimental_paradigm.py
- nilearn/glm/first_level/hemodynamic_models.py
- nilearn/glm/regression.py
- nilearn/image/image.py
- nilearn/interfaces/bids/glm.py
- nilearn/interfaces/fmriprep/load_confounds_utils.py
- nilearn/interfaces/tests/test_bids.py
- nilearn/maskers/nifti_maps_masker.py
- nilearn/maskers/nifti_spheres_masker.py
- nilearn/masking.py
- nilearn/plotting/_utils.py
- nilearn/plotting/tests/test_find_cuts.py
- nilearn/plotting/tests/test_img_comparisons.py
- nilearn/reporting/glm_reporter.py
- nilearn/signal.py
- Fix typos.
- Start applying [Sourcery](https://sourcery.ai/) suggestions.
> [MAINT] Fix typos and apply Sourcery suggestions

- nilearn/_utils/estimator_checks.py
- nilearn/regions/tests/test_hierarchical_kmeans_clustering.py
- Relates to #5442
- adapt estimator checks for HierarchicalKMeans (fewer expected clusters) to be able to rely on the sklearn checks
> [MAINT] run some more sklearn checks on HierarchicalKMeans

- nilearn/glm/first_level/first_level.py
- nilearn/glm/tests/test_first_level.py
- nilearn/glm/tests/test_second_level.py
- Closes #5408 
- throw warning when some attributes passed at first level model init will be ignored at fit time
> [FIX] warn when some attributes passed at first level model init will be ignored at fit time

- CITATION.cff
- doc/conf.py
- Closes none
- fix / ignore some deadlinks
> [MAINT] fix links

- .github/workflows/build-docs.yml
- examples/03_connectivity/plot_group_level_connectivity.py
- nilearn/_utils/estimator_checks.py
- nilearn/connectome/connectivity_matrices.py
- nilearn/connectome/tests/test_connectivity_matrices.py
- nilearn/glm/tests/test_second_level.py
- Fixes https://github.com/nilearn/nilearn/pull/5424#issuecomment-2990087910
- make ConnectivityMeasure more flexible in the input it accepts
- one of our examples actually passes a 3D array to fit (so an iterable of 2D arrays) and this worked before #5424
> [FIX] fix input connectivity matrices

- AUTHORS.rst
- doc/changes/0.12.0.rst
- doc/changes/latest.rst
- doc/changes/whats_new.rst
- doc/maintenance.rst
- doc/versions.rst
- maint_tools/citation_cff_maint.py
- nilearn/image/image.py
- Closes none
- resets files post release
> [MAINT] post release

- nilearn/decomposition/tests/test_dict_learning.py
- nilearn/regions/tests/test_parcellations.py
> [MAINT] mark slow test

- examples/02_decoding/plot_haxby_full_analysis.py
- examples/02_decoding/plot_haxby_glm_decoding.py
- examples/02_decoding/plot_mixed_gambles_frem.py
- examples/04_glm_first_level/plot_adhd_dmn.py
- examples/06_manipulating_images/plot_roi_extraction.py
- examples/06_manipulating_images/plot_smooth_mean_image.py
- examples/07_advanced/plot_ica_neurovault.py
- nilearn/decoding/decoder.py
- nilearn/glm/first_level/first_level.py
- nilearn/maskers/nifti_masker.py
- Closes none
-  reduce number of warnings in examples
-
> [DOC] reduce number of warnings in examples

- nilearn/_utils/estimator_checks.py
- nilearn/connectome/connectivity_matrices.py
- Relates #5441
- add n_features_in_ to ConnectivityMeasure during fitting
> [MAINT] add n_features_in_ to ConnectivityMeasure

- nilearn/_utils/estimator_checks.py
- nilearn/decomposition/tests/conftest.py
- nilearn/decomposition/tests/test_decomposition_estimators.py
- nilearn/regions/hierarchical_kmeans_clustering.py
- nilearn/regions/rena_clustering.py
- pyproject.toml
- Closes none
- perform check that was skipped for decomposition estimators
> [MAINT] ensure decomposition estimator return self

- nilearn/decoding/tests/conftest.py
- nilearn/decoding/tests/test_decoder.py
- nilearn/glm/contrasts.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/tests/test_first_level.py
- Closes none
- reduce number of warnings in doc build and test suite
> [MAINT] silence warnings in test and doc build

- nilearn/_utils/estimator_checks.py
- Closes none
- minor refactor for clustering estimators expected failed checks: turns out rena and kmeans should fail the same checks
> [REF] minor refactor for clustering estimators expected failed checks

- nilearn/_utils/estimator_checks.py
- Closes none
- ignore warnings when running nilearn estimator checks
> [MAINT] ignore warnings for nilearn check estimators

- nilearn/connectome/connectivity_matrices.py
I may be missing something, but I don't see why a set was added here.
> [MAINT] Unnecessary comprehension

- nilearn/decomposition/tests/test_decomposition_estimators.py
- nilearn/regions/tests/test_parcellations.py
- Closes none
- set no timeout on some slow tests
> [MAINT] mark slow tests

- nilearn/_utils/tests/test_common.py
- nilearn/plotting/_engine_utils.py
- nilearn/plotting/_utils.py
- nilearn/plotting/html_connectome.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/plotting/surface/_matplotlib_backend.py
- nilearn/plotting/surface/_plotly_backend.py
- nilearn/plotting/surface/html_surface.py
- nilearn/plotting/surface/surf_plotting.py
- nilearn/plotting/surface/tests/test_html_surface.py
- nilearn/plotting/surface/tests/test_matplotlib_backend.py
- nilearn/plotting/tests/test_engine_utils.py
- nilearn/plotting/tests/test_html_stat_map.py
- nilearn/plotting/tests/test_js_plotting_utils.py
- Closes None
- Move utility functions importing from `matplotlib`  and used by multiple modules to `plotting._engine_utils`.
> There is no change in code, just functions are moved across modules.
> [ENH] Refactor plotting to extract engine utils

- doc/changes/latest.rst
- doc/modules/generated_reports/masker_reports_examples.rst
- examples/03_connectivity/plot_atlas_comparison.py
- examples/03_connectivity/plot_group_level_connectivity.py
- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_multi_subject_connectome.py
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
- examples/07_advanced/plot_age_group_prediction_cross_val.py
- nilearn/image/image.py
- nilearn/maskers/nifti_maps_masker.py
- Closes #5515 
- change resampling interpolation of maps by NiftiMapsMasker
> [FIX] change resampling interpolation of maps

- CITATION.cff
Never added my name to citation list when contributing to PR #4501, I have now done that.
> added my name to citation list

- doc/changes/latest.rst
- fixes error in doc build that can be seen on main
https://github.com/nilearn/nilearn/actions/runs/16780106791/job/47519382056#step:13:20513
```
/home/runner/work/nilearn/nilearn/doc/changes/latest.rst:17: WARNING: py:class reference target not found: nilearn.surface.surface.Polydata
```
> [DOC] fix bad reference in changelog

- nilearn/_utils/estimator_checks.py
- Relates to #5446, #5445, #5444, #5447
- add check_pipeline_consistency for nilearn estimators
> [MAINT] add check_pipeline_consistency for nilearn estimators

- doc/changes/latest.rst
- nilearn/_utils/estimator_checks.py
- nilearn/decoding/decoder.py
- nilearn/decoding/searchlight.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/second_level/second_level.py
- Closes none
- implement replacement for sklearn checks on n_feature_in
- see https://scikit-learn.org/stable/developers/develop.html#universal-attributes
> [FIX] check n_features_in_ for estimators

- CITATION.cff
- doc/changes/names.rst
- Closes none
- fixes a link redirect (see https://github.com/nilearn/nilearn/actions/runs/17149625016/job/48652686004#step:6:1949)
> [MAINT] fix link redirect

- nilearn/interfaces/tests/test_bids.py
- nilearn/plotting/_engine_utils.py
- nilearn/plotting/_utils.py
- nilearn/plotting/surface/_matplotlib_backend.py
- nilearn/plotting/surface/_utils.py
- nilearn/plotting/surface/tests/test_utils.py
- Closes None
- Refactors `nilearn.plotting.surface._matplotlib_backend` to extract common code to 3 functions:
- get_bg_data
- _normalize_bg_data
- _apply_darkness
- Add docstring for `get_colorbar_and_data_ranges`
> This PR is part of changes in https://github.com/nilearn/nilearn/pull/5537/files to simplify code review.
> [ENH] Refactor `nilearn.plotting`: extract common code

- doc/changes/latest.rst
- doc/changes/whats_new.rst
- doc/maintenance.rst
- Closes none
- reset docs post release
> [MAINT] post-release

- nilearn/maskers/base_masker.py
- Closes none
- typo 'resamping' -> 'resampling'
> [FIX] typo 'resamping' -> 'resampling'

- nilearn/tests/test_signal.py
- Closes none
- improve some tests for signal.py via mutation testing
- run mutatest on main to detect surviving mutations (change in the codebase that would not be detected by the test suite)
```bash
pip install mutatest
mutatest -s nilearn/signal.py -t "pytest nilearn/tests/test_signal.py" -r 314
```
> [MAINT] improve some tests for signal.py via mutation testing

- nilearn/_utils/tests/test_common.py
- nilearn/maskers/_mixin.py
- nilearn/maskers/base_masker.py
- nilearn/maskers/nifti_labels_masker.py
- nilearn/maskers/surface_labels_masker.py
- Closes none
- move methods and functions only used by label maskers into the LabelsMaskerMixin
> [REF] extract label properties and functions to mixin

- doc/Makefile
- nilearn/datasets/func.py
- pyproject.toml
- Closes none but should fix doc build in main
> [FIX] revert one path change

- nilearn/_utils/helpers.py
- nilearn/plotting/surface/_matplotlib_backend.py
- Closes none
- remove some hacks that were necessary to deal with older matplotlib
> [MAINT] clean up post matplotlib version bump

- doc/conf.py
- maint_tools/check_docstrings.py
- maint_tools/check_gha_workflow.py
- maint_tools/check_glossary_term.py
- maint_tools/check_private.py
- maint_tools/citation_cff_maint.py
- maint_tools/utils.py
- nilearn/_utils/data_gen.py
- nilearn/_utils/tests/test_data_gen.py
- nilearn/glm/first_level/first_level.py
- nilearn/interfaces/bids/query.py
- nilearn/interfaces/bids/utils.py
- nilearn/maskers/multi_surface_masker.py
- nilearn/maskers/surface_masker.py
- nilearn/plotting/image/tests/test_img_plotting.py
- nilearn/typing.py
- Closes none
- importing annotation from future seems not needed anymore
> [MAINT] remove import annotation

- nilearn/_utils/estimator_checks.py
- nilearn/_utils/param_validation.py
- nilearn/connectome/tests/test_connectivity_matrices.py
- nilearn/decoding/space_net.py
- nilearn/decomposition/tests/conftest.py
- nilearn/glm/first_level/first_level.py
- nilearn/image/tests/test_image.py
- nilearn/maskers/multi_nifti_masker.py
- nilearn/maskers/surface_masker.py
- nilearn/maskers/tests/test_multi_nifti_masker.py
- nilearn/maskers/tests/test_nifti_masker.py
- nilearn/masking.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/plotting/_utils.py
- nilearn/reporting/data/js/carousel.js
- Closes none
- should reduce number of issues flagged by https://github.com/nilearn/nilearn/actions/workflows/sourcery.yml
> [REF] apply sourcery refactoring suggestions
