nilearn/nilearn

nilearn/datasets.py

This PR add an error message if a string instead of a list of string is given in the localizer fetching function (I think that it may be a common mistake and the previous error message was cryptic). I also removed the variables for the URL when using default verbose option (verbose=0). The full URL is still displayed if verbose > 0 (fix #316).

Better error message for localizer, simpler error message.

---

examples/.gitignore

See issue #343 for details.
**Limitations:**
Since the outputs use relative paths, this will only work if you run the examples from anywhere within the `examples` subdirectory.  If, for example, you run this from the base directory (`nilearn`, you'll still see these files show up.
If desired, I could change the examples to output to the same directory that the example file resides in, rather than the current working directory.

Ignore all current example file-based outputs.

---

nilearn/input_data/base_masker.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_region.py
nilearn/input_data/tests/test_base_masker.py
nilearn/input_data/tests/test_multi_nifti_masker.py
nilearn/input_data/tests/test_nifti_region.py
nilearn/masking.py
nilearn/plotting/img_plotting.py
nilearn/region.py
nilearn/tests/test_masking.py
nilearn/tests/test_region.py

Some functions with mask arguments did not complain about iterables of niimg-like objects.
attempts to address #302

Added missing 3d-image enforcements

---

nilearn/plotting/displays.py

Fix #338.
* use plt.draw_if_interactive() to avoid having to do plt.draw()
manually
* use a solid rather than a transparent color to show the edges to make
them more visible

Fixes for add_edges et al. methods

---

nilearn/__init__.py
nilearn/version.py
setup.py

(edited to add link to original issue: fix #328)
**Summary:**
Previously, dependency checks were defined inside `__init__.py`.  I've:
* Moved the dependency check code to `version.py`
* Called the code from `__init__.py` and `setup.py`
This required some additional tweaks:
* Add metadata about which modules must be installed manually.
* Do slightly different dependency checks pre-setup (when we only need to check modules requiring manual installation) and post-setup (where we should check all modules).
There were a few other tiny tweaks I made, that I'll document inline.
**Testing:**
* I tested that `nilearn` installs properly when all dependencies are installed
* I tested that `nilearn` fails with an error message if one of the `manual_only` modules is not installed (in my case, …

Add dependency checks to setup.py

---

.travis.yml
continuous_integration/install.sh
nilearn/_utils/niimg_conversions.py
nilearn/datasets.py
nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py
nilearn/plotting/displays.py
nilearn/plotting/glass_brain.py
nilearn/plotting/glass_brain_files/svg_to_json_converter.py
nilearn/plotting/tests/test_img_plotting.py
nilearn/tests/test_datasets.py
nilearn/tests/test_masking.py
nilearn/tests/test_niimg_conversions.py
nilearn/version.py

This partially addresses #357.
There are a few issues preventing the setup script, code, and tests from running in Python 2.6:
* Trailing whitespace in `version.py` led to a setup syntax error.
* `"format_str{}".format(str)` is illegal in Python 2.6; use `"format_str{0}".format(str)`
* Dictionary comprehensions are NYI in Python 2.6; use `dict([list_comprehension])`
* Many `assert_X` functions are unavailable in Python 2.6; convert the few we were using to `assert_true`
* Context managers for `ZipFile`, `TarFile` don't exist in Python 2.6; wrap with `contextlib`
* Context manager for `nose.assert_raises` doesn't exist in Python 2.6; use our custom `assert_raises_regexp`, which was more appropriate anyway (since we wanted to check the error message of the error anyway).
I've also changed …

Enable Python 2.6 support

---

nilearn/plotting/img_plotting.py

...because colormaps refer to values in any time of image (BOLD, source-reconstructed, ROI, ...), rather than only anatomical images.

fix in docstrings of plotting functions

---

doc/data_analysis/decoding.rst
examples/connectivity/plot_connect_comparison.py
examples/decoding/plot_haxby_grid_search.py
examples/decoding/plot_haxby_multiclass.py
nilearn/_utils/extmath.py
nilearn/_utils/niimg_conversions.py
nilearn/_utils/testing.py
nilearn/datasets.py
nilearn/decomposition/multi_pca.py
nilearn/group_sparse_covariance.py
nilearn/image/image.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_masker.py
nilearn/masking.py
nilearn/mass_univariate/permuted_least_squares.py
nilearn/tests/test_datasets.py
nilearn/tests/test_extmath.py
nilearn/tests/test_group_sparse_covariance.py
nilearn/tests/test_niimg_conversions.py

Fix for #366
The `verbosity` parameter should control output from a function, with `0` meaning no output (and a non-zero default for functions that we want to output by default.  In some functions, current behavior was to always output. 
Here, I have fixed the above, tweaked docstrings, and changed places where `verbose` was passed as a boolean to be passed as an int.
I've also made changes to the testing code, to suppress output by forcing `verbose=0`.  With this, we can expect no output in tests--allowing browsing test results more cleanly and exposing more clearly unexpected prints and warnings.

Verbosity=0 should mean silent

---

nilearn/_utils/cache_mixin.py
nilearn/_utils/niimg_conversions.py
nilearn/decomposition/multi_pca.py
nilearn/group_sparse_covariance.py
nilearn/input_data/base_masker.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_masker.py
nilearn/input_data/nifti_region.py
nilearn/tests/test_cache_mixin.py

Addresses #385.
Fix semantic problems in cache_mixin that led to misuse of the functions. Shorten the code.
Roadmap:

Fix cache mixin

---

nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py

Copying the data makes the array C contiguous and the int32 index a lot less likely to overflow
in the scipy C code. Add test.
Full disclosure: I haven't investigated the penalty performance of copying the data for big images. I tried to put together a heuristic a little while ago to decide whether the array was big enough to trigger this segmentation fault but I didn't have time to investigate fully.
Fixes #346.

[MRG] Resample_img segmentation fault

---

nilearn/plotting/img_plotting.py

Fix for #389
added `colorbar` argument, set to ~~`true`~~ `false` by default.

[MRG] Adding colorbar argument to plot_img (fix #389)

---

.travis.yml

This is to ensure that we use nilearn installed in site-packages via python setup.py install rather than the one from the current directory.  Amongst other things it will detect problems in setup.py, for example missing entries in package_data.
Putting that in .travis.yml seemed like the most sensible thing to do. Let me know if you see a better way.

Travis should cd outside current working directory before running tests

---

nilearn/_utils/niimg_conversions.py
nilearn/image/tests/test_image.py

```python
import nibabel as nib
from nilearn import image
data = np.ones((11, 12, 13, 14))
img = nib.Nifti1Image(data, np.eye(4))
filename = 'test.nii'
img.to_filename(filename)
iter = image.iter_img(filename)
result = [i.get_data().shape for i in iter]
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/test.py in <module>()
11 img.to_filename(filename)
12 
---> 13 iter = image.iter_img(filename)
14 
15 
/home/lesteve/dev/nilearn/nilearn/image/image.pyc in iter_img(imgs)
543     output: iterator of 3D nibabel.Nifti1Image
544     """
--> 545     return check_niimgs(imgs, return_iterator=True)
/home/lesteve/dev/nilearn/nilearn/_utils/niimg_conversions.pyc in …
```

image.iter_img with a str argument was broken

---

nilearn/decomposition/multi_pca.py

Fix for #442.  Simple one-liner.

Pass verbose parameter to nifti masker.

---

nilearn/plotting/find_cuts.py

`find_xyz_cut_coords` says it returns 3 floats, but it was actually returning 3 one-element arrays.  Tweak the code to return a list of floats.
This necessitated a call to `np.asscalar` in https://github.com/nilearn/nilearn/pull/441 (since changed).
I also added a bit of linting / line breaks while I was in the code.

Return cut coords as a list of floats

---

nilearn/plotting/displays.py
nilearn/plotting/tests/test_img_plotting.py

See #450 for details.  @GaelVaroquaux 's suggestion seems to work well.  Note that there's also some slight whitespace tweaks for PEP8 compatibility.
I'm not familiar enough with matplotlib to understand how to add a regression test for this; any pointers / suggestions are welcome!
See #450 for code to test this fix.

Bugfix: Add axes on figure of received axes, not on current figure.

---

nilearn/masking.py
nilearn/tests/test_masking.py

Fix for #458.  Now, a bit more checking occurs before allocating memory:
* If a transposed matrix (n_features, n_slices) is passed in, it is transposed before assignment.
* If a 2D matrix with no dimensions of size `n_features` exists, a friendly error is thrown.

Avoid exploding memory on transpose error

---

.travis.yml

rather than nilearn in the current directory.
This is to detect missing files from the sdist. This generally happens
for data files in a folder without __init__.py.
Run the Travis tests from /tmp and use make -f instead of make -C.  make
-C actually cds into the directory before running make which exactly
what we are trying to avoid.
Any comments let me know, otherwise I'll merge that this afternoon.

Make sure that Travis tests use site-packages nilearn

---

nilearn/input_data/nifti_masker.py
nilearn/input_data/tests/test_nifti_masker.py

Coveralls shows that `nifti_masker.py` has only ~85% code coverage, e.g. 
https://coveralls.io/builds/1973818/source?filename=nilearn%2Finput_data%2Fnifti_masker.py
It pointed out that an error case was not covered, nor was computation via the "epi" `mask_strategy` option.
I added tests for both (with epi tests based on those in `test_masking`), and added a small bugfix that I found after adding the tests.

Improve Nifti masker code coverage

---

nilearn/decomposition/multi_pca.py
nilearn/decomposition/tests/test_canica.py
nilearn/decomposition/tests/test_multi_pca.py

I'm separating this issue out of https://github.com/nilearn/nilearn/pull/371, as I think it's a simple issue / bugfix to cleanly discuss on its own.
CanICA and MultiPCA require `imgs` to be passed to their `fit` functions.  However,
* `MultiPCA` lists `imgs` as an optional parameter.
* When either of these classes are created with an explicit `mask_img`, their `fit()` function raises a warning (despite users doing the right thing).
Fixes:
* Make `imgs` a required parameter.
* Call the downstream masker with `imgs`, only if it has no `mask_img`.

CanICA / MultiPCA: Fix interface / avoid warning for fitting with and without images

---

nilearn/plotting/find_cuts.py
nilearn/plotting/tests/test_find_cuts.py

find_xyz_cut_coords() is currently crashing for very small values in nifti image due to failure of largest_connected_component() call.

bugfix in findcuts()

---

nilearn/plotting/displays.py

The colorbar axis code was in some places assuming that the axis size would be [0, 0, 1, 1].  This is not always the case, in particular when using subplots.
I've generalized the code to work for axis sizes in general.  I also abstracted a new variable, `colorbar_margin`, to try and improve code readability.  There was also code in there to control the tick formatting, that wasn't working properly; rather than remove it, I fixed it to work.
Code for producing these images, in case you'd like to test:
```python
import matplotlib.pyplot as plt
from nilearn.plotting import plot_stat_map, plot_glass_brain
from nilearn.image import index_img, iter_img
msdl_atlas_dataset = datasets.fetch_msdl_atlas()
maps_img = msdl_atlas_dataset.maps …
```

Generalize colorbar axis computations for different input axis sizes

---

nilearn/_utils/compat.py
nilearn/_utils/testing.py
nilearn/datasets.py

This PR fixes some bugs in the dataset downloader:
* resuming in general (broken since python3 PR)
* resuming broken for some servers (those who don't comply with standard HTTP error)
* downloading of files with no name (they are named after a md5 hash of the URL)

Url opener

---

nilearn/_utils/__init__.py
nilearn/_utils/niimg.py
nilearn/_utils/niimg_conversions.py
nilearn/datasets.py
nilearn/image/image.py
nilearn/image/resampling.py
nilearn/image/tests/test_image.py
nilearn/input_data/base_masker.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_labels_masker.py
nilearn/input_data/nifti_maps_masker.py
nilearn/input_data/nifti_masker.py
nilearn/input_data/tests/test_base_masker.py
nilearn/masking.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/region.py
nilearn/tests/test_masking.py
nilearn/tests/test_niimg_conversions.py
nilearn/tests/test_region.py

This PR restore the original behavior of check_niimg and check_niimgs:
* check_niimg loads 3D niimages
* check_niimgs loads 4D niimages
This is a first step toward cleaner file loading in nilearn.

Refactor check niimg 

---

examples/connectivity/plot_ica_resting_state.py
examples/plot_haxby_simple.py
examples/plot_python_101.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_cm.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_img_plotting.py

Replace pylab by pyplot. Also, I reraise the import exception because, in the case of people that doesn't have matplotlib installed, we want to raise a meaningful error and not crash in the middle of a script.

Replace pylab import by pyplot

---

nilearn/_utils/testing.py
nilearn/plotting/__init__.py
nilearn/plotting/cm.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_cm.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_img_plotting.py

Matplotlib backend is set once and for all in
`nilearn/plotting/__init__.py`. Agg is used only when DISPLAY is unset. I am happy also always using Agg when running the tests but on my machine the difference for running `nosetests nilearn/plotting/tests` is something like 1.5s.
Failing to import matplotlib is only ok when running the tests. 
Protecting matplotlib imports is not needed anymore anymore in nilearn.plotting submodules.

Simplify matplotlib backend choice and test skipping when matplotlib is not installed

---

nilearn/plotting/displays.py
nilearn/plotting/tests/test_img_plotting.py

and add test.
This can happen when `edge_threshold` is too high or the adjacency matrix is diagonal for example:
```python
from nilearn.plotting import plot_connectome
regions = [(10, 10, 10), (0, 0, 0)]
covariance = np.eye(2)
plot_connectome(covariance, regions)
```

Fix plot_connectome without any edge to draw

---

examples/connectivity/plot_canica_resting_state.py
examples/connectivity/plot_ica_resting_state.py
examples/connectivity/plot_inverse_covariance_connectome.py
examples/connectivity/plot_multi_subject_connectome.py
examples/connectivity/plot_probabilistic_atlas_extraction.py
examples/connectivity/plot_rest_clustering.py
examples/connectivity/plot_signal_extraction.py
examples/decoding/plot_haxby_anova_svm.py
examples/decoding/plot_haxby_different_estimators.py
examples/decoding/plot_haxby_full_analysis.py
examples/decoding/plot_haxby_grid_search.py
examples/decoding/plot_haxby_multiclass.py
examples/decoding/plot_haxby_searchlight.py
examples/decoding/plot_haxby_stimuli.py
examples/decoding/plot_miyawaki_reconstruction.py
examples/decoding/plot_oasis_vbm.py
examples/manipulating_visualizing/plot_atlas.py
examples/manipulating_visualizing/plot_demo_plotting.py
examples/manipulating_visualizing/plot_haxby_masks.py
examples/manipulating_visualizing/plot_haxby_mass_univariate.py
examples/manipulating_visualizing/plot_localizer_mass_univariate_methods.py
examples/manipulating_visualizing/plot_mask_computation.py
examples/manipulating_visualizing/plot_roi_extraction.py
examples/manipulating_visualizing/plot_smooth_mean_image.py
examples/manipulating_visualizing/plot_visualization.py
examples/plot_haxby_simple.py
examples/plot_nifti_simple.py

Newcommers to nilearn (not seldomly: and to python) have expressed difficulty in understanding the format in which the datasets are represented.
It would therefore be helpful to
- show in the code that bunches are minor modifications of dictionaries
- print where the (fetched/located) files are actually located on the disk
- show how to access the important dataset parts right after first access

Add explicit explications/prints for bunches in the nilearn examples

---

nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py

rather than relying on kwargs. Fixes #524.
Better suggestions for vmin/vmax docstring documentation more than welcome. At the moment this is a bit cryptic:
```
vmin: float
vmin passed to plt.imshow
vmax: float
vmax passed to plt.imshow
```

Add explicit vmin and vmax parameters to plotting functions

---

nilearn/signal.py
nilearn/tests/test_signal.py

Fixes #549
The signals were normlized when confounds were used, for little good
reason

[MRG] BUG: don't normalize when confounds

---

doc/introduction.rst

Added words suggesting nilearn users to install 64 bit Anaconda installation. Please suggest/comment if any additional sentences need to be added to warn users who are using 32 bit.

Addressing the simple documentation issue suggesting a 64 bit installation

---

nilearn/plotting/img_plotting.py

tested like this by including few arguments in plot_anat as viewed in files changed
```python
from nilearn import plotting
display = plotting.plot_anat()
display = plotting.plot_anat(threshold=0)
display = plotting.plot_anat(threshold=None)
```
worked well without error. Any suggestions or comments if it cannot be included that way or to be included in a better way.

Regarding issue 557, included optional argument threshold and set default as None

---

nilearn/plotting/displays.py
nilearn/plotting/tests/test_img_plotting.py

* threshold application is done after image reordering/resampling
* add regression test
Fix #599.

Fix threshold application during plotting for affine with rotation

---

nilearn/_utils/niimg_conversions.py
nilearn/tests/test_niimg_conversions.py

Fix #601
Dimensionality was not checked for the first image, yielding a crash with a non-friendly error message.

Check dimensionality of first img in `concat_niimgs`

---

nilearn/_utils/compat.py
nilearn/_utils/niimg_conversions.py
nilearn/input_data/base_masker.py

Fix #584.
Basically, it uses a proper zip iterator when using _iter_check_niimg, otherwise the list of niimg is precaclulated and the number of file descriptors (or memory) could explode.
Cannot create a reliable test for that.
Ping @mrahim @banilo could you validate that (don't try on drago since the number of fd allowed on it is now tremendous).

Use izip to iterate on _iter_check_niimg to avoid memory/fd explosion

---

nilearn/_utils/__init__.py
nilearn/_utils/exceptions.py
nilearn/_utils/niimg_conversions.py
nilearn/input_data/tests/test_base_masker.py
nilearn/input_data/tests/test_multi_nifti_masker.py
nilearn/input_data/tests/test_nifti_labels_masker.py
nilearn/input_data/tests/test_nifti_maps_masker.py
nilearn/tests/test_masking.py
nilearn/tests/test_niimg_conversions.py
nilearn/tests/test_region.py

#601 raised the poorness of some error messages. In particular, when trying to use `index_img` on a list of 4D image.
I solved that by creating a custom type error but I don't know if it's the best way to do it.
Test script:
```python
from nilearn import image, datasets
hb = datasets.fetch_haxby()
image.index_img(hb.func, 0)
```
Previous output:
```
TypeError: Data must be a 3D Niimg-like object but you provided an image of shape (40, 64, 64, 1452). See http://nilearn.github.io/building_blocks/manipulating_mr_images.html#niimg
```
New output:
```
nilearn._utils.niimg_conversions.DimensionError: Data must be a 4D Niimg-like object but you provided a list of 4D images. See http://nilearn.github.io/building_blocks/manipulating_mr_images.html#niimg.
```

Enhances error messages for image manipulation

---

nilearn/datasets.py
nilearn/tests/test_datasets.py

Following Gael suggestion: prefix all atlas fetching functions by `fetch_atlas`.
Discussion: should we choose that solution or create an atlas module?

Rename dataset fetching functions.

---

nilearn/datasets.py

Fix #602
For the moment, I added NITRC as an explicit mirror. The reason is that download is faster on the original URL from here.
It is open to discussion!

Add a NITRC mirror for fetch_smith_2009

---

nilearn/_utils/logger.py
nilearn/tests/test_logger.py

We were implicitely relying on the top level stack level being an
anonymous module. This wasn't the case in the debian build environment,
that relies on "python -m nose"
Cc @hanke : this should fix build under Debian.

BUG: fix failure in "python -m nose"

---

nilearn/_utils/niimg.py
nilearn/_utils/niimg_conversions.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

Fix #611.
Supersedes #621.
I introduced a `dtype='auto'` in `check_niimg` that converts data to `int32` if it is integral and `float32` if it is real. I use it in the plotting functions so that we never end up with unsigned type. However, we are not protected from unsigned values given as threshold or vmax. I solved the current problem by casting explicitely the threshold to float but I don't know if it's the best way to do.

Fix loading dtype for plotting functions.

---

doc/Makefile

We were keeping a lot of stale files around for example http://nilearn.github.io/auto_examples/plot_haxby_simple.html which dates back from when all the examples were in the same folder.
Also maybe more controversial I switched from git to https authentication. As a consequence I moved the git clone as the first thing to do in order not to block `make install` in the middle when asking for the password.

[MRG] Make upload to nilearn.github.io more robust

---

doc/connectivity/resting_state_networks.rst
examples/connectivity/plot_canica_resting_state.py

Solution for #691. Added a line to plot the components together as an atlas before the individual plot of the components. Updated documentation accordingly.
Here the resulting plot:

[MRG] Plot prob atlas 691

---

nilearn/_utils/numpy_conversions.py
nilearn/signal.py
nilearn/tests/test_numpy_conversions.py

Fix #628.
This PR modifies CSV loading for confounds.
If `np.genfromtxt` fails, we try to guess the delimiter in the file (most of the time, a comma).

[MRG+1] Makes loading of CSV files more robust

---

nilearn/input_data/masker_validation.py
nilearn/input_data/tests/test_masker_validation.py

This PR adds an utility function check_embedded_nifti_masker, that retrieves a MultiNiftiMasker / NiftiMasker from the parameters of a given estimator instance.
This would be useful in decomposition module, spacenet module, spectral clustering module, and would help sorting issue #688 
Ping @dohmatob @ahoyosid @AlexandreAbraham @GaelVaroquaux

[MRG] Added check_embedded_nifti_masker

---

nilearn/decomposition/multi_pca.py
nilearn/input_data/base_masker.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_labels_masker.py
nilearn/input_data/nifti_maps_masker.py
nilearn/input_data/nifti_masker.py
nilearn/input_data/nifti_spheres_masker.py
nilearn/input_data/tests/test_base_masker.py
nilearn/input_data/tests/test_nifti_masker.py
nilearn/masking.py
nilearn/signal.py

Address #720 step 1.2, 1.3 and 3.1.
The goal here is to establish a common basis for NiftiMasker, NiftiLabelsMasker and NiftiMapsMasker. There are a lot of advantages:
* NiftiMasker features come for free in Nifti*Maskers (sessions and sample masks)
* If we design it well, MultiNifti*Masker flavors will come for free for all Nifti*Maskers.
* Code is slightly more complicated (very slightly actually) but much smaller, making maintenance and bug tracking easier.
Steps done:

[MRG] Use filter_and_extract as a basis signal extractor.

---

doc/modules/reference.rst
nilearn/datasets/__init__.py
nilearn/datasets/atlas.py
nilearn/datasets/description/aal_spm_12.rst
nilearn/datasets/tests/test_atlas.py

@GaelVaroquaux I added the fetch_atlas_aal function following example from the other atlas downloaded as requested in #706 
For now I implemented the download of the SPM12 version, any other SPM version would require to hardcode reference to a lot matlab files. I dont know if this would actually be useful for the users, but can implement it if you want. What do you think?

added aal atlas download and updated reference.rst

---

nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

Fix #762.
Amend test to highlight this bug and add one for plot_glass_brain.
Fix was to use dtype='auto' in check_niimg prior to vmin and vmax computation by _get_plot_stat_map_params.

[MRG] Fix remaining bug in the colorbar code with uint8 data

---

nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py

for 4d images. The dtype after resampling was always 'float64' for 4d images
* Share same code for 3d and 4d images
* add test for dtype equality before and after resampling
An example that highlights the issue:
```python
import nibabel as nib
from nilearn import image
img_4d = nib.Nifti1Image(np.ones((10, 10, 10, 5), dtype='int64'), np.eye(4))
resampled_img = image.resample_img(img_4d, 2. * np.eye(4))
print('img_4d dtype:       ', img_4d.get_data().dtype)
print('resampled_img dtype:', resampled_img.get_data().dtype)
```
and its output:
```
img_4d dtype:        int64
resampled_img dtype: float64
```

[MRG] Fix output data dtype after resampling for 4d images

---

.travis.yml
nilearn/decoding/space_net.py
nilearn/decoding/tests/test_space_net.py

The Python 3.5 now has the most recent versions. This uncovered a buglet in space_net.py for python 3 and numpy < 1.9 ... @dohmatob maybe you just want to glance a the fix?
The root issue is that:
```python
array = np.arange(10)
array[range(3)]
```
doesn't work in numpy < 1.9 (array index can not be an iterator). It does the right thing in numpy >= 1.9.

[MRG+1] Add python3.5 to Travis

---

nilearn/mass_univariate/permuted_least_squares.py

This is a small change that appeared to fix the Overflow error on windows. I can't really explain as np.iinfo(np.int32).max returns the same value on Windows 64bit and Linux 64.
This is related to #809

[MRG] fixing overflow error on Windows (and potentially on i686)

---

nilearn/datasets/func.py
nilearn/datasets/tests/test_atlas.py
nilearn/datasets/tests/test_func.py
nilearn/datasets/tests/test_struct.py
nilearn/datasets/tests/test_utils.py
nilearn/datasets/utils.py

This PR partly fix the issue #809 
But it maybe worth to merge. Summary of changes:
* fixed Environment variable split character for windows as it uses ';'
* replaced '/' with os.sep when required
* fixed permission issues when removing files in test_atlas.py/test_utils.py
* fixed file:// prefix using urllib crossplatform dedicated function "pathname2url"

[MRG] Fixing path and environment variables issues + tests on windows

---

README.rst
appveyor.yml

Fixes #804 
Added an appveyor.yml file to configure the automatic setup of the environnement installation, nilearn dist installation and testing.
Note the environnement is set up using miniconda because I couldn't build some nilearn dependencies (scipy/scikit-learn). I tried to use python-appveyor-demo project but couldn't make it work : scipy needs lapack/blas libraries.

[MRG] Setting up appveyor ci

---

nilearn/decoding/space_net.py
nilearn/decoding/tests/test_space_net.py

The ratio of brain size to mask volume was applied wrong in the
screening percentile.
In addition, add a bit more warnings.
Fixes #822

FIX: Proper brain-size correction in percentile

---

nilearn/decomposition/multi_pca.py
nilearn/decomposition/tests/test_multi_pca.py

Bug #827. I force `transpose = True` for `multi_pca` to yield the same result when we put twice the same data, and if we run fit twice on the same data

HOTFIX: multi pca reproducibility

---

nilearn/datasets/utils.py

`_fetch_file` and `_fetch_files` claim that `data_dir` is optional (it is not) and that it can be `None` (it cannot be). Fix here is to change the docstrings.
It's worth noting that parameter order in the two functions is opposite: `_fetch_file(url, data_dir, ...)` vs. `_fetch_files(data_dir, files, ...)`. An additional change here could be to flip the parameters of one (I think `_fetch_files(files, data_dir, ...)` would be the way to go.

Update _fetch_file* docstring.

---

nilearn/datasets/tests/test_atlas.py
nilearn/datasets/tests/test_func.py
nilearn/datasets/tests/test_struct.py
nilearn/datasets/tests/test_utils.py
nilearn/datasets/utils.py
nilearn/tests/test_niimg.py

This PR attempts to solve three issues:
* `_fetch_files` cannot overwrite existing files (note: `_fetch_file` actually allows this)
* `_fetch_file`'s `overwrite=True` flag is not tested.
* `setup_mock`, `teardown_mock`, `setup_tmpdata`, `teardown_tmpdata` is copied across `datasets/tests/test_*.py`, including an orphaned copy in `test_utils.py`.
The first is the only one I care about; the other two I dealt with while trying to test this.
I would like to use this functionality in the NeuroVault downloader. Since those datasets are dynamic, previous data may need to be overwritten.

Add overwrite option to _fetch_files

---

nilearn/image/tests/test_resampling.py

Some cleaning was done regarding this in 39c9063 but there was still some related code remaining in the test function.

[MRG] Remaining occurences of APPVEYOR_TEST environment variable

---

appveyor.yml

Should fix #836. It seems that matplotlib can be installed via conda. Let's see if it helps with appveyor.

[MRG] Install matplotlib with conda

---

nilearn/datasets/utils.py

In the neurovault fetcher, I need to attempt to download metadata by big chunks (100 rows). If offline, then I read the chunks from individual collections stored on disk.
I am trying to use `_fetch_files` to download the chunks of metadata, but the output of `_fetch_files` is making things tough.
* `verbose=2` is necessary to show the URL querystring (which I need to do; it's the only thing that changes from request to request), but it also outputs warnings if `total_size` is not set (which it is not). I need to suppress the warning but show the URL.
* After download, `...done` is printed to a new line. I find that messy and hard to read. I'd rather print on the same line as the download bytes.
* When a connection error occurs, I handle that and take care of things locally. However, I …

Fetching output is not as flexible as needed for NeuroVault 

---

doc/connectivity/connectome_extraction.rst
doc/developers/group_sparse_covariance.rst
examples/connectivity/plot_multi_subject_connectome.py
examples/connectivity/plot_simulated_connectome.py
nilearn/__init__.py
nilearn/connectome/__init__.py
nilearn/connectome/group_sparse_covariance.py
nilearn/connectome/tests/test_group_sparse_covariance.py

Trying to Fix Issue #850 
See #850 for more details.
1. Moved file ```group_sparse_covariance``` to ```nilearn.connectome```
2. Moved test files
3. Changed doc and examples accordingly.

Move group sparse covariance

---

nilearn/_utils/niimg.py
nilearn/image/image.py
nilearn/tests/test_niimg.py

Fixes #793 and adds tests for this issue. 
copy_img / get_data / new_image_like 
Header of the image in new_image_like was being modified because of a copy instead of a deepcopy. This was creating side effects on nifti images, for example, when caching.

[BF] copy_img / get_data / new_image_like side effects on nifti images (e.g troublesome when caching)

---

examples/connectivity/plot_inverse_covariance_connectome.py
examples/connectivity/plot_multi_subject_connectome.py
examples/connectivity/plot_probabilistic_atlas_extraction.py
examples/manipulating_visualizing/plot_overlay.py
nilearn/datasets/__init__.py
nilearn/datasets/atlas.py

Removing deprecated function names according to latest release:
``` python
* fetch_msdl_atlas
* fetch_craddock_2012_atlas
* fetch_harvard_oxford
* fetch_smith_2009
* fetch_yeo_2011_atlas
* fetch_atlas_aal_spm_12
```

PR trying to address removing deprecated functions of atlas fetcher

---

doc/connectivity/resting_state_networks.rst

Fixing image link to dictionary learning examples.
Would be great to provide a developer section describing shortly the generated doc tree, especially for sphinx gallery, I guess we all loose time on this :)

FIX: doc link to examples

---

doc/manipulating_visualizing/manipulating_images.rst

I found this overlapping text in the online documentation (see https://nilearn.github.io/manipulating_visualizing/manipulating_images.html#fetching-open-datasets). I took this opportunity to fix the full dataset example.

DOC: fixing overlapping text and wrong example

---

.travis.yml
continuous_integration/after_success.sh
continuous_integration/flake8_diff.sh
continuous_integration/install.sh
continuous_integration/test_script.sh
setup.cfg

Add this as a separate entry in the Travis build matrix. For now this
entry is marked as "allowed_failures".
* add flake8_diff.sh that finds the common ancestor between the branch
and upstream/master (or origin/master) and flake8 the diff with respect
to this common ancestor
* general .travis.yml refactor to follow more closely the Travis-CI docs.
* move each build step into its own script
* additional SKIP_TESTS environment variable to be able to skip the
tests. This is useful when you only want to do the flake8 --diff part
* Ignore 'module level import not at top of file' in setup.cfg, because
we have plenty of those in our examples.

[MRG] Flake8 diff in pull requests

---

nilearn/plotting/__init__.py

Under MacOSX, using the maptloblib MacOSX backend works even without X
Should fix #929

ENH: plotting: more robust backend choice

---

nilearn/input_data/base_masker.py

This is in reference to https://github.com/nilearn/nilearn/pull/832 
I hit an error while calling a `Masker` without having called `fit()` first. When investigating, I saw that most maskers / functions call `_check_fitted()`. Here is a place where it was not called.
Pretty sure this is the right thing...

[MRG+1] BF: Check that mask is fitted before accessing fitted data.

---

nilearn/signal.py
nilearn/tests/test_signal.py

When the signal is not detrended or normalized, we need to account for
constant confounds

BUG: don't ignore constant part of confounds

---

nilearn/_utils/numpy_conversions.py

In order to check if `genfromtxt` failed in `csv_to_array`, we checked that the resulting array is full of nan values. This may fail even when the resulting array is OK. This PR makes this check rely on the `loose=False` option of `genfromtxt` that raises a `ValueError` in case of a problem.

Robustify csv_to_array

---

nilearn/datasets/utils.py

This should fix #972 
The general idea is to use the CIRCLECI environment variable available when building on circle ci along with `functools.partial` to override a parameter of the fetch functions.
I choose to add a `report_frequency` named parameter (I couldn't find a better one, suggestions greatly appreciated) in `_chunk_read` with is set so that it keeps the current behaviour by default. Setting it to 5, will reduce the number of report displayed.
It seems that the output on circle ci is pretty weird: on my local computer I have 5 distinct output but this is not always the case on the ci.

MRG: limit download status output displayed on circle ci

---

nilearn/input_data/nifti_spheres_masker.py
nilearn/input_data/tests/test_nifti_spheres_masker.py

Solves the same problem as #880. Fix #873.
Here is my version of the fix. I didn't tested it extensively but, on the toy script below, it works. The code is super ugly because of the need to switch between seed representation (triplet) and coord_transform one (3 lists of coordinates).
I'm convinced that a better to do it exists but I am too tired to figure it out.
Test script:
```python
from nilearn.input_data import NiftiSpheresMasker
import nibabel
data = np.random.random((3, 3, 3))
mask = np.zeros((3, 3, 3))
mask[1, 1, 1] = 1
affine = np.eye(4) * 1.2
seed = (1.4, 1.4, 1.4)
masker = NiftiSpheresMasker([seed], radius=0.1,
mask_img=nibabel.Nifti1Image(mask, affine))
masker.fit_transform(nibabel.Nifti1Image(data, affine))
```

Fix problem of small radius

---

continuous_integration/install.sh
nilearn/_utils/testing.py
nilearn/tests/test_niimg_conversions.py
nilearn/tests/test_testing.py

This should fix #736 but it's not fully functional. The problem is memory_profiler cannot be really trusted when a function increase the memory less than 1MiB. I also couldn't apply it on a real test.
Here is an example (but it doesn't work) with it `test_masking.py`:
```python
from nilearn._utils.testing import with_memory_usage, assert_memory_less_than
@with_memory_usage
def test_memory_usage_with_multi_epi_mask():
mask_a = np.zeros((400, 400, 1), dtype=np.bool)
mask_a[200:400, 200:400] = 1
mask_a_img = Nifti1Image(mask_a.astype(int), np.eye(4))
mask_b = np.zeros((800, 800, 1), dtype=np.bool)
mask_b[200:600, 200:600] = 1
mask_b_img = Nifti1Image(mask_b.astype(int), np.eye(4) / 2.)
mask_ab = np.zeros((400, 400, 1), dtype=np.bool)
mask_ab[200, 200] = 1
test_mem = 2 * …
```

[MRG] Memory check based on memory profiler

---

nilearn/plotting/displays.py
nilearn/plotting/tests/test_displays.py

This will gives us choosing levels depending on the statistical values. See work around example results.
Example:
```python
from nilearn import plotting
localizer_dataset = datasets.fetch_localizer_contrasts(
["left vs right button press"],
n_subjects=2, get_tmaps=True)
localizer_tmap_filename = localizer_dataset.tmaps[1]
display = plotting.plot_glass_brain(None, title='Statistical results overlayed as contour fillings',
plot_abs=False)
display.add_contours(localizer_tmap_filename, filled=True, levels=[-4.7, -3], colors='b', alpha=0.9)
display.add_contours(localizer_tmap_filename, filled=True, levels=[3], colors='r', alpha=0.9)
```

ENH [Plotting] Accepting User defined levels in contour fillings

---

nilearn/plotting/img_plotting.py

A better approach to dimming on white bg: lighten more the background.
Old behavior:
New behavior:

[MRG] ENH: plotting: better dimming on white bg

---

nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

The computation of vmin/vmax values was made on NiftiImages wich is not pertinent since we do not need the affine. Plus, this is blocking for extending the use of this function to surface data.

Make data range computation work on data instead of images

---

circle.yml

@GaelVaroquaux I changed the .yml for circleCI to ignore the unit tests as you pointed out in #1029 by overriding the test section with just an 'echo' statement. [link](https://github.com/sahmed95/nilearn/commit/b9dd4a69ac252bb2d07b34bfbb9e4af9a979cfec) It is passing circleCI test but failing with appveyor even though I haven't changed any setting for appveyor. Any suggestions?

#1029 Ignore unit tests in circleCI

---

nilearn/signal.py

in the case of masking 3D images with detrend and standardize = False, _standardize would give the 'Standardization of 3D signal has been requested' warning, since the warning was not located within if normalize.
I have moved the warning.

fix: warn 3D normalization only if normalize==True

---

circle.yml
doc/conf.py

Should fix #1000
As #998 and #999 are merged, only changing the version to 3.4 made the job. I kept python 3.4 because the most recent compatible with sphinx 1.2.3.
Question: is there a specific reason why we use this version of sphinx ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/nilearn/nilearn/1045)

[MRG] Circle ci py3

---

nilearn/__init__.py
nilearn/_utils/cache_mixin.py
nilearn/tests/test_cache_mixin.py

Fix #1051 + non regression test

[MRG+1] Use expandpath when memory attribute is a basestring in CacheMixin 

---

doc/connectivity/functional_connectomes.rst

Fixing small typos on doc/connectivity/functional_connectomes.rst.

Fixing small typos on functional_connectomes.rst

---

doc/manipulating_images/data_preparation.rst

Fixing small typos on [doc/manipulating_images/data_preparation.rst](https://nilearn.github.io/manipulating_images/data_preparation.html).

[MRG +1] Fixing small typos on data_preparation.rst

---

nilearn/_utils/niimg.py
nilearn/_utils/niimg_conversions.py
nilearn/decoding/searchlight.py
nilearn/decoding/space_net.py
nilearn/decomposition/base.py
nilearn/decomposition/dict_learning.py
nilearn/decomposition/multi_pca.py
nilearn/image/image.py
nilearn/image/resampling.py
nilearn/input_data/base_masker.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_labels_masker.py
nilearn/input_data/nifti_maps_masker.py
nilearn/input_data/nifti_masker.py
nilearn/input_data/nifti_spheres_masker.py
nilearn/masking.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/regions/signal_extraction.py

Links to `http://nilearn.github.io/manipulating_visualizing/*` are broken in part of the documentation.

DOC: Fix broken links in the documentation

---

nilearn/plotting/displays.py
nilearn/plotting/tests/test_img_plotting.py

Fix #1101, a string can be use for cmap when `colorbar=True`.
Also speeds up plotting tests by closing figures at the end of each test.

Allow the use of a string for colormap when colorbar=True

---

nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

- documentation improvements accordingly in ```plot_prob_atlas``` plotting function
- tests added for threshold=None ```plot_prob_atlas```
Trying to Fix #1047

[MRG+1] threshold=None implies keeping data as it is to be visualized in plot_prob_atlas function

---

doc/modules/reference.rst
doc/whats_new.rst
nilearn/datasets/__init__.py
nilearn/datasets/struct.py
nilearn/datasets/tests/test_struct.py

As imposed in issue #945 created using MNI template.
Output of the **brain mask** with selected coordinates:

[MRG+1] A canonical brain mask

---

doc/user_guide.rst

Downloads the latest version of the user guide for offline viewing.
This is what it looks like:

DOC: add a link to download the user guide

---

nilearn/plotting/displays.py
nilearn/plotting/tests/test_img_plotting.py

Hi,
This fix I think it makes sense since BaseSlices._map_show can actually return an empty list.

displays.add_overlay: Add check if ims is empty

---

.travis.yml
README.rst
doc/whats_new.rst
examples/README.txt
nilearn/version.py

- Minimum version required will be now 0.14.1
Attempts to fix #1160

Dropping scikit learn dependency < 0.14.1

---

nilearn/datasets/func.py

Fix #1175 
Technically, this makes each file download of ABIDE atomic, otherwise downloading everything can be cumbersome.

[MRG+1] Make ABIDE more resumable

---

nilearn/plotting/cm.py
nilearn/plotting/tests/test_cm.py

Fix #1151
Problem: ATM, you need to import nilearn.plotting.cm for them to be registered. It would be nice to register them directly when nilearn is imported but that implies loading the whole plotting module, which is a but heavy.
What should we do?

[MRG] Register colormaps in matplotlib

---

doc/whats_new.rst
nilearn/connectome/connectivity_matrices.py
nilearn/connectome/tests/test_connectivity_matrices.py

Depending on the type of connectivity matrix extracted, keeping diagonal elements can be pertinent or not. I suggest to add a parameter to be able to discard them.
One problem is that it makes the multiplication of off-diagonal elements by sqrt(2) useless so I removed it. But I don't know what is the best option here.

[MRG] Discard diagonal in sym_to_vec and refactor scaling

---

doc/decoding/space_net.rst

Small stuff, fixes the links to  [Grosenick et al. 2013](http://www.ncbi.nlm.nih.gov/pubmed/23298747) as seen in #1130.

[MRG] fixes links on space net tutorial

---

nilearn/plotting/displays.py

Small correction for the glass brain visualization where display_mode includes 'l' or 'r'. It seems that the data from the left side was displayed in the right hemisphere and vice versa.
In my example, this was obvious, as I have two clusters on the right and one on the left. This is with the old code:
And this is with the correction from this pull request:

FIX: correct left and right hemisphere mix-up in glass brain visualization

---

nilearn/plotting/displays.py

OK, here is how the bug happens.
Here is what happens in the code (I'm sorry, I'll dig a bit into how matplotlib works because you can't understand the bug if you don't know it):
* First, we create the base layer of the glass brain (ie the brain outline). In the case of left-side brain, we call `invert_xaxis` to flip it horizontally. Behind the scenes, matplotlib simply takes `x_min`, `x_max` and invert them (this is not just a flag, this is important). So we have `x_min` > `x_max`.
* Then, we want to plot the "data" layer over this background. When we do it, we compute the bounds of the data to plot in order to readjust the limits of the axis if needed. Two cases:
1. the data fits in the glass brain: we do nothing. Everything is fine.
1. there is a voxel outside of the canvas of the …

Re-invert the axis after bounding box update if needed.

---

doc/whats_new.rst
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

- Setting default to 'auto' instead of True and 0 implies no dimming instead of False. Should address #1138

[MRG + 1] Documentation changes related to 'dim' argument in plotting functions

---

nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py

A change in the way scipy computes offsets for 1D affine matrices in ndimage.affine_transform is most likely the reason that CircleCI currently fails.
This PR adds a test, and hopefully soon a fix.

[MRG]: bug resampling & bbox in scipy 0.18

---

examples/03_connectivity/plot_probabilistic_atlas_extraction.py
examples/03_connectivity/plot_signal_extraction.py

fixes #1212 
default `LedoitWolf` covariance estimator of `ConnectivityMeasure` is kept, as it is preferred to `EmpiricalCovariance`

use ConnectivityMeasure instead of np.corrcoef in examples

---

examples/03_connectivity/plot_adhd_spheres.py

fixes #1211 (and #1214 for `plot_adhd_sphares` example)

[MRG+1] use ConnectivityMeasure instead of manual fitting of LedoitWolf

---

nilearn/decoding/searchlight.py

It appears that values from outside the brain mask are being included when SearchLight is run without the optional `process_mask_img`. Accordingly, omitting the `process_mask_img` argument produces different results than passing the same Niimg-like object image as both the `mask_img` and the `process_mask_img` (whereas, if I understand correctly, identical results would be the expected behavior).  I believe this change addresses the issue.

Issue with searchlight with no process mask?

---

doc/Makefile

When generating the html documentation I had lots of warning with `ln` command trying to create an already existing link.
Using `-f`option (--force) silent them.

DOC: fix cache symlinks warnings when generating doc.

---

nilearn/decoding/searchlight.py
nilearn/decoding/tests/test_searchlight.py
nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py
nilearn/input_data/nifti_spheres_masker.py

Because `coord_transform` returns either a list of arrays or a list of number, iterating on the return values fails if only one point is transformed. I decided to directly add an option in `coord_transform` instead of "catching" the problem in the searchlight because I think it may be useful for other usage.
Update:
For the bug fix: We have two masks in SearchLight: mask_img, that masks voxels outside of the brain and process_mask_img that "selects" the voxels to process. Before, mask_img was not used properly, process_mask_img was used instead. I fixed it.

[MRG] SearchLight cannot handle one-voxel mask

---

doc/Makefile

Follow-up of #1266 : I missed the fix of the warning generated when creating nilearn_cache if it exists already.
I use the simplest way use `-p` option of `mkdir` to silent it.

DOC: fix warning when creating an already existing nilearn_cache

---

circle.yml

Since Sphinx-Gallery summarizes build errors at the end and exits with
error. There is no need to grep for errors in the build log to fail in
Circle CI.

Remove error grep on Sphinx build

---

nilearn/image/image.py

In 0.2.6, when we pass a path to a 4D Nifti image to clean_img, we  get an error msg,
```
lib/python3.5/site-packages/nilearn/image/image.py", line 861, in clean_img
imgs_.get_data().reshape(-1, imgs.shape[-1]).T, sessions=sessions,
AttributeError: 'str' object has no attribute 'shape'
```
The reason is ```imgs``` is a path string not nii object.
This commit corrects the problem by modfiy ```imgs``` to ```imgs_```.

correct a bug in nilearn.image.clean_img

---

README.rst
nilearn/version.py

Accentuated characters are creating build failures with python3 (during rpmbuild)

Removing accentuated characters

---

nilearn/plotting/displays.py

Hi!
I was trying to plot a statmap using`plt.plot_glass_brain()`and using `vmin` and `vmax` parameters to force range the colorbar between 2 given values. `vmax` works fine, but I could not make the colorbar's lower values to adapt to `vmin` 's values (should I open an issue?). I came to the source and spotted this small bug, which has no relation with my first problem, but I think it was fine to solve. 
thanks!

Line correction; if vmax was None, no point on assigning

---

nilearn/_utils/cache_mixin.py
nilearn/input_data/masker_validation.py
nilearn/tests/test_cache_mixin.py

With this PR we solve the issue #1365.
We separate the function that checks the memory in _utils/chache_mixin.py, and use it use it in check_embedded_nifti_masker.
Basically this functions returns a memory object with the predefine cachedir.
Ping @GaelVaroquaux  @KamalakerDadi

Check memory

---

.travis.yml
README.rst
codecov.yml
continuous_integration/after_success.sh
continuous_integration/install.sh

It's all in the title and is similar to what was done in [joblib](https://github.com/joblib/joblib/pull/492).
Codecov merges results from different builds that's why coverage is activated in python 2.7.

[MRG] MAINT: switching from coveralls to codecov

---

nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

Attempts to address issue #1333. By default plotting functions should work with images which contains NaN or Inf values. Also, added tests in test_img_plotting which tests this additions.
Any kind of reviews are welcome.

FIX: Plotting functions works with NaNs in images

---

.travis.yml
README.rst
doc/whats_new.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py
nilearn/input_data/tests/test_multi_nifti_masker.py
nilearn/input_data/tests/test_nifti_masker.py
nilearn/version.py

Following the discussion from PR #1016 . We bump the nibabel requirement to 1.2.0. which helps in grabbing a module 'freesurfer' useful to read/write labels for surface based atlases.
Reviews please. Thanks.

[MRG] Drop Nibabel 1.1.0 minimum dependency to 1.2.0

---

examples/01_plotting/plot_surf_stat_map.py
examples/03_connectivity/plot_seed_to_voxel_correlation.py

Attempts to Fix #1388.
Sphinx documentation error related to could not find source location in current example folder when used to refer using ```:doc:```. Fixed using with ```:ref:``` which can be able to find source location.
Reviews are welcome. ping @chrisfilo @GaelVaroquaux

FIX: unknow document build error plot_seed_to_voxel_correlation

---

doc/whats_new.rst
nilearn/datasets/utils.py

Currently master has data fetching failures. See for instance below link
https://circleci.com/gh/nilearn/nilearn/2280?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Hopefully, this fix will address the failure of data fetching in master which will therefore fix documentation errors in CircleCI. We have to wait and see if everything goes green.

FIX: Data downloading failures from _uncompress_file

---

doc/connectivity/resting_state_networks.rst
examples/03_connectivity/plot_compare_resting_state_decomposition.py

I changed the reference for the actual dictionary learning code. It looks like self-publicity, but it was indeed an issue raised in #1323.

Doc: Dictionary learning documentation

---

nilearn/datasets/neurovault.py
nilearn/datasets/tests/test_neurovault.py

The neurovault download stops if too many images fail to be downloaded in a row, so that it doesn't continue trying if there is no internet connection, for example. The current value for max fails in a row is 10 but this is far too optimistic; it's actually likely to find 10 bad images in a row (in the cases I've seen, it's metadata referencing files that don't exist). I suggest we allow 500 failures instead.

increase threshold for stopping dl in neurovault

---

nilearn/plotting/glass_brain.py

Using them in glass_brain.py. While plotting with glass brain we see this deprecation warning. Moreover ```get_axis_bgcolor``` will be removed in future release.
Reviews please ?

[MRG] FIX: Deprecated get_axis_bgcolor with matplotlib < 2.0

---

circle.yml

Attempts to FIX,
- CircleCI failure particularly with timedout errors where every PR is failing on this.
- To make it a faster to build doc.
This was done basically to increase timeout (I don't have better alternative right now) and use parallel=true.
Both changes are made in circle.yml.
It is just an attempt to see CircleCI now. Other suggestions are also welcome.

FIX: CircleCI timedout error

---

nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

This prevents the `plotting.plot_roi` function crashing with
```
File "/home/chymera/src/SAMRI/samri/plotting/maps.py", line 146, in atlas_label
plotting.plot_roi(roi, bg_img=anat, black_bg=black_bg, threshold=None)
File "/usr/lib64/python3.4/site-packages/nilearn/plotting/img_plotting.py", line 659, in plot_roi
vmin=vmin, vmax=vmax, **kwargs)
TypeError: _plot_img_with_bg() got multiple values for keyword argument 'threshold'
```
if a threshold parameter is passed.

setting the default threshold value in the correct position

---

nilearn/regions/region_extractor.py
nilearn/regions/tests/test_region_extractor.py

Added `smoothing_fwhm` attribute to `RegionExtractor`

[MRG] Fix #1424: control smoothing in region extraction

---

doc/modules/reference.rst
doc/whats_new.rst
nilearn/_utils/ndimage.py
nilearn/image/__init__.py
nilearn/image/image.py
nilearn/image/tests/test_image.py
nilearn/tests/test_ndimage.py

Work on Issue: #1296  
Created the largest_connected_component_img and fixed a small bug in largest_connected_component, where entering a nifti image returns True.

[MRG] Added largest_connected_component_img

---

doc/whats_new.rst
nilearn/_utils/ndimage.py
nilearn/image/image.py
nilearn/image/tests/test_image.py
nilearn/tests/test_masking.py
nilearn/tests/test_ndimage.py

This issue came across with this PR #1409

FIX: Non-native endian bug with largest_connected_component function

---

doc/decoding/decoding_intro.rst

One of the Travis environment is failing with recent sklearn.
```FAIL: Doctest: decoding_intro.rst ```
FIX: I have added a doctest SKIP. I am open to better fix if anybody wants to suggest ?
Can I have reviews please ?

[MRG] FIX: Documentation failure with decoding_intro

---

nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

For our data, `plot_glass_brain` takes ~4 seconds to plot data. When using `nearest` mode, it takes ~2 seconds, with (in some cases) a negligible decrease in quality.
This PR adds a `resampling_interpolation` argument to `plot_glass_brain`. It could also be done in a hidden way via the undocumented `**kwargs` parameter if that's preferred.
Here are two examples. Continuous:
Nearest:
And a lower-resolution MRI one, continuous:
And nearest:

ENH: Add resampling_interpolation kwarg to plot_glass_brain

---

doc/introduction.rst

Small edit per issue #1497 -- `doc/introduction.rst` gave the wrong mailing list URL.

Update scikit mailing list

---

.travis.yml
circle.yml
continuous_integration/install.sh

Few examples and travis are failing with recent matplotlib 2.1.0.
Details about recent failures with ```imshow``` matplotlib 2.1.0 are in [here](https://github.com/matplotlib/matplotlib/issues/9280)
Examples: plot_overlay.py & plot_prob_atlas.py
I agree this is not a good FIX and I even don't know if this fixes it.
Any ideas are welcome

FIX: travis and circle with matplotlib

---

.travis.yml
nilearn/_utils/compat.py
nilearn/image/image.py
nilearn/version.py

We can bump the requirement to nibabel 2.0.2, which has been release mid 2015 and is in most distributions.

[WIP] MAINT: bump the nibabel version

---

appveyor.yml

- Temporary work around
- This work around will be removed after a new matplotlib release
- Currently master is failing on this. [See](https://ci.appveyor.com/project/nilearn-ci/nilearn/build/1.0.2100/job/2cckvjw356wim35p)
We have two environments failing on master with AppVeyor CI.
One failure is because of the issues with recent matplotlib 2.1.0.
For instance, see the FIX made with travis and CircleCI a while ago.
See https://github.com/nilearn/nilearn/pull/1525
Similar step can taken here to force matplotlib install in this environment to 2.0.2.
Another failure is because of the conflict issues with matplotlib forced version 2.0.2 dependency in Python 3.4.3 environment. We have conflict issues for matplotlib > 2.0.0 with this Python version.
Here, I am upgrading environment to Python …

FIX: Appveyor, force install matplotlib=2.0.2

---

doc/whats_new.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py
nilearn/signal.py

Two issues was seen with recent SciPy here:
- smoothing_fwhm=0. fails with ```scipy.ndimage.gaussian_filter1d``` (see https://travis-ci.org/nilearn/nilearn/jobs/299711990#L3471). More details about this particular FIX is discussed in this issue #1537 
- Having more strict checks on the critical frequencies should be ```Digital filter critical frequencies must be 0 < Wn < 1``` with ```scipy.signal.butter``` rather should be btw 0 and 1. This FIX seems like a more reasonable approach to restrict to ```1 - 10 * np.finfo(1.).eps``` when given frequency is more than nyquist criteria.
Can I please have reviews ?

FIX: issues with recent SciPy

---

.travis.yml
appveyor.yml
circle.yml
nilearn/plotting/displays.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_img_plotting.py

Attempts to fix the issues with matplotlib 2.1.0 by removing temporary work-around with CIs.
We are trying this way with this small patch because to release soon for teaching.

Add a patch to fix issues with matplotlib 2.1.0

---

nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

This PR should fix incorrect labels as mentioned in this issue #1371. An update of all atlases to atlases shipped with FSL version 5.0. This version has in-built symmetrically split *cortical* atlases (max-prob types).
Can I have reviews on this please ?

[MRG] ENH: Update Harvard Oxford atlas from 3.3 to 5.0

---

examples/03_connectivity/plot_multi_subject_connectome.py
nilearn/datasets/atlas.py

In response to #1568, adds atlas labels to generated matrices in `plot_multi_subject_connectome`
example for ease of interpretability.

Add matrix labels for plot_multisubj example

---

.travis.yml
continuous_integration/install.sh
nilearn/image/image.py
nilearn/image/tests/test_image.py

Patch to eliminate the need for explicitly calling `.values` with older versions of Pandas, as discussed in #1582 and #1570

[MRG+1] FIX: patch for older pandas versions in examples

---

nilearn/connectome/connectivity_matrices.py
nilearn/connectome/tests/test_connectivity_matrices.py

ENH: error for a single subject in fit_transform for tangent space
A classic error is that people call fit_transform on single subjects when the tangent space parametrization. This cannot work.
This PR raises an error in this case.
The code is extracted from PR #1477 that we will probably drop.

Error on tangent

---

doc/themes/nilearn/layout.html

Attempts to FIX #1586.
Lets see it is fixed after CircleCI build is succeeded. Just a try.
Steps I have done so far to fix this:
I have created a new search engine with nilearn.github.io/* and generated html code snippet and pasted at the relevant area in doc/themes/nilearn/layout.html

FIX: broken online documentation search

---

doc/introduction.rst
nilearn/__init__.py
nilearn/mass_univariate/permuted_least_squares.py

We are seeing doc test failures in Travis with recent NumPy 0.14. From NumPy 0.14, we will not see any spaces in the output arrays. Which is where out tests are failing.
See for instance failures in this build. https://travis-ci.org/nilearn/nilearn/jobs/327386377#L3859
Failed example:
```python
normalize_matrix_on_axis(X, axis=1)
Expected:
array([[ 0.,  1.],
[ 1.,  0.]])
Got:
array([[0., 1.],
[1., 0.]])
```
Doc tests in:
nilearn/mass_univariate/permuted_least_squares.normalize_matrix_on_axis
doc/introduction.rst
The idea is to use numpy.set_printoptions(legacy='1.13') to print the output to old pattern to be consistent will all versions. Otherwise, better solutions are welcome. @lesteve since you have already seen this problem. Could you please advice that this FIX seems better ?

[MRG] FIX: Doc test failures with recent NumPy

---

nilearn/version.py

As raised in this issue https://github.com/nistats/nistats/issues/154, current error management does not provide user friendly information with Python 3. Example as in #1507 displays there is no user friendly information.  This PR attempts to improve that. Keeping functionality which works both for Python 2 and 3. Mostly, the idea is from Scikit-learn. This is mostly done. Ready for getting some opinions on this.
The another concern raised in that issue is installing dependencies automatically. Especially when user does not necessarily have installed the dependencies before pip install nilearn.
This can be done by setting dependencies requirement in “install_requires”.
I have few questions on this:
- is_installing() functionality should go below setup ? This makes installation first and …

[MAINT] Improves error message while installing Nilearn with Python 3 and install dependencies automatically

---

nilearn/plotting/displays.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_img_plotting.py

Fixes #1595 
Error is returned when coord is None at https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/displays.py#L835. This is because no image is given to find the positioning of the coordinates.
This patch checks if ```coord is None``` or a Number. If coord is None, plot as it is. Inspired from private/helper function ```_add_markers``` in class ```GlassBrainAxes```.
Added tests. Can I please have reviews/opinions on this ?

[MRG] FIX add_markers plotting with glass_brain

---

nilearn/__init__.py

Fixes #1600 .
As mentioned in the issue #1600 added try/except for catching the ImportError in nilearn/__init__.py to allow using nilearn package without necessarily installing nose.

MAINT: Fix import error of nose while using nilearn as a package

---

nilearn/decomposition/base.py
nilearn/decomposition/tests/test_canica.py
nilearn/decomposition/tests/test_dict_learning.py
nilearn/decomposition/tests/test_multi_pca.py

Attempts to close issue #1575 
Took the opportunity to close this issue of having globbing patterns in the input images given to
decomposition estimators i.e. MultiPCA, CanICA, Dictionary Learning.
Can I have opinions/reviews on this please ?
Still to do so far:
- Add this whats_new section

FIX: globbing issues with decomposition estimators

---

doc/sphinxext/numpydoc/numpydoc.py
doc/sphinxext/sphinx_gallery/docs_resolv.py
nilearn/image/image.py
nilearn/image/tests/test_image.py

As reported in neurostars tracker https://neurostars.org/t/missing-field-error-in-nilearn-with-nifti-2/1365
A fix to overcome the error regarding header attribute "glmax" which is not present in the Nifti2 images.

FIX: glmax error in new_img_like with Nifti2Images

---

nilearn/plotting/img_plotting.py

The newest release of matplotlib [v2.2](https://github.com/matplotlib/matplotlib/releases) removed the colormap `spectral` (see [commit](https://github.com/matplotlib/matplotlib/commit/b42a9f87142d0ff9200bfa57a976cef9a6db788e#diff-ef5eff380470cb1e91c47fe27bf3bdc3L1423)). This leads to the following error when I've tried to `import nilearn.plotting`:
```bash
----> 1 from nilearn import plotting
/opt/conda/envs/neuro/lib/python3.6/site-packages/nilearn/plotting/__init__.py in <module>()
39 
40 from . import cm
---> 41 from .img_plotting import plot_img, plot_anat, plot_epi, \
42     plot_roi, plot_stat_map, plot_glass_brain, plot_connectome, \
43     plot_prob_atlas, show
/opt/conda/envs/neuro/lib/python3.6/site-packages/nilearn/plotting/img_plotting.py in <module>()
509 …
```

FIX: changes default colormap of plotting, due to drop of 'spectral' in matplotlib v 2.2

---

examples/03_connectivity/plot_probabilistic_atlas_extraction.py
examples/03_connectivity/plot_signal_extraction.py
nilearn/plotting/matrix_plotting.py
nilearn/plotting/tests/test_matrix_plotting.py

Hey y'all,
this is the pull request for issue #1543 
I added a reorder argument to the plot_matrix function. Default (for reorder=True) is average linkage.
A quick comparison on the probabilistic atlas example, seems to give the most sensible ("blockiest") ordering for average and complete. 
Should this be tested on more/different data?

[MRG] reorder argument for matrix plotting function

---

doc/whats_new.rst
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_img_plotting.py

Fixes issue as reported in #1607 
This PR will allow to ```plot_connectome``` to display nodes when a unique color is passed in ```node_color``` parameter. It can be either be as a string node_color='red' or sequence ['red'].
Still-to-do
- Add into whats_new
Thank you for reviewing.

[MRG] FIX: plot_connectome displaying hemispheric cuts in single node color

---

examples/02_decoding/plot_haxby_anova_svm.py

As discussed in #1622, patches the plot_haxby_anova_svm to correctly index session labels for cross-validation.

[MRG] patch plot_haxby_anova_svm example

---

nilearn/datasets/func.py

There were only one `warnings.warn` to modify. This should fix issue #1560

[MRG] fix adding deprecation in warn calls

---

examples/01_plotting/plot_3d_map_to_surface_projection.py
examples/01_plotting/plot_surf_atlas.py
nilearn/plotting/surf_plotting.py

by default, `plot_stat_map` uses the `cold_hot` colormap. `plot_glass_brain`
does too, if the background is black, otherwise `cold_white_hot`.
`plot_surf_stat_map` uses `coolwarm`.
current default:
suggested default:
more importantly, `plot_roi` uses a rainbow colormap, namely
`gist_ncar`. `plot_surf_roi` uses `coolwarm`, which is not adapted for rois.
current default:
suggested default:
I suggest we use the same defaults for surface plots as for slice plots.
note that the suggested defaults are the colormaps actually used in the
examples.

make surface default cmaps same as in slice plotting

---

nilearn/datasets/utils.py

Fixes #1644 and supersedes #1645

raise HttpError than AttributeError and print the user friendly error message

---

doc/themes/nilearn/layout.html
doc/whats_new.rst
nilearn/version.py

Update doc/whats_new.rst for release of Nilearn 0.4.2 and moved the changelog additions in 0.4.1 to 0.4.2.

DOC: Update changelog

---

.travis.yml

To check if travis environment 3 is happy with NumPy 1.11.2

MAINT: temp work-around for conda install 1.11.2

---

nilearn/plotting/find_cuts.py
nilearn/plotting/tests/test_find_cuts.py

I tried to call ```reorder_img``` whenever an image is passed which has non-diagonal affine. @bthirion do you think this fixes issue we have in #1660 
Thank you for reviewing.

[MRG] FIX: find_cut_slices returning the repetion of values

---

nilearn/plotting/find_cuts.py
nilearn/plotting/tests/test_find_cuts.py

This PR tries to return the central cut coordinates (0., 0., 0.) when an empty image is passed to ```nilearn.plotting.find_xyz_cut_coords```.
Current code returns coordinates half the image data shape and not in real world coordinates. This came across while working on a PR #1602 
Thanks for reviewing.

FIX: find_xyz_cut_coords returns MNI default coordinate to AC-PC line

---

doc/manipulating_images/masker_objects.rst
doc/whats_new.rst
nilearn/input_data/base_masker.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_labels_masker.py
nilearn/input_data/nifti_maps_masker.py
nilearn/input_data/nifti_masker.py
nilearn/input_data/nifti_spheres_masker.py
nilearn/input_data/tests/test_multi_nifti_masker.py
nilearn/input_data/tests/test_nifti_masker.py
nilearn/regions/signal_extraction.py

This PR aims at solving issue #1669 
I only used `_utils.check_niimg` which already has this `dtype` feature and is used in both `NiftiMasker` and `MultiNiftiMasker`

ENH add dtype option for NiftiMasker

---

examples/01_plotting/plot_3d_map_to_surface_projection.py
examples/01_plotting/plot_surf_stat_map.py
nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py

This is the PR for #1649 
Several things to note:
- If no texture is given, the colorbar argument is ignored. The alternative would be to throw an error or show an empty colorbar.
- In the tests I changed `bg_on_stat` to `bg_on_data` since the first one doesn't seem to be used anymore.
- Cropping of the space around the surface is done via viewing distance. In addition the Figure margins can be cropped, but I am hesitant to do this since the user can give a Figure or Axes argument (then using subplots_adjust might force a messed up layout on them).

Surface colorbars

---

doc/install_doc_component.html

[Review] Added scipy as dependency in installation documentation for Linux

---

doc/manipulating_images/masker_objects.rst
nilearn/datasets/atlas.py
nilearn/plotting/tests/test_img_plotting.py

Following PR #1767 , seems like add_markers doesn't like to give 4 colors to a numpy array of size 3. This PR makes a minor adaptations to pass the tests.
here is the test failure: https://travis-ci.org/nilearn/nilearn/jobs/435402098#L7699

[MRG] MAINT: Fix tests with plot_connectome add_markers

---

doc/whats_new.rst
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py

For plotting functions, the colorbar has a white background. This is problematic because colormaps with an alpha channel are displayed incorrectly. This sets the background color to mid gray, and thus also sets the `cmaplist` entries that are below `threshold` just to be fully transparent. This should have the same effect as using `(0.5, 0.5, 0.5, 1.0)` directly but is more consistent with what the plotting is actually doing.

BUG: Fix alpha for transparent colormaps

---

doc/conf.py

Enable parallel computing during docs
This will work only with recent scikit-learn versions.
It is a bit of a hack, as nilearn is not yet fully suited to use the new dynamical jobs backend, but let's see if it gives speed ups.

Faster doc builds

---

nilearn/datasets/struct.py

They take less space on the disk. This should help CircleCI.
Fixes #1791

Download zipped version of the ICBM templates

---

doc/whats_new.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py
nilearn/signal.py
nilearn/tests/test_signal.py

This PR closes https://github.com/nilearn/nilearn/issues/1021.
As recapped by @GaelVaroquaux (https://github.com/nilearn/nilearn/issues/1021#issuecomment-190209612), the following changes were requested:
1. `signals.clean` should have a default of `None` (actually, `t_r` should always default to `None`) https://github.com/nilearn/nilearn/blob/master/nilearn/signal.py#L347
2. When `t_r` is `None` and we are asking for filtering, we should raise an error (probably in `filter_and_extract` https://github.com/nilearn/nilearn/blob/master/nilearn/input_data/base_masker.py#L24) and inspect the nifti image header to suggest a value.
https://github.com/nilearn/nilearn/pull/1164 added the error message for `clean`, if `t_r` is set to `None`, but the rest was still missing.
This PR...
- sets the …

[MRG+1] Sets default value of t_r in singal.clean and image.clean_img to None

---

doc/whats_new.rst
nilearn/image/image.py
nilearn/signal.py
nilearn/tests/test_signal.py

This PR changes the order of the cleaning function, as discussed in https://github.com/nilearn/nilearn/issues/1828.
As a new feature, confound removal will be done orthogonally to temporal filters (according to [Lindquist et al. (2018)](https://www.biorxiv.org/content/biorxiv/early/2018/09/04/407676.full.pdf)), if both are specified.

[MRG+1] ENH: Corrects order and behavior of filters in `nilearn.signal.clean`

---

nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

Closes #1792 . Shipping Allen atlases from OSF to reduce the disk space load on CircleCI.

Allen atlases

---

doc/whats_new.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py

Closes https://github.com/nilearn/nilearn/issues/1839#issuecomment-432988036.
As discussed in https://github.com/nilearn/nilearn/issues/1839#issuecomment-432988036, this PR adds a `mask_img` parameter to `clean.img` to restrict the computation to voxels inside the mask.
I struggled a bit with the header information in the mask condition, [here](https://github.com/nilearn/nilearn/compare/master...miykael:add_mask_to_clean_img?expand=1#diff-b61cedb53334db86de8881757209d3feR921). I solved it by unmasking the image and then extracting the data. Because if we would just save the unmasked image, we wouldn't have the TR (temporal resolution) and probably other header information.

[MRG] ENH: Adds mask parameter to image.clean_img

---

nilearn/decoding/space_net.py
nilearn/decoding/tests/test_same_api.py
nilearn/decoding/tests/test_space_net.py

This PR is a follow-up to an issue posted in [neurostars](https://neurostars.org/t/nilearn-error-using-spacenetregressor/2298/6) which tries to raise a meaningful error message when target 'y' ends being all same values for regression task.

[MRG] FIX: Passing meaningful error when y contains all 1s

---

nilearn/plotting/img_plotting.py

```anat_img``` is deprecated and should be removed for release 0.5

[MRG] Removing deprecated argument anat_img at plot_prob_atlas

---

nilearn/plotting/html_stat_map.py
nilearn/plotting/tests/test_html_stat_map.py

As discussed in PR #1766 , I got rid of plotting.html_stat_map._deduplicate_cmap, and the "value" annotation is now absent from the brainsprite viewer.

Removing the "value" annotation in view_stat_map

---

doc/plotting/index.rst
doc/whats_new.rst
examples/01_plotting/plot_demo_more_plotting.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_img_plotting.py

Adressing  issue #1822  opened by @TheChymera, we have created a new display class called TiledSlicer, which is a variation of the OrthoSlicer class with changed `_locator `method, changed` _init_axes` method and different `_default_figsize` to arrange plots in a 2x2 fashion.
It can be called with specifying `display_mode='tiled'` in nilearns plotting functions, for example
`plot_anat(display_mode='tiled')`

[MRG] Issue #1822: volumetric plot arrangement

---

nilearn/plotting/data/html/connectome_plot_template.html
nilearn/plotting/data/html/surface_plot_template.html
nilearn/plotting/html_connectome.py
nilearn/plotting/html_stat_map.py
nilearn/plotting/html_surface.py
nilearn/plotting/js_plotting_utils.py

as was requested somewhere in the discussion of #1766 . this is purely cosmetic
https://github.com/nilearn/nilearn/pull/1766#discussion_r226188070

[MRG] use Template.safe_substitute instead of str.replace

---

doc/whats_new.rst
nilearn/plotting/data/js/surface-plot-utils.js

plotly defaults for lighting of the surface plots actually look better than those we use in my opinion; main difference is more ambient light (shadows are not so dark) and no reflection (surface is more rough, less shiny, no bright spots)

Lighting surf plot

---

nilearn/input_data/nifti_labels_masker.py

transform_single_imgs loads a (potentially large) dataset into the imgs_ variable, potentially uses it for a couple of things, and then does not use it anymore. filter_and_extract, which gets called later in transform_single_imgs, loads the same 3D/4D scan into a different variable (local to filter_and_extract). This leads to two separate copies of a potentially large dataset being loaded into memory while transform_single_imgs runs. `del imgs_' ensures only a single copy is in memory at a time.

Remove temporary variable imgs_ from memory

---

nilearn/plotting/js_plotting_utils.py
nilearn/plotting/tests/test_js_plotting_utils.py

Closes #1915 
- Quotes iframe attributes for `width` and `height`.

fix: quote iframe attributes

---

nilearn/_utils/niimg.py
nilearn/plotting/img_plotting.py

Hey, 
This appears to be a bug. Whenever there is a call to `nilearn._utils.load_niimg`, (or `nilearn._utils.check_niimg_4d()`) and dtype='auto' and the data's dtype!=target_dtype, the header gets dropped. This does not seem optimal. Here is an example mimicking the behaviour. 
But this can be fixed by adding copy_header flag and a call to niimg.header.set_data_dtype() 
The code below recreates the behaviour of the bug.
```
from nilearn._utils import check_niimg_4d
import nibabel as nb 
import numpy as np 
dataset = datasets.fetch_adhd(n_subjects=1)
fname = dataset.func[0]
img1 = nb.load(fname)
img2 = check_niimg_4d(img1,dtype=None)
img3 = check_niimg_4d(img1,dtype=np.int32)
print(img1.header.get_zooms()[-1])
print(img2.header.get_zooms()[-1]) …
```

load_niimg drops header if dtype is changed

---

doc/whats_new.rst

transform_single_imgs now uses less memory. The what's new document
didn't reflect this change.

whats_new.rst update - transform_single_imgs

---

doc/whats_new.rst
nilearn/plotting/html_connectome.py
nilearn/plotting/tests/test_html_connectome.py

For issue #1886 
Deprecated view_connectome params that differed from params of plot_connectome, docstrings & tests pending.

[MRG] Make parameter names in view_connectome() consistent with plot_connectome()

---

nilearn/datasets/description/brainomics_localizer.rst
nilearn/datasets/func.py

This published dataset is to be cited differently from the initial internal Localizer dataset.
Fixes #1925.

Proper citation for Brainomics/Localizer dataset

---

nilearn/_utils/__init__.py
nilearn/_utils/helpers.py
nilearn/_utils/param_validation.py
nilearn/plotting/html_connectome.py
nilearn/plotting/tests/test_html_connectome.py
nilearn/tests/test_helpers.py

This PR intends to undo the code redundancy introduced via PRs #1913 & #1918 by refactoring the functionality into one utility function. This will also help with the same functionality in Nistats and address code redundancy there as well.
Finally I foresee this as a useful function in future use cases as well.

Replace specialized parameter deprecation code with a general utility

---

nilearn/image/image.py
nilearn/image/tests/test_image.py

the last release broken the MNE CIs due to plotting from .mgz files. This fixes it.
to replicate the pb:
```
from nilearn.image import new_img_like
import nibabel
niimg = nibabel.load('/Applications/freesurfer/subjects/fsaverage/mri/T1.mgz')
new_img_like(niimg, niimg.get_data().astype(float), niimg.affine, copy_header=True)
```
let me know if I can turn this into a non-regression test

[MRG+2] FIX : new_img_like broken with mgz files

---

doc/plotting/index.rst
doc/themes/nilearn/layout.html
doc/whats_new.rst

I've just noticed that the releases had not been added to the front page. This PR adds them.
The PR also fixes minor problems fix the documentation.

DOC: small formatting fixes

---

examples/03_connectivity/plot_sphere_based_connectome.py

In #1953 the smoothing in the `plot_sphere_based_connectome.py` example was changed from 6mm to 4mm, but only for the fist (dosenbach) atlas, not the second (power). Since @emdupre and @KamalakerDadi can't figure out why that happened, we make this consistent by reverting to 4mm for both atlases.

[FIX] revert fwhm for dosenbach example back to 4mm

---

.travis.yml

Travis is defaulting to Python3.6.
Nilearn is dropping support for Python2, 3.4 .
This PR attends to all this.

Remove Travis tests for python v2, 3.4, upgrade it for python3.6

---

nilearn/decoding/objective_functions.py
nilearn/decoding/space_net.py
nilearn/decoding/space_net_solvers.py
nilearn/decoding/tests/test_objective_functions.py
nilearn/decoding/tests/test_same_api.py
nilearn/masking.py
nilearn/tests/test_masking.py

Renaming stand-alone _unmask function for SpaceNet to _unmask_from_to_3d_array and moving it in nilearn/masking.py with the relevant tests and import changes.
The goal is to use this function later to refactor ReNA for PR#1983

[MRG] Moving nilearn.decoding.objective_functions._unmask to nilearn.masking._unmask_from_to_3d_array

---

examples/03_connectivity/plot_adhd_spheres.py
examples/03_connectivity/plot_group_level_connectivity.py
examples/03_connectivity/plot_multi_subject_connectome.py
examples/03_connectivity/plot_seed_to_voxel_correlation.py
examples/03_connectivity/plot_sphere_based_connectome.py

Fixes #2014 
The change in the examples from the adhd dataset to the fmri development dataset left the t_r at 2.5. The development dataset has a TR of 2.
This now has been changed in the examples

[FIX] t_r in examples using the development dataset

---

doc/whats_new.rst
examples/01_plotting/plot_surf_stat_map.py
nilearn/plotting/surf_plotting.py

This addresses issues mentioned in #1738 
(and https://neurostars.org/t/thresholded-surface-plot-with-nilearn/2992).
- Accidental thresholding of zeros removed
- Changed behaviour when no background map. Instead of a solid grey background (which removes 3D structure of the surface) the default is to display thresholded maps on grey half-transparent background. This is also shown in the example plot_surf_stat_map now. 
- Some additional small bugs and inconsistencies were removed

[MRG] Fix/surf plot thresholds

---

doc/development.rst

Changed text reference to use __ instead of _ to avoid warnings
- Fix based on https://github.com/sphinx-doc/sphinx/issues/3921

Fix warning generated in `development.rst`

---

doc/whats_new.rst
nilearn/plotting/html_surface.py
nilearn/plotting/tests/test_html_surface.py

after all I think the symmetric_cmap option is useful for `view_img_on_surf`

[MRG] add symmetric_cmap option in view_img_on_surf

---

doc/manipulating_images/masker_objects.rst
nilearn/decoding/tests/test_graph_net.py
nilearn/decoding/tests/test_space_net.py

fixes #2056 : sklearn.utils.extmath.norm deprecated in 0.19 and removed in 0.21

[MRG] import norm from scipy.linalg not sklearn.utils.extmath

---

nilearn/plotting/tests/test_html_stat_map.py

imsave doesn't support saving to 'raw' in matplotlib 3.1 . in practice nilearn code (in brainsprite viewer) only saves to png anyway; so i changed the tests to test saving to png, not raw.

don't save sprites to RAW format (removed in matplotlib 3.1)

---

nilearn/surface/surface.py

Fixes issue #2082 
changed np.round to np.floor in _masked_indices to stay within the image dimensions.

fix 2082: vol_to_surf samples out of image np.round to np.floor

---

examples/02_decoding/plot_miyawaki_encoding.py
examples/04_manipulating_images/plot_extract_rois_statistical_maps.py
nilearn/image/image.py
nilearn/image/tests/test_image.py
nilearn/regions/region_extractor.py

The threshold_img was not following the conventions of the other
image functions and was performing in-place thresholding without
offering the possibility to turn it off. This is now fixed.

Add copy=True parameter to threshold_img

---

doc/conf.py
doc/connectivity/connectome_extraction.rst
doc/developers/group_sparse_covariance.rst
examples/03_connectivity/plot_inverse_covariance_connectome.py
examples/03_connectivity/plot_multi_subject_connectome.py
examples/03_connectivity/plot_simulated_connectome.py
examples/03_connectivity/plot_sphere_based_connectome.py
nilearn/connectome/group_sparse_cov.py

For issue #2069
Since the usage is in examples & documentation, it is improbable that users will run it in the oldest support Scikitlearn version. CIrcleCI uses the latest versions. Hence not accommodating the older version immediately. Will reasses based on feedback.

[MRG] Replace GraphLasso* with GraphicalLasso*

---

doc/whats_new.rst
nilearn/plotting/cm.py

Without this change I get warnings of the form:
```
/home/larsoner/python/nilearn/nilearn/plotting/cm.py:159: MatplotlibDeprecationWarning: 
The revcmap function was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use Colormap.reversed() instead.
_cmaps_data[_cmapname_r] = _cm.revcmap(_cmapspec)
```
The suggested fix of `.reversed()` is not immediately usable because that wouldn't give us the data to put in `_cmaps_data`, so just take the (simple) mpl code to do the reversal knowing they're all `dict` and not `callable`.

MAINT: Future-compatible cmap reversal

---

doc/whats_new.rst
nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

Addresses #2137. `base_url=None` in `fetch_atlas_schaefer_2018` downloads the most recent Schaefer parcelation version, v0.14.3. Previously this downloaded v0.8.1. Using v0.14.3 ensures that users will get the correct atlas label names by default. I added a note to the docstring as well. 
When I was going through [the updates](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal#updates), I also noticed that 700 and 900 region parcelations have been available since v0.10.2. Although this was not discussed in #2137,  I've updated `fetch_atlas_schaefer_2018` to include these as options for the `n_rois` parameter; `n_rois` now takes values 100-1000 in increments of 100.

Update Schaefer parcelation to v0.14.3

---

nilearn/tests/test_signal.py

Some how there are two tests in `test_signal.py` with the same name, which means one of the test is overridden by another during collection and never run. This can be fixed by giving the tests unique names.
The purpose of the second test & hence it's name needs to be determined & decided.
@jeromedockes

[WIP] Rename test to deduplicate name in test_signal

---

.travis.yml
continuous_integration/install.sh

Fixes #2115 
Conda has become unreliable for use with CIs. Replacing it with alternatives such as pip and apt seems a prudent long term solution.

[MRG] Replac conda with pip in CI setup

---

doc/whats_new.rst
nilearn/plotting/img_plotting.py

expose bg_img, vmin and vmax in plot_img signature

---

nilearn/plotting/js_plotting_utils.py
nilearn/plotting/tests/test_js_plotting_utils.py

Import HTMLDocument in its original module to preserve backwards compatibility

---

doc/whats_new.rst
nilearn/plotting/html_connectome.py
nilearn/plotting/tests/test_html_connectome.py

`nilearn.plotting.view_connectome` now converts NaNs in the adjacency matrix to 0.

[MRG] Nans in view connectome

---

nilearn/datasets/neurovault.py

In some cases the neurovault fetcher tries to update the metadata. at the moment this can fail if the user has write permission for the neurovault data directory, but not for the metadata file of a particular image for some weird reason. this pr skips these updates with a warning

do not fail if metadata cannot be updated for an image

---

doc/whats_new.rst
examples/03_connectivity/plot_sphere_based_connectome.py

https://github.com/nilearn/nilearn/pull/2028#issuecomment-541675600
Removing the last example in `plot_sphere_based_connectome`, plot connectome using the Seitzman atlas.

[WIP] Removed sub-example due to unfit for lasso dataset - unstable float values

---

examples/01_plotting/plot_dim_plotting.py
nilearn/datasets/func.py
nilearn/datasets/tests/test_func.py

Fixes #2181 
Making `fetch_localizer_button_task` & `fetch_localizer_calculation_task` backwards compatible.
- TODO: fetch_localizer_calculation_task()
- TOFIX: Example plot_dim_plotting.py is failing here & in pre PR 2097.

Restore Localizer fetchers interface for backwards compatibility

---

doc/whats_new.rst
nilearn/plotting/displays.py

FIX: marker size issue in plot_connectome #2185

---

doc/manipulating_images/input_output.rst

...by decompressing nii's per issue #2218 at @GaelVaroquaux 's request.

[DOC] Add note about decreasing memory usage

---

nilearn/_utils/testing.py
nilearn/datasets/atlas.py
nilearn/datasets/func.py
nilearn/datasets/neurovault.py
nilearn/datasets/struct.py
nilearn/datasets/tests/test_neurovault.py

On latest `sklearn` master takes care of warnings of the form:
```
E   FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
```
and
```
E   FutureWarning: The sklearn.datasets.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.datasets. Anything that cannot be imported from sklearn.datasets is now part of the private API.
```

MAINT: sklearn Deprecations

---

.travis.yml
nilearn/surface/tests/test_surface.py

[WIP] Fixing failure in minimum build of TravisCI

---

doc/whats_new.rst
nilearn/__init__.py
nilearn/tests/test_init.py

Fixes #2213 
Remove warnings for Python2, 3.4 .
Add warning to for Python 3.5

Update Python version warnings

---

.travis.yml
continuous_integration/install.sh

Fixes #1728 
I noticed that you aren't testing pre-releases (I was checking to see if the nibabel RC was causing problems). I've found it very helpful to see when changes coming down the pipeline (particularly from numpy) are going to break compatibility.
This PR adds an optional `PIP_FLAGS` environment variable that will be added to `pip install` commands for requirements and nilearn.
Feel free to merge if this seems useful. I can also just use the Travis results for this PR to see if we're breaking anything.

CI: Test pre-release versions of dependencies

---

continuous_integration/show-python-packages-versions.py

While reading outputs in #2224, it looked like scikit-learn was not installed, but this is because the import is `sklearn`.
[Example](https://travis-ci.org/nilearn/nilearn/jobs/615268943):
```
Dependencies versions
numpy: 1.15.4 from /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/numpy/__init__.py
scipy: 1.3.2 from /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/scipy/__init__.py
scikit-learn: not installed
joblib: 0.14.0 from /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/joblib/__init__.py
matplotlib: not installed
nibabel: 3.0.0rc1 from /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/nibabel/__init__.py
```
I looked around, and the `pkg_resources` package that comes with `setuptools` can retrieve information about …

CI: Use pkg_resources to list installed dependencies

---

nilearn/input_data/nifti_masker.py

I added an explanation for the resampling processes in `NiftiMasker`. Before this, it was not clear what happens in the background, when you provide a mask image and images of different resolution and how this does interact with target_shape and target_affine.
See [this post](https://neurostars.org/t/how-does-niftimasker-work-when-dealing-with-mask-and-data-images-of-different-resolutions/4892) on neurostars.org where I originally asked the question. Pinging @jeromedockes here, because he gave an answer to my question and might be interested to know about this pull request.
This pull request is related to issue #355, where I made a comment.

Improved nifti masker documentation

---

doc/whats_new.rst
nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

Argument version='det' for Pauli 2017 atlas in documentation was not implemented as described.

Argument version='det' in pauli 2017 atlas now works correctly

---

examples/plot_3d_and_4d_niimg.py
nilearn/image/image.py

Addresses #2188 
* Adds a description of using the `slice()` constructor to the `nilearn.image.index_img` docstring *Examples* section
* Adds an example of using the `slice()` constructor to index a 4D image in the `plot_3d_and_4d` examples image
Updated outputs:
* Rendered [example](https://5074-1235740-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/auto_examples/plot_3d_and_4d_niimg.html#sphx-glr-auto-examples-plot-3d-and-4d-niimg-py)
* Rendered [docstring](https://5074-1235740-gh.circle-artifacts.com/0/home/circleci/project/doc/_build/html/modules/generated/nilearn.image.index_img.html#nilearn-image-index-img)

[doc] improve documentation re: using index_img with slice()

---

nilearn/plotting/tests/test_html_connectome.py
nilearn/tests/test_helpers.py

While attending to issue #2251 I noticed the tests are inadequate. They don;t check for warning category, only the message. This fixes that.

Fix tests pertaining to replace_parameters functionality

---

nilearn/datasets/func.py

Closes #2230 
- Sets deprecation cycle for `fetch_haxby_simple` to 0.7.x release
- Add  `VisibleDeprecationWarning` on function call

[MRG+1]: maint: warn upcoming deprecation for fetch_haxby_simple

---

doc/whats_new.rst
nilearn/input_data/nifti_labels_masker.py
nilearn/input_data/tests/test_nifti_labels_masker.py
nilearn/input_data/tests/test_nifti_maps_masker.py

Get NiftiLabelsMasker.inverse_transform to work even without calling
transform.
Fixes #2192
Ping @banilo : this should fix your problem.

BUG: NiftiLabelsMasker inverse_transform without transform

---

doc/decoding/searchlight.rst

References #2245. 
Consider this an _initial draft_. Moves code out of the user guide, and references the Haxby searchlight example. I expanded several sections after removing the code examples, as well as elaborated on aspects such as cross-validation, sphere radius, and the initial section that overviews the technique. 
I left _Comparing to massively univariate analysis: F_score or SPM_ untouched. As per #2245, we could include a section on other alternatives to searchlights.
Let me know what you think

[documentation] Searchlight user guide

---

examples/05_advanced/plot_ica_resting_state.py

Closes #2259.
- Removes internal note
- Removes outdated references to running on multiple subjects

[DOC] Remove outdated references in plot_ica_resting_state

---

AUTHORS.rst

Closes None.
- Corrects typos in author list, as discovered when drafting the Nilearn OHBM abstract

[FIX, DOC] Correct typos in author list

---

nilearn/datasets/func.py

To troubleshoot #2285.
The original resource we're requesting returns a 308 error. Trying with a 302 link, since it _might_ redirect on its own and we can still query it systematically. See:
@kchawla-pi did OSF admin get back in touch with you ?

[FIX] Patch non-resolving OSF download links

---

nilearn/surface/surface.py

Tiny typo fix (ouside -> outside)

---

doc/whats_new.rst
nilearn/plotting/__init__.py

Before this, importing nilearn.plotting after running "%matplotlib inline" would reset the backend. Thanks @emdupre for spotting it.
I checked interactively with jupyter that it would fix the problem, but I don't think that we can do a test.

Fix "%matplotlib inline" in notebook

---

nilearn/datasets/description/seitzman_2018.rst

The preprint referenced in the docs is now published as a paper. I have added the paper reference, but have left the reference to the preprint in so that the year in the function name still makes sense.

[DOC] updated reference Seitzman 2018

---

examples/04_manipulating_images/plot_affine_transformation.py

Fix affine transformation example introduction paragraph typo: the 4x4 matrix
encodes the affine transformation.

[MRG] DOC: Fix affine transformation example typo

---

doc/themes/nilearn/static/nature.css_t
doc/whats_new.rst

The CSS changes are to make the download link both more visible and not too intrusive. They are illustrated below for different screen sizes:

Fix small cosmetics on docs + CSS for the download links

---

nilearn/plotting/tests/test_surf_plotting.py

matplotlib may delay rendering a figure until it is needed, and some details
such as tick labels, bounding boxes etc. may not be set before the figure
is actually drawn. we can cause the figure to be drawn by calling
`fig.canvas.draw`, `fig.savefig`, `plt.show`

[MRG] draw figure before checking tick labels

---

azure-pipelines.yml

Certain VMs used for testing are now obsolete and will be discontinued in the near future and hence are being updated.

Update Azure VM host versions (obsolete, near discontinuation)

---

doc/Makefile

Joblib cache now cleaned with 'make clean' for doc building

---

AUTHORS.rst

This pull request is to change a tiny typo in the AUTHORS.rst file, the word "gitub" I believe is referring to GitHub.

Typo in AUTHORS.rst "gitub"

---

nilearn/stats/first_level_model/design_matrix.py

This argument is passed to `_make_drift`, so I replaced the text with the same description as is used in `_make_drift `.

Add high_pass to docs for make_first_level_design_matrix

---

codecov.yml

this should reduce noise of checks failing with "+- .01%" diff coverage etc.
1% is the value used by scikit-learn

add 1% threshold in codecove yml

---

doc/introduction.rst
doc/manipulating_images/masker_objects.rst

since the scikit-learn release 0.23 (12 may 2020), by default estimator's `__repr__` only show parameters that are different from the default values:
https://scikit-learn.org/stable/whats_new/v0.23.html#miscellaneous
https://github.com/scikit-learn/scikit-learn/pull/17061
this causes some of nilearn's doctests to fail; this PR sets sklearn's config to
the old behaviour for the affected files. 
(note that for the NiftiMasker at least the doctest in question is meant to show
the parameters to the reader so in this particular case the old behaviour is
indeed what we want)

[MRG] set config to print_changed_only=False for doctests

---

nilearn/stats/contrasts.py

Simply fixes a typo in the docstring issue #2409

DOC: fixed docstring typo

---

nilearn/decomposition/canica.py
nilearn/decomposition/tests/test_canica.py

The calculated threshold in `canica` may throw an error.
The reason is that the percentile of the threshold takes on an undefined value range.
The range of the percentile used to calculate the threshold in `canica` is limited to [0,100].

Fix: CanICA ensure valid percentile

---

doc/whats_new.rst
nilearn/_utils/testing.py
nilearn/datasets/func.py
nilearn/datasets/tests/test_func.py

start addressing #2283 by deprecating cobre fetcher
it is not used in any example nor by other functions

deprecate cobre fetcher

---

nilearn/decoding/decoder.py
nilearn/decoding/tests/test_decoder.py

Closes #2414 and closes #2360 
- Fixed screening_percentile be corrected twice when doing fit
- Better docstring on screening_percentile param
- Reshaping coefficients of fitted estimator inside parallel_fit to prevent RidgeCV from behaving weirdly
- Improvement for `test_decoder.py`: increase difficulty of `test_decoder_regression`, removed unnecessary varible definition

[ENH] bug fixing on Decoder module:

---

nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py

This PR deals with the aesthetics of colorbar on black backgrounds (issue #2485). For glass brain, plotting overlay for thresholded colorbar is set up to default gray color in the same way as for `plot_stat_map`. Additionally, this PR changes the outline of the colorbar for a black background as it should be changed to white in the same way as color of `tick_params`. Note, that this will also affect colorbar on other plotting functions when `black_bg=True`.
Plots after fix:

Fixed colorbar aesthetics on a black backgroud

---

doc/whats_new.rst
nilearn/connectome/connectivity_matrices.py
nilearn/connectome/tests/test_connectivity_matrices.py

This PR enhances the ConnectivityMeasure object by implementing confounds to regress out from the vectorized matrices. This is called as Connectome-level regression for example, to clean Mean FD.

[WIP] ENH: Confounds for ConnectivityMeasure

---

continuous_integration/install.sh

otherwise e.g. numpy which has an old version pre-installed on travis virtualenv
doesn't get upgraded

use pip install --upgrade in install.sh

---

nilearn/_utils/stats.py
nilearn/datasets/func.py
nilearn/plotting/surf_plotting.py

Running some code over in MNE with `warnings.simplefilter('error')` I found a few warnings that could be fixed involving escape chars and literal int comparisons.

BUG: Escape chars

---

nilearn/_utils/param_validation.py
nilearn/decoding/decoder.py
nilearn/decoding/space_net.py

Do not import from modules that have been made private and moved
Currently, nilearn does not run on sklearn 0.24. This PR fixes it.

Fix nilearn under scikit-learn 0.24

---

nilearn/image/tests/test_resampling.py

fix test failing because numpy warning type changed in 1.19 release
see e.g. https://github.com/nilearn/nilearn/pull/2529#issuecomment-650832712

[MRG] numpy warning changed in 1.19

---

doc/themes/nilearn/layout.html

the sphinxdoc/layout.html has been removed in latest sphinx release
before it extended basic/layout.html

[MRG] fix TemplateNotFound error

---

nilearn/plotting/tests/test_html_stat_map.py

otherwise the save_sprite and save_cm tests fail because of small changes in matplotlib 3.3

[MRG] check img content rather than png file bytes

---

nilearn/signal.py
nilearn/tests/test_signal.py

Closes #2281 and closes #2475.
- Copy the input array at the top of `nilearn.signal.clean` so that the original array will not be modified.
- Add tests to cover the cases reported in #2281 and #2475.
- Add more tests for the same issue interspersed throughout the testing functions for `nilearn.signal.clean`.

[FIX] Ensure nilearn.signal.clean will not modify original array

---

doc/whats_new.rst
nilearn/mass_univariate/permuted_least_squares.py
nilearn/mass_univariate/tests/test_permuted_least_squares.py

Closes #2554.
- Transpose output array in `nilearn.mass_univariate.tests.test_permuted_least_squares.get_tvalue_with_alternative_library()
- The docstring said the outputs would be in (n_regressors, n_descriptors) but they were actually in (n_descriptors, n_regressors).
- Transpose t-values output in `nilearn.mass_univariate.permuted_ols()` when `n_perm == 0`.
- Add a number of shape checks to tests in `nilearn.mass_univariate.tests`.
- Add some whitespace to the checks as well, to aid readability.

[FIX] Transpose array in permuted_ols

---

nilearn/glm/first_level/first_level.py
nilearn/glm/model.py
nilearn/glm/regression.py

nibabel.onetime.setattr_on_read has been renamed to [auto_attr](https://nipy.org/nibabel/reference/nibabel.onetime.html#auto-attr).
Deprecation is [mentioned in a comment](https://github.com/nipy/nibabel/blob/516434c086b64aae03c69b6549548e5556760002/nibabel/onetime.py#L174-L179), but not raised as a warning. I'll plan to tag it with a `DeprecationWarning` in an upcoming release, but might as well change it here first.

MNT: Rename setattr_on_read -> auto_attr

---

setup.py

Tackling #2288, and its consequences as in #2481 (potential bugs with recent versions of scikit)
Now we don't use AppVeyor anymore, this should be useless

Removing fake sklearn import

---

nilearn/mass_univariate/permuted_least_squares.py
nilearn/mass_univariate/tests/test_permuted_least_squares.py

Closes #2556.
- Add a warning if any voxels in `target_vars` are all zeros across samples.
- Use `numpy.nanmax` instead of `numpy.amax` to get the permutation-wise maximum values, so that all-zero voxels are ignored.

[FIX] Ignore all-zero voxels in permuted_ols null distribution generation

---

doc/whats_new.rst
examples/03_connectivity/plot_compare_decomposition.py
nilearn/decomposition/base.py
nilearn/decomposition/tests/test_canica.py
nilearn/decomposition/tests/test_dict_learning.py
nilearn/signal.py
nilearn/tests/test_signal.py

Closes #2342 #1744 .
- The explained variance `score` method now returns a value based on the number of components rather than 0. always. 
- ```per_component```, a new argument introduced in `score` method returns a value per component.

[MRG] FIX score method with decomposition estimators

---

nilearn/_utils/data_gen.py
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py
nilearn/glm/tests/test_utils.py

In https://github.com/nipreps/fmriprep/commit/73e4ccde5080f2d66ba720bba03a13d270f8f65f, `fmriprep` changed the path of the output confound file from `~_desc-confounds_regressors.tsv` to `~_desc-confounds_timeseries.tsv`. This change occurred before the release of the LTS version 20.2 which is now recommended. I didn't find a reference to this change in either the changelogs or BIDS specification but this caused a bug in my pipeline.
This commit updates the function `first_level_from_bids` in `first_level.py` so that the `get_bids_files` call that seeks confound files matches both possible path. A possible alternative would be to match only the new version but this would break backward compatibility with `fmriprep` versions before 20.2
There are no associated issue yet, but I was about to …

[FIX] Update confounds filename following `fmriprep`

---

nilearn/plotting/cm.py

On latest matplotlib I get:
```
File "../examples/inverse/plot_mixed_source_space_inverse.py", line 16, in <module>
from nilearn import plotting
File "/home/larsoner/python/nilearn/nilearn/plotting/__init__.py", line 42, in <module>
from . import cm
File "/home/larsoner/python/nilearn/nilearn/plotting/cm.py", line 214, in <module>
_cm.register_cmap(name=k, cmap=v)
File "/home/larsoner/python/matplotlib/lib/matplotlib/cm.py", line 150, in register_cmap
raise ValueError(msg)
ValueError: Trying to re-register the builtin cmap 'bwr'.
```
This uses a try/except pattern to avoid this.
On alternative would be to do:
```
if k not in _cm._cmap_registry
```
but this uses the private `_cmap_registry` which is probably not a great idea. I do not know of a public interface to get all registered cmaps.

FIX: Avoid colormap readd

---

nilearn/_utils/data_gen.py
nilearn/_utils/numpy_conversions.py
nilearn/conftest.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/conftest.py
nilearn/plotting/tests/test_img_plotting.py

On latest matplotlib I get (this is from MNE but we vendor your fix):
```
File "/home/larsoner/python/mne-python/mne/fixes.py", line 1104, in _crop_colorbar
xy = cbar._outline(new_X, new_Y)
AttributeError: 'ColorbarBase' object has no attribute '_outline'
```
See inline comments for description.
Not sure if there is a better fix or not...

BUG: Fix for latest matplotlib

---

nilearn/plotting/surf_plotting.py

- Matplotlib version bump from 3.3.2 to 3.3.3 introduced the attribute `_facecolors3d` of `'Poly3DCollection` to become `_facecolor3d` which caused PR #2589 to fail

Change _facecolors3d to _facecolor3d in surf_plotting

---

doc/Makefile
doc/conf.py

On my computer, these changes are needed so that sphinx-gallery does not error saying that the matplotlib backend is tkagg

BUILD: make sphinx-gallery more robust

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Fix labelling in current issue templates as part of the todolist of #2629 :
- label `bug` was misspelled
- label `feature` doesn't exist

Fix label names in issue templates

---

doc/modules/reference.rst
doc/whats_new.rst
examples/01_plotting/plot_prob_atlas.py
examples/03_connectivity/plot_atlas_comparison.py
nilearn/datasets/__init__.py
nilearn/datasets/atlas.py
nilearn/datasets/description/difumo_atlases.rst
nilearn/datasets/tests/test_atlas.py

Initialize work related to #2422 
**TODO:**
**Include fetchers**
So far, I've included the fetchers and they seem to work for all dimensions and resolutions except dimension 128:
```python
from nilearn.datasets import fetch_difumo
fetch_difumo(dimension=128, resolution_mm=2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-ddc87112126d> in <module>
1 from nilearn.datasets import fetch_difumo
----> 2 fetch_difumo(dimension=128, resolution_mm=2)
~/GitRepos/nilearn-fork/nilearn/datasets/atlas.py in fetch_difumo(dimension, resolution_mm, data_dir, resume, verbose)
97     # Download the zip file, first
98     files_ = _fetch_files(data_dir, files, verbose=verbose)
---> 99 …
```

[MRG] Add DiFuMo atlases

---

nilearn/signal.py

`np.version` no longer has `short_version` in NumPy `master`, but it's also not needed because `nilearn` requires 1.11 nowadays anyway and it was only used in a check for 1.4.

FIX: Remove missing name

---

nilearn/_utils/niimg.py
nilearn/image/image.py
nilearn/plotting/find_cuts.py
nilearn/regions/region_extractor.py

The function `_safe_get_data` makes a copy of the data in some particular case, see #956 
This is a possible solution that makes the data copying behaviour explicit.
Note: If the current behaviour is preferred, I can close both this PR and #956.

Make _get_safe_data consistent

---

doc/whats_new.rst
nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py

Fixes #2220 
Add a `cbar_tick_format` argument to the function `plot_surf` such that users can configure how colorbar tick labels are displayed. The default is in scientific notation.
**Example**
Plot colorbar tick labels as integers:
```python
import matplotlib.pyplot as plt
from matplotlib import ticker
from nilearn import plotting, datasets
destrieux_atlas = datasets.fetch_atlas_surf_destrieux()
parcellation = destrieux_atlas['map_left']
surface = datasets.fetch_surf_fsaverage()
plotting.plot_surf_roi(surface["pial_left"], roi_map = parcellation,
hemi = 'left', view = 'lateral', bg_map = surface["sulc_left"],
bg_on_data = True, darkness = 0.6,
cmap = 'jet', colorbar = True, 
vmin=1, vmax=210, cbar_tick_format="%i")
plt.show()
```

Add cbar_tick_format arg to plot_surf

---

nilearn/__init__.py

Warn Python 3.5 users that we will drop support in release 0.8.0.

drop Python 3.5 in release 0.8.0

---

nilearn/plotting/displays.py
nilearn/plotting/tests/test_img_plotting.py

Fixes #2303 
- `node_color` specified as a numpy array (such that the element-wise comparison does not fail), resulted in an error (see #2303). This PR checks that `node_color` is a string before checking if it is equal to `auto`.
- Catch the mismatch between number of nodes and number of colors when the number of colors is larger than 1.
- Add some tests

Allow array for node color in plot connectome

---

nilearn/reporting/_get_clusters_table.py
nilearn/reporting/tests/test_reporting.py

Closes #2647.
- Warn about centers of mass outside of cluster in `nilearn.reporting._get_clusters_table._identify_subpeaks()` by checking if (sub)peaks fall within the cluster.
- Expand test of `nilearn.reporting._get_clusters_table._local_max()` to check for multiple maxima with the same value and binary cluster with center of mass outside of cluster.

[ENH] Warn about cluster centers of mass outside of cluster

---

nilearn/input_data/masker_validation.py
nilearn/input_data/tests/test_masker_validation.py

Fixes #1066 
Attempt to fix #1066. 
- Set default values to provided estimator if needed instead of crashing with uninformative error message.
- Also warn the user that attributes are being set to default values.
- Add some tests.

Fix unset attributes for check embedded nifti masker

---

nilearn/plotting/find_cuts.py
nilearn/plotting/tests/test_find_cuts.py

Fixes #1189 and #1190 
- The function `find_xyz_cut_coords` now always returns a list rather than numpy array or list
- The function `find_xyz_cut_coords` returns the center of mass when all values are masked due to thresholding rather than center of image which was not in real world coordinates.
**Example**
The following code
```python
import nibabel as nib
from nilearn.plotting import plot_img
from nilearn.plotting import find_xyz_cut_coords
data = np.zeros((20, 20, 20))
data[4:6, 4:6, 4:6] = 1000
img = nib.Nifti1Image(data, np.eye(4))
mask_img = nib.Nifti1Image(np.ones((20, 20, 20), dtype=int), np.eye(4))
cut_coords = find_xyz_cut_coords(img, mask_img=mask_img)
print(cut_coords)
plot_img(img)
```
was producing this output:
and now produces:

Fix find xyz cut coords function

---

nilearn/plotting/surf_plotting.py
nilearn/surface/__init__.py
nilearn/surface/surface.py
nilearn/surface/tests/test_surface.py

Updates of surface handling as discussed in #2171
- Changing the representation of a surface mesh from a list to a named tuple
Additional changes towards a surface object that contains both mesh and data are to follow

changing surface mesh from a list to a namedtuple

---

nilearn/glm/first_level/experimental_paradigm.py
nilearn/glm/tests/test_paradigm.py

Fixes #2367 
- Warns the user when an unexpected field is present in the events dataframe
- Add tests for the `check_events` function

Check events warns for invalid fields

---

doc/whats_new.rst
nilearn/decoding/decoder.py
nilearn/decoding/tests/test_decoder.py

Fixes #2667 
This PR proposes to override the `score` method of the base decoder class such as to compute scores using the scoring strategy provided by the user when instantiating the decoder rather than a default method. 
The scoring strategy of the decoder is defined by
- `decoder.scoring` : Callable, or str, or `None`. Either the scoring method itself or its name as defined in the docstring. If set to `None`, `decoder.score(X, y)` will raise an error.
- `decoding._scoring_metric` : Callable. The scoring method.

Override the decoder score method

---

nilearn/glm/first_level/experimental_paradigm.py
nilearn/glm/tests/test_paradigm.py

This PR addresses #2668 by:
- proposing a way to handle duplicate events, that is events with the same trial type and onset. These events are handled in the following way: their modulation is summed, the maximum duration is kept (assuming their are different), and a warning is given to the user that something might be wrong in the input data.
- updating the `check_events` function to rely more on pandas functionalities since a `DataFrame` is assumed as input
- update and add tests
Notes
- This is still WIP
- I'm not sure this is the best way to handle this weird case. I'm open to suggestions if someone has other ideas

[MRG] Glm duplicate events

---

nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

Closes #2687 .
Inverts the order of 2 blocks of codes in `compute_contrast` first
https://github.com/nilearn/nilearn/blob/e372946bfc91419bc1dbbfadebfed6e6a402956d/nilearn/glm/first_level/first_level.py#L578-L583
then https://github.com/nilearn/nilearn/blob/e372946bfc91419bc1dbbfadebfed6e6a402956d/nilearn/glm/first_level/first_level.py#L572-L578 
This fixes computation of contrast given as text formulas for:
- matrices with varying size (mostly due to cosine drifts in runs with varying length) that for now crashes unless hacked.
- matrices with varying column ordering (for whatever weird reason) for which the contrast would be computed on the wrong columns assuming order from first run matrix.

fix for FirstLevelModel compute_contrast for multiple runs with varying matrice size or columns

---

nilearn/input_data/nifti_masker.py
nilearn/reporting/data/html/report_body_template.html
nilearn/reporting/html_report.py
nilearn/reporting/tests/test_html_report.py

This PR tackles one of the points of #2689 by :
- giving a `UserWarning` when generating a report with a `NiftiMasker` and no image provided to fit
- printing a warning message in bold red in the report
**Example**
```python
from nilearn.input_data import NiftiMasker
haxby_dataset = datasets.fetch_haxby()
nifti_masker = NiftiMasker(mask_img=haxby_dataset.mask_vt[0])
nifti_masker.fit()
report = nifti_masker.generate_report()
report
```

Warn in nifti masker report when no image provided to fit

---

nilearn/reporting/_get_clusters_table.py
nilearn/reporting/tests/test_reporting.py

Closes #2700 .
- use check_niimg_3d to load filenames and ensure input is 3D
- test filename functionality and extra dimensions

[FIX] get_clusters_table: ensure input is 3D and accept filenames

---

nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py

Fixes #2690 
Filter out nan values from the texture when no thresholding is performed. This is done automatically with thresholding, hence the inconsistent behaviour observed in #2690 
```python
import warnings;warnings.filterwarnings('ignore')
from nilearn import plotting, datasets, surface
motor_images = datasets.fetch_neurovault_motor_task()
fsaverage = datasets.fetch_surf_fsaverage()
texture = surface.vol_to_surf(motor_images.images[0], fsaverage.pial_right)
texture[::2] = np.nan
plotting.plot_surf_stat_map(fsaverage.infl_right, texture, hemi='right',
title='Surface right hemisphere', colorbar=True,
bg_map=fsaverage.sulc_right)
```
Pinging @alexisthual who found the bug

[MRG] Handle nans in surf plotting

---

doc/whats_new.rst
examples/03_connectivity/plot_multi_subject_connectome.py
nilearn/input_data/base_masker.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_labels_masker.py
nilearn/input_data/nifti_maps_masker.py
nilearn/input_data/nifti_masker.py
nilearn/input_data/nifti_spheres_masker.py
nilearn/tests/test_masking.py

Addresses #1241 
This PR proposes to add a `high_variance_confounds` boolean parameter to the maskers in order to compute high variance confounds on provided images and regress them out on the fly.
The usual coding pattern
```python
from nilearn.image import high_variance_confounds
hv_confounds = high_variance_confounds(img)
masker = NiftiMasker(standardize=True, detrend=False,
mask_img=mask).fit()
tseries = masker.transform(img, confounds=[hv_confounds, conf])
```
would get simplified to:
```python 
masker = NiftiMasker(standardize=True, detrend=False,
high_variance_confounds=True,
mask_img=mask).fit()
tseries = masker.transform(img, confounds=conf)
```

[MRG] High variance confounds in maskers

---

nilearn/masking.py

Fixes #2163 where loading an SPM image containing NaNs would trigger a runtime warning in older versions of numpy.

Fixes numpy runtime warning in masking.py when img has NaNs.

---

nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

- Adding a warning in the fit function when both the design matrices and (confounds and events) are provided in #2704

Raise warning for FirstLevelModel fit when confounds and design_matrices are both specified

---

doc/plotting/index.rst
doc/whats_new.rst
examples/01_plotting/plot_demo_more_plotting.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_img_plotting.py

Closes #212 .
- display_mode='mosaic' should plot images of multiple rows and columns
- By default, ```cut_coords``` are automatically found for 7 slices to plot against three direction xyz.
A simple code that works:
```python
motor_images = datasets.fetch_neurovault_motor_task()
stat_img = motor_images.images[0]
from nilearn import plotting
plotting.plot_stat_map(stat_img, display_mode='mosaic')
plotting.show()
```
```python
from nilearn.datasets import MNI152_FILE_PATH
from nilearn import plotting
plotting.plot_img(MNI152_FILE_PATH, display_mode='mosaic')
plotting.show()
```
However, there are problems.
- Code breaks if ```cut_coords``` are provided manually by the user. As current code forms a list of 7 …

[MRG] Mosaic mode of displaying brain images

---

examples/03_connectivity/plot_atlas_comparison.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting.py

Addresses #1513 
**Description**
This PR proposes to allow asymmetric matrices to be plotted as a directed graph through the `plot_connectome` function. Previous behaviour was to raise an error.
**Example**
```python
from nilearn import datasets, plotting
from nilearn.input_data import NiftiLabelsMasker
from nilearn.connectome import ConnectivityMeasure
yeo = datasets.fetch_atlas_yeo_2011()
data = datasets.fetch_development_fmri(n_subjects=10)
connectome_measure = ConnectivityMeasure(kind='correlation')
masker = NiftiLabelsMasker(labels_img=yeo['thick_17'], standardize=True,
memory='nilearn_cache')
time_series = []
for func, confounds in zip(data.func, data.confounds):
time_series.append(masker.fit_transform(func, confounds=confounds))
correlation_matrices = …
```

[MRG] Allow asymmetric matrices in plot_connectome

---

doc/whats_new.rst
nilearn/_utils/niimg.py
nilearn/input_data/tests/test_nifti_labels_masker.py
nilearn/input_data/tests/test_nifti_maps_masker.py
nilearn/regions/signal_extraction.py
nilearn/regions/tests/test_signal_extraction.py

Closes #2711.
- Use `_safe_get_data`'s `ensure_finite` parameter to replace NaNs with zeros in the `NiftiLabelsMasker`. This matches the behavior of the `NiftiMapsMasker` and, most likely, the others as well.
- Add a warning to `_safe_get_data` when `ensure_finite` is used and non-finite values are detected in the data.

Replace NaNs with zeros in NiftiLabelsMasker

---

doc/whats_new.rst

Fix current CircleCI build failure by fixing latest entry of  `whats_new.rst` to reference public function `signal.clean` instead of `signal._standardize` (introduced in #2714).

Fix whatsnew entry with public function reference

---

nilearn/_utils/niimg.py
nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py
nilearn/plotting/displays.py
nilearn/plotting/tests/test_img_plotting.py

Fixes #2537 
See explanations in #2537. 
Not sure this is the best fix although it's pretty straightforward.

bugfix resample only if type is not contour or contourf

---

doc/whats_new.rst
nilearn/reporting/_get_clusters_table.py
nilearn/reporting/glm_reporter.py
nilearn/reporting/tests/test_reporting.py

Closes #2547.
- Add a two_sided flag (default=True) to `nilearn.reporting._get_clusters_table()`.
- Update tests.
- Use two_sided thresholding in `glm_reporter`.

Add two_sided flag to get_clusters_table

---

doc/development.rst

Since we are close to make the `0.7.1` release, I thought it'd be a good idea to have the steps for making a new release of Nilearn in the contributing doc. 
This is a first draft proposal. I am not sure I added the text in the best place, and I don't know if it is too detailed or not enough. Comments and suggestions are welcome, especially if I forgot something!

[DOC] Add guidelines in doc for making new releases of Nilearn

---

nilearn/plotting/matrix_plotting.py

- Rewrites `inverse_transformed` for matrix plotting as recommended in matplotlib 3.3

[MAINT] matplotlib will soon drop inverse_transformed

---

nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py

See Neurostars post [here](https://neurostars.org/t/plot-3d-nifiti-on-surface-using-nilearn/18715).
Calling `plot_surf_roi` with a texture containing nans raises an error wile `plot_surf_stat_map` doesn't, although both functions rely on the same `plot_surf` function. This PR makes it possible to use `plot_surf_roi` with nans in the texture and makes the surface plotting more consistent.
*Note: output figures order is reversed for some reason...*
```python
from nilearn.surface import vol_to_surf
from nilearn.plotting import plot_surf_roi
from nilearn.datasets import fetch_surf_fsaverage, fetch_neurovault_motor_task
fsaverage = fetch_surf_fsaverage('fsaverage')
stat_img = fetch_neurovault_motor_task()
texture = vol_to_surf(stat_img.images[0], 
fsaverage.pial_left)
assert …
```

handle nans in plot_surf_roi

---

.circleci/config.yml
doc/Makefile
tools/circleci_build_type.sh
tools/circleci_dependencies.sh
tools/circleci_dependencies_apt.sh

This is an attempt to reduce the documentation generation time on CircleCI, and is largely inspired by the way MNE handles this. 
The main idea is to adapt the build type depending on the branch and the files that have been modified. The behaviour should be the following:
- *Full build* on master
- *Full build* on other branches if the commit message contains the tag `[circle full]`
otherwise, do a *partial build*:
- Build only the examples that were modified in the branch
- Make a "no-plot" build if examples weren't modified 
I am also cleaning the current CircleCI workflow since I'm not sure everything is still mandatory or useful.
*Note: This is WIP, failures expected...*

[MAINT][MRG] Reduce CircleCI build time

---

tools/circleci_build_type.sh

Typo currently causing circleCI to make "no-plot" builds on master... :sweat:

[FIX][MAINT] Fix typo in CircleCI script

---

nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

This PR proposes to improve the testing of `nilearn/glm/first_level/first_level.py` since the coverage of this file was significantly (around 74%) lower than for most others. 
It also adds a few safety checks in `fit` to avoid unexpected `AttributeErrors` to occur in some edge cases.

Improve testing/coverage of first level glm

---

nilearn/_utils/data_gen.py
nilearn/connectome/group_sparse_cov.py
nilearn/datasets/func.py
nilearn/decoding/decoder.py
nilearn/decoding/objective_functions.py
nilearn/decoding/proximal_operators.py
nilearn/glm/first_level/hemodynamic_models.py
nilearn/glm/regression.py
nilearn/image/tests/test_resampling.py
nilearn/plotting/edge_detect.py
nilearn/plotting/find_cuts.py
nilearn/plotting/img_plotting.py
nilearn/regions/tests/test_signal_extraction.py
nilearn/signal.py
nilearn/tests/test_masking.py
nilearn/tests/test_signal.py

Remove remaining numpy type deprecation warnings.
Note: This reduces the number of warnings from around 39200 to around 1300 when running the tests.

[MAINT] Remove numpy type deprecation warnings

---

nilearn/glm/second_level/second_level.py
nilearn/glm/tests/test_second_level.py

Following #2764 this PR proposes to improve testing and coverage for `nilearn/glm/second_level/second_level.py`.
Helper functions from this file are also unit-tested in a consistent way.

Improve testing and coverage of glm second level

---

doc/bibliography.rst
doc/conf.py
doc/references.bib
doc/themes/nilearn/layout.html
nilearn/datasets/atlas.py
nilearn/regions/rena_clustering.py
requirements-build-docs.txt
tools/circleci_dependencies.sh

This PR proposes to use [sphinxcontrib-bibtex](https://github.com/mcmtroffaes/sphinxcontrib-bibtex) to manage references in the documentation. This PR configures the extension and provides a couple examples. 
Other references will have to be added to the bib file and the docstrings will have to be updated. I will open small "good first issues" for the sprint targeting the different files which need to be updated. This is what [MNE](https://github.com/mne-tools/mne-python) did for their last sprint and I think it was a very good way to onboard new people with a very simple first PR. 
WDYT?
This will have the following advantages:
- consistent formatting of references across doc
- no more copy-pasting of references, they are all stored in `references.bib`
- easier maintenance
- Auto …

[DOC][MRG] Configure bibtex references

---

doc/whats_new.rst
nilearn/signal.py
nilearn/tests/test_signal.py

- Fixes the issue raised in #2730 
- In particular, it changes the order of detrending and low and high pass filtering in `clean` such that it is the same that takes place with the input signal, i.e, first detrend and then frequency filtering. Currently, confounders were first low or high-pass filtered and then detrended, if requested from the beginning.

Detrending before low and high pass filtering for the confounders in clean function

---

doc/whats_new.rst
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

Closes #2772 
Fixed indentations in `_get_voxelwise_model_attribute` to return as many attributes as design matrices. Added test with either 1 or 2 design matrices to make sure it's working fine.

First Level get_voxelwise_model_attribute should return as many elements as # design matrices

---

nilearn/plotting/surf_plotting.py

Closes #1755 
- To the docstrings of a few functions that plot surface images, links have been added to `nilearn.surface.vol_to_surf`

[DOC] Mention vol_to_surf in plot_surf* function docstrings

---

doc/references.bib
nilearn/plotting/img_plotting.py

Closes #2786 
- Converted the reference in `nilearn/plotting/img_plotting.py` to bibtex format and added it to `doc/references.bib`

[DOC] Convert references in nilearn/plotting to bibtex format

---

doc/whats_new.rst
examples/01_plotting/plot_3d_map_to_surface_projection.py
nilearn/plotting/html_surface.py
nilearn/plotting/tests/test_html_surface.py

Closes #2180  .
- Added an optional parameter `vol_to_surf_kwargs` to `view_img_on_surf` and pass this through to `full_brain_info`.

WIP: Pass through vol_to_surf_kwargs

---

doc/references.bib
nilearn/connectome/connectivity_matrices.py
nilearn/connectome/group_sparse_cov.py

Closes #2780
- Converted the references in `nilearn/connectome/connectivity_matrices.py` and `nilearn/connectome/group_sparse_cov.py` to bibtex format and added them to `doc/references.bib`

[DOC] Convert references in nilearn/connectome to bibtex format

---

doc/whats_new.rst
nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py

This PR closes #2790.
So far, this PR adds 2 possible entries for the `avg_method` argument in `plotting.plot_surf`: `min` and `max`.
We are still considering adding the possibility to pass a custom aggregation function for `avg_method`.

[WIP] Add min and max as possible avg_method in plot_surf (#2790)

---

nilearn/_utils/testing.py
nilearn/surface/tests/test_surface.py
nilearn/tests/test_niimg_conversions.py
nilearn/tests/test_numpy_conversions.py

Fixes #2832 
This PR aims at replacing `mktemp` with `mkstemp` as suggested by @jeromedockes in #2832 
I think we also need to test on ARM architectures to detect these kinds of bugs. 
For the moment, this would mean bringing travis back into the CI, and only run ARM tests to save credits (this is what scikit-learn is doing currently for instance). I will open a separate issue on this as this would require some work (especially to avoid systematic building of wheels...).

Replace mktemp with mkstemp

---

.github/workflows/assign.yml
CONTRIBUTING.rst

Fixes #2794 
This PR proposes to use a github action to assign issues automatically when commenting "take" on them. It also removes the label "help wanted" in case it was associated to the issue.
This comes from scikit-learn so I can add a comment citing the source at the beginning of the file if we decide to use it.

Add issue assignment action

---

.circleci/config.yml

See #2846 
On circleCI, partial builds can cache data although they usually have only partial data. 
This PR aims at restricting the data caching to full builds only.

[MAINT] Restrict data caching to full builds

---

.github/workflows/testing.yml
build_tools/github/dependencies.sh
build_tools/github/test.sh
build_tools/github/test_docs.sh

Following PR #2848 this PR makes sure tests, doctests, and flake8 checks are run in separate steps of the workflows instead of running them in a single step and using environment variables to configure which scripts are run.
I realized that if you run, for example, tests and doctests in the same step and tests fail while doctests pass, you will get a :heavy_check_mark:  instead of a :x: next to the github action, which is very confusing... See for example [here](https://github.com/nilearn/nilearn/pull/2815/checks?check_run_id=2689751187)

[MAINT] Run tests, doctests, and flake8 diff in their own steps

---

nilearn/glm/model.py
nilearn/glm/regression.py
nilearn/glm/tests/test_regression.py

Some attributes in the GLM module are deprecated but the deprecation warnings were missing the version numbers. I assumed these are deprecated since 0.7.0 and will be removed in 0.9.0.
These was also a `@auto_attr` decorator missing for one of the `predicted` method.

[MAINT] Add missing versions in some deprecation warnings

---

doc/manipulating_images/masker_objects.rst
doc/whats_new.rst
nilearn/_utils/__init__.py
nilearn/_utils/helpers.py
nilearn/input_data/base_masker.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_labels_masker.py
nilearn/input_data/nifti_maps_masker.py
nilearn/input_data/nifti_masker.py
nilearn/input_data/nifti_spheres_masker.py
nilearn/input_data/tests/test_nifti_masker.py
nilearn/signal.py
nilearn/tests/test_signal.py

Closes #1012. Replace #2857 due to formatting was messed up. 
- In `base_masker`, move parameter `sample_mask` from initialization to `transform` method, and all the Masker modules.
- Handle `sample_masks` with `signal.clean`
- Move input validation related to `runs` to a separate private function from `_process_runs`  and `_sanitize_inputs` to `_sanitize_runs` 
While implementing the discussed changes, I found how sample_mask should be handled when there are multiple runs more complicated than anticipated.
Here's a summary of the current implementation:  
* accept any input valid for indexing NumPy array as `sample_mask`
* for multiple runs, user must pass a list of sample masks to `sample_mask` (a set of index per run).
I have tried to implement …

Move `sample_mask` to `transform` method in maskers, handle `sample_mask` in `signal.clean`

---

.circleci/README.md
.circleci/config.yml
.github/pull_request_template.md
.github/workflows/pep8.yml
.github/workflows/testing.yml
README.rst
azure-pipelines.yml
build_tools/circle/build_type.sh
build_tools/flake8_diff.sh
codecov.yml
doc/conf.py
doc/development.rst
nilearn/tests/test_signal.py

Fixes #2841 
This PR prepares the renaming of branch `master` into `main`. 
I am not sure when we want to pull the trigger, but the steps will be the following:
- Rename branch `master` into `main` on the repo's main page (this should update the target branch of ongoing PRs including this one)
- Check that everything runs fine here and merge
- All clones will have to run locally:
```bash
$ git branch -m master main
$ git fetch origin
$ git branch -u origin/main main
$ git remote set-head origin -a
```
Note that GitHub will display a note on the main page saying that the main branch has been renamed, and that you should run these commands to update your clone.

[MAINT] Rename master into main

---

doc/whats_new.rst
nilearn/connectome/__init__.py
nilearn/connectome/connectivity_matrices.py

Function `sym_to_vec` is deprecated since release 0.4 and scheduled to be removed in 0.8.

Remove deprecated function `sym_to_vec`

---

examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
nilearn/decomposition/base.py
nilearn/decomposition/canica.py
nilearn/decomposition/dict_learning.py
nilearn/decomposition/multi_pca.py

Closes #2862 
This PR:
- Removes the deprecation message for attribute `components_` and replaces it with a usage note explaining that `components_img_` can be used instead. Both attributes are kept to conform with other objects in Nilearn (Decoder for example).
- Uses `components_img_` instead of unmasking `components_`
- Moves the definition and fitting of NiftiMapsMasker from `transform` and `inverse_transform` to `fit`

Fix deprecation of decomposition `components_`

---

doc/whats_new.rst
examples/06_manipulating_images/plot_nifti_labels_simple.py
nilearn/input_data/nifti_labels_masker.py
nilearn/input_data/nifti_masker.py
nilearn/reporting/data/html/report_body_template.html
nilearn/reporting/data/html/report_body_template_niftilabelsmasker.html
nilearn/reporting/html_report.py
nilearn/reporting/tests/test_html_report.py

See #2689 
**Description**
This draft PR proposes to add reporting capabilities to the `NiftiLabelsMasker`: 
- It reworks the template logic a little bit to be able to select different templates depending on the estimator
- It proposes a possible report format which is composed of a `plot_roi` of the regions as suggested by @GaelVaroquaux  in #2689, a count of the different regions, and adds a button to display information about each region. For now, only the label number, the name, the size (in number of voxels), and relative size are provided for each region.
*Note: Comments are welcome to improve the report!* 
**Example**
```python
from nilearn.input_data import NiftiLabelsMasker
atlas = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
data = …
```

[MRG][ENH] NiftiLabelsMasker Reporting

---

doc/decoding/estimator_choice.rst
doc/decoding/frem.rst
doc/decoding/going_further.rst
doc/decoding/searchlight.rst
doc/decoding/space_net.rst
doc/introduction.rst
doc/references.bib

This PR proposes some small enhancements to the user guide (introduction and decoding) by:
- fixing some broken links and adding a few new ones
- fixing some formatting issues
- adding dummy options for the estimators
- converting hard-coded scientific references to Bibtex (they will be much easier to maintain and will appear in the general bibliography).
Still WIP...

[DOC] Decoding and introduction documentation enhancements

---

doc/whats_new.rst
nilearn/plotting/html_stat_map.py
nilearn/plotting/tests/test_html_stat_map.py

Fixes #2874 
This PR proposes a possible fix for #2874. 
I'm slightly out of my comfort zone here so I'll take any advice... :sweat_smile: 
```python
from nilearn import plotting, datasets
plotting.view_img(datasets.load_mni152_template(), black_bg=False, bg_img=None)
```

[FIX] Fix view_img colorbar

---

doc/whats_new.rst
nilearn/_utils/__init__.py
nilearn/_utils/docs.py
nilearn/datasets/atlas.py
nilearn/datasets/func.py
nilearn/datasets/struct.py
nilearn/datasets/utils.py
nilearn/decoding/decoder.py
nilearn/decoding/searchlight.py
nilearn/decoding/space_net.py
nilearn/plotting/html_surface.py

This PR proposes to add a `fill_doc` decorator to automatically fill parts of docstrings. 
An example on the `datasets`  and `decoding` modules is also provided with the parameters `verbose`, `resume`, `data_dir`, `url`, `smoothing_fwhm`, `standardize`, `target_affine`, `target_shape`, `low_pass`, `high_pass`, `t_r`, `memory`, `memory_level`, and `n_jobs`.
Note: The code for the decorator comes from MNE (link at the top of `nilearn/_utils/docs.py`).
This has the following benefits:
- Standard documentation entries are all in one place
- Simplifies the maintenance of docstrings/documentation
- Reduces the length of files (several hundreds of lines were removed from the `datasets` module with this simple example although the rendering is exactly the same as before).
If we decide to adopt …

[MAINT] Add `fill_doc` decorator

---

README.rst

This PR proposes to add a few lines in the README to advertise for the Nilearn office hours with the next date and discord link, as suggested by @RaphaelMeudec as a way to increase the visibility of these events.

[DOC] Advertise for office hours in README

---

doc/modules/reference.rst
doc/whats_new.rst
nilearn/image/__init__.py
nilearn/image/image.py
nilearn/image/tests/test_image.py

If there is interest, this PR adds a function to the image package to binarize images. I see myself using it all the time, and thought I'd share it.
It is based off of threshold img and math img to reduce burden on maintainers. As long as those two functions work properly, bin img should as well.

Add bin_img to binarize images

---

README.rst
build_tools/circle/dependencies.sh
build_tools/travis/install.sh
requirements-build-docs.txt
requirements-dev.txt

This PR adds both plotly and kaleido to the optional dependencies.
See also #2902

[INFRA] Add plotly and kaleido to dependencies

---

nilearn/datasets/func.py

- This PR fixes a dead link: from http://brainomics.cea.fr/localizer/ to https://osf.io/vhtf6/

[DOC] Fix dead link for localizer dataset

---

doc/whats_new.rst
nilearn/_utils/docs.py
nilearn/plotting/html_stat_map.py
nilearn/plotting/img_plotting.py
nilearn/plotting/matrix_plotting.py
nilearn/plotting/surf_plotting.py

This PR proposes to extend recent work from #2875 to the `plotting` module where a lot of arguments are common to multiple functions. It also improves already standardized docstrings (add object references for example).

[DOC][MAINT] Standardize docstrings of `plotting` module

---

doc/connectivity/functional_connectomes.rst
doc/plotting/index.rst

Closes # .
- FIX the order of the plotting figures demonstration in plotting user guide.
That was probably because of me while working on this PR #2684

DOC: Fixing the order of the linked displays while demoing plotting in user guide

---

nilearn/externals/tempita/__init__.py

Call to a non-callable of class Template.
Looks like an LGTM false positive to me.
Anyway, this alternative sytax should make the error go away.

[FIX] LGTM error: Non-callable called

---

nilearn/plotting/data/html/connectome_plot_template.html

This is a JavaScript issue, in an HTML page:
Variable info is used like a local variable, but is missing a declaration.

[FIX] LGTM warning: Missing variable declaration

---

nilearn/image/resampling.py

Values compared using 'is' when equivalence is not the same as identity. Use '==' instead.
The above suggestion is incorrect, though. See discussion in https://github.com/nilearn/nilearn/pull/2920#discussion_r690723512. Instead use code suggested in https://github.com/nilearn/nilearn/pull/2920#discussion_r691281123.

[FIX] LGTM warning: Comparison using is when operands support `__eq__`

---

doc/whats_new.rst
nilearn/_utils/docs.py
nilearn/datasets/tests/test_atlas.py
nilearn/datasets/tests/test_func.py
nilearn/datasets/tests/test_neurovault.py
nilearn/datasets/tests/test_utils.py
nilearn/datasets/utils.py

This PR adds support for `pathlib.Path` to `data_dir` argument in datasets fetchers. All the fetchers from `nilearn.datasets` now accepts `pathlib.Path` or a string (instead of string only).
I have modified the tests from all fetchers which had to cast the `tmp_path` fixture to a string. Now the fixture is used directly as `data_dir` argument. This means there is no more tests for `data_dir` as a string, and I wasn't sure if I needed to keep both case (through a parametrize for each test for example)
The PR can easily be read commit by commit:
1. Changes to `nilearn.datasets.utils` that add `pathlib.Path` support
2. Modifications of the tests to avoid casting `tmp_path` to string everytime
3. Update document variable `data_dir`
4. Whatnew entry
I'm open to your opinions on the "no more …

Add pathlib.Path support for nilearn.datasets

---

nilearn/glm/_base.py
nilearn/glm/contrasts.py
nilearn/glm/first_level/design_matrix.py
nilearn/glm/first_level/experimental_paradigm.py
nilearn/glm/first_level/first_level.py
nilearn/glm/second_level/second_level.py
nilearn/glm/tests/test_check_events_file_uses_tab_separators.py
nilearn/glm/tests/test_dmtx.py
nilearn/glm/tests/test_first_level.py
nilearn/glm/tests/test_hemodynamic_models.py
nilearn/glm/tests/test_paradigm.py
nilearn/glm/tests/test_second_level.py
nilearn/glm/tests/test_utils.py
nilearn/glm/thresholding.py

Following #2915 and #2916 I noticed that flake is only run on changes to code (I think?). So I manually ran a flake check locally on the GLM module and then manually fixed most errors. I didn't use an automated approach, I can if you prefer.
No hard feeling if you want to reject this PR, I didn't ask in advance, and it touches a lot of code, so is probably risky.
TODO:

Flake fixes for GLM module

---

nilearn/image/image.py

The value assigned to local variable '`imgs`' is never used.

[FIX] LGTM recommendation: Unused local variable

---

nilearn/datasets/func.py
nilearn/datasets/tests/test_utils.py
nilearn/glm/tests/test_thresholding.py

As in [flake8 documentation](https://flake8.pycqa.org/en/latest/user/violations.html#in-line-ignoring-errors) and according to usual English punctuation. Consistent with the rest of the code.

[DOC] Canonical noqa syntax

---

nilearn/plotting/cm.py
nilearn/plotting/displays.py
nilearn/plotting/img_plotting.py

Should fix on latest `matplotlib` dev:
```
matplotlib._api.deprecation.MatplotlibDeprecationWarning: LUTSIZE was deprecated in Matplotlib 3.5 and will be removed two minor releases later. Use rcParams['image.lut'] instead.
```

MAINT: Deal with mpl deprecation

---

nilearn/datasets/atlas.py

Missing `fill_doc` decorator was causing documentation bugs [here](https://7947-1235740-gh.circle-artifacts.com/0/dev/modules/generated/nilearn.datasets.fetch_atlas_yeo_2011.html#nilearn.datasets.fetch_atlas_yeo_2011)

[DOC] Add missing `fill_doc` decorator

---

nilearn/glm/first_level/first_level.py

- fixed a minor typo in docstring. No functional changes.
On that note, this is probably not the right place to ask, but how does one get the the parameter estimates from ``compute_contrast``? I know this should be super simple...
````
from nilearn.glm.first_level import FirstLevelModel
glm = FirstLevelModel()
glm = glm.fit(fmri_img, design_matrices=design_matrices)
glm.compute_contrast(contrast_val, output_type='z_score')
`````
If I understand correctly, the supported values for ``output_type`` provide only a p-value, the test statistics (t or F), or a z-value (i.e., df-free representation of the test statistic).
This [example](https://nilearn.github.io/auto_examples/04_glm_first_level/plot_spm_multimodal_faces.html#sphx-glr-auto-examples-04-glm-firs …

[DOC] fix typo in FirstLevelModel docstring

---

doc/manipulating_images/masker_objects.rst
doc/whats_new.rst
examples/03_connectivity/plot_compare_decomposition.py
examples/06_manipulating_images/plot_mask_computation.py
nilearn/_utils/docs.py
nilearn/decoding/decoder.py
nilearn/decomposition/base.py
nilearn/decomposition/canica.py
nilearn/decomposition/dict_learning.py
nilearn/decomposition/multi_pca.py
nilearn/input_data/multi_nifti_masker.py
nilearn/input_data/nifti_masker.py
nilearn/input_data/tests/test_multi_nifti_masker.py
nilearn/input_data/tests/test_nifti_masker.py
nilearn/regions/parcellations.py

Fixes #2890 
Following the work of #2738, this PR proposes to add more options for the argument `mask_strategy`. 
That is, the former option `template` is replaced by `wb-template`, and options `gm-template` and `wm-template` are added to rely on the grey and white matter templates.

[ENH] Add more options for `mask_strategy`

---

doc/Makefile

HTTPS authentication has been deprecated for a while and is not supported by GitHub since mid-August.
This PR updates the `install` target of the doc Makefile to use SSH instead of HTTPS.

[MAINT] Use SSH in doc Makefile

---

nilearn/_utils/numpy_conversions.py

This assignment to '`ret`' is unnecessary as it is redefined [`here`](https://lgtm.com/projects/g/nilearn/nilearn/snapshot/d520eb8468e57b591fe97798f038a56ab134679b/files/nilearn/_utils/numpy_conversions.py?sort=name&dir=ASC&mode=heatmap#x8ed7d7b85aaf0808:1) before this value is used.
Closes #2959.

[FIX] LGTM warning: Variable defined multiple times

---

nilearn/plotting/cm.py

In general, you cannot modify the local symbol table returned by `locals()`.
However, in the scope of the module, `locals()` is identical to `globals()`.
To make the intent clear, use `globals()` instead of `locals()`.
Closes #2957.

[FIX] locals() → globals()

---

examples/07_advanced/plot_advanced_decoding_scikit.py

This assignment to '`cv_scores`' is unnecessary as it is redefined [`here`](https://lgtm.com/projects/g/nilearn/nilearn/snapshot/3af46e7cd3a9362bb815e3deb17d8c3d95485758/files/examples/03_connectivity/plot_extract_regions_dictlearning_maps.py?sort=name&dir=ASC&mode=heatmap#x673dd6739f275dd8:1) before this value is used.
https://lgtm.com/projects/g/nilearn/nilearn/snapshot/3af46e7cd3a9362bb815e3deb17d8c3d95485758/files/examples/07_advanced/plot_advanced_decoding_scikit.py#x5b739e019ffb38d3:1

[FIX] LGTM.com warning: Variable defined multiple times

---

README.rst
nilearn/decomposition/base.py
nilearn/decomposition/dict_learning.py
nilearn/externals/tempita/__init__.py
nilearn/externals/tempita/_looper.py
nilearn/glm/tests/test_second_level.py

These `from __future__ import` seem to be leftovers from when Python 2 was supported.
[__future__ — Future statement definitions](https://docs.python.org/3/library/__future__.html)

from __future__ import: not needed in Python >= 3.6

---

doc/glossary.rst
examples/04_glm_first_level/plot_bids_features.py
nilearn/_utils/data_gen.py
nilearn/datasets/func.py

Small PR to add `fMRIPrep` to the glossary and try triggering the auto-comment action (See #2982).
Ping @thomasbazeille

[DOC] Add `fMRIPrep` to glossary

---

examples/05_glm_second_level/plot_thresholding.py

Closes None, but fixes a bug I introduced into the `plot_thresholding` example in #2965.
- Replace pipes in example with `abs()`. Apparently pipes indicate a substitution, which I was not aware of when I used them.

[FIX] Replace undefined RST substitution in example

---

nilearn/input_data/nifti_labels_masker.py
nilearn/masking.py

The value assigned to local variable '`mask_data`' is never used.
The value assigned to local variable '`mask_affine`' is never used.
Closes #2993.

[MAINT] LGTM.com recommendation: Unused local variable

---

nilearn/regions/rena_clustering.py

Base classes have conflicting values for attribute '`_more_tags`': Function `_more_tags` and Function `_more_tags`.
Both `BaseEstimator` and `ClassifierMixin` define `_more_tags()`. Override the function in the subclass `ReNA` to explicitly implement the previous behaviour, implicitly chosen by the Python [MRO](https://www.python.org/download/releases/2.3/mro/).
**Please review carefully**, as I'm not certain whether the initial implicit behaviour was the expected behaviour.

[FIX] LGTM.com warning: Conflicting attributes in base classes

---

examples/02_decoding/plot_miyawaki_reconstruction.py
examples/07_advanced/plot_advanced_decoding_scikit.py
examples/07_advanced/plot_age_group_prediction_cross_val.py

Scikit-learn has deprecated positional args in various parts of their API since 0.23 and removed them in 1.0 (See [this PR](https://github.com/scikit-learn/scikit-learn/pull/20002)).

[MAINT] Fix positional args deprecations (sklearn >= 1.0)

---

doc/whats_new.rst
nilearn/signal.py
nilearn/tests/test_signal.py

Closes #2999.
When `standardize_confounds=False, detrend=False`, raise warning and remind users to either apply the option or demean the signal.

[ENH] add warning message to illogical parameter combination passed to `signal.clean`

---

doc/glossary.rst
doc/modules/reference.rst
nilearn/_utils/docs.py
nilearn/signal.py

Similarly to #3004 for `masking`, this PR proposes to make some improvements to the documentation of the `signal` module.
It also adds the function `nilearn.signal.butterworth` to the public API as this function was public but not included in the docs.

[DOC] Improve documentation of `signal` module

---

doc/whats_new.rst
nilearn/_utils/docs.py
nilearn/glm/first_level/design_matrix.py
nilearn/glm/first_level/first_level.py
nilearn/glm/first_level/hemodynamic_models.py
nilearn/glm/tests/test_hemodynamic_models.py

See feature request #2940 
**Description**
This PR is still (very) WIP but proposes a draft of a possible API allowing users to provide a custom HRF model when running GLMs. The user basically has to write a function, or a list of functions computing the samples rather than providing the values directly.
Note: This PR is still lacking a lot of things but I wanted to discuss the possible API before going further.
**Example**
```python
from nilearn.glm.first_level import FirstLevelModel
def custom_hrf(tr, oversampling=50, time_length=32, onset=0.):
"""This should be defined by the user and comply with the API of other
HRF models implemented in Nilearn.
"""
hrf = np.ones(time_length)
hrf[0] = 0
hrf[-1] = 0
hrf /= hrf.sum()
return hrf
fmri_glm = FirstLevelModel(
t_r=2, …
```

[ENH] Allow custom HRF models

---

nilearn/plotting/surf_plotting.py

This assignment to '`face_colors`' is unnecessary as it is redefined [here](https://github.com/nilearn/nilearn/blob/4280451/nilearn/plotting/surf_plotting.py#L392) before this value is used.
https://lgtm.com/projects/g/nilearn/nilearn/snapshot/0277ef6bc1aaa54a0419a4102beeb2e410a3a306/files/nilearn/plotting/surf_plotting.py?sort=name&dir=ASC&mode=heatmap#x841fc8fb537934bc:1

[MAINT] LGTM.com warning: Variable defined multiple times

---

nilearn/input_data/fmriprep_confounds.py
nilearn/input_data/fmriprep_confounds_components.py
nilearn/input_data/fmriprep_confounds_strategy.py
nilearn/input_data/tests/test_fmriprep_confounds.py
nilearn/input_data/tests/test_fmriprep_confounds_strategy.py

In `nilearn.input_data.fmriprep_confounds`, two parameter names are not matching the docstrings.
`fd_thresh` -> `fd_threshold`
`std_dvars_thresh` -> `std_dvars_threshold`

[FIX] scrubbing parameter names in `nilearn.input_data.fmriprep_confounds` not matching docstring

---

doc/conf.py

Fix needed with latest version (`0.10.1`) of `sphinx-gallery`. `plot_gallery` should no longer be a string, but a boolean, otherwise a warning is raised which makes the CI fail in strict mode.
See https://github.com/sphinx-gallery/sphinx-gallery/pull/863

[FIX] Fix sphinx config

---

nilearn/datasets/func.py

SciPy made the `scipy.io.matlab` namespace private. This is a temporary workaround PR until https://github.com/scipy/scipy/pull/15004 is in and these hopefully land in a public namespace, so don't merge yet.

MAINT: Work around SciPy deprecation

---

examples/04_glm_first_level/plot_spm_multimodal_faces.py

Example `04_glm_first_level/plot_spm_multimodal_faces.py` returns the same two warnings hundreds of times because it makes heavy resampling operations. 
This PR proposes to silence these warnings in the example to get cleaner outputs and logs.

[MAINT] Filter `Userwarning` in example

---

doc/whats_new.rst
examples/03_connectivity/plot_probabilistic_atlas_extraction.py
nilearn/input_data/nifti_maps_masker.py
nilearn/reporting/data/html/report_body_template_niftimapsmasker.html
nilearn/reporting/html_report.py
nilearn/reporting/tests/test_html_report.py

See #2689 
Minimum code to experiment:
```python
from nilearn.input_data import NiftiMapsMasker
msdl = datasets.fetch_atlas_msdl()
masker = NiftiMapsMasker(maps_img=msdl.maps)
masker.fit()
report = masker.generate_report(displayed_maps=[19, 22, 2, 4, 16, 6, 9])
report
```

[ENH] NiftiMapsMasker Reporting

---

doc/whats_new.rst
nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

See #2036 
This PR adds a test failing with extra labels present in the csv file but not in the image, and adds a fix which removes these labels. This PR only targets `fetch_atlas_destrieux_2009`.

[FIX] Fix labels in `fetch_atlas_destrieux_2009`

---

doc/whats_new.rst
nilearn/plotting/__init__.py
nilearn/plotting/tests/test_matplotlib_backend.py

PR that tackles elements said in #3063 
This PR contains:
- more robust backend switch using `matplotlib.use` instead of testing hard-coded backends
- warning if matplotlib backend is switched
- tests
Closes #3063

Matplotlib backend switch warning

---

doc/whats_new.rst

Fix wrong function reference in `whats_new` introduced in #3078.
Completely missed it during the review...

[FIX] Fix function reference in whats_new

---

doc/whats_new.rst
nilearn/masking.py
nilearn/tests/test_masking.py

Remove function `compute_gray_matter_mask` (`compute_brain_mask` should be used instead) as its deprecation cycle has reached its end.

[MAINT] Remove `compute_gray_matter_mask`

---

doc/whats_new.rst
nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

This PR undoes most of the recently merged #3070 since the proposed fix was not correct (see discussion in #3080).
Once this is merged, I will close #3080 and #2036.
#3083 improves the documentation and makes the implicit relationship between labels and integer values in the atlas image more clear to users.
Finally, the next steps are explained in #3085.
(Ping @jeromedockes)

[FIX] Undo wrong fix `fetch_atlas_destrieux_ 2009`

---

.github/workflows/testing.yml
nilearn/surface/surface.py

I recently moved to Python 3.10 and found that `collections.Mapping` no longer exists in that namespace, but rather `collections.abc.Mapping`. This existed all the way back to 3.6 so should be okay.
Closes #3095

BUG: Import from collections.abc for 3.10

---

doc/whats_new.rst
nilearn/signal.py

Parameter `sessions` is deprecated in favor of `runs` and deprecation cycle ends with release 0.9.

[MAINT] Remove parameter `sessions` in `clean()`

---

README.rst
doc/whats_new.rst
nilearn/__init__.py
requirements-min.txt

Closes #2429
Support for Nibabel 2.x was deprecated since #2869 and scheduled to stop for release 0.9.

[MAINT] Drop support for Nibabel 2.x

---

requirements-build-docs.txt

`sphinxext-opengraph` is required to build the docs but missing from `requirements-build-docs.txt`.
Also adds `memory_profiler`.
Linking related #2953

[INFRA] Add missing documentation building requirements

---

doc/whats_new.rst
examples/01_plotting/plot_visualization.py
examples/plot_single_subject_single_run.py
nilearn/plotting/displays/_slicers.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting/test_img_plotting.py
nilearn/plotting/tests/test_img_plotting/test_plot_anat.py

This PR adds the possibility to control the number formatting on the colorbars of volume plots through a `cbar_tick_format` argument. This extends what has been done in #2643 for surface plots.

[ENH] Add `cbar_tick_format` to plotting functions

---

nilearn/_utils/segmentation.py

Closes #3129 
Add `atol='legacy'` option in `scipy.sparse.linalg.cg` to avoid deprecation warning.

Scipy deprecation warning in RegionExtractor

---

doc/manipulating_images/masker_objects.rst
doc/whats_new.rst
examples/02_decoding/plot_haxby_multiclass.py
examples/02_decoding/plot_haxby_searchlight.py
examples/07_advanced/plot_advanced_decoding_scikit.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/tests/test_nifti_masker.py

`sessions` has been replaced by `runs`, and `sample_mask` is now provided through `transform`.
Both are deprecated and scheduled to be removed with release 0.9.

[MAINT] Remove deprecated `sessions` and `sample_mask` attributes of `NiftiMasker`

---

doc/whats_new.rst
nilearn/glm/tests/test_thresholding.py
nilearn/glm/thresholding.py

fixed code + added test

---

nilearn/plotting/html_document.py

The `python` command is not guaranteed to exist. On some systems it refers to old python 2.
See https://www.python.org/dev/peps/pep-0394/
Outside of a virtualenv, this test fails:
```
[  158s] ___________________________ test_temp_file_removing ____________________________
[  158s] [gw3] linux -- Python 3.9.9 /usr/bin/python3.9
[  158s] 
[  158s]     def test_temp_file_removing():
[  158s]         html = html_document.HTMLDocument('hello')
[  158s]         wb_open = webbrowser.open
[  158s]         webbrowser.open = _open_mock
[  158s]         fd, tmpfile = tempfile.mkstemp()
[  158s]         try:
[  158s]             os.close(fd)
[  158s]             with pytest.warns(None) as record:
[  158s]                 html.open_in_browser(file_name=tmpfile, temp_file_lifetime=None)
[  158s] …
```

replace interpreter call

---

doc/whats_new.rst

Fix wrong whats_new entry introduced by #2282 (most likely due to a merge/rebase)

[DOC] Fix wrong whats_new entry

---

README.rst
doc/changes/latest.rst
requirements-min.txt

This PR proposes to bump our dependencies for the 0.9.0 release:
- Joblib: 0.12  -->  0.15
- Numpy: 1.16  -->  1.18
- Scipy: 1.2  -->  1.5
- Scikit-learn: 0.21  -->  0.22
- Pandas:  0.24  --> 1.0
I also realized that the README says that matplotlib >= 1.5.1 is required although we don't test this. The minimum requirements tests are without matplotlib:
https://github.com/nilearn/nilearn/blob/c549dc0a66327b05ab3a25ddff02abe99db02501/.github/workflows/testing.yml#L26-L31
I think we should add a CI job testing minimum requirements WITH matplotlib. In this case, we could also bump the minimum version for matplotlib (>= 3.0 ??). 
WDYT?

[MAINT] Bump dependencies for release `0.9.0`

---

nilearn/interfaces/fmriprep/tests/test_load_confounds.py
nilearn/interfaces/fmriprep/tests/test_load_confounds_utils.py
nilearn/interfaces/fmriprep/tests/utils.py

Add test to verify this note in comments:
fmriprep has changed the file suffix between v20.1.1 and v20.2.0 with
respect to BEP 012.
cf. https://neurostars.org/t/naming-change-confounds-regressors-to-confounds-timeseries/17637 # noqa
Check file with new naming scheme exists or replace,
for backward compatibility.
This test was lost while migrating the library.
Although it didn't break any existing code, it's still better to have this test.

[TEST] check both old and new derivative suffix

---

azure-pipelines.yml

Update for https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows

MAINT: Update Azure

---

doc/changes/latest.rst
examples/01_plotting/plot_carpet.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting/test_plot_carpet.py

Closes #3155.
- Add a `t_r` parameter to `nilearn.plotting.plot_carpet`, with a default value of None.
- Document the current behavior (TR is inferred from the data image's header if not provided by the user).
- Use the new parameter in the `plot_carpet` example.
- Add a whatsnew entry for the new parameter.

[ENH] Add `t_r` parameter to `plot_carpet`

---

doc/changes/latest.rst
doc/glossary.rst
nilearn/datasets/atlas.py

This PR proposes to add definitions to glossary for 'probabilistic' and 'deterministic' atlases (definitions might need some improvements/rewording...).
It also updates the docstrings of atlas fetchers to make it more clear what kind of atlases are  returned.

[DOC] Add deterministic and probabilistic atlases to glossary

---

nilearn/plotting/matrix_plotting.py

Avoid this by using `fig.canvas.get_renderer`:
```
File "/home/larsoner/python/nilearn/nilearn/plotting/matrix_plotting.py", line 9, in <module>
from matplotlib.tight_layout import get_renderer
File "/home/larsoner/python/matplotlib/lib/matplotlib/tight_layout.py", line 3, in <module>
_api.warn_deprecated(
File "/home/larsoner/python/matplotlib/lib/matplotlib/_api/deprecation.py", line 101, in warn_deprecated
warn_external(warning, category=MatplotlibDeprecationWarning)
File "/home/larsoner/python/matplotlib/lib/matplotlib/_api/__init__.py", line 361, in warn_external
warnings.warn(message, category, stacklevel)
matplotlib._api.deprecation.MatplotlibDeprecationWarning: The module matplotlib.tight_layout is deprecated since 3.6.
```

MAINT: Use non-deprecated method

---

doc/Makefile

This PR updates the steps for the `install` target of the documentation Makefile.
This is necessary since we now deploy the development version of the documentation every time a PR is merged in main.

[INFRA] Update docs `install` target

---

doc/changes/latest.rst
nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

Closes #3088 .
- Juelich and Oxford atlases now have the rightful filename in their `filename` attribute instead of the nifti image

Expose filename in fetch atlas

---

CONTRIBUTING.rst

Closes #1919. Per discussion in #1919, large-scale changes to nilearn's coding style should be avoided, so we should just try to ensure that any affected code in new PRs follows this guideline. I think mentioning it in the contributing documentation should be sufficient.
I didn't think this required a whatsnew entry, but I can add one if necessary.
- Specifically mention absolute imports are recommended within the coding style guidelines in the contributing documentation.
- Fix path to whatsnew in contributing guidelines. I think this was missed in #3049.

[DOC] Request absolute imports in coding style guidelines

---

doc/changes/latest.rst
nilearn/mass_univariate/permuted_least_squares.py
nilearn/mass_univariate/tests/test_permuted_least_squares.py

Closes #3180.
- Return `h0_fmax` (the null distribution of maximum t-statistics used for voxel-level FWE correction) for all regressors, instead of just the first regressor.
- Update tests to check for the right shape.
- Add a versionchanged directive to the `permuted_ols` docstring reflecting this change.
- Add a whatsnew entry for the change.
NOTE: It doesn't look like `non_parametric_inference` retains `h0_fmax` from `permuted_ols`, and none of the examples that use `permuted_ols` seem to retain `h0_fmax` either, so I think the scope of these changes is limited to the function and its tests.

[FIX] Return `h0_fmax` for all regressors from `permuted_ols`

---

nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

A bug has been introduced by myself in #3179 leading to the documentation not building anymore in the CI. This PR fixes it.
Reason for the bug:
- in #3179, I changed the behaviour of atlas fetching for Juelich and Oxford: before the `.filename` element contained the image element instead of the path, the purpose of my PR was to switch this image element to the appropriate element path
- doing so, I made the method return a relative path instead of the absolute path of the element, returning path like `data/atlases/Juelich/Juelich-maxprob-thr0-1mm.nii.gz`
- the problem is that during `fetch_files`, this relative path is added to the data_dir, which is generally `$HOME/nilearn_data/fsl`
- this lead the documentation build to look for the atlas image in the current directory instead of …

Fix documentation build

---

nilearn/reporting/_get_clusters_table.py

Closes #3199.
This PR changes the docstring for `min_distance` argument in the `reporting.get_clusters_table` method to explicitly note that the minimal distance applies intra-clusters and not between clusters.

More explicit docstring regarding min_distance

---

doc/changes/latest.rst
doc/modules/reference.rst

Closes #3198.
~~I'm not sure if this merits a whatsnew entry.~~ Perhaps with the addition of `fetch_mixed_gambles` it does.
- Add subheadings for different dataset function types to the reference page.
- Organize dataset functions into the appropriate sections, then sort alphabetically within each section.
- Add `fetch_mixed_gambles` to reference page. It was missing.
- Add whatsnew entry.

[DOC] Separate dataset functions by type of data returned

---

doc/changes/latest.rst
nilearn/datasets/func.py

Trying to run a full build locally I had a few errors related mainly to the docstring of ``fetch_mixed_gambles`` (added to the API docs in recently merged #3207).
We didn't catch these since the CI is not running full build anymore.
This PR fixes these issues and improves the rendering of the docstring a little bit.

[DOC] Fix docstring of `fetch_mixed_gambles` and broken ref in `latest.rst`

---

doc/changes/latest.rst
nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

Closes #3087 
To try it out, remove `aal` folders from `nilearn_data` and you should get the following output:
```python
In [1]: from nilearn import datasets, image
/home/nicolas/GitRepos/nilearn-fork/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
warn("Fetchers from the nilearn.datasets module will be "
In [2]: for version in [5, 8, 12]:
...:     bunch = datasets.fetch_atlas_aal(version=f"SPM{version}")
...:     assert len(bunch.description) > 0
...:     assert len(bunch.labels) == 116
...:     assert len(bunch.indices) == 116
...:     assert image.load_img(bunch.maps).shape ==  (91, 109, 91)
...: 
Dataset created in …
```

[FIX] Make `fetch_atlas_aal` work with `SPM5` and `SPM8`

---

doc/changes/latest.rst
doc/changes/names.rst
doc/references.bib
nilearn/mass_univariate/permuted_least_squares.py

Closes [#2785](https://github.com/nilearn/nilearn/issues/2785)
- Converted references in `nilearn/mass_univariate/permuted_least_squares.py` to bibtex format
- Added them to `doc/references.bib`

[DOC] Convert references in nilearn/mass_univariate to bibtex format

---

doc/maintenance.rst

While releasing ``0.9.1``, I realized that the steps for updating the change logs were outdated since we moved to multiple files a few months ago. This PR proposes to update the documentation with the new steps required.

[DOC] Update the "How to make a release" section in the maintenance documentation

---

.github/workflows/auto-comment.yml
CONTRIBUTING.rst
doc/maintenance.rst

Closes #1865. I don't think this needs a whatsnew entry.
Changes proposed:
- Add a bullet point about including versionadded and versionchanged directives to the contributing guidelines.

[DOC] Mention versionadded/versionchanged directives in contributing guidelines

---

nilearn/_utils/numpy_conversions.py
nilearn/datasets/atlas.py
nilearn/datasets/func.py

Resolves stalled pull request #1947 
- Add encoding=None to np.genfromtxt to remove warning when fetching data:
`VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
phenotypic = np.genfromtxt(phenotypic, names=True, delimiter=',',`

Added encoding parameter to np.genfromtxt to remove VisibleDeprecationWarning

---

setup.cfg

Closes #3244.
- Remove `mkl`, `cython`, and `pillow` from the documentation requirement group in `setup.cfg`.
- Remove `cython` from the testing requirement group.
- Reference the `plotly` requirement group in the documentation requirement group instead of duplicating the requirements.
Open questions:
- Cython is mentioned in the Makefile, but only in reference to `pyx` files, and I couldn't find any of those.
- Neither `pillow` nor `PIL` appears outside `setup.cfg`.
- Per @NicolasGensollen, it's used to profile the documentation build.

[MAINT] Remove extraneous `doc` requirements

---

nilearn/mass_univariate/tests/test_permuted_least_squares.py

Closes #3246.
- Remove the following duplicate tests, which do not test multiple regressors:
- test_permuted_ols_intercept_withcovar_multivariate
- test_permuted_ols_intercept_nocovar_multivariate
- test_permuted_ols_withcovar_multivariate

[TST] Remove duplicate `permuted_ols` tests

---

doc/introduction.rst
examples/02_decoding/plot_simulated_data.py
examples/06_manipulating_images/plot_roi_extraction.py
nilearn/_utils/data_gen.py
nilearn/_utils/ndimage.py
nilearn/datasets/struct.py
nilearn/decoding/space_net.py
nilearn/decoding/tests/simulate_graph_net_data.py
nilearn/image/image.py
nilearn/image/resampling.py
nilearn/masking.py
nilearn/mass_univariate/_utils.py
nilearn/mass_univariate/permuted_least_squares.py
nilearn/mass_univariate/tests/test__utils.py
nilearn/plotting/edge_detect.py
nilearn/plotting/find_cuts.py
nilearn/plotting/img_plotting.py
nilearn/regions/region_extractor.py
nilearn/regions/tests/test_region_extractor.py
nilearn/reporting/_get_clusters_table.py

This PR proposes to fix some deprecations we have when importing the `ndimage` module from `spicy` in the following way : `from scipy import ndimage`.
For example:
```
nilearn/mass_univariate/tests/test_permuted_least_squares.py: 10 warnings
[10101](https://github.com/nilearn/nilearn/runs/6442110474?check_suite_focus=true#step:8:10101)
/home/runner/work/nilearn/nilearn/nilearn/mass_univariate/_utils.py:120: DeprecationWarning: Please use `label` from the `scipy.ndimage` namespace, the `scipy.ndimage.measurements` namespace is deprecated.
[10102](https://github.com/nilearn/nilearn/runs/6442110474?check_suite_focus=true#step:8:10102)
labeled_arr3d, _ = ndimage.measurements.label(arr3d > 0, bin_struct)
```
Indeed, submodules of `scipy.ndimage` were recently made private even if they do not …

[MAINT] Fix `scipy.ndimage` deprecations

---

nilearn/surface/tests/test_surface.py

When running 
```
$ pytest test_surface.py -k test_load_surf_data_file_glob
```
We have a few deprecations like this one: 
```
/Users/nicolas.gensollen/GitRepos/nilearn-fork/nilearn/surface/tests/test_surface.py:409: 
DeprecationWarning: giftiio.write function deprecated. Use nibabel.save() instead.
* deprecated from version: 2.1
* Will raise <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 4.0
gifti.write(gii, fnames[f])
```
This has been deprecated for a while (see https://github.com/nipy/nibabel/pull/360 back in 2015) and should be removed in NiBabel 4.0.
This PR proposes to address these deprecations.

[MAINT] Fix `giftiio` deprecations

---

nilearn/surface/data/README.txt

This a one-liner change in the README file that describes how the test data for the surface module is generated. The namespace organization of this module might have changed since last time this was updated, causing this regression.

DOC: Fixes import in surface/data README file

---

nilearn/mass_univariate/permuted_least_squares.py
nilearn/mass_univariate/tests/test_permuted_least_squares.py

quick fix for #3227 recently breaking the build: ~store cluster sizes in floats not ints. another option is to store in int32 rather than int64, as for realistic resolutions even if a cluster fills the whole image it will still fit in int32. @tsalo  please advise which you prefer~
create the images with `nilearn.image.new_img_like` rather than `nib.Nifti1Image`; `new_img_like` takes care of converting int64 to int32 if it does not cause an overflow

avoid creation of int64 nifti in cluster inference + update tests

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

- Add an optional `random_state` kwarg to `nilearn.glm.first_level.first_level.run_glm()`. Because we like reproducibility!

Add optional random_state kwarg to run_glm()

---

README.rst

Links to the installation and development docs in `README.rst` are outdated and now broken after cleaning of Github pages in nilearn/nilearn.github.io#3. 
Added path to stable pages.

[DOC] Update links in `README.rst`

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/reporting/_get_clusters_table.py
nilearn/reporting/tests/test_reporting.py

Closes #3278.
- For binary clusters whose center of mass falls outside of the cluster, report the nearest within-cluster voxel instead.
- Don't filter locally constant "maxima" in the binary cluster case.
- Vectorize some operations.

[ENH] Shift centers of mass outside of clusters to closest in-cluster voxel

---

doc/changes/latest.rst
nilearn/decomposition/__init__.py
nilearn/decomposition/_base.py
nilearn/decomposition/_multi_pca.py
nilearn/decomposition/canica.py
nilearn/decomposition/dict_learning.py
nilearn/decomposition/tests/test_base.py
nilearn/decomposition/tests/test_multi_pca.py
nilearn/regions/parcellations.py

Closes #3138 
This PR proposes to rename some objects and submodules of `nilearn.decomposition` with a leading "_" to make it clear that these objects are private.

[ENH] Rename objects of `nilearn.decomposition` with leading "_"

---

nilearn/image/resampling.py
nilearn/plotting/find_cuts.py

Avoids warnings of the form:
```
File "/Users/larsoner/python/mne-python/tutorials/inverse/70_eeg_mri_coords.py", line 73, in <module>
plot_glass_brain(img_mni, cmap='hot_black_bone', threshold=0., black_bg=True,
File "/Users/larsoner/python/nilearn/nilearn/plotting/img_plotting.py", line 1051, in plot_glass_brain
display = _plot_img_with_bg(
File "/Users/larsoner/python/nilearn/nilearn/plotting/img_plotting.py", line 201, in _plot_img_with_bg
display.add_overlay(new_img_like(img, data, affine),
File "/Users/larsoner/python/nilearn/nilearn/plotting/displays/_slicers.py", line 274, in add_overlay
ims = self._map_show(img, type='imshow', threshold=threshold, **kwargs)
File "/Users/larsoner/python/nilearn/nilearn/plotting/displays/_slicers.py", line 383, in _map_show …
```

MAINT: Avoid deprecation

---

doc/changes/latest.rst
nilearn/signal.py
nilearn/tests/test_signal.py

Closes #3288.
Currently `signal._check_wn` sets critical frequencies to an equal value below 1 if they are above the threshold of 1. A scipy update now enforces that its two-element sequence `Wn` for upper and lower critical frequencies should meet the condition `Wn[0] < Wn[1]`. This causes `test_decoder_apply_mask` to fail. 
- ~~Add negligible value to low-pass filter to satisfy condition~~
- Give warning to user to input appropriate values if critical frequencies are coerced into the same value

[FIX] Change setting of critical frequencies to meet `Wn[0] < Wn[1]`

---

nilearn/plotting/html_document.py
nilearn/plotting/tests/test_html_document.py

Closes #3301.
- Add ~~`_pid`~~ `_temp_file_removing_proc` attribute to class `HTMLDocument`
- Store suprocess in  `_remove_after_n_seconds` and return it
- ~~Use returned object to get pid of subprocess and store it in `_pid`~~
- Use ~~`os.waitpid`~~ `subprocess.Popen.wait` to pause process until subprocess is finished
- This replaces `time.sleep(1.5)`

[ENH] Improve test checking for removal of temporary file

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting/test_plot_connectome.py

Minor fix: `alpha` in `plotting.plot_connectome` is currently not passed on to `plot_glass_brain()`.

[FIX] Pass alpha on to glass brain when plotting connectome

---

doc/changes/latest.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py

Replaces and closes #1500 
Related to nipy/nibabel#913
- Defaulting boolean input to `np.uint8` instead of `np.int8` for function `image.new_img_like`

[FIX] Default to `np.uint8` for encoding boolean data based on image type

---

doc/changes/latest.rst
nilearn/_utils/cache_mixin.py
nilearn/_utils/docs.py
nilearn/_utils/glm.py
nilearn/_utils/helpers.py
nilearn/_utils/niimg.py
nilearn/_utils/niimg_conversions.py
nilearn/_utils/numpy_conversions.py
nilearn/_utils/path_finding.py
nilearn/_utils/testing.py
nilearn/glm/first_level/first_level.py
nilearn/glm/second_level/second_level.py
nilearn/image/image.py
nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py
nilearn/maskers/base_masker.py
nilearn/maskers/multi_nifti_masker.py
nilearn/regions/parcellations.py
nilearn/signal.py
nilearn/surface/surface.py
nilearn/tests/test_niimg.py
nilearn/tests/test_niimg_conversions.py
nilearn/tests/test_numpy_conversions.py

Closes #2642.
Replaces and closes #2803.
Also replaces #2644.
Allow `os.PathLike` and `pathlib.Path` objects to be passed to functions expecting a string.
Use function based on `nibabel.filename_parser._stringify_path` to convert them to string.

[ENH] Add support for path-like objects where string filesystem paths are expected

---

CONTRIBUTING.rst
doc/changes/latest.rst

Closes #3308.
Also close #2528 in my opinion since there is consensus not to automate formatting and linting.
This PR proposes additional information to the contributing guidelines about running flake8 on the diff locally before pushing changes. This is meant to reduce PEP8 check failures.

[MAINT] [DOC] Add suggestion for running flake8 on diff locally before pushing changes

---

doc/changes/latest.rst
nilearn/maskers/base_masker.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py
nilearn/maskers/tests/test_multi_nifti_masker.py
nilearn/maskers/tests/test_nifti_labels_masker.py
nilearn/maskers/tests/test_nifti_maps_masker.py
nilearn/maskers/tests/test_nifti_masker.py
nilearn/maskers/tests/test_nifti_spheres_masker.py
nilearn/masking.py

Closes #3296.
- Add an `n_elements_` attribute to each of the masker classes.
- Document any post-fit attributes in the masker class docstrings.
- Expand masker tests to check the post-fit attributes.
- Some minor improvements to coding style in the masker code files.
- Replace relative imports in multi_nifti_masker.py and nifti_masker.py with absolute ones.
- Check that mask is binary/valid in fit, rather than just in transform, for NiftiMasker and MultiNiftiMasker.
- Still allow empty mask at this stage, though it will fail at transform.
- Apply consistent, black-like formatting to the masker files (except using single quotes, of course).

[ENH] Add n_elements_ attribute to masker classes

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/mass_univariate/_utils.py

This PR is designed as a first pass at solving performance issues as noted in [#3266](https://github.com/nilearn/nilearn/issues/3266).
This PR is rather minimal in scope in that it only changes the internal content of the '_calculate_tfce' method and produces identical results to the previous version of the code. The change is of course that the code is now a bit faster. Running the updated code on the same benchmark as mentioned in https://github.com/nilearn/nilearn/pull/3196 the 'plot_localizer_mass_univariate_methods' now runs in ~7 minutes on a single core, whereas the old version of the code ran in ~30 minutes on my machine with the same settings. 
Notably with the example above and to some extent the current code, the runtime is very dependent on the shape of the original images. …

[REF] Performance optimizations for TFCE

---

nilearn/glm/first_level/first_level.py
nilearn/glm/second_level/second_level.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py
nilearn/mass_univariate/permuted_least_squares.py
nilearn/plotting/img_plotting.py

This removes the `dev` tag from the version number in `versionadded`/`versionchanged` directives in preparation for the release

[MAINT] Update sphinx version directives for release

---

nilearn/regions/signal_extraction.py

`measurements` has been made private since Scipy `1.8.0`, see : https://github.com/scipy/scipy/pull/14447
This PR fixes the deprecation warnings.

[MAINT] Fix `scipy.ndimage.measurements` deprecations

---

doc/maintenance.rst

Since it was agreed at the last core developer meeting to not reinstate the news section in the new docs, I'm removing the instructions to update the section for releases.

[MAINT] Remove instructions on the maintenence page for updating the news section during releases

---

doc/changes/latest.rst
nilearn/glm/contrasts.py
nilearn/glm/first_level/first_level.py
nilearn/glm/first_level/hemodynamic_models.py
nilearn/glm/tests/test_contrasts.py
nilearn/glm/tests/test_dmtx.py
nilearn/glm/tests/test_first_level.py
nilearn/glm/tests/test_hemodynamic_models.py

Closes #3323.
- Allow design matrix column name to be invalid identifier

[FIX] Allow invalid identifiers for design matrix column names

---

nilearn/interfaces/fmriprep/load_confounds.py
nilearn/interfaces/fmriprep/load_confounds_strategy.py

Closes #3356.
- Remove the mention of intercept as this is no longer relevant as `signals.clean` standardize confounds by default and will raise warning when illogical combination of parameters are present.

[DOC] remove the mention of intercept from `load_confounds`

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/plotting/displays/_axes.py
nilearn/plotting/tests/test_displays.py

For `plotting.plot_connectome(...)`, I was interested in plotting a matrix with only negative edges. However, when you set the `edge_vmin` parameter to be less than zero, it raises an error. My PR is a fix. I provide details in #3389.
Closes #3389.
I changed one line:
```Python
abs_norm = Normalize(vmin=0, vmax=vmax)
```
to
```Python
abs_norm = Normalize(vmin=0, vmax=max(abs(vmax), abs(vmin)))
```
From what I can tell, `abs_norm` is meant to essentially represent the magnitude of x relative to the highest magnitude specified by the user.  `abs_norm`  takes some x (a connectivity edge weight) and returns `(x - 0)/vmax` . 
My updated code does while accounting for cases where ` vmax < 0`  and ` abs(vmin) > abs(vmax)`, where you would likely be more …

[FIX] Error when using plot_connectome(...) and edge_vmax < 0

---

nilearn/datasets/func.py

Downloading fiac dataset from http://nipy.sourceforge.net/data-packages/nipy-data-0.2.tar.gz throws a 404 error.
See line 140 in https://github.com/nilearn/nilearn/actions/runs/3343296692/jobs/5536366621

[FIX] Change URL for fetching fiac fMRI dataset

---

doc/changes/latest.rst
nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py

Also remove unused local variable `n_ticks`, reported by LGTM.com.
Closes #3104.

[FIX] Off-by-one error while setting up ticks

---

nilearn/_utils/cache_mixin.py
nilearn/connectome/group_sparse_cov.py
nilearn/connectome/tests/test_group_sparse_cov.py
nilearn/datasets/neurovault.py
nilearn/decoding/searchlight.py
nilearn/decoding/space_net.py
nilearn/externals/tempita/__init__.py
nilearn/externals/tempita/_looper.py
nilearn/glm/contrasts.py
nilearn/glm/model.py
nilearn/glm/regression.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py
nilearn/maskers/tests/test_masker_validation.py
nilearn/plotting/displays/_axes.py
nilearn/plotting/displays/_slicers.py
nilearn/plotting/glass_brain_files/svg_to_json_converter.py
nilearn/plotting/html_document.py
nilearn/surface/tests/test_surface.py
nilearn/tests/test_logger.py

Classes inherit from `object` implicitly.

[MAINT] No need to inherit `object` in Python 3

---

doc/conf.py
doc/sphinxext/gh_substitutions.py
nilearn/_utils/docs.py
nilearn/reporting/glm_reporter.py
nilearn/reporting/tests/test_glm_reporter.py
nilearn/version.py

In Python 3, not need to  declare it explictly.

[MAINT] Source encoding is UTF-8 by default

---

doc/changes/latest.rst
nilearn/_utils/glm.py
nilearn/signal.py
nilearn/tests/test_signal.py

Move volume censoring after signal filtering so the cosine drift term can be correctly generated.
Closes #3364.
I also took the chance to add a small feature - detect if cosine drift terms are already supplied in confounds, fix a void test etc.
- enh: check if confounds supplied by user contains cosine drift terms
- fix/test: change the high-pass filter in the test so the test data actually contains cosine drift term, rather than just a constant (oops)
- fix: remove constant from cosine drift term as this function works on mean centred data. Having the constant doesn't impact the performance (see `test_clean_confounds`)
- add: interpolation function and related documentation
- fix and refactor: processing runs independently, make the code work better for interpolation, and added relevant …

[FIX/ENH] signal interpolation for scrubbed volumes when applying butterworth filter in signal.clean

---

.github/workflows/testing.yml

GitHub Actions now fails with tests that use some python versions such as 3.6 if runner is set to `Ubuntu-latest` (which is now ubuntu-22.04). It should work with ubuntu-20.04.
See failure: https://github.com/nilearn/nilearn/actions/runs/3498548522/jobs/5859058796
More details at similar issue: https://github.com/actions/setup-python/issues/543

[INFRA][FIX] Actions setup-python for v3.6 does not work with Ubuntu-latest runner

---

doc/changes/latest.rst
nilearn/maskers/tests/test_multi_nifti_masker.py
nilearn/masking.py
nilearn/tests/test_masking.py

Remove `masking.compute_multi_gray_matter_mask` which has been deprecated and replaced by `masking.compute_multi_brain_mask` in version 0.8.1

[MAINT] Remove deprecated function `compute_multi_gray_matter_mask`

---

doc/changes/latest.rst
nilearn/plotting/matrix_plotting.py

Fixes #3378
Revise how the colorbar is added to better handle subplots.
Before: 
After:
```python
from nilearn.maskers import NiftiMapsMasker
from nilearn.connectome import ConnectivityMeasure
from nilearn.plotting import plot_matrix
import matplotlib.pyplot as plt
atlas = datasets.fetch_atlas_msdl()
atlas_filename = atlas['maps']
labels = atlas['labels']
data = datasets.fetch_development_fmri(n_subjects=1)
fmri_filenames = data.func[0]
masker = NiftiMapsMasker(maps_img=atlas_filename, standardize=True, detrend=True)
correlation_measure = ConnectivityMeasure(kind='correlation')
time_series = masker.fit_transform(fmri_filenames)
correlation_matrix = correlation_measure.fit_transform([time_series])[0]
np.fill_diagonal(correlation_matrix, 0) …
```

Fix colorbar behaviour in subplots

---

.github/workflows/testing.yml
azure-pipelines.yml
build_tools/github/build_docs_dependencies.sh
doc/changes/latest.rst
doc/conf.py
nilearn/__init__.py
nilearn/datasets/atlas.py
nilearn/tests/test_init.py
setup.cfg
setup.py

Even though we initially agreed to extend support for python 3.6 due to many machines still using it, it was then discussed in #3423 that it is more reasonable to drop its support since dependencies such as scikit-learn do not support it anymore and it has been EOL since Dec2021.

[MAINT] Drop support for python 3.6 and deprecate 3.7

---

doc/changes/latest.rst
nilearn/decoding/decoder.py
nilearn/decoding/tests/test_space_net.py
nilearn/decomposition/dict_learning.py

Pre-release of scikit-learn enforces correct behavior of:
- Passing `int` to the `max_iter` parameter used by some estimators
- Deletion of deprecated parameter
- `fit_intercept` only accepts booleans
See failing test: https://github.com/nilearn/nilearn/actions/runs/3574331280/jobs/6009470192

[FIX] Pass correct type to scikit-learn estimators parameter

---

doc/changes/latest.rst
nilearn/_utils/cache_mixin.py
nilearn/tests/test_cache_mixin.py

Closes #3256.
- `_safe_cache` now handles if versions are different types by continuing to flush the cache as if the versions don't match

[FIX] Remove `_safe_cache` function that is outdated and error-prone

---

doc/changes/latest.rst
nilearn/datasets/struct.py
nilearn/datasets/tests/test_struct.py
nilearn/image/image.py
nilearn/image/resampling.py
nilearn/tests/test_signal.py

This is to remove some future warnings that won't be relevant in v `0.10`.
Changes:
- Loading MNI152 templates now defaults to 1mm resolution
- Updated tests and docs
- Removed old scipy bug hack that doesn't seem relevant anymore. We don't support the scipy version it checks for

[MAINT] Remove `FutureWarning`s due for release `0.10` and update related components

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/mass_univariate/permuted_least_squares.py
nilearn/mass_univariate/tests/test_permuted_least_squares.py

This addresses the bug report in #3435.

[FIX] Combine positive and negative cluster labels for two sided permutation tests 

---

azure-pipelines.yml

Noticed because of brownout leading to cancelled tests in #3453 
e.g. https://dev.azure.com/Parietal/Nilearn/_build/results?buildId=5245&view=results
For details see: https://github.com/actions/runner-images/issues/6002

[MAINT] Update deprecated Ubuntu 18.04 Actions runner

---

nilearn/image/tests/test_image.py
nilearn/image/tests/test_resampling.py
nilearn/tests/test_niimg.py

Resolves failures on tests using dtype int64 data arrays. See https://github.com/nilearn/nilearn/actions/runs/3881843135/
From nibabel changelog: Passing an int64 array to [Nifti1Image](https://nipy.org/nibabel/reference/nibabel.nifti1.html#nibabel.nifti1.Nifti1Image) without a header or dtype argument will raise a `ValueError`

[FIX] Nibabel Nifti1Image class now requires `header` or `dtype` arguments for int64 data

---

.circleci/config.yml

This change is related to the recent rotation of CircleCI secrets in response to https://circleci.com/blog/january-4-2023-security-alert/

[MAINT] Update fingerprint in CircleCI deploy job 

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py

Closes #3461
This adds a guard to ensure the input image has the `get_sform()` method prior to calling it, and a quick test.

FIX: `resample_img()` compatibility with non-NIfTI images

---

doc/changes/latest.rst
doc/manipulating_images/masker_objects.rst
nilearn/maskers/base_masker.py

Closes #3416 .
- Adds a note to inverse transform section, stating that it only performs spatial unmasking

[DOC] Note that Masker.inverse_transform only performs spatial unmasking in docstring

---

doc/changes/latest.rst
examples/03_connectivity/plot_sphere_based_connectome.py
nilearn/_utils/docs.py
nilearn/image/image.py
nilearn/maskers/base_masker.py
nilearn/maskers/multi_nifti_labels_masker.py
nilearn/maskers/multi_nifti_maps_masker.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py
nilearn/maskers/tests/test_base_masker.py
nilearn/maskers/tests/test_nifti_masker.py
nilearn/signal.py
nilearn/tests/test_signal.py

Closes #3475.
I haven't thought about testing or examples yet, but I can start on that if folks feel like this is a good direction.
I also don't know if I should make these kwargs available in the maskers as well. This kwargs approach could be useful for #3437.
- Add `padtype` and `padlen` as parameters in `nilearn.signal.butterworth`.
- Add `**kwargs` to `nilearn.signal.clean`. Kwargs prefixed with `butterworth__` will be fed into `nilearn.signal.butterworth`. This will allow users to set `padtype`, `padlen`, `order`, and `copy`.

[ENH] Make filter options available as kwargs in `signal.clean`

---

examples/06_manipulating_images/plot_resample_to_template.py
examples/07_advanced/plot_ica_neurovault.py
nilearn/_utils/data_gen.py
nilearn/datasets/tests/test_struct.py
nilearn/plotting/html_stat_map.py
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_html_stat_map.py
nilearn/plotting/tests/test_html_surface.py
nilearn/plotting/tests/test_img_plotting/test_img_plotting.py
nilearn/plotting/tests/test_img_plotting/test_plot_stat_map.py

Closes #3482.
- Lower resolution of loaded templates for tests from 1mm to 2mm
- Change some examples to load lower resolution templates
- Simplify mni space data generator by passing resolution argument directly into `load_mni152_brain_mask`

[MAINT] Use lower resolution MNI152 templates for tests and examples

---

nilearn/glm/tests/test_utils.py

Closes #3506
Replaces deprecated method `get_data()` with `get_fdata()` for one failing test.

[FIX] Fix failing test due to use of deprecated Nibabel method

---

nilearn/__init__.py

The MNE-Python CIs are hitting a new `DeprecationWarning` today when we import nilearn. It appears to arise from the (unused) importing of `pkg_resources` in your `__init__.py`. Locally when I run `pytest nilearn` after this change, all tests pass, and `pip install -e .` into a clean environment also works, so I'm pretty sure that import was just cruft.
Here's the warning we've been hitting, FYI:
<details>
```
mne/viz/tests/test_3d_mpl.py:34: in <module>
@requires_version('nilearn', '0.4')
mne/utils/_testing.py:94: in requires_version
return pytest.mark.skipif(not check_version(library, min_version),
mne/utils/check.py:106: in check_version
library = import_module(library)
/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/importlib/__init__.py:126: in import_module
return …
```

remove unused pkg_resources import

---

doc/changes/latest.rst

Resolve doc build fail on main: https://github.com/nilearn/nilearn/actions/runs/4183070013/jobs/7246957945

[DOC] Fix Sphinx reference to function due to spelling error 

---

nilearn/interfaces/bids/glm.py

Pandas pre-release 2.0.0rc0 deprecates parameter `line_terminator` for `lineterminator` in method `to_csv` causing some tests to fail on pre-release workflow (e.g. https://github.com/nilearn/nilearn/actions/runs/4233168828/jobs/7353781075#step:8:16674)
Edit: Closes #3530
Edit: Or remove it alltogether if not needed (new parameter name doesn't meet minimum supported requirements )

[MAINT] Update deprecated parameter name for Pandas `DataFrame.to_csv` method

---

doc/Makefile

Closes #3493.
This will prompt the full sphinx build to keep going and finish when encountering a first warning so that all subsequent warnings are caught. Build will still exit with exit status 1 as expected

[MAINT] Add flag to full doc build to finish build when first warning is encountered 

---

.github/workflows/update_precommit_hooks.yml
.pre-commit-config.yaml

Closes #3490
- add a github workflow to automatically to check for update of all the pre-commit hooks every monday
- if some hooks require to be updated then the pre-commit config is updated and a PR is opened against the main branch
- only the upstream repo should be affected to avoid extra noise on the 500 forks of nilearn
- this workflow is not trigger by pushes or PR but can be triggered manually by maintainers from the action tab.
I forced a this to trigger a PR on my fork to give an example:
https://github.com/Remi-Gau/nilearn/pull/7

[INFRA] add a GH workflow to regularly update pre-commit hooks

---

doc/building_blocks/manual_pipeline.rst

Fixing build fail on main: https://github.com/nilearn/nilearn/actions/runs/4316077088/jobs/7531359830
In the reformatting process, a pattern for the Sphinx `:start-after:` directive was changed.

[DOC] Fix Sphinx build error caused by changed pattern

---

doc/changes/latest.rst
nilearn/interfaces/fmriprep/load_confounds_utils.py
nilearn/interfaces/fmriprep/tests/test_load_confounds.py
nilearn/interfaces/fmriprep/tests/utils.py

Closes #3479.
- Use `nilearn.interfaces.bids.parse_bids_filename` to parse and construct file names that fits fMRIPrep doc better
- Adapt BIDS compatible test file name

[FIX] Allow preprocessed data in native space in `load_confounds`

---

nilearn/decomposition/tests/test_canica.py

Closes #3546 
- simplify test by making sure that only one warning with the expected message is thrown
tidy up gitignore

[MAINT] make test_percentile_range for canica less brittle

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/reporting/_get_clusters_table.py
nilearn/reporting/tests/test_reporting.py

Closes #3561.
- Relabel the clusters in `label_maps` to match their corresponding cluster IDs in the clusters table.

[Fix] relabel `label_maps` to match the cluster IDs in the clusters table

---

doc/conf.py

It seems that the doc build is broken due to a recent release of sphinx-gallery.
This first failed on a scheduled build after a successful build on a merge: https://github.com/nilearn/nilearn/actions/runs/4371630220

[DOC] Fix documentation build failure on main

---

doc/themes/custom.css

This PR implements minor changes of the docs' CSS:

Slight css enhacements on the documentation

---

doc/changes/latest.rst
nilearn/signal.py
nilearn/tests/test_signal.py

Closes #3406 .
- Add "zscore_sample" strategy as an option for `standardize` parameter (Suggestions welcome for a better strategy name)
- Add a `FutureWarning` about default behavior changing to this new strategy in release 0.13.
- If current default should be removed entirely then add this to the warning

[FIX] Add corrected standardize strategy to `signal.clean`

---

nilearn/surface/tests/test_surface.py

See failures on main, e.g. https://github.com/nilearn/nilearn/actions/runs/4605300937/jobs/8137164142
Nibabel release includes a fix for enforcing valid datatypes for GIFTI
See https://github.com/nipy/nibabel/pull/1199

[MAINT] Fix failing tests on main due to creating unsupported GiftiDataArrays

---

.github/ISSUE_TEMPLATE/bug.yml

Closes none
Otherwise the bug label is not automatically added to new issues

[MAINT] update label in bug report form

---

nilearn/glm/tests/test_second_level.py

Closes #3642
Act as regression test for #3636 
- add a test that pass but would fail if #3637 is reverted
- this checks that a second level model fit can accept a list of 3D image filenames as input

[MAINT] add test for second level input as list of 3D image filenames

---

nilearn/image/tests/test_resampling.py

Closes #3658
- make sure that tests do not change globals

[FIX] deal with test pollution in image modules

---

azure-pipelines.yml
environment.yml
pyproject.toml

Closes #3674
Closes #3676
- removes the codecov dependency as the github action is used
- use the codecov uploader in azure
- test with python 3.10 and 3.11 in azure on windows

[MAINT] remove codecov dependency and test with python 3.10 and 3.11 on windows

---

.gitignore

Related to #3660 
The extension .tar.gz in .gitigore should not be ignored. It leads to test data being left out when building the distribution because hatchling uses .gitignore by default to exclude files during build.

[MAINT] Remove data extension from .gitignore

---

doc/changes/latest.rst
nilearn/decoding/decoder.py
nilearn/decoding/tests/test_decoder.py

Closes #3715.
- Add test (`nilearn.decoding.decoder.tests.test_decoder.py`)
- In [nilearn.decoding.decoder._parallel_fit](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/decoder.py#L163), before looping over the hyperparameters, collect all the unique keys in `param_grid`
- Inside the loop, check if `best_param` is missing any keys, and add them if necessary

[FIX] Missing values in `Decoder.cv_params_` when `param_grid` is a list of dicts with different keys

---

nilearn/interfaces/fmriprep/load_confounds_strategy.py

I spotted a small type in the documentation of the "load_confounds_strategy" function. 
When running the function, it takes the correct spelling "scrubbing" as input, so it's only the docs that need updating, the function works great.

Correcting typo in the "load_confounds_strategy" function ("scrubbing")

---

doc/changes/latest.rst
nilearn/_utils/docs.py
nilearn/decoding/decoder.py
nilearn/decoding/tests/test_decoder.py

Closes #2200.
- Replace [`LogisticRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) with [`LogisticRegressionCV`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegressionCV.html) in `nilearn.decoding.decoder`
- Note that the `param_grid` should now contain `Cs` instead of `C`, meaning that any code that explicitly provides a `param_grid = {'C': [...]}` would now break. Does this mean this needs a deprecation cycle? If so how is this usually done?
- Another option could be to change `C` to `Cs` when processing the `param_grid` (with maybe a warning)
- I used `LogisticRegressionCV` for both `"logistic_l1"` and `"logistic_l2"`. `sklearn` also has a …

[ENH] Use LogisticRegressionCV instead of LogisticRegression to improve Decoder performance

---

nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py
nilearn/maskers/nifti_maps_masker.py

Closes #3745.
Fix test_resampling.py::test_resampling_nan
Fix test_html_report.py::test_nifti_maps_masker_report_list_and_arrays_maps_number

[FIX] Fix tests failing due to deprecations in pre-release dependencies

---

azure-pipelines.yml

Related to #3718 
I'm implementing a solution given to me by Microsoft support which is to set the parameter timeoutInMinutes to 0. This allows for the maximum limit which for public projects is 6 hours. It doesn't really answer the question of why the tests are taking so long to run but for now it's enough to make sure our tests run fully.

[INFRA] Add timeout setting in Azure Pipelines CI 

---

nilearn/decoding/tests/test_decoder.py

See prerelease dependencies CI error: https://github.com/nilearn/nilearn/actions/runs/5290261152/jobs/9574189485?pr=3762

[FIX] Change error string to match scikit-learn `InvalidParameterError` message

---

nilearn/plotting/matrix_plotting.py
nilearn/plotting/tests/test_matrix_plotting.py

Closes #3750 
- relax regex for warning on sanitize reorder error to reduce chances of failures

[MAINT] relax regex for warning on sanitize reorder error

---

examples/00_tutorials/plot_decoding_tutorial.py
examples/01_plotting/plot_surf_stat_map.py
examples/02_decoding/plot_haxby_glm_decoding.py
examples/02_decoding/plot_simulated_data.py
examples/03_connectivity/plot_group_level_connectivity.py
examples/03_connectivity/plot_seed_to_voxel_correlation.py
examples/07_advanced/plot_localizer_simple_analysis.py
nilearn/_utils/data_gen.py
nilearn/_utils/extmath.py
nilearn/_utils/helpers.py
nilearn/_utils/niimg.py
nilearn/_utils/param_validation.py
nilearn/_utils/testing.py
nilearn/_utils/tests/test_niimg_conversions.py
nilearn/datasets/func.py
nilearn/interfaces/bids/_utils.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/reporting/_visual_testing/_glm_reporter_visual_inspection_suite_.py
nilearn/tests/test_signal.py

Relates to #2528 
- format remaining f strings in

[REF] fix f strings

---

doc/changes/latest.rst
doc/changes/names.rst
nilearn/datasets/description/destrieux_surface.rst

Closes #3773 
**Describe your proposed suggestion in detail.**
The function fetch_atlas_surf_destrieux returns a dictionary with the keys 'labels', 'map_left', 'map_right', and 'description'. However, in the description, 'map_left' and 'map_right' are called 'annot_left' and 'annot_right'. These should be changed to be consistent with the API. The change should be made in [nilearn/datasets/description/destrieux_surface.rst](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/description/destrieux_surface.rst).
List any pages that would be impacted.
No response

[ENH][DOC] Fix inconsistent description of return keys for fetch_atlas_surf_destrieux

---

Makefile
pyproject.toml

Closes #3756
- add lint recipe to make file
- move linting dependencies to the [dev] install group

[MAINT] add lint recipe to make file

---

examples/00_tutorials/plot_python_101.py
examples/01_plotting/plot_haxby_masks.py
examples/01_plotting/plot_prob_atlas.py
examples/02_decoding/plot_haxby_stimuli.py
examples/03_connectivity/plot_simulated_connectome.py
examples/04_glm_first_level/plot_design_matrix.py
examples/06_manipulating_images/plot_smooth_mean_image.py

Part of #3728.
Fix stuff like this:
To become this:

[DOC] Fix position of plots in relation to code blocks

---

.pre-commit-config.yaml
nilearn/maskers/_masker_validation.py
nilearn/maskers/base_masker.py
nilearn/maskers/multi_nifti_labels_masker.py
nilearn/maskers/multi_nifti_maps_masker.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/tests/test_base_masker.py
nilearn/maskers/tests/test_input_data.py
nilearn/maskers/tests/test_masker_validation.py
nilearn/maskers/tests/test_multi_nifti_labels_masker.py
nilearn/maskers/tests/test_multi_nifti_maps_masker.py
nilearn/maskers/tests/test_multi_nifti_masker.py
pyproject.toml

- update configs to include nilearn/maskers
- apply black

[FMT] apply black to maskers - part 1

---

maint_tools/citation_cff_maint.py

Supersedes #3806 
- update script that generates names.rst to prevent "tug of war" with pre-commit

[FIX] prevent extra line with spaces at the end of names.rst

---

doc/conf.py

See #3800. See also https://github.com/scikit-learn/scikit-learn/issues/26761
This warning fails the full doc build
- Add nitpicky option to conf.py
- Add reference targets to ignore
-

[DOC] Workaround for sphinx warning reference target not found for 2 scikit-learn (v1.3) classes

---

examples/02_decoding/plot_miyawaki_encoding.py
examples/02_decoding/plot_miyawaki_reconstruction.py
examples/03_connectivity/plot_group_level_connectivity.py
examples/07_advanced/plot_advanced_decoding_scikit.py
examples/07_advanced/plot_age_group_prediction_cross_val.py
nilearn/decoding/decoder.py
nilearn/decoding/searchlight.py
nilearn/decoding/tests/test_decoder.py
nilearn/decomposition/dict_learning.py
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py
nilearn/regions/parcellations.py

Relates to #3800 
silence some warnings in doc build:
- setting defaults for dual explicitly in LinearSVC
- settings default in  when fitting sklearn.linear_model.OrthogonalMatchingPursuit

[MAINT] deal with new warnings related to sklearn 1.3

---

doc/changes/latest.rst
nilearn/interfaces/fmriprep/load_confounds_utils.py
nilearn/interfaces/fmriprep/tests/test_load_confounds.py
nilearn/interfaces/fmriprep/tests/test_load_confounds_utils.py
nilearn/interfaces/fmriprep/tests/utils.py

Closes #3792.
- Build candidate confounds filenames from entities in the image files. The only value that is hardcoded is "desc-confounds".
- Update tests to cover more cases.
- The tests that would have failed before are `test_get_file_name[True-_desc-confounds_regressors-part]` and `test_get_file_name[False-_desc-confounds_timeseries-part]`.

[FIX] Make load_confounds' confounds file selection more generic

---

doc/changes/latest.rst
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

Closes #3735 
- make sure warnings is not raised when slice_time_ref is provided
- improve warnings readibility

[FIX] improve warnings in building glm from BIDS 

---

doc/changes/latest.rst
nilearn/_utils/data_gen.py
nilearn/_utils/tests/test_data_gen.py
nilearn/interfaces/bids/_utils.py
nilearn/interfaces/fmriprep/load_confounds_utils.py
nilearn/interfaces/fmriprep/tests/test_load_confounds.py
pyproject.toml

Closes #3817 
- add regression test
- swap space and hemi entities in filename pattern to fix test

[FIX] fix loading of confounds for giftis

---

.pre-commit-config.yaml
nilearn/interfaces/fmriprep/load_confounds_utils.py
nilearn/plotting/matrix_plotting.py
nilearn/plotting/tests/test_displays.py
nilearn/plotting/tests/test_find_cuts.py
nilearn/plotting/tests/test_img_plotting/test_get_colorbar_and_data_ranges.py
pyproject.toml

- update configs to more from nilearn/plotting
- apply black

[FMT] apply black to plotting - part 3

---

nilearn/_utils/docs.py
nilearn/plotting/html_surface.py
nilearn/plotting/img_plotting.py
nilearn/plotting/surf_plotting.py
nilearn/regions/parcellations.py
nilearn/regions/rena_clustering.py
nilearn/signal.py

Closes #3832 
- remove parameters definitions that were put in _utils.docs.py even though they are used only once in the whole code base.

[DOC] remove single occurence from docs.py

---

.git-blame-ignore-revs
CONTRIBUTING.rst
doc/changes/latest.rst

In my opinion this is the last PR for the formatting automation
and so this closes https://github.com/nilearn/nilearn/issues/2528
- update contributing to say that we now use: black and isort
- update gitblame ignore

[MAINT] update gitblame ignore and contributing

---

doc/changes/latest.rst
examples/01_plotting/plot_demo_glass_brain_extensive.py
examples/01_plotting/plot_demo_more_plotting.py
examples/01_plotting/plot_haxby_masks.py
examples/02_decoding/plot_haxby_different_estimators.py
examples/02_decoding/plot_oasis_vbm.py
examples/02_decoding/plot_simulated_data.py
examples/05_glm_second_level/plot_second_level_one_sample_test.py
examples/06_manipulating_images/plot_extract_rois_statistical_maps.py
examples/07_advanced/plot_bids_analysis.py
examples/07_advanced/plot_haxby_mass_univariate.py
examples/07_advanced/plot_localizer_simple_analysis.py

[DOC] Fix rendering of plots in some examples where titles or images are cut off

---

CITATION.cff
doc/building_blocks/manual_pipeline.rst
doc/building_blocks/neurovault.rst
doc/changes/latest.rst
doc/connectivity/connectome_extraction.rst
doc/connectivity/functional_connectomes.rst
doc/decoding/decoding_intro.rst
doc/manipulating_images/input_output.rst
doc/plotting/index.rst

Closes #3681.
- doctest blocks that had skipped lines were converted to (default) code-blocks
- output that could have been tested against via a doctest ([e.g.](https://github.com/psadil/nilearn/blob/6fb7df5c7af3ec9bcc447e2b3ee274df7273e370/doc/manipulating_images/input_output.rst?plain=1#L121-L127)) were converted into comments

[DOC] replace skipped doctests with default code-blocks

---

CITATION.cff
doc/changes/latest.rst
nilearn/plotting/surf_plotting.py

Closes #3470 .
Surface from `surf_plotting` with the matplotlib engine has transparent surfaces.
- Add vertices width
- Apply surface color to the vertices

[FIX] transparent vertices in `surf_plotting` function

---

doc/changes/latest.rst
nilearn/surface/surface.py

Closes #3844.
- Add cross-refence links
I didn't read the original PR title closely, so I edited everything.....

[DOC] First pass on adding cross-refence links surface module

---

.pre-commit-config.yaml
pyproject.toml

Closes #3870 
- adds a pre-commit hook for toml formatting to the pre-commit config
- apply the hook
- toml is formatted
- only if people install the hook (could be solved by adding something in CI)

[FMT] apply toml formatting hook on pyproject.toml

---

nilearn/_utils/tests/test_niimg.py
nilearn/datasets/tests/test_neurovault.py
nilearn/glm/tests/test_check_events_file_uses_tab_separators.py
nilearn/glm/tests/test_dmtx.py
nilearn/image/tests/test_image.py
nilearn/interfaces/tests/test_bids.py
nilearn/plotting/tests/test_matrix_plotting.py
nilearn/reporting/tests/test_glm_reporter.py

- relates to https://github.com/nilearn/nilearn/issues/3726
- extracted from [WIP] rely more on tmp_path in testing Do Not REVIEW  #3891

[MAINT] use tmp_path fixture in tests that do not depend on fake fmri data generation

---

nilearn/glm/tests/test_first_level.py

- relates to https://github.com/nilearn/nilearn/issues/3726
- extracted from #3891
- ~~blocked by #3892~~

[MAINT] use tmp_path in tests for first lvl GLM

---

CITATION.cff
doc/changes/latest.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py

I received `TypeError: The reference image should be a niimg` when putting a `pathlib.Path` as an argument into `nilearn.image.new_image_like`. I fixed it to properly accept Niimg-like objects, which include `pathlib.Path` in its definition.
- Check for `isinstance` of `pathlib.Path` as well as `str`

[Fix] Fix pathlib.Path not being counted as Niimg-like in new_image_like

---

nilearn/_utils/testing.py
nilearn/_utils/tests/test_testing.py
nilearn/image/resampling.py
nilearn/plotting/displays/_slicers.py
nilearn/plotting/glass_brain.py
nilearn/plotting/tests/test_displays.py
nilearn/surface/surface.py
nilearn/surface/tests/test_surface.py

[MAINT] remove obsolete version comparison

---

nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_displays.py

- Closes #
- In matplotlib > 3.7.2 axes have to be explicitly removed using `ax.remove()` instead of being automatically overwritten
- Adjust failing test in `test_displays.py` to get around matplotlib bug https://github.com/matplotlib/matplotlib/issues/26531

[MAINT] Fix failing tests in prerelease job due to deprecation and bug in matplotlib 3.8.0rc1

---

nilearn/plotting/matrix_plotting.py
nilearn/plotting/tests/test_matrix_plotting.py

- Relates to #3728
- Simplify how title is added to matrix plots and make use of `tight_layout` for automatic adjustment
- Update relevant tests
Relevant to the following examples:
- https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_sphere_based_connectome.html#
- after fix: https://output.circle-artifacts.com/output/job/a9439351-08ed-476f-808e-6cb69147e4ce/artifacts/0/dev/auto_examples/03_connectivity/plot_sphere_based_connectome.html#connectome-extracted-from-dosenbach-s-atlas
- https://nilearn.github.io/dev/auto_examples/02_decoding/plot_haxby_multiclass.html#
- after fix: https://output.circle-artifacts.com/output/job/a9439351-08ed-476f-808e-6cb69147e4ce/artifacts/0/dev/auto_examples/02_decoding/plot_haxby_multiclass.html#plot-a-con …

[FIX] Fix overlapping titles for `plot_matrix` function

---

nilearn/glm/tests/test_second_level.py

- relates to https://github.com/nilearn/nilearn/issues/3726
- extracted from #3891
- ~~blocked by https://github.com/nilearn/nilearn/pull/3892~~

[MAINT] use tmp_path in scd lvl tests

---

nilearn/glm/first_level/experimental_paradigm.py

Fixes:
```
...
../nilearn/nilearn/glm/first_level/design_matrix.py:236: in _convolve_regressors
trial_type, onset, duration, modulation = check_events(events)
../nilearn/nilearn/glm/first_level/experimental_paradigm.py:114: in check_events
.agg(STRATEGY)
...
../virtualenvs/base/lib/python3.11/site-packages/pandas/core/apply.py:1828: in warn_alias_replacement
warnings.warn(
E   FutureWarning: The provided callable <function sum at 0x7fa1a230afc0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass 'sum' instead.
```
Seems like it was available at least back to Pandas 1.4 (Jan 2022) so maybe good enough... couldn't find docs for earlier versions despite them having a drop-down :man_shrugging:

MAINT: Pandas deprecation

---

nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting/test_plot_glass_brain.py

- Closes #3923
- Revert behavior of plot_glass_brain from changes in #3873
- Add test
-

Revert breaking behavior in `plot_glass_brain`

---

doc/changes/latest.rst
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py

[FIX/ENH] Improve generate_report method to work with fit_transform for the maskers

---

pyproject.toml

closes none
`long_description` are replaced by the `readme` (that we do specify) metadata in pyproject.toml:
https://peps.python.org/pep-0621/#readme

[MAINT] remove long decription from pyproject.toml

---

.flake8
.github/workflows/flake8.yml
.pre-commit-config.yaml
nilearn/regions/tests/test_signal_extraction.py
pyproject.toml

- relates to https://github.com/nilearn/nilearn/issues/3570
- extract tests for warnings

[MAINT] refactor tests regions extractions

---

CONTRIBUTING.rst

- Addresses part of #3628
I just copied the example from the issue with @jeromedockes cited as the source at the bottom of the example (but it won't render in the html). IS it ok?

[DOC] Include guidelines for private functions in contributing docs

---

examples/02_decoding/plot_haxby_searchlight.py

- I'm just fixing a tiny typo in the [tutorial](https://nilearn.github.io/stable/auto_examples/02_decoding/plot_haxby_searchlight.html#sphx-glr-auto-examples-02-decoding-plot-haxby-searchlight-py), where the text says "z = 26" but the example is about "z = 29". I didn't make any issue, since this is so minuscule.

Fix typo in tutorial

---

doc/changes/latest.rst
nilearn/plotting/js_plotting_utils.py
nilearn/plotting/tests/test_js_plotting_utils.py
nilearn/plotting/tests/test_surf_plotting.py

[FIX] Allow both vmin and threshold argument values to be used in plotting functions using `colorscale`

---

CONTRIBUTING.rst

[DOC] improve section on private functions

---

pyproject.toml

I moved the flake8 dependencies to the dev category and coverage is already listed in test. Any reason these need to stay in doc?

[INFRA] Reorganize some optional dependencies under doc

---

nilearn/plotting/img_plotting.py

- Closes none
~~Resets handling of matplotlib deprecation. With the newest matplotlib v3.7.3 release, this change is causing the CI failures. I have to see if I handled it incorrectly or if it's a new bug on their side. For the time being, will merge this PR so the CI passes~~
Edit: see comment below

[MAINT] Update handling of matplotlib ax overwrite deprecation

---

README.rst
doc/conf.py

closes none
- add an edit button to the doc
- add links to github repo and twitter in the footer

[DOC] add links and edit buttons to doc

---

AUTHORS.rst
CITATION.cff
maint_tools/citation_cff_maint.py

- Closes #3805 
- makes sure that scripts in charge of citation.cff curation always keep the consortium author at the top of the list of authors in the citation.cff.

[MAINT] add consortium authorship

---

CITATION.cff
doc/changes/latest.rst
nilearn/maskers/multi_nifti_labels_masker.py
nilearn/maskers/multi_nifti_maps_masker.py
nilearn/maskers/tests/test_multi_nifti_labels_masker.py
nilearn/maskers/tests/test_multi_nifti_maps_masker.py

- Closes #3967
- Iterate over the `sample_mask` in `MultiNiftiMapsMasker.transform_imgs` (mirroring the handling of `confounds`)

[FIX] allow using a list of `sample_mask` in `MultiNiftiMapsMasker.fit_transform`

---

AUTHORS.rst
CITATION.cff

- Relates to #3966 
- update several orcids in citation.cff

[MAINT] update ORCID

---

examples/06_manipulating_images/plot_mask_computation.py

[DOC] Fix rendering of explanatory text

---

doc/changes/latest.rst
nilearn/plotting/surf_plotting.py

[FIX] Set edgecolors when plotting contours so that they are rendered

---

doc/themes/custom.css

- Closes #3928
Technically this does not quite solve the overflow but indirectly helps by making the headings smaller.
This was especially needed on smaller viewports.
- reduce headings size for different view ports

[DOC] reduce font size for headings

---

.circleci/config.yml
.github/workflows/testing.yml
.github/workflows/trigger-hosting.yml

[INFRA] Use latest Ubuntu machines for CI

---

build_tools/github/install.sh
pyproject.toml

- Closes None
See https://github.com/nilearn/nilearn/pull/3973#issuecomment-1719365341

[INFRA] Test minimum supported version of matplotlib for min_requirements testing

---

nilearn/plotting/matrix_plotting.py

[DOC] fix doc that mentioned `event_type` instead of `trial_type`

---

doc/changes/latest.rst
nilearn/glm/first_level/design_matrix.py
nilearn/glm/first_level/experimental_paradigm.py
nilearn/glm/tests/test_paradigm.py
nilearn/plotting/matrix_plotting.py

- Closes #3948
- run check_events on inputs of plot_events to ensure that they get the same treatment as before design matrix generation
- extract summation of modulation of duplicated events in a separate function

[MAINT] check events before plotting them

---

.circleci/config.yml
.github/workflows/build-docs.yml
.github/workflows/trigger-hosting.yml
build_tools/github/trigger_hosting.sh

- Closes None
With the current set up, a failure on the doc build prevents circleci from hosting the docs that have been built. This is annoying since the htmls exist but cannot be easily viewed (sometimes for very trivial errors) and thus hinders the review process. This PR changes the configuration so that the docs are always hosted if a build exists. Note that deploy will still only run on main only with a successful doc build.
I've tested this on my fork on [main](https://github.com/ymzayek/nilearn) and in a [PR](https://github.com/ymzayek/nilearn/pulls)

[INFRA] Configure doc build CI to always host artifacts

---

build_tools/github/install.sh
pyproject.toml

Since recent CI change in #3976
seems like minimum testing with minimum matplotlib is not installing matptlotlib at all due to a syntax error. See for example https://github.com/nilearn/nilearn/actions/runs/6272781202/job/17034981917?pr=4001

[INFRA/FIX] Minimum testing with minimum matplotlib is not installing matplotlib

---

.pre-commit-config.yaml
doc/changes/latest.rst
nilearn/glm/contrasts.py
nilearn/glm/tests/test_contrasts.py
nilearn/glm/tests/test_first_level.py
nilearn/glm/tests/test_second_level.py
pyproject.toml

closes #3194.
Still need more tests (for F tests). 
Detecting some inconsistencies in dimension: se sometimes require effect sizes for t contrasts to have shape (1, n_voxels) while it would be more natural to have shape (n_voxels). I think that we should actually support both cases seamlessly.

[FIX] improve support for  F statistics in `compute_fixed_effects`

---

.pre-commit-config.yaml
CONTRIBUTING.rst
README.rst
doc/building_blocks/manual_pipeline.rst
nilearn/_utils/docs.py
nilearn/datasets/atlas.py
nilearn/plotting/displays/_projectors.py
nilearn/plotting/displays/_slicers.py
nilearn/surface/data/README.md
pyproject.toml

- Relates to #4003
- apply black to docs
- update pre-commit hooks

[WIP] apply black to docs

---

CONTRIBUTING.rst
doc/changes/0.10.1.rst
doc/changes/latest.rst

- Closes none
- add tags to changelog in view of next release

[REL] add tags to changelog

---

doc/introduction.rst
examples/04_glm_first_level/plot_first_level_details.py
examples/04_glm_first_level/plot_spm_multimodal_faces.py
nilearn/_utils/exceptions.py
nilearn/decoding/fista.py
nilearn/decomposition/_base.py
nilearn/glm/regression.py
nilearn/regions/tests/test_parcellations.py

- Closes #4025 
- fix typos caught by codespell

[FIX] fix spelling

---

.github/workflows/black.yml
.github/workflows/detect_test_pollution.yml
.github/workflows/f_strings.yml
.github/workflows/flake8.yml
.github/workflows/isort.yml
.github/workflows/testing.yml
.github/workflows/update_authors.yml
.github/workflows/update_precommit_hooks.yml
examples/02_decoding/plot_haxby_grid_search.py
nilearn/decoding/decoder.py
nilearn/interfaces/fmriprep/tests/test_load_confounds.py
nilearn/surface/surface.py
pyproject.toml

- relates to #3812 
- use python 3.12 in CI

[MAINT] Add python 3.12 to CI

---

doc/changes/latest.rst
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/tests/test_multi_nifti_masker.py

- Fixes bug reported in #3960
- Relates to #3935
- Allow MultiNiftiMasker to use `generate_report` for one subject for now (mimicking multi labels and maps masker behavior)

[FIX] Allow `MultiNiftiMasker` to use `generate_report` method

---

.github/workflows/README.md
.github/workflows/check_deprecations.yml
nilearn/conftest.py
nilearn/mass_univariate/tests/utils.py

- Closes #3541 and maybe #1737
-
-

[MAINT] Implement deprecation warnings-as-errors in prerelease test using pytest fixture

---

nilearn/conftest.py

- Closes None
Minor maintenance thing. Running pytest automatically imports all files in nilearn modules and the file `reporting/_visual_testing/_glm_reporter_visual_inspection_suite_.py` writes an empty directory when imported. So this it just to prevent its import since it is only for visual testing and not actually used by nilearn

[MAINT] Ignore private visual testing file when running pytest

---

Makefile
build_tools/github/build_type.sh
doc/Makefile

[MAINT] Add partial build specific to CI doc build workflow

---

nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

- Closes #2588
- fixes typos and trailing spaces in atlas labels

[FIX] fix typos in Harvard Oxford atlas labels

---

nilearn/datasets/tests/test_utils.py
nilearn/datasets/utils.py

- Closes #1803
- add readme in default data location to let user know it is sage to remove this folder

[ENH] add readme to default data locations

---

CONTRIBUTING.rst

- Closes None
Just a quick thing I noticed that the example here https://nilearn.github.io/stable/development.html#guidelines-for-private-functions doesn't have the right indentations

[DOC] Fix wrong indentation of example code

---

nilearn/conftest.py
nilearn/image/tests/test_image.py
nilearn/plotting/tests/test_img_plotting/test_img_plotting.py
nilearn/plotting/tests/test_img_plotting/test_plot_carpet.py

- Closes #3725 
- extract several fixtures from a single complex one used for plotting

[MAINT] Refactor fixture for plotting

---

nilearn/_utils/tests/test_extmath.py
nilearn/decoding/tests/test_graph_net.py
nilearn/decoding/tests/test_objective_functions.py
nilearn/decoding/tests/test_same_api.py
nilearn/decoding/tests/test_space_net.py
nilearn/mass_univariate/permuted_least_squares.py
nilearn/mass_univariate/tests/test_permuted_least_squares.py
nilearn/mass_univariate/tests/test_utils.py

- closes https://github.com/nilearn/nilearn/issues/3926

[MAINT] Use rng fixture instead of check_random_state

---

nilearn/_utils/docs.py
nilearn/connectome/connectivity_matrices.py
nilearn/connectome/group_sparse_cov.py
nilearn/decoding/decoder.py
nilearn/decoding/space_net.py
nilearn/decomposition/_base.py
nilearn/decomposition/_multi_pca.py
nilearn/decomposition/canica.py
nilearn/decomposition/dict_learning.py
nilearn/plotting/displays/_projectors.py
nilearn/regions/hierarchical_kmeans_clustering.py
nilearn/regions/parcellations.py
nilearn/regions/region_extractor.py
nilearn/regions/rena_clustering.py

- Closes #4016
- unindent some code blocks
- remove extra backticks in class attributes doc
Started to solve #4016 and improve visual rendering, also ended up homogenzing Attributes in classes doc string to match [numpy styles](https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring)

[STY] Minor doc formatting

---

doc/changes/latest.rst
nilearn/glm/_utils.py
nilearn/glm/contrasts.py
nilearn/glm/model.py
nilearn/glm/tests/test_contrasts.py
nilearn/glm/tests/test_model.py
nilearn/glm/tests/test_second_level.py

- Closes #2396
- pad t and F constrast when they are too short
- throw a warning when padding is done
- throw error only when contrast are longer than the number of columns

[ENH] pad t and F 'short' contrasts with zeros

---

doc/changes/latest.rst
nilearn/glm/_utils.py
nilearn/glm/contrasts.py
nilearn/glm/first_level/design_matrix.py
nilearn/glm/first_level/first_level.py
nilearn/glm/first_level/hemodynamic_models.py
nilearn/glm/model.py
nilearn/glm/second_level/second_level.py
nilearn/glm/tests/test_check_events_file_uses_tab_separators.py
nilearn/glm/tests/test_contrasts.py
nilearn/glm/tests/test_first_level.py
nilearn/glm/tests/test_hemodynamic_models.py
nilearn/glm/tests/test_model.py
nilearn/glm/tests/test_second_level.py
nilearn/glm/tests/test_thresholding.py
nilearn/glm/tests/test_utils.py

- Relates to #3570
- refactor and simplify complex tests in nilearn
- apply some sourcery suggested refactor in nilearn

[MAINT] refactor of tests and code in GLM module

---

CONTRIBUTING.rst

- Closes none
- add a warning in the contributing doc regarding adding new downloaders

[DOC] Make scope limit more obvious regarding accepting new downloaders

---

examples/04_glm_first_level/plot_first_level_details.py

[FIX] fix typo

---

CONTRIBUTING.rst
doc/maintenance.rst

- Closes #3576 
- mention checking changelog badges during release

[DOC] mention checking badges during release

---

CITATION.cff
doc/changes/latest.rst
nilearn/signal.py
nilearn/tests/test_signal.py

- Closes #4024
- include a `extrapolate` parameter in the `signal._interpolate_volumes()` function, exposing the identically named parameter from the Scipy class used underneath for the Splines-based interpolation (see https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicSpline.html#scipy.interpolate.CubicSpline). 
- setting the default `extrapolate` new parameter value to False, disabling the undesired interpolation on out-of-bounds volumes

[FIX] Disable extrapolation of out-of-bounds volumes

---

examples/02_decoding/plot_haxby_frem.py
examples/02_decoding/plot_haxby_searchlight.py
examples/02_decoding/plot_haxby_searchlight_surface.py
examples/02_decoding/plot_mixed_gambles_frem.py
examples/02_decoding/plot_miyawaki_encoding.py
examples/02_decoding/plot_miyawaki_reconstruction.py
examples/02_decoding/plot_oasis_vbm.py
examples/02_decoding/plot_oasis_vbm_space_net.py
examples/02_decoding/plot_simulated_data.py
examples/03_connectivity/plot_atlas_comparison.py
examples/03_connectivity/plot_compare_decomposition.py
examples/04_glm_first_level/plot_bids_features.py
examples/05_glm_second_level/plot_oasis.py
examples/05_glm_second_level/plot_proportion_activated_voxels.py
examples/05_glm_second_level/plot_second_level_association_test.py
examples/05_glm_second_level/plot_second_level_one_sample_test.py
examples/05_glm_second_level/plot_second_level_two_sample_test.py
examples/05_glm_second_level/plot_thresholding.py
examples/07_advanced/plot_advanced_decoding_scikit.py
examples/07_advanced/plot_age_group_prediction_cross_val.py
examples/07_advanced/plot_beta_series.py
examples/07_advanced/plot_bids_analysis.py
examples/07_advanced/plot_haxby_mass_univariate.py
examples/07_advanced/plot_localizer_mass_univariate_methods.py
examples/07_advanced/plot_surface_bids_analysis.py

[DOC] Speed up fit computation with parallel processing

---

nilearn/plotting/find_cuts.py
nilearn/plotting/tests/test_find_cuts.py

[REF] Clarify code in `find_parcellation_cut_coords` function

---

nilearn/experimental/surface/_maskers.py

- Closes #
This is an initial attempt to implement signal.clean to SurfaceMasker.
Concerns (generalisable to niftimaskers):
- clean_kwargs - should filter out confounds and sample mask to prevent
user adding those parameters upon creating the masker
- all the cleaning related parameters - what do we want to choose to
expose?
If we set on the solution I will expand this to `SurfaceLabelsMasker`

[EHN] Implement signal.clean to SurfaceMasker

---

doc/changes/latest.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py

Addresses #3467.
This change introduces the `two_sided` argument for `binarize_img` which allows users to control whether the `threshold` is applied to the original value of the image (`two_sided=False`) or absolute value of the image (`two_sided=True`). The behavior does not change from what is was (`two_sided` was always `True`), but I think it should change to default to `False` as it is more intuitive when thresholding images with negative values.
I am also interested in expanding the function to include multiple operators (less than, more than, etc), but figured this is a good place to start that addresses the linked issue.

[ENH] Update binarize_img for negative value handling

---

.pre-commit-config.yaml
doc/changes/latest.rst

- update name of of one file to ignore in the precommit config (was renamed everywhere else but there)
- minor RST fix flagged by `pre-commit run -a`

[MAINT] minor pre-commit fix

---

.github/workflows/numpy2_compatibility.yml
doc/decoding/decoding_intro.rst
nilearn/_utils/niimg.py
nilearn/datasets/tests/test_func.py
nilearn/decoding/space_net.py
nilearn/decoding/tests/test_decoder.py
nilearn/decomposition/dict_learning.py
nilearn/glm/tests/test_thresholding.py
nilearn/glm/thresholding.py
nilearn/image/tests/test_image.py
nilearn/plotting/find_cuts.py
nilearn/plotting/tests/test_edge_detect.py
nilearn/regions/signal_extraction.py
nilearn/tests/test_masking.py
tox.ini

[MAINT] Test against Numpy 2.0 nightly releases

---

CITATION.cff
doc/changes/latest.rst
examples/02_decoding/plot_haxby_glm_decoding.py

Addresses issue: https://github.com/nilearn/nilearn/issues/4109

[DOC] Mention classification type in plot_haxby_glm_decoding.py

---

CITATION.cff
doc/changes/latest.rst
examples/05_glm_second_level/plot_proportion_activated_voxels.py
examples/05_glm_second_level/plot_second_level_two_sample_test.py

- Closes #4135
- Remove `get_tmaps=True` from all calls to `fetch_localizer_contrasts() 
` because tmaps aren't used in the examples.

Don't use get_tmaps=True if tmaps aren't used

---

doc/changes/latest.rst
examples/07_advanced/plot_beta_series.py

Makes the text more coherent (as the full form for LSA is written above) and prevents people from scrolling up to remember what LSS stands for.

[DOC] Specify full form of LSS in beta series tutorial

---

nilearn/maskers/nifti_masker.py
nilearn/maskers/tests/test_nifti_masker.py

- Related to https://github.com/nilearn/nilearn/pull/4126#issuecomment-1847137828
- Raise a more meaningful error than 
```bash
E TypeError: Data given cannot be loaded because it is not compatible with nibabel format:
E None
```

[MAINT] Improve error for nifti masker when fit is called without imgs or mask_img

---

nilearn/datasets/_utils.py
nilearn/datasets/func.py
nilearn/datasets/neurovault.py
nilearn/datasets/tests/test_utils.py

- Closes #4155
- rename `nilearn.datasets._utils.fetch_file` to `nilearn.datasets._utils.fetch_single_file`

[ENH]  rename `nilearn.datasets._utils.fetch_file` to `nilearn.datasets._utils.fetch_single_file`

---

nilearn/datasets/__init__.py
nilearn/datasets/func.py
nilearn/datasets/tests/test_func.py
nilearn/datasets/tests/test_utils.py
nilearn/datasets/utils.py

- Closes #4139
- relocate load_sample_motor_activation_image
- throw deprecation warning when imported from the older location

[MAINT] relocate functions from nilearn.datasets.utils

---

nilearn/plotting/html_document.py
nilearn/plotting/tests/test_html_document.py

I'm not 100% sure why but at least on some jupyter versions defining `_repr_html_` is not enough; defining `_repr_mimebundle_` instead (or as well) fixes the issue.
main branch:
this PR:
```
❯ jupyter --version
Selected Jupyter core packages...
IPython          : 8.19.0
ipykernel        : 6.28.0
ipywidgets       : 8.1.1
jupyter_client   : 8.6.0
jupyter_core     : 5.6.1
jupyter_server   : 2.12.1
jupyterlab       : 4.0.10
nbclient         : 0.8.0
nbconvert        : 7.14.0
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.5.1
traitlets        : 5.14.0
```

[FIX] rich display in jupyter notebook/lab

---

nilearn/glm/second_level/second_level.py
nilearn/glm/tests/test_second_level.py

- Closes #3807, closes #4140
TODO:

[ENH] Allow string expressions for `second_level_contrast` of `non_parametric_inference`

---

CITATION.cff
doc/changes/0.10.2.rst
nilearn/tests/test_signal.py

This caused a third line to be unnecessary so I removed it also.
- Closes #4175
- Removed three useless lines.

[MAINT]  Remove unnecessary lines describe in `test_clean_psc`

---

examples/03_connectivity/plot_signal_extraction.py
examples/07_advanced/plot_beta_series.py
nilearn/connectome/connectivity_matrices.py
nilearn/connectome/group_sparse_cov.py
nilearn/datasets/atlas.py
nilearn/datasets/func.py
nilearn/datasets/neurovault.py
nilearn/datasets/struct.py
nilearn/decoding/decoder.py
nilearn/decomposition/canica.py
nilearn/decomposition/dict_learning.py
nilearn/glm/regression.py
nilearn/glm/thresholding.py
nilearn/image/image.py
nilearn/interfaces/fmriprep/load_confounds.py
nilearn/interfaces/fmriprep/load_confounds_strategy.py
nilearn/mass_univariate/permuted_least_squares.py
nilearn/plotting/img_plotting.py
nilearn/regions/region_extractor.py
nilearn/regions/rena_clustering.py
nilearn/signal.py

- Relates to #4207
- ensure that we have prettier citations
this
https://output.circle-artifacts.com/output/job/aadb2832-9b73-48f2-8a9f-c0a25691abda/artifacts/0/dev/modules/generated/nilearn.datasets.fetch_atlas_craddock_2012.html#nilearn-datasets-fetch-atlas-craddock-2012
instead of this
https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_atlas_craddock_2012.html#nilearn-datasets-fetch-atlas-craddock-2012

[DOC] format citation

---

.gitignore
doc/changes/latest.rst
nilearn/_utils/param_validation.py
nilearn/glm/contrasts.py
nilearn/glm/first_level/first_level.py
nilearn/plotting/displays/_slicers.py
nilearn/plotting/tests/test_img_plotting/test_img_plotting.py
nilearn/reporting/_visual_testing/_glm_reporter_visual_inspection_suite_.py
nilearn/reporting/get_clusters_table.py
nilearn/reporting/glm_reporter.py
nilearn/reporting/tests/test_glm_reporter.py

- Closes #4203 
- bump stack level of several warnings (make sure they "point" to some public API function)
- add regression test and fix

[FIX] fix plotting of an image with color bar when maximum value is exactly zero

---

doc/changes/latest.rst
examples/03_connectivity/plot_signal_extraction.py
nilearn/interfaces/fmriprep/load_confounds.py
nilearn/interfaces/fmriprep/load_confounds_strategy.py
nilearn/interfaces/fmriprep/tests/test_load_confounds_strategy.py

Closes #4222
Closes #4223
- deprecation for scrubbing thresholds to match fmriprep docmentation (`fd_threshold=0.5`; `std_dvars_threshold=1.5`)
- for `load_confounds_strategy` allow global signal in compcor strategy to reflect on fmriprep documentation. This change does not break any existing behaviour as the default remains to be False
Need help:

FIX/EHN update load_confound_strategy defaults

---

doc/changes/latest.rst

- Closes none
- add highlights and sort changelog by label

[DOC] sort changelog and add highlights

---

nilearn/experimental/__init__.py

- Relates to https://github.com/nilearn/nilearn/issues/4027#issuecomment-1908667900
- remove warning from experimental module
- add it as part of the doc string to be rendered in the doc

[DOC] remove warning from experimental module and add it as doc string

---

doc/changes/latest.rst
nilearn/glm/contrasts.py

Looks like `contrast_type` was deprecated but at least one internal use was not updated to `stat_type`. Discovered because I tried to follow the deprecation instructions when using `compute_contrast` but kept getting a DeprecationWarning.

[FIX] Replace remaining `contrast_type` by `stat_type`

---

nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py
nilearn/interfaces/bids/query.py

- Closes #4252
- indicate folder where subjects were not found
- increase stack level of several warnings
- add error when no subject was found
- use absolute path

[DOC] Improve warnings for BIDS folders

---

doc/changes/latest.rst
examples/03_connectivity/plot_sphere_based_connectome.py
nilearn/maskers/nifti_spheres_masker.py

- Closes #4282
- fix positions markers on images on sphere masker reports
- minor changes in example with report to trigger its build in CI

[FIX] fix positions markers on images on sphere masker reports

---

nilearn/maskers/multi_nifti_labels_masker.py
nilearn/maskers/multi_nifti_maps_masker.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py

- Closes #4276
- clarify the maskers Classes doc strings to help differentiate them
- link to the user guide section on labels and maps

[DOC] update doc strings of the maskers

---

doc/changes/latest.rst
nilearn/plotting/displays/_slicers.py

- Closes #4283 
- increase width of colorbar in mosaic display
-

[FIX] improve colorbar in mosaic display

---

doc/changes/latest.rst
nilearn/glm/first_level/first_level.py
nilearn/reporting/_visual_testing/_glm_reporter_visual_inspection_suite_.py
nilearn/reporting/glm_reporter.py

FIX] fixes several plotting details in glm reports

---

doc/changes/latest.rst
nilearn/_utils/docs.py
nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py

- Closes #4294
- enforce type for views in surface plotting
- update test
- update doc string

[FIX] force views in surface plotting to be pairs of `int` or `float` when not a `string`

---

.github/codespell_ignore_words.txt
.gitignore
doc/changes/latest.rst
doc/modules/generated_reports/masker_reports_examples.rst
doc/visual_testing/reporter_visual_inspection_suite.py
nilearn/image/resampling.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py

[DOC] display all masker reports in the doc

---

nilearn/externals/conftest.py
pyproject.toml

Reverts nilearn/nilearn#4306
Closes #4305

Revert "[FIX] remove conftest for externals"

---

doc/changes/latest.rst
nilearn/_utils/docs.py
nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py

- Related to #4296 
- add `avg_method` parameter to `plot_surf_stat_map`
- throw warnings when using plotly and passing an unimplemented parameter to one of the surface plotting function to avoid users being confused why some parameters have no effect.
- this required setting the default of a few parameters to `None` in the function declaration and using the original default when using the matplotlib engine.
- this should now be reflected in the doc strings

[ENH] Add `avg_method` to `plot_surf_stat_map`

---

.github/workflows/README.md
.github/workflows/prettier.yml
.pre-commit-config.yaml
.prettierignore
CONTRIBUTING.rst
doc/changes/latest.rst
doc/themes/custom.css
nilearn/plotting/data/html/connectome_plot_template.html
nilearn/plotting/data/html/stat_map_template.html
nilearn/plotting/data/html/surface_plot_template.html
nilearn/reporting/data/html/report_body_template.html
nilearn/reporting/data/html/report_body_template_niftilabelsmasker.html
nilearn/reporting/data/html/report_body_template_niftimapsmasker.html
nilearn/reporting/data/html/report_body_template_niftispheresmasker.html
nilearn/reporting/data/html/report_head_template.html
nilearn/reporting/glm_reporter_templates/contrast_template.html
nilearn/reporting/glm_reporter_templates/design_matrix_template.html
nilearn/reporting/glm_reporter_templates/report_body_template.html
nilearn/reporting/glm_reporter_templates/report_head_template.html
nilearn/reporting/glm_reporter_templates/stat_maps_contrast_clusters_template.html
tox.ini

- Closes none but related to https://github.com/nilearn/nilearn/pull/4295#issuecomment-1971863445
- add prettier hook to pre-commit config
- run the hook on the code and doc base
- add github action to check formating

[MAINT] Use prettier to format HTML and CSS

---

AUTHORS.rst
maint_tools/citation_cff_maint.py

- Closes #4321
- adding myself to authors list
- removing Yasmin (?)

[DOC] Adding Himanshu to authors

---

examples/00_tutorials/plot_nilearn_101.py

- Closes #810
- add a section in [this](https://nilearn.github.io/stable/auto_examples/00_tutorials/plot_nilearn_101.html) example about globbing

[DOC] Advertise nilearn's in built globbing

---

nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/tests/test_nifti_labels_masker.py

- Closes none but follow up on #4333
- add match argument to test of errors
- add explicit test of resampling_target=None
- simplify some variable names that were made too complicated after splitting long tests in #4333

[MAINT] add test to `resampling_target = None` for nifti label maskers

---

CITATION.cff
doc/changes/latest.rst
doc/connectivity/parcellating.rst
doc/glossary.rst

- Closes none
- Fix typo of the word "mutli" for the definition of MVPA in the glossary
- Fix typo footcite Thirion2014

[DOC] Fix typos doc

---

nilearn/surface/tests/test_surface.py

- Closes #4328
- uses `assert_array_almost_equal` with decimal=15 instead of `assert_array_equal`

[ENH] relax requirements for test_sampling_affine

---

nilearn/glm/first_level/first_level.py

- Closes #4342 
- Fixed typo: `confound_` prefix should be `confounds_` for the kwargs
- Fixed some formatting weirdness in the autodocs
- Indented the part about the `confounds_` kwargs to be under the entry for `kwargs`
- Moved some text referring to other arguments and subject labels to before the "Parameters" section
- Added double back ticks around `None` etc. and turned the references to e.g. `FirstLevelModel` into links
@Remi-Gau does this function currently only process kwargs that have the `confounds_` prefix? Should we raise a warning or throw an error if there are other kwargs provided by the user?

[DOC] Fix typo and docstring formatting in `glm.first_level.first_level_from_bids`

---

nilearn/glm/first_level/first_level.py

- Closes #4309
- implemented recommendations from https://numpy.org/devdocs/release/2.0.0-notes.html#removed-ambiguity-when-broadcasting-in-np-solve

[FIX] resolve numpy2 compatibility related to ambiguity when broadcasting in np.solve

---

.github/workflows/build-docs.yml
.github/workflows/detect_test_pollution.yml
.github/workflows/numpy2_compatibility.yml
.github/workflows/test_with_tox.yml
.github/workflows/testing_minimum.yml
.gitignore
Makefile
doc/Makefile
tox.ini

- Closes #4314
- clean up makefiles to remove unused recipes
- transfer basic doc building from main makefile to tox.ini
- add recipe in doc/makefile to allow easy viewing of the built doc with `make view` or `make -D doc view`
- update tox config and CI workflows so that the tests and doc output shows color in CI reports

[MAINT] clean up makefiles and allow color in CLI in github workflows

---

.github/workflows/build-docs.yml
.github/workflows/codespell.yml
.github/workflows/detect_test_pollution.yml
.github/workflows/numpy2_compatibility.yml
.github/workflows/testing_minimum.yml
.github/workflows/update_precommit_hooks.yml

- Closes none
Motivation: some GH workflows were run daily on top of being run after a merge on main.
- change schedule of github workflows
- all monthly actions run on the first of the month
- all other actions with a schedule run once a week on monday (numpy 2 check, and doc build)
- make sure all scheduled workflow can also be triggered 'manually' from the github GUI in [the action tab](https://github.com/nilearn/nilearn/actions).

[MAINT] change schedule of GH workflows

---

CITATION.cff
doc/changes/latest.rst
nilearn/plotting/html_stat_map.py
nilearn/plotting/tests/test_html_stat_map.py

- Closes #4415 
- Add input field for the output image width of view_img() in pixels

add width input to view_img()

---

doc/changes/latest.rst
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

- Closes #4357 
- Make `_check_kwargs_load_confounds` return unused `remaining_kwargs` in addition to `kwargs_load_confounds`
- Throw an error in `first_level_from_bids` if there are any remaining kwargs after the confound ones are extracted
- Not sure if this is too strong, we could also raise a warning instead

[FIX] Raise error if unknown kwargs are given to `first_level_from_bids`

---

AUTHORS.rst
CITATION.cff
doc/changes/latest.rst
doc/changes/names.rst
nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py

- closes [2305](https://github.com/nilearn/nilearn/issues/2305).
The force_resample=False which is currently default, the code is not implemented correctly. There are several of #TODO flags in the code for force_resample=False case. Therefore, changed the default option to force_resample=True.

[ENH] Add warning for future change of the default of `force_resample` to True

---

doc/changes/latest.rst
doc/visual_testing/reporter_visual_inspection_suite.py
nilearn/reporting/data/html/report_head_template.html
nilearn/reporting/html_report.py

- Closes #4300 
- Extracted from #4295
- add footer to masker reports

[ENH] add footer to all masker reports

---

nilearn/experimental/surface/tests/test_maskers.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/tests/test_nifti_labels_masker.py
nilearn/maskers/tests/test_nifti_maps_masker.py
nilearn/maskers/tests/test_nifti_masker.py
nilearn/maskers/tests/test_nifti_spheres_masker.py

- Closes #4456
- move where warning is actually thrown
- add tests for the behavior
based on #4432 so needs to be merged after it (requires some conftest refactoring)

[FIX] throw warning a masker `generate_report` is called without matplotlib

---

examples/08_experimental/plot_3d_map_to_surface_projection_experimental.py
examples/08_experimental/plot_surf_stat_map_experimental.py

- Closes none but should fix doc build failure in main
- the exprimental [fetch_destrieux for surface data returns a list of strings](https://github.com/nilearn/nilearn/commit/59c236d74b56d18f0c0c534fa329666cfc7bfb98#r143380304) as label names and not a list of bytes as its volume counterpart: this PR fixes this

[FIX] use string as label names in example involving the new surface based destrieux atlas

---

nilearn/datasets/func.py
nilearn/glm/first_level/hemodynamic_models.py
nilearn/glm/tests/test_dmtx.py
nilearn/glm/tests/test_first_level.py
nilearn/glm/tests/test_hemodynamic_models.py
nilearn/tests/test_signal.py

- Closes none but relates to https://github.com/nilearn/nilearn/issues/4466#issuecomment-2184903945
Context: aims to have the same variable name in the codebase to avoid issues like the one mentioned in the comment above.
- this "only" rename `tr` into `t_r` in tests and private functions. I will tackle the occurences in public function in another PR as it will involve some deprecation.

[MAINT] rename `tr` variable - private occurences

---

doc/changes/latest.rst
nilearn/glm/first_level/hemodynamic_models.py
nilearn/glm/tests/test_dmtx.py

- Closes #2981
- Change the default `ratio` value to `0.48` in `glover_hrf` & `glover_dispersion_derivative` when calling `_gamma_difference_hrf` to fit the canonical Glover HRF (1999) curve.

[FIX] Change default `ratio` value in glover to fit canonical Glover HRF (1999)

---

.github/workflows/test_with_tox.yml
.gitignore
.pre-commit-config.yaml
maint_tools/templates/index.html
pyproject.toml
tox.ini

Closes none
Just trying to see if there are some pytest plugin we can use that help us navigate the gigantic output of the test suite.
Other options:
- https://github.com/Teemu/pytest-sugar
- https://github.com/nicoddemus/pytest-rich
See also options that build full HTML reports:
- https://pytest-html.readthedocs.io/en/latest/index.html
- https://github.com/christiansandberg/pytest-reporter-html1
- https://github.com/prashanth-sams/pytest-html-reporter

[MAINT] use pytest-reporter-html1 to create test reports

---

nilearn/decoding/decoder.py

- Closes #4488
- changing the default value of `clustering_percentile` in `_BaseDecoder` docstring from 10 to 100

Change default `clustering_percentile` in `_BaseDecoder` docstring

---

CONTRIBUTING.rst

conda doesn't come with pip included
- Small correction on contribution guidelines

[DOC] Small correction on instructions for setting up environment

---

doc/changes/latest.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py

- Closes #4498
- Avoids the warning by casting the mask to `np.int8` instead of `int`(64)

[FIX] Reduce `dtype` of mask from `int64` to `int8` in `image.binarize_img`

---

.github/workflows/nightly_dependencies.yml
nilearn/glm/first_level/design_matrix.py
nilearn/glm/tests/test_dmtx.py

- Closes #4495 
- force np.float64 format to make sure compatibility with pandas 3.0

[FIX] force np.float64 format for second level matrix dataframe

---

nilearn/_utils/helpers.py
nilearn/interfaces/bids/glm.py
nilearn/plotting/matrix_plotting.py
nilearn/reporting/glm_reporter.py

- Closes none
- deal with one deprecation warning from matplotlib to set figure layout to "tight"
- deal with one warnings from numpy about using matrix instead of array
Should remove about 100 warnings from the test run.

[MAINT] Handle 2 numpy and matplolib deprecation warnings

---

examples/06_manipulating_images/plot_affine_transformation.py
nilearn/_utils/helpers.py

- Closes none
- raise stacklevel of `copy_header` warning to allow user to know which function call triggered the warning so they can act on it.

[MAINT] raise stacklevel of `copy_header` warning

---

nilearn/decoding/searchlight.py
nilearn/decoding/tests/test_space_net.py
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

- Closes none 
- change some tested value in space_net to avoid warnings
- update first_level_from bids to reduce amount of meaningless warnings
- update searchlight to no pass groups to KFold CVs as it does not use it anyway (would trigger a warning otherwise)

[MAINT] Clean up some warnings from the tests

---

doc/visual_testing/reporter_visual_inspection_suite.py
examples/04_glm_first_level/plot_first_level_details.py
examples/04_glm_first_level/plot_spm_multimodal_faces.py
examples/05_glm_second_level/plot_oasis.py
examples/06_manipulating_images/plot_affine_transformation.py
examples/06_manipulating_images/plot_resample_to_template.py
nilearn/_utils/niimg_conversions.py
nilearn/image/resampling.py
nilearn/image/tests/test_resampling.py
nilearn/maskers/base_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/masking.py
nilearn/plotting/html_stat_map.py
nilearn/plotting/img_plotting.py
nilearn/surface/surface.py

- Closes none but relates to #4412, #4441, #4450
- some internal occurrence of force `resample_img` and `resample_to_img` were not set with `force_resample=False` leading to extra warnings that users cannot act on despite the warning message implying that they can.
- change dtype of some of the data used to test resample_img to reduce occurences of "casting to float" warnings in tests

[MAINT] reduce occurence of resampling related warnings

---

CITATION.cff
doc/changes/latest.rst
doc/modules/datasets.rst
nilearn/datasets/atlas.py
nilearn/datasets/description/aal.rst
nilearn/datasets/tests/test_atlas.py
nilearn/datasets/tests/test_utils.py

- Closes #4551 
- Added an option in `fetch_atlas_aal(version="3v2")` to fetch the latest AAL version.
- Updated the documentation accordingly.
- Added a _DeprecationWarning_ when the default AAL atlas is fetched, notifying users that version 3v2 will become the default instead of SPM12 starting from version 0.13.

 [ENH] Add last version of the AAL atlas to its fetcher

---

nilearn/_utils/docs.py

- Closes none
- make sure the name of the extract_type parameter matches that of the key in the doc dictionary to avoid mismatch in the rendered doc (see example in image below where parameter name 'extract_type' in the function signature does not match the name of the parameter in the doc string 'extractor')

[FIX] fix name of parameter in the "extract_type" definition

---

CITATION.cff
doc/changes/latest.rst
nilearn/image/resampling.py

- Closes #4563 
- Reorder condition checking for internal [`_resample_one_img`](https://github.com/nilearn/nilearn/blob/4c209b49b42ad2093ee3c2ce268b4d87d18a5ee2/nilearn/image/resampling.py#L292), first checking interpolation order before checking array values, improving performance by skipping the value checks when `nearest` interpolation is selected for [`resample_img`](https://github.com/nilearn/nilearn/blob/4c209b49b42ad2093ee3c2ce268b4d87d18a5ee2/nilearn/image/resampling.py#L349).
- Update the check of array values to call `np.array_equal` to assert values are `[0, 1]`, avoiding redundant sorting and typecasting from `np.array` to `list`

[MAINT] Optimize `_resample_one_img` logic check for nearest interpolation

---

doc/changes/latest.rst
nilearn/plotting/img_plotting.py
nilearn/plotting/tests/test_img_plotting/test_plot_roi.py
nilearn/regions/parcellations.py
nilearn/regions/tests/test_parcellations.py

- Closes none
- fix plotting_roi and Parcellations that threw the warning even if users data with a type different from int64:
> Data array used to create a new image contains 64-bit ints. This is likely due to creating the array with numpy and passing `int` as the `dtype`. Many tools such as FSL and SPM cannot deal with int64 in Nifti images, so for compatibility the data has been converted to int32.
- Should remove > 80 warnings from the test suite
- warnings in the example:
https://nilearn.github.io/stable/auto_examples/03_connectivity/plot_data_driven_parcellations.html
https://nilearn.github.io/stable/auto_examples/01_plotting/plot_atlas.html#visualizing-the-juelich-atlas-with-contours

[FIX] avoid warning when creating int64 images

---

.github/ISSUE_TEMPLATE/bug.yml
.github/workflows/test_with_tox.yml
.github/workflows/testing_install.yml
.github/workflows/testing_minimum.yml
.pre-commit-config.yaml
doc/changes/latest.rst
nilearn/_utils/segmentation.py
nilearn/decoding/decoder.py
nilearn/experimental/surface/_datasets.py
nilearn/experimental/surface/_io.py
nilearn/experimental/surface/_surface_image.py
pyproject.toml
tox.ini

- Closes #4399
- Closes #4521 
- drop python 3.8
- run minimal install with python 3.9
- adapt dependencies version so all tests pass

[MAINT] drop python 3.8

---

doc/changes/latest.rst
examples/03_connectivity/plot_atlas_comparison.py

Closes #4473
* Emphasized that connectivity is computed for both hemispheres as default behavior.
* Added an example where Yeo 17 networks is divided into two separate images & connectivity analysis is run on them separately.
In the future however it would be nice if the plotting function displayed both hemispheres by default for Yeo so as to align with the default connectome computation.

[DOC] Demonstrate how to compute & plot functional connectivity for each hemisphere separately with Yeo 17 networks

---

nilearn/datasets/_utils.py
nilearn/datasets/tests/test_utils.py
pyproject.toml

- Closes  none but relates to #4327 
- fixes error: https://docs.astral.sh/ruff/rules/os-path-splitext/

[FIX] fix error PTH122 from

---

nilearn/_utils/masker_validation.py
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

- Closes #4586
- check that mask and input data are of compatible types (that is for volumetric or surface based analysis) and raise an error when that's not possible

[FIX] check type compatibility of GLM mask and input data

---

nilearn/signal.py
nilearn/tests/test_signal.py

This ended up being a pretty chunky PR.
- Closes #4466 
- Return signals if standardization was not applied. This is straight forward.
- Extra tests for PSC - make sure at least the output is correlated with those created by other linear scaling method (z score).
- Tighten the logic for adding back mean to signals.
Instead of checking user supplied strategy, I check if the original signal mean has a factor of 10 difference after filtering / detrending / regressing confounds. This absolutely would be triggered by `detrend` as the mean is usually 1-e16. And for high-pass filtered signal, the mean is usually 1-e2 - 1-e3, so it get triggers too. I added a warning when this is happening, and also inform users that if the original signal mean is too small, …

Return signals if standardisation was not applied, and change the condition when adding signal mean back for psc method

---

nilearn/_utils/tests/test_niimg_conversions.py
nilearn/_utils/tests/test_numpy_conversions.py
nilearn/plotting/tests/test_js_plotting_utils.py
nilearn/surface/tests/test_surface.py

- Closes #4615 
- Replace tempfile in tests with pytest tmp_path fixture where possible and easy
- simplify imports in nilearn/_utils/tests/test_niimg_conversions.py to avoid importing entire modules

[MAINT] Replace tempfile in tests with proper pytest fixtures

---

doc/changes/latest.rst
nilearn/_utils/testing.py
nilearn/_utils/tests/test_testing.py
nilearn/connectome/tests/test_connectivity_matrices.py
nilearn/datasets/tests/test_func.py
nilearn/glm/tests/test_contrasts.py
nilearn/glm/tests/test_hemodynamic_models.py
nilearn/maskers/tests/test_nifti_labels_masker.py
nilearn/maskers/tests/test_nifti_maps_masker.py
nilearn/maskers/tests/test_nifti_masker.py
nilearn/maskers/tests/test_nifti_spheres_masker.py
nilearn/mass_univariate/tests/test_permuted_least_squares.py
nilearn/plotting/tests/test_html_document.py
nilearn/plotting/tests/test_img_plotting/test_plot_carpet.py

Closes #3625
Old PR: #4596
- Removed `check_deprecation` from `nilearn/nilearn/_utils/testing.py`
- Replaced `pytest.warns(DeprecationWarning, match = pattern)` with `pytest.deprecated_call(match = pattern)` in all test scripts where the former was used.
- Updated change log

[MAINT] Replace `pytest.warns(DeprecationWarning, match = pattern)` with `pytest.deprecated_call(match = pattern)`

---

nilearn/conftest.py
nilearn/decoding/tests/test_decoder.py
nilearn/experimental/conftest.py

- Closes #4626 
- test if screening percentile is adjusted properly during decoding, enforcing following behavior
- if mask size is smaller than screening percentile wrt to the mesh size, use whole mask
- if mask size is greater than screening percentile wrt to the mesh size, adjust the screening percentile for that mask size

Test for screening adjustment

---

CITATION.cff
doc/changes/latest.rst
nilearn/glm/contrasts.py
nilearn/glm/second_level/second_level.py
nilearn/glm/thresholding.py

Completes the following tasks from https://github.com/nilearn/nilearn/issues/3865:
Added missing default values in docstrings of the following files: 
[nilearn/glm/thresholding.py::cluster_level_inference - line: 112](https://github.com/nilearn/nilearn/blob/main/nilearn/glm/thresholding.py#L112)
[nilearn/glm/thresholding.py::threshold_stats_img - line: 190](https://github.com/nilearn/nilearn/blob/main/nilearn/glm/thresholding.py#L190)
[nilearn/glm/contrasts.py::compute_contrast - line: 54](https://github.com/nilearn/nilearn/blob/main/nilearn/glm/contrasts.py#L54)
[nilearn/glm/contrasts.py::compute_fixed_effect_contrast - line: 146](https://github.com/nilearn/nilearn/blob/main/nilearn/glm/contrasts.py#L146)
[nilearn/glm/contrasts.py::compute_fixed_effects - line: …

[DOC] Add missing default values to the docstrings in 'nilearn/glm' - part 1

---

nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

- Closes #4588
- Warn if `smoothing_FHWM` is not `None` for first-level GLM with surface data
- Adds test to check that warning is correctly raised and flm fitting proceeds correctly

[FIX] Warn if smoothing_fwhm parameter passed to FLM for surface data

---

nilearn/datasets/_utils.py
nilearn/datasets/atlas.py
nilearn/datasets/func.py
nilearn/datasets/neurovault.py
nilearn/datasets/tests/test_atlas.py
nilearn/datasets/tests/test_func.py
nilearn/datasets/tests/test_mocking_autoused.py
nilearn/datasets/tests/test_neurovault.py
nilearn/datasets/tests/test_testing.py
nilearn/datasets/tests/test_utils.py
nilearn/datasets/utils.py
pyproject.toml

- Closes  none but relates to #4327 
fixes errors remaining in `nilearn/datasets` package:
- PTH 101: https://docs.astral.sh/ruff/rules/os-chmod/
- PTH 102: https://docs.astral.sh/ruff/rules/os-mkdir/
- PTH 107: https://docs.astral.sh/ruff/rules/os-remove/
- PTH 110: https://docs.astral.sh/ruff/rules/os-path-exists/
- PTH 111: https://docs.astral.sh/ruff/rules/os-path-expanduser/
- PTH 113: https://docs.astral.sh/ruff/rules/os-path-isfile/
- PTH 201: https://docs.astral.sh/ruff/rules/path-constructor-current-directory/

[FIX] Fix several errors (PTH101, PTH102, PTH107, PTH110, PTH111, PTH113, PTH201) in `nilearn.datasets` package

---

examples/07_advanced/plot_beta_series.py

- Closes none but fixes doc build fail on main
- scaling_axis was removed in https://github.com/nilearn/nilearn/pull/4517 as it was deprecated but not from the example

[FIX] do not use scaling_axis in example

---

nilearn/datasets/_utils.py
nilearn/datasets/tests/_testing.py
nilearn/datasets/tests/test_utils.py

- Closes #4697
- Use `request_mocker` so that the test actually works
- Deleted `local_file` (always `None`) and use actual filename instead
- Make exception catching more specific
- Some improvements in other tests, especially regarding to the use of context managers and `pathlib.Path`'s `read_text` and `write_text` methods

[FIX] Fix bug in `fetch_single_file` with `resume=True` and improve tests

---

nilearn/_utils/helpers.py
nilearn/_utils/testing.py
nilearn/_utils/tests/test_common.py
nilearn/interfaces/tests/test_bids.py
nilearn/plotting/__init__.py
nilearn/plotting/tests/test_matplotlib_backend.py
nilearn/reporting/__init__.py
nilearn/reporting/tests/test_glm_reporter.py
nilearn/reporting/tests/test_reporting.py
nilearn/tests/test_package_import.py

- Closes #4702.
- tests in `nilearn.plotting` and `nilearn.reporting` are still ignored by `conftest.py` 
- removed all `@pytest.mark.skipif(not is_matplotlib_installed(), ...` lines  from `nilearn.plotting` and `nilearn.reporting` tests, as these tests are already ignored by `conftest.py` (considering [your answer](https://github.com/nilearn/nilearn/issues/4702#issuecomment-2456859036) on reporting @Remi-Gau  to be able to work without matplotlib in the future, I am not sure about this part, and I can revert it. However for the moment I see these marks misleading)
- moved `_set_mpl_backend` to `nilearn._utils.helpers` so that it can be imported from any package
- added tests to see if the exception and warning are raised when matplotlib is not installed while importing from …

[MAINT] remove dependency on matplotlib to filter packages to be tested

---

.github/workflows/build-docs.yml

Hi! I'm Joyce from Google's Open Source Security Team([GOSST](https://opensource.googleblog.com/2023/04/googles-open-source-security-upstream-team-one-year-later.html)) and I'm here to suggest this small fix to prevent from script injection attacks through the GitHub workflows.
- parse `github.event.head_commit.message` to an envvar before using it to protect from script injection.
You can see further explanation about this kind of threat in this blogpost [Keeping your GitHub Actions and workflows secure Part 2: Untrusted input](https://securitylab.github.com/resources/github-actions-untrusted-input/).
Let me know if you have any questions!

[FIX] GitHub workflow script injection

---

nilearn/datasets/__init__.py

Deprecated function `fetch_openneuro_dataset_index` was removed in 6a7a807.
- See #3216 and #4517.

[MAINT] Undefined name in `__all__`

---

nilearn/datasets/neurovault.py
nilearn/image/tests/test_image.py
nilearn/plotting/tests/test_img_plotting/test_img_plotting.py

A comparison with a callable may suggest you have forgotten to actually call the function or method. If you intended to check if both of these callables are the same, it's recommended to use the `is` operator for comparison.

[STY] Comparison with callable

---

nilearn/plotting/displays/_figures.py

The boolean expression contains an unneeded negation and can be re-written without using the `not` statement.

[STY] Use of an unneeded `not`

---

nilearn/datasets/neurovault.py

From https://docs.python.org/3/library/constants.html#NotImplemented
> When a binary (or in-place) method returns `NotImplemented` the interpreter will try the reflected operation on the other type (or some other fallback, depending on the operator). If all attempts return `NotImplemented`, the interpreter will raise an appropriate exception.

[MAINT] Special method should return `NotImplemented`

---

nilearn/maskers/surface_labels_masker.py
nilearn/maskers/tests/test_surface_labels_masker.py

- Closes #4762
- use concatenation of a list of surface images and then do the masking
- allow inverse_transform method to work with 2D extracted region signals

[ENH] Allow SurfaceLabelsMasker to work with a list of Surface images

---

pyproject.toml

Also disable deprecated and problematic rules.
Addresses part of #4739.

[MAINT] Disable ruff rules conflicting with the formatter

---

doc/Makefile
nilearn/datasets/func.py

- Closes none
- fixes warning in doc build:
```
/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/numpydoc/docscrape.py:421: UserWarning: Unknown section Legacy Output in the docstring of fetch_language_localizer_demo_dataset in /home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/nilearn/datasets/func.py.
```
- https://github.com/nilearn/nilearn/actions/runs/11972529499/job/33379897556?pr=4780#step:13:4592
- refactor makefile to create nojekyll file (only needed when deploying to github pages)

[DOC] fix doc string to remove warning in doc build

---

.github/workflows/README.md
.github/workflows/build-docs.yml
.github/workflows/test_with_tox.yml
CONTRIBUTING.rst

- Closes https://github.com/nilearn/nilearn/issues/4669
- add jobs in doc and test CI workflows to skip doc or test workflows in CI by adding
`[skip doc]` and respectively `[skip test]`

[MAINT] allow possiblity to skip doc build or test in CI via specific commit message

---

nilearn/signal.py
nilearn/tests/test_signal.py

- Closes #4803
- allow t_r, high_pass, low_pass to be int in signal.clean

[FIX] allow t_r, high_pass, low_pass to be int in signal.clean

---

examples/07_advanced/plot_beta_series.py
examples/07_advanced/plot_bids_analysis.py
examples/07_advanced/plot_surface_bids_analysis.py
nilearn/glm/first_level/first_level.py
nilearn/interfaces/bids/query.py
nilearn/interfaces/tests/test_bids.py

- relates to #4801 
- allow query_bids to not return filename containing `entity` when passed filter contain `entityname = ""`
- add test
- adapt first level from bids
- adapt example

[ENH] allow to ignore certain BIDS entities when using query_bids

---

examples/02_decoding/plot_miyawaki_encoding.py
nilearn/_utils/cache_mixin.py
nilearn/_utils/testing.py

- Closes none
Apply the following rules from sourcery
https://docs.sourcery.ai/Coding-Assistant/Reference/Rules-and-In-Line-Suggestions/Python/Default-Rules/
- replace-interpolation-with-fstring 
- use-fstring-for-concatenation     
- use-fstring-for-formatting         
sourcery config used
```yaml
---
version: '1'  # The schema version of this config file
ignore: # A list of paths or files which Sourcery will ignore.
-   .env
-   .git
-   .venv
-   .tox
-   env
-   node_modules
-   vendor
-   venv
-   nilearn/_version.py
-   externals/
-   nilearn/externals/tempita/
-   nilearn/externals/tempita/__init__.py
-   plotting/data/js/*.js
rule_settings:
enable:
-   default
disable: 
-   assign-if-exp
-   assignment-operator 
-   aug-assign
- …
```

[REF] apply use-fstring suggested by sourcery

---

doc/Makefile

- Closes none but tries to fix the release docs workflow
We get a permission denied error when we try to clone the `nilearn.github.io` repo in `_build/nilearn.github.io`. 
- ~I think it's because `_build` directory does not yet exists, so create a `_build` dir first~
- it seems `git clone` can handle making a new directory if the specified cloning path does not exist. Now I think this happens because we are trying to do things in `.` and we might not have permissions to create directory there. So now we do everything in `~/`

[FIX] release_docs workflow

---

doc/conf.py

- Closes none
- use the monokai theme for rendering code in dark mode (higher contrast, comments more visible, better people with suboptimal vision)

[DOC] use higher contrast pygment style for dark mode

---

nilearn/decoding/space_net.py
nilearn/decomposition/_base.py
nilearn/decomposition/_multi_pca.py
nilearn/decomposition/canica.py
nilearn/decomposition/dict_learning.py
nilearn/decomposition/tests/test_base.py
nilearn/decomposition/tests/test_canica.py
nilearn/decomposition/tests/test_dict_learning.py
nilearn/decomposition/tests/test_multi_pca.py

- Closes none but relates to https://github.com/nilearn/nilearn/issues/4538#issuecomment-2527259857
- check compatibility of estimators in nilearn.decomposition with scikitlearn
- update constructors to avoid doing any logic in it: all checks are done at fit time

[MAINT] check constructors compatibility with scikitlearn in nilearn.decomposition

---

.github/workflows/test_with_tox.yml

- fail early on tests runs
- if one of the OS / python version fails then all the other ones are cancelled (whether queued or in progress)
- pros: speed things up by vacating resources for other CI jobs (which we currently need)
- cons: things may fail for only a specific OS or python version and this may hide it

[MAINT] Fail fast for test matrix

---

doc/changes/latest.rst
nilearn/_utils/glm.py
nilearn/glm/first_level/first_level.py
nilearn/glm/tests/test_first_level.py

- Closes #4893
- add test to check that numpy array confounds are used in model
- adapt code to make test pass

[FIX] allow support for confounds as numpy arrays in FirstLevelModel

---

.github/workflows/build-docs.yml

Closes none
Add a check in the doc build workflow and only run the linkcheck if we are doing a html-strict build (so on main or when requested on PR).

[MAINT] only run link checks on full build of the doc

---

doc/visual_testing/reporter_visual_inspection_suite.py
examples/07_advanced/plot_beta_series.py
maint_tools/check_gha_workflow.py
maint_tools/citation_cff_maint.py
nilearn/_utils/tests/test_exceptions.py
nilearn/datasets/tests/_testing.py
nilearn/datasets/tests/test_neurovault.py
nilearn/glm/second_level/second_level.py
nilearn/glm/tests/test_first_level.py
nilearn/interfaces/fmriprep/tests/test_load_confounds.py
nilearn/maskers/surface_labels_masker.py

- [E203](https://docs.astral.sh/ruff/rules/whitespace-before-punctuation/)
- [C420](https://docs.astral.sh/ruff/rules/unnecessary-dict-comprehension-for-iterable/)
- [FURB118](https://docs.astral.sh/ruff/rules/reimplemented-operator/)
- [FURB156](https://docs.astral.sh/ruff/rules/hardcoded-string-charset/)
- [RUF036](https://docs.astral.sh/ruff/rules/none-not-at-end-of-union/)
- [RUF039](https://docs.astral.sh/ruff/rules/unraw-re-pattern/)

[STY] Apply assorted ruff preview rules

---

doc/themes/custom.css

Remove code block wrapping in doc
- the solution to long line is not to wrap them but to break them in smaller chunks 
- code block wrapping kicks in on most narrow device making the code much harder to read.
- Closes #4972

[STY] remove code block wrapping

---

doc/index.rst
doc/versions.rst

- Closes none
- add a page to link to older versions of the doc similar to what can be found in sklearn doc: https://scikit-learn.org/dev/versions.html
- I had to to do some git archeology to dig out old versions of the doc and put them in separate folder in the doc repo: https://github.com/nilearn/nilearn.github.io
-

[DOC] add page for older doc versions

---

.github/workflows/build-docs.yml

Closes none but should fix deploy of dev doc on main:
see failure: https://github.com/nilearn/nilearn/actions/runs/12545676635/job/34984186478#step:6:150
```
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
```

[FIX] set git username / mail for dev doc deploy

---

doc/visual_testing/reporter_visual_inspection_suite.py
nilearn/datasets/atlas.py
nilearn/datasets/tests/test_atlas.py

- Closes none but should fix doc build
- make Schaeffer atlas labels are a list of strings
- update script to generate masker report to avoid errors

[FIX] Convert Schaeffer atlas labels to list of strings

---

nilearn/image/image.py
nilearn/image/resampling.py
pyproject.toml

- Closes none but relates to #4797 
- fix B028 ruff error in nilearn.image
-

[STY] add mising stacklevel in warnings in in nilearn.image

---

nilearn/maskers/nifti_masker.py
nilearn/plotting/displays/_axes.py
nilearn/plotting/html_connectome.py
nilearn/plotting/html_stat_map.py
nilearn/plotting/html_surface.py
nilearn/plotting/img_plotting.py
nilearn/plotting/matrix_plotting.py
nilearn/plotting/surf_plotting.py

- Closes none
- update some colormaps forgotten in #4959
- update doc strings that still used the old default

[DOC] update colormaps and doc strings

---

build_tools/github/deploy_doc.sh

- Closes none
- Doc build of of the doc on release should have clear identifiable commit message.
Currently they look like those of the dev build: 
`stable docs https://github.com/nilearn/nilearn/commit/ : [MISC] update doc strings types (#5023)`
See https://github.com/nilearn/nilearn.github.io/commit/ceab1acb6c749b5b6e999610b725e90b4743e668
-

[MAINT] use tag for commit message of release

---

nilearn/maskers/surface_labels_masker.py
nilearn/maskers/surface_masker.py
nilearn/reporting/data/html/report_body_template_surfacemasker.html
nilearn/reporting/tests/test_html_report.py

- Closes None but related to point 3 in https://github.com/nilearn/nilearn/pull/4968#issuecomment-2594970907 
- use `figure_to_png_base64` instead of `figure_to_svg_base64`
- update report template accordingly

[ENH] Plot PNG instead of SVG in surface masker reports

---

maint_tools/check_docstrings.py
maint_tools/utils.py
nilearn/interfaces/fmriprep/load_confounds_utils.py
nilearn/masking.py

- Closes none
- `maint_tools/utils.list_modules` ignores all modules if a parent directory above the repository root matches a folder to skip. For example if my Nilearn repo is at `/data/nilearn`, then the `check_docstrings.py` script doesn't work. Updated to only check parent directories within the `nilearn` root repo
- I noticed that [`nilearn.masking.load_mask_img`](https://github.com/nilearn/nilearn/blob/d52c31f79a74219aa38477fde267f4fd25600ce8/nilearn/masking.py#L43-L65) is decorated with `fill_doc` but does not have any `%(` substring inside it. Somehow that wasn't caught by `check_fill_doc_decorator`, so I updated it to catch that too
- Removed 2 instances of unneeded `fill_doc`

[MAINT] Fix `check_docstrings` not checking any files and not catching unneeded `fill_doc`

---

tox.ini

- Closes #5080
- Apparently Kaleido stopped shipping with chromium as suggested in https://github.com/plotly/Kaleido/issues/223#issuecomment-2483824967
- fix is to pin it to 0.2.1 Kaleido

[FIX] Pin Kaleido to 0.2.1

---

doc/visual_testing/reporter_visual_inspection_suite.py

- Closes none
- fix typo that cause crash of doc build on main

[FIX] fix typo that prevents doc build on main

---

.github/workflows/build-docs.yml
.github/workflows/linkcheck.yml
doc/conf.py

- Closes none
- extract linkcheck from doc build and run it as a separate workflow on main only 
- skip linkcheck for DOIs as they can be quite flaky

[MAINT] run linkcheck only on main

---

nilearn/_utils/class_inspect.py
nilearn/maskers/tests/test_multi_nifti_labels_masker.py
nilearn/maskers/tests/test_multi_nifti_maps_masker.py
nilearn/maskers/tests/test_multi_nifti_masker.py
nilearn/maskers/tests/test_nifti_masker.py

- Closes none but relates to #5095 
- add test to check that nifti maskers cannot transform 5D but that multi niftimasker can

[REF] refactor test to check 5D input to nifti masker transform

---

examples/01_plotting/plot_demo_more_plotting.py
examples/01_plotting/plot_demo_plotting.py
examples/06_manipulating_images/plot_threshold_image.py
nilearn/plotting/img_plotting.py

- Closes #5106 
- Modify notebook [examples/01_plotting/plot_demo_plotting.py](https://github.com/nilearn/nilearn/blob/main/examples/01_plotting/plot_demo_plotting.py) to add examples on usage of `threshold`, `vmin` and `vmax` for image plotting.
- Modify notebook [examples/01_plotting/plot_demo_more_plotting.py](https://github.com/nilearn/nilearn/blob/main/examples/01_plotting/plot_demo_more_plotting.py) reorganize headings and heading levels.
- Move colorbar example from [examples/01_plotting/plot_demo_more_plotting.py](https://github.com/nilearn/nilearn/blob/main/examples/01_plotting/plot_demo_more_plotting.py) to  [examples/01_plotting/plot_demo_more_plotting.py](https://github.com/nilearn/nilearn/blob/main/examples/01_plotting/plot_demo_more_plot …

[ENH] Add  thresholding examples

---

examples/01_plotting/plot_demo_plotting.py
nilearn/typing.py

- Closes none but fixes doc build crash on main
- expand accepted numeric types for common parameters to accept numpy.floating and numpy.integer where appropriate
Should avoid error due to 
```python
>>> import numpy as np
>>> a = np.int32(1)
>>> isinstance(a, int)
False
```

[ENH] allow numpy equivalent to int and float for several common parameters

---

doc/visual_testing/reporter_visual_inspection_suite.py
examples/04_glm_first_level/plot_two_runs_model.py
nilearn/datasets/description/fiac.rst
nilearn/datasets/func.py
nilearn/datasets/tests/test_func.py

- Closes #2400
- Relates to #4218
- improve doc FIAC dataset
- return design matrices as dataframes with proper column names
- update examples that use this dataset

[FIX] return design matrices of FIAC as dataframes

---

examples/06_manipulating_images/plot_resample_to_template.py

- Closes none
- make it easier to compare images before and after resampling to avoid
Note I find it a tad strange that a resampled image would lead to an image with a higher maximum (unless there is another reason that the max of the colorbar was changed).

[ENH] add vmax to example plot_resample_to_template.py

---

.binder/postBuild

This fixes Binder link similarly to https://github.com/scikit-learn/scikit-learn/pull/30697 and https://github.com/scikit-learn/scikit-learn/pull/30835. Recently Binder is expected to be more reliable, see https://github.com/scikit-learn/scikit-learn/pull/30697#issuecomment-2659881848 for more details.
Fix https://github.com/nilearn/nilearn/issues/4953
Current broken link from [dev doc example](https://nilearn.github.io/dev/auto_examples/07_advanced/plot_mask_large_fmri.html#sphx-glr-download-auto-examples-07-advanced-plot-mask-large-fmri-py):
https://mybinder.org/v2/gh/nilearn/nilearn/main?urlpath=lab/tree/notebooks/auto_examples/07_advanced/plot_mask_large_fmri.ipynb
Test it on my PR branch:
https://mybinder.org/v2/gh/lesteve/nilearn/fix-binder?urlpath=lab/tree/notebooks/auto_examples/07 …

DOC Fix binder notebook generation

---

nilearn/glm/tests/test_first_level.py
nilearn/interfaces/tests/test_bids.py
nilearn/mass_univariate/tests/test_permuted_least_squares.py
nilearn/regions/tests/test_region_extractor.py
pyproject.toml

Still some tests that sometimes fail in CI for being too slow, so I am upping the timeout to 60 seconds globally.

[MAINT] up timeout of test

---

nilearn/glm/tests/test_first_level.py
nilearn/glm/tests/test_second_level.py
nilearn/interfaces/tests/test_bids.py

- Closes none
- use same variable name for `write_fake_fmri_data_and_design` and `generate_fake_fmri_data_and_design`
- try to make clearer in the tests when we are dealing with files or in memory objects

[MAINT] use same variable name for `write_fake_fmri_data_and_design` and `generate_fake_fmri_data_and_design`

---

CITATION.cff
doc/changes/latest.rst
nilearn/_utils/docs.py
nilearn/mass_univariate/_utils.py
nilearn/mass_univariate/tests/test_utils.py

- Closes #5178 
- Changed the floating-point upper bound value of an `np.arange` call so that the range terminates with the correct value.

[FIX] prevent range overrun

---

.github/workflows/linkcheck.yml
.github/workflows/sourcery.yml
.sourcery.yaml

- Closes none
- run checklink and sourcery checks on upstream only
- tweak sourcery config to avoid ignore some folders

[MAINT] only run some workflows on upstream

---

nilearn/surface/surface.py

- Closes none but follow up on #5169
- add a version changed directive under 'nearest' interpolation method to say that it will be deprecated in 0.13.0
-

[DOC] Add future deprecation directive for 'nearest' interpolation in `vol_to_surf`

---

doc/get_data_examples.py
examples/00_tutorials/plot_3d_and_4d_niimg.py
examples/01_plotting/plot_demo_glass_brain_extensive.py
nilearn/datasets/func.py
nilearn/datasets/neurovault.py
nilearn/datasets/tests/test_neurovault.py

- Closes none
- fetch_neurovault_motor_task is always used to fetch data from neurovault to load the same single image we ship with nilearn anyway
- should prevent some doc build failure when neurovault does not work (see doc build on main at the moment)

[MAINT] start deprecation of fetch_neurovault_motor_task

---

doc/changes/latest.rst
nilearn/image/image.py
nilearn/image/tests/test_image.py
nilearn/masking.py
nilearn/signal.py
nilearn/tests/test_masking.py

- Closes #5275
- add support for SurfaceImage input to 
- nilearn.image.high_variance_confounds
- nilearn.masking.apply_mask

[ENH] add surface suport to nilearn.image.high_variance_confounds

---

nilearn/_utils/exceptions.py
nilearn/_utils/tests/test_common.py
nilearn/glm/second_level/second_level.py
nilearn/image/image.py
nilearn/maskers/surface_labels_masker.py
nilearn/maskers/surface_maps_masker.py
nilearn/maskers/surface_masker.py
nilearn/maskers/tests/test_surface_masker.py
nilearn/masking.py
nilearn/plotting/img_comparison.py
nilearn/plotting/surface/_utils.py
nilearn/plotting/surface/tests/test_surf_plotting.py
nilearn/surface/utils.py

- Closes #5303
- check if meshes are equal in most cases and fall back to checking if they have the same number of vertices if that fails

[FIX] throw warning when meshes are unequal but have compatible number of vertices

---

nilearn/_utils/docs.py
nilearn/_utils/estimator_checks.py
nilearn/maskers/base_masker.py
nilearn/maskers/multi_nifti_labels_masker.py
nilearn/maskers/multi_nifti_maps_masker.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py
nilearn/maskers/surface_labels_masker.py
nilearn/maskers/surface_maps_masker.py
nilearn/maskers/surface_masker.py
nilearn/maskers/tests/test_multi_nifti_labels_masker.py
nilearn/maskers/tests/test_multi_nifti_maps_masker.py
nilearn/maskers/tests/test_surface_labels_masker.py
nilearn/maskers/tests/test_surface_maps_masker.py
nilearn/signal.py

- Closes none
- use single doc strings for confounds and sample_mask for maskers methods
- add estimator checks 'tests' for maskers to transform iamges using sample_mask and confounds

[REF] refactor doc strings for sample_mask and confounds for maskers

---

examples/07_advanced/plot_mask_large_fmri.py

- Closes none but tries to fix the broken doc build on main
- I think the issue is due to oversubscription of threads
- I am using N_REGIONS=6, so masking 6 regions in parallel
- changing to 4 as github ci runner only has 4 threads

[FIX] plot_mask_large_fmri.py oversubscribing threads

---

nilearn/glm/first_level/first_level.py
nilearn/reporting/glm_reporter.py
nilearn/reporting/tests/test_glm_reporter.py

- Closes none
- fixes minor bug that would prevent the generation of GLM report when no contrast was passed

[FIX] allow generation of glm report with no contrasts

---

.github/workflows/benchmark.yml

- right now, older commits can't be seen on https://nilearn.github.io/benchmarks
- this is because `asv publish` can't find those commits in the nilearn git history: https://github.com/nilearn/nilearn/actions/runs/14471245839/job/40585467668#step:10:17
- so we fetch full nilearn history with `actions/checkout`
- this allows `asv publish` to find older commits to display in the HTML pages
- fetch full nilearn history with `actions/checkout`

[FIX] fetch full history to append new results to older results

---

nilearn/_utils/estimator_checks.py
nilearn/connectome/connectivity_matrices.py
nilearn/connectome/group_sparse_cov.py
nilearn/connectome/tests/test_connectivity_matrices.py
nilearn/connectome/tests/test_group_sparse_cov.py
nilearn/decomposition/_base.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py
nilearn/maskers/surface_labels_masker.py
nilearn/maskers/surface_maps_masker.py
nilearn/maskers/surface_masker.py
nilearn/regions/hierarchical_kmeans_clustering.py
nilearn/regions/region_extractor.py
nilearn/regions/rena_clustering.py

- Closes none but relates to https://github.com/nilearn/nilearn/issues/4538
- add estimator check to make all our estimators have a y parameter for fit() and fit_transform()

[ENH] ensure estimators have a y parameter

---

examples/07_advanced/plot_surface_image_and_maskers.py

- Closes none
- update one of the examples to use one of the new public property instead of one the old private attributes (that has been removed)

[FIX] use property region_names_ in surface label examples

---

.github/workflows/benchmark.yml

- Closes None but fixes the failing benchmark workflow on schedule: https://github.com/nilearn/nilearn/actions/runs/14825724575/job/41618562617#step:9:1851
- The error code suggests it's a timeout error in setup_cache step
- We download a dataset in that step
- So my guess is that downloading the dataset jus tfails for some reason on Sunday 10pm UTC
- changing to every Monday at 9am UTC (should run at 11am Paris time)

[FIX] Failing benchmark workflow on schedule

---

.github/workflows/testing_minimum.yml
nilearn/_utils/estimator_checks.py

- Closes #5373 
- only rely on __sklearn_tags__ to get tags of an estimator

[FIX] rely in `__sklearn_tags__` for sklearn > 1.5.2  and `on _more_tags` otherwise

---

nilearn/_utils/docs.py
nilearn/connectome/connectivity_matrices.py
nilearn/connectome/group_sparse_cov.py
nilearn/decomposition/_base.py
nilearn/interfaces/bids/glm.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/surface_labels_masker.py
nilearn/maskers/surface_maps_masker.py
nilearn/maskers/surface_masker.py
nilearn/regions/hierarchical_kmeans_clustering.py
nilearn/regions/region_extractor.py
nilearn/regions/rena_clustering.py

- Closes none
- use a template doc strings for estimator methods that do not use their y parameter

[DOC] use template doc string for dummy y

---

nilearn/plotting/_utils.py
nilearn/plotting/surface/_backend.py
nilearn/plotting/surface/_matplotlib_backend.py
nilearn/plotting/surface/_plotly_backend.py
nilearn/plotting/surface/surf_plotting.py
nilearn/plotting/surface/tests/test_backend.py
nilearn/plotting/surface/tests/test_matplotlib_backend.py
nilearn/plotting/surface/tests/test_surf_plotting.py

- Closes None, but relates to:
- #5234 
- #5253 
- #5276
- #5282 
- #5322
- #5349
-  Refactor `plotting.surface.surf_plotting.plot_surf_stat_maps` to separate matplotlib code to `_matplotlib_backend` and plotly code to `_plotly_backend` and common parts to `backend`
- Add/update missing docstrings for tests in `test_surf_plotting` for `plot_surf_stat_maps`

[ENH] Refactor to separate backends for plot_surf_stat_map

---

doc/changes/latest.rst
doc/manipulating_images/manipulating_images.rst
doc/manipulating_images/masker_objects.rst
nilearn/_utils/docs.py
nilearn/_utils/estimator_checks.py
nilearn/conftest.py
nilearn/decomposition/_base.py
nilearn/maskers/base_masker.py
nilearn/maskers/multi_nifti_labels_masker.py
nilearn/maskers/multi_nifti_maps_masker.py
nilearn/maskers/multi_nifti_masker.py
nilearn/maskers/nifti_labels_masker.py
nilearn/maskers/nifti_maps_masker.py
nilearn/maskers/nifti_masker.py
nilearn/maskers/nifti_spheres_masker.py
nilearn/maskers/surface_labels_masker.py
nilearn/maskers/surface_maps_masker.py
nilearn/maskers/surface_masker.py
nilearn/maskers/tests/test_nifti_labels_masker.py
nilearn/maskers/tests/test_nifti_maps_masker.py
nilearn/maskers/tests/test_nifti_masker.py
nilearn/maskers/tests/test_nifti_spheres_masker.py
nilearn/maskers/tests/test_surface_labels_masker.py
nilearn/maskers/tests/test_surface_maps_masker.py
nilearn/maskers/tests/test_surface_masker.py
nilearn/surface/utils.py

- relates to https://github.com/nilearn/nilearn/issues/5380
- relates to #3322 
Ensure the following
for nifti maskers
- transform of 3D images returns 1D arrays
- transform of 4D images returns 2D arrays
- inverse_transform of 1D arrays return 3D images
- inverse_transform of 2D arrays return 4D images
- check_arrays before inverse transform
for surface maskers
- transform of 1D images returns 1D arrays
- transform of 2D images returns 2D arrays
- inverse_transform of 1D arrays return 1D images
- inverse_transform of 2D arrays return 2D images
- check_arrays before inverse transform
Move and refactor tests and integrate them in estimat_check
---
TODO:

[MAINT] ensure transform on 3D volume (1D surface) images returns 1D arrays

---

examples/04_glm_first_level/plot_two_runs_model.py
nilearn/glm/contrasts.py
nilearn/glm/tests/test_first_level.py

- Closes none
- return z score image when computing fixed effects as this will be the new default in 0.13

[MAINT] avoid extra warning when computing fixed effects

---

nilearn/signal.py

- Closes **None**
- Fix incorrect `dtype.itemsize` check in `_ensure_float`, which should be a number instead of string.

[FIX] incorrect `dtype.itemsize check` in `_ensure_float`

---

nilearn/_utils/tests/test_common.py
nilearn/plotting/surface/_matplotlib_backend.py
nilearn/plotting/surface/_plotly_backend.py
nilearn/plotting/surface/_utils.py
nilearn/plotting/surface/html_surface.py
nilearn/plotting/surface/surf_plotting.py
nilearn/plotting/surface/tests/test_html_surface.py
nilearn/plotting/surface/tests/test_matplotlib_backend.py
nilearn/plotting/surface/tests/test_surf_plotting.py
nilearn/plotting/surface/tests/test_utils.py

- Closes None, but relates to:
- #5234 
- #5253 
- #5276
- #5282 
- #5322
- #5349
- #5389
- #5391
- #5401 
- #5407 
-  Refactor `plotting.surface.html_surface` to extract `get_vertexcolor` function that uses matplotlib and move it to `_matplotlib_backend`
- Move tests accordingly
This is the final PR that refactors `nilearn.plotting.surface` package to separate `matplotlib` and `plotly` code to backend modules.

[ENH] Refactor `nilearn.plotting.surface.html_surface` to separate backend

---

doc/changes/latest.rst
nilearn/mass_univariate/tests/test_permuted_least_squares.py
nilearn/plotting/js_plotting_utils.py
nilearn/plotting/tests/test_js_plotting_utils.py

- Closes #4296 
- Do not change value of `symmetric_cmap`  inside `nilearn.plotting.js_plotting_utils.colorscale` function depending on the values of the specified data.
- Let user set `vmin` even if `symmetric_cmap` is specified to be `True`.
- Remove `symmetric_cmap` from the dictionary returned from `nilearn.plotting.js_plotting_utils.colorscale`.

[FIX] Align `symmetric_cmap` behavior in plotting package for `plotly` backend with `matplotlib` backend

---

nilearn/_utils/estimator_checks.py
nilearn/_utils/tests/test_estimator_checks.py
nilearn/regions/region_extractor.py

- Relates to #5444, #5446, #5445
- run check_img_estimator_dict_unchanged on all image estimators with a transform methods

[MAINT] check all image estimators are unchanged by transform

---

nilearn/datasets/neurovault.py

- Closes #5522
- Update deprecation warning for `nilearn.datasets.fetch_neurovault_motor_task` as the data type returned is different from `load_sample_motor_activation_image`.

[FIX] Update deprecation warning for `nilearn.datasets.fetch_neurovault_motor_task`

---

.pre-commit-config.yaml

Changes:
```
ruff (legacy alias)......................................................Passed
```
into:
```
ruff check...............................................................Passed
```

[MAINT] Update pre-commit ruff legacy alias

---

pyproject.toml

- Closes #5548
- ignore version of setuptools-scm that does not play well with hatcling-vcs

[FIX] do not use setuptools-scm 9... for now

---

LICENSE
pyproject.toml

- Declare licenses using only these two fields, as per PEP 639:
* `license`: SPDX license expression consisting of one or more license identifiers
* `license-files`: list of license file glob patterns
Supported by hatchling ≥ 1.27.0:
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files

[MAINT] PEP 639 compliance

---

nilearn/_utils/estimator_checks.py
nilearn/_utils/masker_validation.py
nilearn/decoding/decoder.py
nilearn/decoding/searchlight.py
nilearn/decoding/space_net.py
nilearn/decoding/tests/test_decoder.py
nilearn/glm/tests/test_first_level.py
nilearn/glm/tests/test_second_level.py
nilearn/image/tests/test_image.py
nilearn/plotting/tests/test_img_comparisons.py

- Closes none
- make sure all decoders are tested on surface images
- check that decoders that can work both with volume and surface data check compatibility of input images with their mask (for example to also avoid trying to get score from surface data when the model was fitted on volume)

[FIX] check all decoders can work with surfaces

---

doc/changes/latest.rst
nilearn/_utils/estimator_checks.py
nilearn/decoding/searchlight.py
nilearn/decomposition/_base.py
nilearn/decomposition/tests/test_decomposition_estimators.py

- Relatest to https://github.com/nilearn/nilearn/issues/5444
- make sure all image estimators take a y for methods: transform, fit_transform, score

[FIX] ensure fit and transform takes a y parameter

---

doc/changes/latest.rst
nilearn/image/image.py

- Relates to #5619 
- Ends deprecation cycle started in : https://github.com/nilearn/nilearn/pull/4121
- change default of `two_sided` for `binarize_img` changed to False

[DEP] change default of `two_sided` for `binarize_img` changed to False
