- nilearn/datasets.py
> Adding info to fetch_haxby dataset fetcher

- nilearn/_utils/niimg_conversions.py
- nilearn/image/__init__.py
- nilearn/image/tests/test_image.py
- nilearn/tests/test_niimg_conversions.py
> added concat_img() in nilearn.image

- nilearn/datasets.py
Addresses #350, and does a bit of code & comment cleanup.
Tweaked the function to report download information:
* Pass along `initial_size` - the size of anything that was downloaded previously.
* Use `initial_size` to help compute the `download_rate`, and then the `time_remaining`.
* Remove comments (and code) suggesting that any of the parameters are optional.
**Testing:**
* Tested download from scratch.   Gave a reasonable time remaining.
* Tested resuming download at various stages of download.  Gave a reasonable time remaining.
> Tweak download rate reporting to account for resuming.

- nilearn/_utils/niimg_conversions.py
- nilearn/image/__init__.py
- nilearn/image/image.py
- nilearn/image/tests/test_image.py
- nilearn/tests/test_niimg_conversions.py
> Add functions to slice and iterate over a 4D image

- nilearn/decoding/searchlight.py
- nilearn/decomposition/multi_pca.py
- nilearn/image/image.py
- nilearn/input_data/nifti_masker.py
- nilearn/masking.py
An old branch I never merged, fixing part of the remaining inconsistent docstrings after #294.
> Fix a few Niimg-like related docstrings

- examples/connectivity/plot_canica_resting_state.py
- examples/connectivity/plot_ica_resting_state.py
- examples/decoding/plot_haxby_searchlight.py
- examples/manipulating_visualizing/plot_mask_computation.py
- examples/plot_nifti_simple.py
> switch examples to index/iter_img

- doc/building_blocks/data_preparation.rst
- examples/connectivity/plot_adhd_covariance.py
Reordering of images in the example to change its thumbnail (fix #373).
Ugly sideimages are rewritten on separate lines (fix #372).
> Small documentation fixes

- nilearn/datasets.py
> Fetcher for Harvard-Oxford atlas

- nilearn/datasets.py
Shorten the code of Danilo by considering FSL_DIR as a data read-only repository.
> Optimize fetch ho

- nilearn/_utils/niimg_conversions.py
- nilearn/decomposition/canica.py
- nilearn/decomposition/multi_pca.py
- nilearn/image/image.py
- nilearn/image/resampling.py
- nilearn/image/tests/test_image.py
- nilearn/input_data/base_masker.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/masking.py
- nilearn/plotting/displays.py
- nilearn/plotting/img_plotting.py
- nilearn/tests/test_niimg_conversions.py
> Docstring fixes related to Niimg-like objects

- nilearn/_utils/niimg_conversions.py
- nilearn/input_data/nifti_region.py
- nilearn/input_data/tests/test_nifti_region.py
Tentative fix for #340 
For now, it is only implemented for NiftiLabelsMasker. I will work on NiftiMapsMasker, but I welcome feedback eg from @AlexandreAbraham  and @lesteve
> ENH: resample_data="data" for LabelsMasker

- nilearn/_utils/fixes/matplotlib_backports.py
- nilearn/plotting/displays.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
Adding functionality to make colorbar range from 0 to vmax instead of -vmax to +vmax. Which example should I best illustrate this on? @lesteve
> [ENH + MRG] added symmetric_range kw to plot_stat_map

- nilearn/input_data/nifti_region.py
> (very) small docstring fix

- doc/building_blocks/manipulating_mr_images.rst
- examples/decoding/plot_haxby_different_estimators.py
- examples/decoding/plot_haxby_full_analysis.py
- examples/manipulating_visualizing/plot_roi_extraction.py
> Cosmetics in code and documentation

- nilearn/plotting/img_plotting.py
Removed exception. It was in a private function and didn't make sense.
> FIX exception raised when no cbar, but cbar bounds specified

- nilearn/plotting/displays.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
> [MRG] adding resampling parameter when plotting

- nilearn/plotting/tests/test_img_plotting.py
Adds test cases that run the scenarios where #410 and #409 ran into bugs.
> TST smoke tests for bugfixes for issues 409 and 410

- nilearn/plotting/tests/test_img_plotting.py
A few modifications that save 2 seconds more or less. Not sure if it's worth it.
> Speed up test_plot_functions

- nilearn/input_data/base_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
> [ENH] NiftiMasker: added time mask

- nilearn/input_data/multi_nifti_masker.py
> improve masker docstrings

- continuous_integration/install.sh
> Enable test coverage

- nilearn/_utils/__init__.py
- nilearn/_utils/logger.py
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
try to fix #433 
_utils.logger seemed like the most reasonable place to put this...
> _compose_err_msg() moved to _utils

- .travis.yml
- continuous_integration/install.sh
> Finish up coveralls support

- nilearn/decomposition/multi_pca.py
For #444; tweaks to error message.  Test case exists.
> Update error message info and formatting.

- examples/connectivity/plot_adhd_covariance.py
See #446 for details.  The plotting suggestion is implemented in #441.  
Note: there will be a small whitespace merge conflict between this PR and #441.
> Enhancements to plot_adhd_covariance.py

- nilearn/plotting/displays.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
tries to fix #379 
It's a quick fix for now that handles 0 to positive valued colorbars. Do we want more than that?
> glass_brain: fix colorbar

- nilearn/plotting/tests/test_img_plotting.py
fix #408. The speed-up is achieved mostly by splitting test_plot_functions in separate tests
and thereby reducing the total number of plots done. nosetests test_img_plotting.py take ~30s instead of ~70s on my machine.
> Speed-up plotting tests

- nilearn/datasets.py
- nilearn/tests/test_datasets.py
> Fix bug in environment variable lookup in dataset fetcher

- nilearn/signal.py
Add workaround for scipy < 0.10.0
> Add workaround for scipy < 0.10.0

- nilearn/datasets.py
- nilearn/description/miyawaki.rst
- nilearn/description/smith.rst
> Provide dataset descriptions

- nilearn/plotting/displays.py
- nilearn/plotting/tests/test_img_plotting.py
> connectome-plot-bugfix

- nilearn/input_data/base_masker.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/tests/test_multi_nifti_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
> check_fitted() for 2 maskers

- doc/building_blocks/manual_pipeline.rst
- doc/manipulating_visualizing/manipulating_images.rst
- nilearn/datasets.py
- nilearn/description/ABIDE_pcp.rst
- nilearn/description/adhd.rst
- nilearn/description/brainomics_localizer.rst
- nilearn/description/msdl_atlas.rst
- nilearn/description/oasis1
Episode III: back to the future of data descriptions
> Data descr3

- nilearn/datasets.py
This fix a problem related to old versions of six
> Attempt to fix #499

- nilearn/plotting/displays.py
- nilearn/plotting/tests/test_img_plotting.py
Related to #510
Has the works-on-my-machine certificate, but perhaps makes Travis break?
> regression test for colorbar

- nilearn/input_data/tests/test_nifti_masker.py
- nilearn/signal.py
- nilearn/tests/test_signal.py
Added plenty of tests :)
I written while listening to stupid conf calls...
> Detrend 3d img

- nilearn/signal.py
Just a complement to Gael's PR.
> Add warning message when detreending 3D signal

- doc/manipulating_visualizing/manipulating_images.rst
Add how to print a dataset description to the narrative documentation.
> add description of datasets in doc

- nilearn/group_sparse_covariance.py
reduced verbosity of group sparse covariance. i) The default is 0. ii) the verbosity is decremented when other objects/functions are called.
Adresses #342.
> MRG: Addresses #342

- doc/sphinxext/sphinxgallery/__init__.py
- doc/sphinxext/sphinxgallery/gen_gallery.py
Sphinx gallery has a dev-release on pypi including the patch that fixes the no plot flag issue #554
> Update to sphinxgallery 0.0.9 dev-release to fix bug on no plot flag

- nilearn/_utils/__init__.py
- nilearn/_utils/niimg_conversions.py
- nilearn/image/image.py
- nilearn/input_data/tests/test_base_masker.py
- nilearn/input_data/tests/test_multi_nifti_masker.py
- nilearn/input_data/tests/test_nifti_labels_masker.py
- nilearn/input_data/tests/test_nifti_maps_masker.py
- nilearn/tests/test_masking.py
- nilearn/tests/test_niimg_conversions.py
- nilearn/tests/test_region.py
Supersedes #536.
@banilo: This is still WIP but I have fixed some stuff. You can take over the branch again if you want ;)
> Rely on a common iterator for check_niimg* and concat_niimg.

- nilearn/plotting/displays.py
- nilearn/plotting/img_plotting.py
Added an optional Normalizer to the edge colouring of plotted graphs to be able to modulate edge colors.
> [MRG+1] Added the possibility to use a Normalize class to modulate edge coloring 

- nilearn/plotting/find_cuts.py
- nilearn/plotting/tests/test_find_cuts.py
- nilearn/plotting/tests/test_img_plotting.py
> [MRG+1] Fix issue575

- nilearn/_utils/ndimage.py
- nilearn/masking.py
- nilearn/plotting/img_plotting.py
Very small modifications of code I ran into.
> Clean up some code

- nilearn/input_data/nifti_spheres_masker.py
Added mask_img in NiftiSpheresMasker docstring
> NiftiSpheresMasker Docstring

- nilearn/datasets.py
- nilearn/tests/test_datasets.py
Add a fetcher for cortical atlas Destrieux et al. 2009.
Thanks to @mrahim for doing most of the work!
> Add fetcher for destrieux 2009

- examples/decoding/plot_haxby_different_estimators.py
> typo in different estimator example

- nilearn/datasets.py
- nilearn/tests/test_datasets.py
> Solve ADHD downloader problem.

- nilearn/masking.py
- nilearn/tests/test_masking.py
Fixed bug #622 arising when providing a list of string to `intersect_mask`
> Fixed bug in intersect_mask

- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/tests/test_nifti_labels_masker.py
Review fast, I'd like to a bugfix release
> BUG: filenames in label masker were not working

- doc/introduction.rst
- setup.cfg
Fix #668 
@AlexandreAbraham @lesteve please review
> [MRG] BUG: fix doc tests

- examples/decoding/plot_haxby_searchlight.py
- examples/manipulating_visualizing/plot_roi_extraction.py
Doing the work of @banilo. Because, let's be honest, he's not really reliable. He assigned himself issues and only solve them halfway through. But he's a nice guy.
Fortunately, nobody will read that.
> Use new_img_like where it's possible.

- .travis.yml
- doc/whats_new.rst
- nilearn/decomposition/canica.py
- nilearn/version.py
> Drop sklearn 0.12

- doc/manipulating_visualizing/manipulating_images.rst
Next round of documentation tuning...
> doccheck 3: manipulation

- circle.yml
- examples/plot_nilearn_101.py
It will not catch failing examples until: https://github.com/sphinx-gallery/sphinx-gallery/issues/45 will be fixed.
> Added CircleCI support

- doc/themes/nilearn/layout.html
I fixed the links of the right top corner of the banner in layout.html. Solution for issue #684
This branch only contains the correct commit to solve issue #684. Unlike #686
> [MRG] Broken links correct branch. 

- circle.yml
> Fix dependencies on CircleCI

- nilearn/input_data/nifti_maps_masker.py
> Fix documentation in NiftiMapsMasker.

- .travis.yml
- doc/introduction.rst
As discussed in #668 , we need to run the doctests too on travis.
> [MRG] MAINT: test docs in travis

- nilearn/datasets/tests/test_atlas.py
- nilearn/datasets/tests/test_func.py
- nilearn/datasets/tests/test_struct.py
- nilearn/datasets/utils.py
> PEP8 fixes in datasets/*

- nilearn/datasets/utils.py
> Security guard in file fetching with authentication.

- doc/install_doc_component.html
Only tweak proposed in #701 implemented. Just changed the phrasing of the Neurodebian install in the install documentation.
> [MRG] small tweak to the phrasing and links of Neurodebian install doc

- nilearn/input_data/base_masker.py
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
First step toward code factorization in Nifti*Masker.
> Factorize code in NiftiLabelsMasker and NiftiMapsMasker

- nilearn/image/image.py
- nilearn/image/tests/test_image.py
- nilearn/masking.py
Nothing very complicated, but it should save us memory here and there by keeping the life cycle of temporary data copies as short as possible
> [MRG] Small memory optimizations

- doc/decoding/space_net.rst
- nilearn/decoding/space_net_solvers.py
- nilearn/decoding/tests/test_same_api.py
> [MRG+1] Fixing some minor SpaceNet issues (post-merge era)

- nilearn/datasets/tests/test_atlas.py
- nilearn/datasets/tests/test_func.py
- nilearn/decoding/tests/simulate_graph_net_data.py
- nilearn/decoding/tests/test_fista.py
- nilearn/decoding/tests/test_graph_net.py
- nilearn/decoding/tests/test_same_api.py
- nilearn/decoding/tests/test_searchlight.py
- nilearn/decoding/tests/test_sklearn_compatibility.py
- nilearn/decoding/tests/test_space_net.py
- nilearn/decoding/tests/test_tv.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/input_data/tests/test_base_masker.py
- nilearn/input_data/tests/test_multi_nifti_masker.py
- nilearn/input_data/tests/test_nifti_labels_masker.py
- nilearn/input_data/tests/test_nifti_maps_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
- nilearn/plotting/tests/test_displays.py
- nilearn/plotting/tests/test_edge_detect.py
- nilearn/plotting/tests/test_img_plotting.py
- nilearn/tests/test_cache_mixin.py
- nilearn/tests/test_class_inspect.py
- nilearn/tests/test_extmath.py
- nilearn/tests/test_group_sparse_covariance.py
- nilearn/tests/test_logger.py
- nilearn/tests/test_masking.py
- nilearn/tests/test_niimg.py
- nilearn/tests/test_niimg_conversions.py
- nilearn/tests/test_numpy_conversions.py
- nilearn/tests/test_region.py
- nilearn/tests/test_signal.py
Following Elvis remark: massive PEP8 correction.
> Fix PEP8 in tests

- examples/connectivity/plot_adhd_spheres.py
- examples/connectivity/plot_inverse_covariance_connectome.py
- examples/connectivity/plot_probabilistic_atlas_extraction.py
- examples/connectivity/plot_simulated_connectome.py
- examples/decoding/plot_haxby_anova_svm.py
- examples/decoding/plot_haxby_different_estimators.py
- examples/decoding/plot_haxby_full_analysis.py
- examples/decoding/plot_haxby_grid_search.py
- examples/decoding/plot_haxby_multiclass.py
- examples/decoding/plot_haxby_searchlight.py
- examples/decoding/plot_haxby_space_net.py
- examples/decoding/plot_mixed_gambles_space_net.py
- examples/decoding/plot_oasis_vbm.py
- examples/decoding/plot_oasis_vbm_space_net.py
- examples/decoding/plot_simulated_data.py
- examples/manipulating_visualizing/plot_affine_transformation.py
- examples/manipulating_visualizing/plot_mask_computation.py
- examples/manipulating_visualizing/plot_prob_atlas.py
Nobody is working on existing examples AFAIK so it shouldn't be too much pain.
> [MRG] Run autopep8 in examples

- examples/decoding/plot_haxby_space_net.py
- examples/decoding/plot_mixed_gambles_space_net.py
- nilearn/decoding/objective_functions.py
- nilearn/decoding/proximal_operators.py
- nilearn/decoding/searchlight.py
- nilearn/decoding/space_net.py
- nilearn/decoding/space_net_solvers.py
- nilearn/decoding/tests/test_fista.py
- nilearn/decoding/tests/test_same_api.py
- nilearn/decoding/tests/test_sklearn_compatibility.py
- nilearn/decoding/tests/test_space_net.py
- nilearn/decoding/tests/test_tv.py
addresses issues #731, #729, #730, ...
> DOC+ENH: fixing minor docstring issues

- nilearn/tests/test_niimg_conversions.py
> Better check of dimensions.

- nilearn/datasets/func.py
- nilearn/datasets/tests/test_func.py
> Add full brain mask to haxby dataset.

- nilearn/input_data/base_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
> Fix bug in NiftiMasker.transform that allowed 5d

- nilearn/_utils/niimg_conversions.py
- nilearn/tests/test_niimg_conversions.py
> Add dimension check in concat_niimgs

- nilearn/datasets/utils.py
@AlexandreAbraham. Regarding #756, here is what i would propose to make the doc more user friendly. what do you think?
> doc change proposal for _fetch_files function in utils.py

- examples/decoding/plot_haxby_anova_svm.py
- examples/decoding/plot_haxby_grid_search.py
- examples/decoding/plot_haxby_multiclass.py
- examples/decoding/plot_haxby_searchlight.py
- examples/manipulating_visualizing/plot_haxby_mass_univariate.py
- nilearn/datasets/func.py
- nilearn/datasets/tests/test_func.py
changed related documentation.
> Addressing inconsistencies returning as a list of simple haxby datasets.

- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
What I did:
- Move if 'vmin' in kwargs check to the top of the function
- Rename it because it is not related to plot_stat_map only
- Add a test with 'vmin' in kwargs
- Add tests with non-empty kwargs
- Add tests with masked arrays
> [MRG] Minor tweaks to _get_plot_stat_map_params

- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/nifti_spheres_masker.py
> Add names to extraction functors

- examples/decoding/plot_oasis_vbm.py
> Fix double smoothing in Oasis VBM example

- nilearn/plotting/find_cuts.py
- nilearn/plotting/tests/test_find_cuts.py
In plot_stat_map function, "cut_coords"
> Addressing issue to raise error message to input for proper coords

- nilearn/__init__.py
- nilearn/_utils/compat.py
- nilearn/datasets/__init__.py
- nilearn/mass_univariate/__init__.py
- nilearn/mass_univariate/permuted_least_squares.py
This is the PR corresponding to issue #789.
> [MRG] Improving nilearn package docstring

- nilearn/__init__.py
- nilearn/_utils/cache_mixin.py
- nilearn/signal.py
- nilearn/tests/test_cache_mixin.py
This is the PR related to #792.
> [MRG] Use capital letters + other small changes related to PEP8

- nilearn/datasets/atlas.py
fixes the AAL atlas broken URL.
> AAL atlas URL

- doc/whats_new.rst
- nilearn/plotting/find_cuts.py
- nilearn/plotting/tests/test_find_cuts.py
> [MRG] Addressed comments remained for check proper cut_coords in plot_stat_map

- doc/manipulating_visualizing/manipulating_images.rst
- nilearn/__init__.py
- nilearn/_utils/niimg_conversions.py
- nilearn/_utils/testing.py
- nilearn/tests/test_niimg_conversions.py
> [MRG] use glob with check_niimg

- nilearn/input_data/nifti_maps_masker.py
- nilearn/input_data/nifti_spheres_masker.py
- nilearn/input_data/tests/test_nifti_maps_masker.py
- nilearn/input_data/tests/test_nifti_spheres_masker.py
Check for overlap in MapsMasker and SpheresMasker.
Fix #755.
> [MRG] Overlap verification code.

- nilearn/image/resampling.py
- nilearn/image/tests/test_resampling.py
> [WIP] BF: Fix issue #817

- nilearn/plotting/tests/test_img_plotting.py
Fixes the write permissions on windows mentionned in #809
> [MRG] fixing write permission error on windows

- appveyor.yml
- nilearn/_utils/testing.py
- nilearn/image/tests/test_image.py
- nilearn/image/tests/test_resampling.py
- nilearn/input_data/tests/test_multi_nifti_masker.py
- nilearn/input_data/tests/test_nifti_maps_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
- nilearn/plotting/tests/test_img_plotting.py
- nilearn/tests/test_niimg_conversions.py
- nilearn/tests/test_numpy_conversions.py
- nilearn/tests/test_signal.py
- setup.py
Still related to #809
This PR fixes many file access error due to remaining file handle on windows. It also fixes an error when open a memmap on an already opened mmemap, `w+` is not allowed on windows.
> [MRG+1] Fix file access issues

- nilearn/decoding/space_net.py
- nilearn/decoding/tests/test_space_net.py
> BF: handle empty mask in _crop_mask function

- examples/connectivity/plot_probabilistic_atlas_extraction.py
- examples/connectivity/plot_signal_extraction.py
Primarily, not using 'jet' in these two examples.
Also: a call to `plotting.show()` was raising an error in plot_probabilistic*
so this fixes that.
> DOC: A few fixes in examples.

- nilearn/decoding/space_net.py
- nilearn/decoding/tests/test_space_net.py
> Spacenet classifier accuracy score

- nilearn/decoding/space_net.py
- nilearn/decoding/tests/test_space_net.py
> [BF] Fixes issue #849

- nilearn/plotting/find_cuts.py
- nilearn/plotting/tests/test_find_cuts.py
> [BF] find_cuts crashes ungracefully if mask is empty

- nilearn/decoding/searchlight.py
- nilearn/input_data/nifti_spheres_masker.py
> Factorize code between Searchlight and NiftiSpheresMasker

- nilearn/decoding/space_net.py
- nilearn/decoding/tests/test_space_net.py
> [MRG+1] [BF] Fixes SpaceNet crashes when n_alphas=1 specified

- doc/introduction.rst
- doc/manipulating_visualizing/data_preparation.rst
- doc/themes/nilearn/static/nature.css_t
- nilearn/_utils/niimg_conversions.py
> FIX expand user path in glob

- doc/themes/nilearn/static/nature.css_t
Added css improvement after PR #867.
> DOC centering file name matchings sidebar for small width

- doc/building_blocks/manual_pipeline.rst
- doc/connectivity/resting_state_networks.rst
Fixing some references in `manual_pipeline`.
> DOC: fix pipeline demo

- nilearn/masking.py
- nilearn/tests/test_masking.py
> BF: Better error msg for empty mask

- doc/manipulating_visualizing/data_preparation.rst
> DOC: adding a section on NiftiSpheresMasker

- doc/manipulating_visualizing/plotting.rst
- examples/manipulating_visualizing/plot_dim_plotting.py
Should fix #778: control of the intensity of the background.
> [MRG] DOC: add an example to showcase dim

- Makefile
- circle.yml
- doc/Makefile
- examples/connectivity/plot_canica_resting_state.py
- examples/connectivity/plot_connectivity_measures.py
> [MRG] MAINT circle ci is now more strict with documentation generation

- doc/decoding/decoding_tutorial.rst
- doc/introduction.rst
- nilearn/_utils/exceptions.py
- nilearn/_utils/niimg.py
- nilearn/_utils/niimg_conversions.py
- nilearn/decoding/searchlight.py
- nilearn/decomposition/canica.py
- nilearn/decomposition/multi_pca.py
- nilearn/image/image.py
- nilearn/image/resampling.py
- nilearn/input_data/base_masker.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/nifti_spheres_masker.py
- nilearn/masking.py
- nilearn/plotting/displays.py
- nilearn/plotting/img_plotting.py
- nilearn/region.py
Fix #886 
@lesteve : I did a recursive find and replace, something like `find . -type f -print0 | xargs -0 sed -i 's#URL1#URL2#g'`
> DOC: Fix broken URLs

- nilearn/_utils/extmath.py
- nilearn/plotting/tests/test_find_cuts.py
- nilearn/tests/test_extmath.py
> [MRG+1] BF: IndexError in fast_abs_percentile

- examples/decoding/plot_haxby_space_net.py
- examples/decoding/plot_mixed_gambles_space_net.py
- examples/decoding/plot_oasis_vbm_space_net.py
> Set SpaceNet examples cache to 'nilearn_cache'

- nilearn/_utils/niimg_conversions.py
- nilearn/tests/test_niimg_conversions.py
This should address and fix #866.
> [MRG+1] Fix: add globbing to _iter_check_niimg

- doc/modules/reference.rst
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/regions/__init__.py
- nilearn/regions/signal_extraction.py
- nilearn/regions/tests/test_signal_extraction.py
Fix on top of PR #899 that should finish the work.
@AlexandreAbraham : Let's see if this passes on CircleCI and either cherry-pick in your PR, or merge in master.
> [MRG] Fix doc in Region Extractor

- doc/modules/reference.rst
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/regions/__init__.py
- nilearn/regions/signal_extraction.py
- nilearn/regions/tests/test_signal_extraction.py
> Fix doc in Region Extractor

- doc/whats_new.rst
- nilearn/connectome/connectivity_matrices.py
- nilearn/decomposition/base.py
- nilearn/decomposition/dict_learning.py
I vaguely remember about some of the things. Tell me if I miss something.
> Trying to cover all new features, functions, classes in whats new html

- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
> Fixing error message for display mode ortho and cut coords integer

- nilearn/signal.py
- nilearn/tests/test_signal.py
A fix to cast/type issue in high_variance confounds #896
> [MRG]: fixing cast/type issue in high_variance confounds #896

- doc/conf.py
- doc/sphinxext/numpydoc/__init__.py
- doc/sphinxext/numpydoc/comment_eater.py
- doc/sphinxext/numpydoc/compiler_unparse.py
- doc/sphinxext/numpydoc/docscrape.py
- doc/sphinxext/numpydoc/docscrape_sphinx.py
- doc/sphinxext/numpydoc/linkcode.py
- doc/sphinxext/numpydoc/numpydoc.py
- doc/sphinxext/numpydoc/phantom_import.py
- doc/sphinxext/numpydoc/plot_directive.py
- doc/sphinxext/numpydoc/traitsdoc.py
The main goal is to be able to generate nilearn doc with python 3.
Fix #888.
> [MRG] Update numpydoc sphinxext

- nilearn/plotting/displays.py
> BUG fixing with view type as filled_contours in plot prob plotting

- doc/modules/reference.rst
- examples/manipulating_visualizing/plot_visualize_megatrawls_netmats.py
- nilearn/_utils/param_validation.py
- nilearn/datasets/__init__.py
- nilearn/datasets/description/Megatrawls.rst
- nilearn/datasets/func.py
- nilearn/datasets/tests/test_func.py
- nilearn/tests/test_param_validation.py
Fixes #717 
Added:
- Fetcher
- Example
- Doc
- Tests
> [MRG] New fetcher for Megatrawls Netmats

- nilearn/plotting/find_cuts.py
- nilearn/plotting/tests/test_find_cuts.py
> [0.2.2 milestone] find_coords: allow 4D input

- nilearn/_utils/segmentation.py
- nilearn/image/image.py
- nilearn/image/tests/test_image.py
- nilearn/regions/region_extractor.py
- nilearn/regions/tests/test_region_extractor.py
- nilearn/tests/test_segmentation.py
- NAN values in the input images
- A bug reported when labels are reordered, only a list of single integer is returned
> Bug fixes in region extractor

- examples/03_connectivity/plot_canica_resting_state.py
A small change that improves on the readability of  canica example.
> [MRG+1] REWRITE: dataset.func[0] ==> func_filenames[0]

- doc/whats_new.rst
- nilearn/datasets/func.py
and some pep8 
Should fix #897
> [MRG+1] Change number of subjects in adhd from 40 to 30

- nilearn/datasets/atlas.py
- nilearn/datasets/tests/test_atlas.py
Fix #914 
There are still problems since some lateralized regions are splitted because they cross the inter-hemispheric limit but this PR, as for now, addresses most problems.
> [MRG+1] Harvard oxford

- nilearn/connectome/connectivity_matrices.py
- nilearn/connectome/tests/test_connectivity_matrices.py
> Bug: connectivity measures with LedoitWolf and wrong dimension

- README.rst
> [MRG] DOC fix README.rst contributing section

- nilearn/_utils/exceptions.py
While working on #982, I discovered a broken link in the DimensionError exception message.
> [MRG] FIX wrong link in exception

- nilearn/_utils/testing.py
This should fix #986 by performing 3 measures and return the max value.
> [MRG+1] Make memory profiling tests more robust

- doc/modules/reference.rst
- nilearn/datasets/__init__.py
- nilearn/datasets/atlas.py
- nilearn/datasets/data/dosenbach_2010.csv
- nilearn/datasets/description/dosenbach_2010.rst
- nilearn/datasets/tests/test_atlas.py
I kept the ROIs order as in the original paper. I also have a version of these ROIs ordered by networks, in case this would be preferred ?
> Dosenbach 2010 ROIs as in paper

- doc/modules/reference.rst
- nilearn/datasets/__init__.py
- nilearn/datasets/atlas.py
- nilearn/datasets/tests/test_atlas.py
> Replace fetch_atlas_{power,dosenbach} by fetch_coords_{power,dosenbach}

- nilearn/_utils/testing.py
- nilearn/datasets/func.py
- nilearn/datasets/tests/test_func.py
- nilearn/datasets/utils.py
In #915, @GaelVaroquaux stated that downloads lasting more than 1 hour were a problem. This PR address this problem by downloading individual files for COBRE dataset.
> [MRG] Transform the COBRE downloader to load individual files per subject

- doc/whats_new.rst
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
- nilearn/plotting/displays.py
- nilearn/plotting/glass_brain.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
This is a continuation of https://github.com/nilearn/nilearn/pull/977 because the history got tangled.
I my side this is good to go but it needs a whatsnew.
> [MRG+1] Colorbar connectome

- nilearn/_utils/niimg_conversions.py
- nilearn/image/image.py
Added examples w/ @GaelVaroquaux at the Brainhack
> [MRG] Added examples to docstring of image.index_img

- nilearn/plotting/find_cuts.py
- nilearn/plotting/img_plotting.py
> Replace get_data by _safe_get_data in plotting where necessary

- doc/whats_new.rst
- examples/03_connectivity/plot_connectivity_measures.py
- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
- nilearn/datasets/atlas.py
- nilearn/datasets/tests/test_atlas.py
> [MRG+1] Datasets: Uniform representation of labels in MSDL Atlas

- nilearn/plotting/displays.py
Attempt to fix #1019.
No doc because it's Brainhack! We don't hack docs.
> Add an `add_marker` method to slicer

- nilearn/datasets/func.py
- nilearn/datasets/tests/test_func.py
> Add background image to miyawaki dataset

- doc/manipulating_images/manipulating_images.rst
- doc/modules/reference.rst
- examples/04_manipulating_images/plot_affine_transformation.py
- nilearn/image/__init__.py
- nilearn/image/resampling.py
- nilearn/image/tests/test_resampling.py
Fix #1004
Maybe some examples in the documentation should added as well.
> [MRG+1] Adding a resample_to_img function

- nilearn/plotting/img_plotting.py
- ```display_mode``` changed from 'xy' to 'yx'
-  changed see also reference in ```plot_roi``` to ```plot_prob_atlas```
> Minor improvements in plotting documentation

- doc/manipulating_images/data_preparation.rst
- doc/manipulating_images/manipulating_images.rst
- examples/04_manipulating_images/plot_resample_to_template.py
Added an example with resample_to_img function.
> [MRG] Resample to img example

- nilearn/datasets/func.py
- nilearn/datasets/tests/test_func.py
For PR #1028, assign an MNI aligned affine to all files in Miyawaki dataset.
> Change miyawaki dataset for a version with MNI aligned affine

- circle.yml
- continuous_integration/circle_ci_test.sh
- continuous_integration/circle_ci_test_doc.sh
- continuous_integration/install.sh
Tries to fix #1003, but still doesn't work. Any help/tips greatly appreciated.
> [MRG+1] Circle ci anaconda

- examples/02_decoding/plot_haxby_space_net.py
> Fixing some py3 issues in Space-Net

- nilearn/datasets/func.py
While working on #1000, I encountered this reported issue. This fix #999.
> [MRG+1] fixing plot_mixed_gambles_space_net.py decoding example

- examples/02_decoding/plot_miyawaki_encoding.py
This is the encoding example for the Miyawaki et al., 2008 dataset, made at the Brainhack in Paris with @GaelVaroquaux
> Encoding example

- doc/decoding/decoding_tutorial.rst
- doc/install_doc_component.html
> Fixing #1057

- examples/plot_nilearn_101.py
Mainly ```cut_coords``` as a list and some additions.
> Minor improvements in the basic Nilearn example

- doc/introduction.rst
- doc/manipulating_images/data_preparation.rst
- doc/manipulating_images/manipulating_images.rst
- examples/04_manipulating_images/plot_mask_computation.py
- nilearn/signal.py
Includes:
- Fixing rst formatting
- Ordering enumerations to have most important items for application
first
- Fixing text and includes to relate to current examples
Any chance that this could be merged this morning?
> DOC: many small changes for Leipzig course

- doc/conf.py
Fix fixes circle ci html strict documentation generation.
> [MRG+1] use imgmath extension when using sphinx >= 1.4

- examples/01_plotting/plot_demo_plotting.py
Integrating of plotting tutorial into example ```01_plotting/plot_demo_plotting.py```
> Minor improvements in plot_demo_plotting example

- nilearn/plotting/glass_brain.py
> FIX: plot_brain_schematics bug with black background

- examples/03_connectivity/plot_canica_resting_state.py
- nilearn/decomposition/base.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/decomposition/tests/test_dict_learning.py
As the bug was triggered in mask extraction, I needed to change the
code to generate the data, and I needed to make it generate data that
looked more like brainz so that the mask extraction routines did not
fail.
> BUG: make sure that CanICA works on single subject

- nilearn/_utils/exceptions.py
- nilearn/image/tests/test_image.py
- nilearn/input_data/tests/test_multi_nifti_masker.py
- nilearn/input_data/tests/test_nifti_labels_masker.py
- nilearn/input_data/tests/test_nifti_maps_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
- nilearn/regions/tests/test_signal_extraction.py
- nilearn/tests/test_masking.py
- nilearn/tests/test_niimg_conversions.py
> [MRG] improve DimensionError exception message

- nilearn/decomposition/dict_learning.py
- ENH: phrasing + typos + layout problems
- REFACTOR: batch_size is optional param, defaults to 20
- REFACTOR: (coding) method is now optional param, defaults to "cd"
- CLEANUP: rmed weird usage of func_memory_level param (had the
unwanted effect of doing no caching!)
> Fixing some minor issues in DictLearning class

- doc/plotting/index.rst
- examples/01_plotting/plot_demo_more_plotting.py
-  Attempts to make example ```plot_demo_more_plotting.py``` looks like a notebook demonstration.
-  Simple documentation improvements in ```doc/plotting/index.rst```
> More improvements in plotting examples

- nilearn/plotting/edge_detect.py
- nilearn/plotting/tests/test_edge_detect.py
> [MRG] Clean edges

- .gitignore
- examples/01_plotting/plot_prob_atlas.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
Issue #1018. I put the colorbar by default for consistency with `plot_stat_map`
Screenshot
> [MRG] Plot prob atlas colorbar

- nilearn/_utils/niimg_conversions.py
- nilearn/tests/test_niimg_conversions.py
> [MRG +1] Add globbing to concat_niimgs

- doc/manipulating_images/manipulating_images.rst
- examples/04_manipulating_images/plot_roi_extraction.py
Attempts to fix #1072  "creating an ROI mask manually" doc section to a notebook-like example.
> Plot roi extraction notebook like example

- doc/modules/reference.rst
- doc/whats_new.rst
- nilearn/image/image.py
- nilearn/image/tests/test_image.py
- nilearn/signal.py
- nilearn/tests/test_signal.py
> Add function clean_img

- doc/Makefile
- doc/connectivity/parcellating.rst
- doc/manipulating_images/masker_objects.rst
- examples/03_connectivity/plot_canica_resting_state.py
- examples/03_connectivity/plot_rest_clustering.py
- examples/04_manipulating_images/plot_mask_computation.py
- examples/04_manipulating_images/plot_nifti_simple.py
- examples/05_advanced/plot_ica_resting_state.py
Use ADHD instead. The rational is to have less different data sources, in
order to have less stress on the download when building the docs.
> [MRG] DOC: don't download NYU in examples

- doc/manipulating_images/input_output.rst
- doc/manipulating_images/manipulating_images.rst
- doc/modules/reference.rst
- doc/whats_new.rst
- examples/plot_3d_and_4d_niimg.py
- examples/plot_nilearn_101.py
- nilearn/datasets/__init__.py
- nilearn/datasets/utils.py
The get_data_dirs function is useful to debug during a tutorial while a user is not putting the data in the right directory when copying from a pen drive (this happens often).
The example should probably be the 2nd one in a beginner tutorial, to make people a bit more familiar with input types.
> [MRG] DOC + ENH: tutorial example and get_data_dirs func

- doc/manipulating_images/masker_objects.rst
- examples/04_manipulating_images/plot_mask_computation.py
In user guide section NiftiMasker objects 5.3.2.1
> Fixing broken link to code from example plot_mask_computation

- nilearn/signal.py
- nilearn/tests/test_signal.py
> [MRG+1] raise explicit TR error

- nilearn/image/image.py
> Fixes issue #1161

- .idea/vcs.xml
- examples/.gitignore
- nilearn/_utils/cache_mixin.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/tests/test_base_masker.py
- nilearn/input_data/tests/test_multi_nifti_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
- nilearn/tests/test_cache_mixin.py
> Add shelving to NiftiMasker

- nilearn/datasets/atlas.py
Fix #1053 
Questions:
* should we fix the file directly?
* should we encode bytestrings into unicode ones?
* this may break user-defined scripts, what should we do about that?
> Remove spurious spaces in MSDL

- nilearn/plotting/displays.py
> add_edges correct docstring parameters

- nilearn/_utils/param_validation.py
> [MRG] Improving warning message in function check_threshold when threshold exceeds

- doc/whats_new.rst
- nilearn/image/resampling.py
And add mention of the bug in whats_new
This is the continuation of my previous PR, taking in @AlexandreAbraham 's feedback.
> COSMIT: simplify resampling code

- doc/connectivity/functional_connectomes.rst
> [MRG+1] replace corrcoef by ConnectivityMeasure in hint

- examples/03_connectivity/plot_connectivity_measures.py
> improve preprocs and remove sites restriction to show tangent measure benefit

- nilearn/_utils/niimg_conversions.py
- nilearn/tests/test_niimg_conversions.py
> [MRG+1] Dtype in concat niimgs

- examples/03_connectivity/plot_seed_to_voxel_correlation.py
this is more explicit than seed-based, which can be confused with spheric ROI-to-ROI connectivity
> use seed-to-voxel terminology

- doc/building_blocks/manual_pipeline.rst
- doc/decoding/searchlight.rst
- doc/manipulating_images/input_output.rst
- doc/whats_new.rst
- examples/01_plotting/plot_demo_more_plotting.py
- examples/01_plotting/plot_demo_plotting.py
- examples/01_plotting/plot_haxby_masks.py
- examples/01_plotting/plot_visualization.py
- examples/02_decoding/plot_haxby_anova_svm.py
- examples/02_decoding/plot_haxby_different_estimators.py
- examples/02_decoding/plot_haxby_full_analysis.py
- examples/02_decoding/plot_haxby_grid_search.py
- examples/02_decoding/plot_haxby_multiclass.py
- examples/02_decoding/plot_haxby_searchlight.py
- examples/02_decoding/plot_haxby_space_net.py
- examples/02_decoding/plot_haxby_stimuli.py
- examples/04_manipulating_images/plot_roi_extraction.py
- examples/05_advanced/plot_haxby_mass_univariate.py
- examples/plot_decoding_tutorial.py
- nilearn/datasets/func.py
- nilearn/datasets/tests/test_func.py
Attempts to Fix #860. Any reviews are welcome.
> [MRG] [ENH] Haxby datasets accepting list of subjects

- nilearn/plotting/displays.py
As suggested by @MartinPerez, I moved the flipping code to draw_2d.
Fix #1252
> Use a more secure code to flip axis in left view

- nilearn/input_data/nifti_spheres_masker.py
> radius and allow_overlap mandatory in _iter_signals

- nilearn/datasets/func.py
> Fix bug in fetching files for ABIDE.

- nilearn/datasets/tests/test_utils.py
- nilearn/datasets/utils.py
> Make _filter_columns robust to different encodings

- examples/03_connectivity/plot_multi_subject_connectome.py
> Fixed typo 'groupe'

- doc/sphinxext/sphinx_gallery/__init__.py
- doc/sphinxext/sphinx_gallery/_static/gallery.css
- doc/sphinxext/sphinx_gallery/downloads.py
- doc/sphinxext/sphinx_gallery/gen_gallery.py
- doc/sphinxext/sphinx_gallery/gen_rst.py
- doc/sphinxext/sphinx_gallery/notebook.py
This update allows to download all examples of the gallery at once, plus
improved support of the RST to markdown conversion for the Jupyter
notebooks
> [MAINT] Update to Sphinx-Gallery 0.1.4

- doc/conf.py
- doc/decoding/decoding_tutorial.rst
> Fix docs (and circleci) with latest scikit-learn release

- nilearn/_utils/testing.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/input_data/tests/test_nifti_maps_masker.py
- nilearn/tests/test_niimg_conversions.py
Addressing comment from PR #1299
> [MRG+1] Fix comment PR #1299, removed calling double get_data for dtype

- nilearn/datasets/atlas.py
> [MRG] Fixing the 'origin' of download link for smith atlas fetcher.

- nilearn/image/image.py
> BUG: fix min value in nifti header

- nilearn/_utils/fixes/__init__.py
Fixed deprecation warning with sklearn 0.18
> Fixed deprecation warning with sklearn 0.18

- nilearn/connectome/jaccard_index.py
Work needed on examples and documentation. We could also consider adding other measures of similarity (ICC, mutual information).
> [WIP] Adding Jaccard index for computing atlas similarity

- nilearn/datasets/func.py
Reverts nilearn/nilearn#1316
I revert it beause it contains spurious commits (Jaccard Index).
> Revert "[MRG] Fixes #1313 and #1314"

- nilearn/datasets/func.py
Clean version of the earlier PR.
> [MRG] Fixes #1313

- examples/01_plotting/plot_demo_glass_brain_extensive.py
- nilearn/datasets/func.py
- nilearn/plotting/displays.py
- nilearn/plotting/tests/test_displays.py
> [MRG] Fix: add_contours (filled=True) which will not require to specify color or alpha

- nilearn/datasets/description/icbm152_2009.rst
- nilearn/datasets/description/msdl_atlas.rst
This PR attempts to fix encode errors arising from characters defined in description files.
Any reviews please.
> Attempts to fix encode error with ascii characters

- nilearn/plotting/cm.py
Green was blue and vice versa. This commit fixes it.
> Fixing the transparent colormaps

- doc/conf.py
This is necessary to fix circleCI.
Let's see if this runs!
> FIX: adapt to latest Circle

- doc/conf.py
> FIX: adapt to Sphinx 1.5

- nilearn/decomposition/dict_learning.py
> Doc: Update to compressed online dictionary learning

- nilearn/_utils/niimg_conversions.py
Implements fix proposed at #1308
> make concat_niimgs preserve header info

- .travis.yml
- nilearn/version.py
scipy 0.17.1 is what neurodebian has
> [MRG] MAINT: adjust versions on CI

- nilearn/_utils/cache_mixin.py
Minor changes in the docstring.
Wrong verbose, better description of the _check_memory function.
> [DOC] improving docstring of _check_memory function

- nilearn/datasets/func.py
- nilearn/decoding/tests/test_same_api.py
- nilearn/decomposition/base.py
- nilearn/plotting/tests/test_find_cuts.py
Attempts to fix recent failures with recent NumPy indexing float errors.
See PR's:
https://travis-ci.org/nilearn/nilearn/jobs/201121267
https://travis-ci.org/nilearn/nilearn/jobs/200513051
Any reviews on this please ?
> [MRG] FIX: NumPy errors mostly indexing problems with float values

- examples/01_plotting/plot_haxby_masks.py
- examples/02_decoding/plot_oasis_vbm.py
- examples/05_advanced/plot_localizer_mass_univariate_methods.py
- examples/05_advanced/plot_localizer_simple_analysis.py
From PR #1378 it seems like there are some examples missed to change.
See https://circleci.com/gh/nilearn/nilearn/2263
This PR would hopefully fix failures related to recent NumPy.
Any reviews please ?
> [MRG] FIX: NumPy errors in advanced examples

- nilearn/plotting/displays.py
- nilearn/plotting/tests/test_displays.py
- nilearn/plotting/tests/test_img_plotting.py
Attempts to Fix #1294. 
Can I have reviews please ?
> [MRG+1] FIX: Plotting functions to use matplotlib colormaps 'Paired', 'Set1' with colorbar=True

- nilearn/decomposition/base.py
- nilearn/decomposition/tests/test_base.py
- nilearn/signal.py
Automatically switch between randomized SVD and lapack
> OPTIM: faster SVD

- nilearn/_utils/niimg.py
- nilearn/_utils/niimg_conversions.py
- nilearn/decoding/searchlight.py
- nilearn/decomposition/base.py
- nilearn/decomposition/dict_learning.py
- nilearn/decomposition/multi_pca.py
- nilearn/image/image.py
- nilearn/image/resampling.py
- nilearn/input_data/base_masker.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/nifti_spheres_masker.py
- nilearn/masking.py
- nilearn/plotting/displays.py
- nilearn/regions/signal_extraction.py
Fixes #1402
Making a PR to check CI, and then merging.
> Remove "." at the end of URLs

- examples/02_decoding/plot_haxby_anova_svm.py
> Use SelectPercentile in ANOVA decoding

- nilearn/datasets/atlas.py
- nilearn/plotting/displays.py
I just adressed the annoying messages from matplotlib 2.0. Works with matplotlib down to 1.3
> Matplotlib 2.0 deprecation

- nilearn/regions/region_extractor.py
- nilearn/regions/tests/test_region_extractor.py
Fixing comments (post-merge) with PR #1328.
Can I have reviews please ? ping @AlexandreAbraham
> DOC: Address comments made on connected_label_regions

- nilearn/plotting/find_cuts.py
> Support for niimg in find_cut_slices

- doc/building_blocks/manual_pipeline.rst
- doc/connectivity/connectome_extraction.rst
- doc/decoding/decoding_intro.rst
- doc/decoding/estimator_choice.rst
- doc/decoding/searchlight.rst
- doc/decoding/space_net.rst
- doc/manipulating_images/manipulating_images.rst
- doc/manipulating_images/masker_objects.rst
A PR with fixed typos in the documentation
> [MRG+1] Fix typos

- examples/02_decoding/plot_simulated_data.py
In this PR, I applied the proposed solution in #1451, changing the variable name 'classifiers' to 'estimators'.
ping @KamalakerDadi
> changing name, classifier is now estimator

- nilearn/decomposition/canica.py
- nilearn/decomposition/tests/test_canica.py
> [MRG] checks that the threshold is not higher than number of maps for canICA 

- .travis.yml
- README.rst
- doc/whats_new.rst
- nilearn/_utils/cache_mixin.py
- nilearn/_utils/testing.py
- nilearn/input_data/tests/test_multi_nifti_masker.py
- nilearn/tests/test_cache_mixin.py
- nilearn/tests/test_testing.py
- nilearn/version.py
> [MRG] Drop Scikit-learn < 0.15

- doc/whats_new.rst
- nilearn/plotting/displays.py
A test implementation for tight bounds in contours.
Attempts to fix #1450
> [MRG]: tight bounds in contours

- nilearn/image/resampling.py
- nilearn/image/tests/test_resampling.py
Attempts to FIX #1445  Can I have your opinion on this FIX ?
> FIX: resampling image bug with big-endian data types

- doc/connectivity/region_extraction.rst
- doc/decoding/decoding_intro.rst
- doc/manipulating_images/manipulating_images.rst
- doc/sphinxext/sphinx_gallery/gen_gallery.py
- examples/02_decoding/plot_haxby_anova_svm.py
- examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
- nilearn/image/tests/test_image.py
- nilearn/masking.py
- nilearn/tests/test_masking.py
- Fixes are related to numpy boolean type operations. Where recommended
solutions are to use numpy functions on arrays.
See for instance in PR #1462 with this link
https://travis-ci.org/nilearn/nilearn/jobs/241458725
Can I have reviews on this please ?
> FIX: Travis failures with recent NumPy release 1.13.0

- examples/01_plotting/plot_atlas.py
- examples/01_plotting/plot_demo_glass_brain.py
- examples/01_plotting/plot_demo_more_plotting.py
- examples/01_plotting/plot_demo_plotting.py
- examples/01_plotting/plot_dim_plotting.py
- examples/01_plotting/plot_multiscale_parcellations.py
- examples/01_plotting/plot_overlay.py
- examples/01_plotting/plot_visualization.py
- examples/01_plotting/plot_visualize_megatrawls_netmats.py
- To look a bit easier to understand about each step
Reviews please ?
> ENH: Making healines to the plotting examples 01_plotting

- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
Attempts to FIX #1268 . Last time we fixed plotting issues with foreground images but not background image. This PR should hopefully fix this as well.
Please reviews ?
Thanks
> FIX: Plotting issues with brain images (bg_img) containing non-finite values

- examples/03_connectivity/plot_adhd_spheres.py
- examples/03_connectivity/plot_canica_resting_state.py
- examples/03_connectivity/plot_compare_resting_state_decomposition.py
- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_multi_subject_connectome.py
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
- examples/03_connectivity/plot_signal_extraction.py
- examples/03_connectivity/plot_simulated_connectome.py
- To make the examples visually better step by step. Also, helpful
when giving tutorials.
Reviews please ?
Thanks
> ENH: Make headlines in 03_connectivity examples

- doc/whats_new.rst
whats_new additions helpful for release.
Thanks for reviewing.
> DOC: Added missing information to whats_new.rst

- examples/02_decoding/plot_haxby_anova_svm.py
- examples/02_decoding/plot_haxby_different_estimators.py
- examples/02_decoding/plot_haxby_full_analysis.py
- examples/02_decoding/plot_haxby_grid_search.py
- examples/02_decoding/plot_haxby_multiclass.py
- examples/02_decoding/plot_haxby_searchlight.py
- examples/02_decoding/plot_haxby_space_net.py
- examples/02_decoding/plot_mixed_gambles_space_net.py
- examples/02_decoding/plot_miyawaki_reconstruction.py
- examples/02_decoding/plot_oasis_vbm.py
- examples/02_decoding/plot_oasis_vbm_space_net.py
Made a pass on decoding examples to make headlines for easier follow through each step in the examples.
Thanks for reviewing.
> ENH: Documentation improvements. Make headlines for examples 02_decoding

- examples/02_decoding/plot_haxby_anova_svm.py
As requested by bthirion in issue #1472 this bug should be fixed now
> Created cv object is not used in example plot_haxby_anova_svm.py

- nilearn/plotting/glass_brain_files/plot_align_svg.py
otherwise importing this submodule results in lots of plotting etc whenever it seems to be just an example
> BF: Move code within submodule example under __main__ conditioning and add shebang

- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
Attempts to fix issue #1226 plus check whether input for dim argument is out of range. Please, review it.
> FIXUP: check invalid input for dim argument (issue #1226)

- doc/connectivity/functional_connectomes.rst
- examples/01_plotting/plot_overlay.py
- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
- nilearn/datasets/description/msdl_atlas.rst
> [MRG] Broken link to MSDL atlas

- examples/01_plotting/plot_visualize_megatrawls_netmats.py
- examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_multi_subject_connectome.py
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
- examples/03_connectivity/plot_signal_extraction.py
- examples/03_connectivity/plot_simulated_connectome.py
- examples/03_connectivity/plot_sphere_based_connectome.py
- nilearn/plotting/__init__.py
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/tests/test_displays.py
Work in Progress from the brainhack event in Paris. Adding a matrix-plotting function.
> WIP: Matrix plotting function

- nilearn/_utils/fixes/__init__.py
- nilearn/decoding/searchlight.py
- nilearn/decoding/tests/test_searchlight.py
Sorry for the commits which I have addressing few fixes in master.
@bthirion Could you please have a look ?
I have added some commits from PR #1487 somehow into master.
> Revert commits from PR #1487

- examples/02_decoding/plot_haxby_multiclass.py
- examples/03_connectivity/plot_group_level_connectivity.py
- examples/03_connectivity/plot_inverse_covariance_connectome.py
- examples/03_connectivity/plot_multi_subject_connectome.py
Updating with our new matrix plotting function ```nilearn.plotting.plot_matrix``` in following examples:
- examples/02_decoding/plot_haxby_multiclass.py
- examples/03_connectivity/plot_group_level_connectivity.py
- examples/03_connectivity/plot_multi_subject_connectome.py
This was discussed last week IRL with @GaelVaroquaux
> [MRG] ENH: Some examples updates to plot_matrix

- nilearn/image/resampling.py
- nilearn/image/tests/test_resampling.py
I found that I was using this in my work. It is a useful feature to have and easily implementable.
> Added option to perform linear resampling

- doc/modules/reference.rst
- doc/whats_new.rst
- examples/02_decoding/plot_miyawaki_encoding.py
- nilearn/image/__init__.py
- nilearn/image/resampling.py
- nilearn/image/tests/test_resampling.py
I addressed remaining comments and took over the PR #1530 
Can I have final reviews ?
> [MRG] Expose coord transform

- nilearn/_utils/fixes/__init__.py
- nilearn/decoding/space_net.py
- nilearn/decoding/tests/test_searchlight.py
Trying to fix some deprecated warnings when running examples or CircleCI.
Deprecated functions or modules which will be removed in sklearn 0.20.
> [MRG] MAINT: Address some deprecations with sklearn

- doc/whats_new.rst
Updating all new enhancements and minor fixes.
> DOC: Update whats_new

- nilearn/image/resampling.py
Closes https://github.com/nilearn/nilearn/issues/1363
> [MRG+1] Suppress UserWarning on calls to affine_transform

- nilearn/regions/region_extractor.py
- nilearn/regions/tests/test_region_extractor.py
> [MRG+1] Region volume

- nilearn/plotting/find_cuts.py
Should fix some issues to more get_affine(img) to img.affine
Please reviews ?
> FIX: nibabel bumpup compatible changes

- examples/04_manipulating_images/plot_extract_rois_statistical_maps.py
- nilearn/plotting/img_plotting.py
Change `anat_img` argument to `bg_img` in plot_prob_atlas and add a DeprecationWarning.
See issue #965
> Harmonize anat_img to bg_img

- doc/whats_new.rst
- examples/01_plotting/plot_surf_atlas.py
- nilearn/plotting/surf_plotting.py
Supersedes Pr #1421 and #1559 to fix the docstring.
> Anterior and posterior views

- circle.yml
- doc/building_blocks/manual_pipeline.rst
- doc/conf.py
- doc/manipulating_images/input_output.rst
- examples/02_decoding/plot_haxby_anova_svm.py
- examples/02_decoding/plot_haxby_different_estimators.py
- examples/02_decoding/plot_haxby_full_analysis.py
- examples/02_decoding/plot_haxby_grid_search.py
- examples/02_decoding/plot_haxby_multiclass.py
- examples/02_decoding/plot_haxby_searchlight.py
- examples/02_decoding/plot_haxby_space_net.py
- examples/04_manipulating_images/plot_roi_extraction.py
- examples/05_advanced/plot_haxby_mass_univariate.py
- examples/plot_decoding_tutorial.py
- nilearn/decoding/space_net.py
In response to #1140, updates examples to use pandas instead of numpy when handling csv files. Also patches `space_net.py` to check if input is classifier when converting to numeric, otherwise stimuli labels passed from pandas introduce errors.
> Pandas examples

- doc/whats_new.rst
- nilearn/plotting/img_plotting.py
Added few missing documenation. Minor cosmetics improvements.
> DOC: Update whats_new deprecated anat_img in plot_prob_atlas

- nilearn/image/resampling.py
- nilearn/image/tests/test_resampling.py
>  [MRG+2] Resample_img clip fix issue #1528

- doc/modules/reference.rst
- doc/whats_new.rst
- nilearn/datasets/__init__.py
- nilearn/datasets/atlas.py
- nilearn/datasets/description/talairach_atlas.rst
- nilearn/datasets/tests/test_atlas.py
> [MRG+1] add a Talairach atlas fetcher (see http://talairach.org)

- README.rst
scipy minimal version just got bumped to 0.14 but it is still 0.9 in README.rst
> update required scipy version in README.rst

- doc/install_doc_component.html
> try fix the anaconda web address

- nilearn/decoding/space_net.py
Still need to check if anything is missing. Otherwise reviewable.
Thanks for reviewing.
> [MRG] DOC: SpaceNet

- nilearn/image/resampling.py
- nilearn/image/tests/test_resampling.py
Closes https://github.com/nilearn/nilearn/issues/1589
> Fix off by one in reorder_img

- nilearn/decomposition/base.py
> [MRG+1] ENH: use float32 rather than float64

- nilearn/plotting/img_plotting.py
this is what i saw needed to be changed but let me know if there are other things
> [MRG] incorporate the dim argument as input to plot_anat in plot_prob_atlas

- doc/whats_new.rst
- nilearn/plotting/matrix_plotting.py
Added missing entries in doc/whats_new.rst
> DOC: Update whats new

- nilearn/plotting/surf_plotting.py
> fix symmetric colormap in plot_surf

- nilearn/datasets/tests/test_utils.py
> [MRG] fixed the test_uncompress function

- nilearn/plotting/surf_plotting.py
* Fixed aspect ratio
* Less lost white space
Overrides #1652
> Improve 3D plotting

- nilearn/image/image.py
- nilearn/signal.py
- nilearn/tests/test_signal.py
This PR is continuation of #1629
> BUG: Repetition time had no effect on signal cleaning

- doc/index.rst
One last thing before release: let's have a prettier image in the carrousel.
> Prettier picture on front page

- doc/modules/reference.rst
- doc/whats_new.rst
- examples/01_plotting/plot_3d_map_to_surface_projection.py
- examples/01_plotting/plot_surf_atlas.py
- examples/01_plotting/plot_surf_stat_map.py
- nilearn/datasets/__init__.py
- nilearn/datasets/description/fsaverage.rst
- nilearn/datasets/struct.py
- nilearn/datasets/tests/test_struct.py
- nilearn/plotting/surf_plotting.py
> [MRG+1] add fsaverage fetcher

- doc/plotting/index.rst
> fix typo in image name

- doc/modules/reference.rst
- doc/whats_new.rst
- examples/01_plotting/plot_prob_atlas.py
- nilearn/datasets/__init__.py
- nilearn/datasets/atlas.py
- nilearn/datasets/description/pauli_2017.rst
- nilearn/datasets/tests/test_atlas.py
Hey guys,
I made a commit that includes a possibility for downloading the subcortical atlas of Pauli et al., 2017. Appreciate feedback.
Cheers,
Gilles
> Pauli et al. 2017 atlas

- doc/connectivity/functional_connectomes.rst
- doc/modules/reference.rst
- doc/plotting/index.rst
- doc/whats_new.rst
- examples/03_connectivity/plot_atlas_comparison.py
- examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
- examples/03_connectivity/plot_multi_subject_connectome.py
- nilearn/datasets/atlas.py
- nilearn/plotting/__init__.py
- nilearn/plotting/find_cuts.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_find_cuts.py
Fixes #646 , #1111  and supersedes #664 
Things to do:
- Improving documentation of the functions ```find_parcellation_cut_coords``` and ```find_probabilistic_atlas_cut_coords```
- Improving the example
- Fixing tests and adding more tests
> Find coordinates given parcellations image

- nilearn/plotting/html_surface.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/plotting/tests/test_js_plotting_utils.py
> add vmax kwarg to view_img_on_surf and view_surf

- nilearn/plotting/html_stat_map.py
- nilearn/plotting/tests/test_html_stat_map.py
- nilearn/plotting/tests/test_html_surface.py
- nilearn/plotting/tests/test_js_plotting_utils.py
accept 4d in view_stat_map if last dim is 1
fixes #1725
> Fix Cater for almost 3D images in view_stat_map

- nilearn/decoding/searchlight.py
- nilearn/decoding/tests/test_searchlight.py
> [MRG] fix searchlight to handle list of 3D images by adding check_niimg_4d

- nilearn/datasets/neurovault.py
neurosynth api has moved and there is no redirection on the old url
> update url for neurosynth api

- nilearn/plotting/js_plotting_utils.py
> Fix open_in_browser()

- nilearn/datasets/atlas.py
- nilearn/tests/test_signal.py
- Bug in scipy generating FutureWarnings
> [MRG+1] Fixed TravisCI failure due to overwhelming number of warnings causing log fail

- .circleci/config.yml
- nilearn/connectome/connectivity_matrices.py
Trying to simplify the circleCI build to make it more stable.
> Lighter circle configuration

- nilearn/__init__.py
- nilearn/_utils/cache_mixin.py
- nilearn/datasets/atlas.py
- nilearn/tests/test_py2_deprecation_warning.py
For #1696 
- Added tests [INCOMPLETE].
> [MRG] In a py2 environment, Nilearn raises a DeprecationWarning once on import

- examples/02_decoding/plot_haxby_different_estimators.py
- nilearn/decoding/tests/test_space_net.py
Fix #1784 _ Improves log quality
- Explicitly specified linear_model.LogisticRegression(solver='liblinear') .
> Fixed FutureWarning from LogicsticReggression about default solver changing

- doc/install_doc_component.html
- nilearn/datasets/atlas.py
> [MRG] Updated the link to Anaconda installation page

- nilearn/datasets/utils.py
Report less often, as in jupyter and in circleCI this clogs the logs.
> MISC: less verbosity in downloads

- examples/02_decoding/plot_haxby_different_estimators.py
- Changed grid parameters to generate a simpler grid for
faster example generation.
> Simpler Grid search for faster example generation

- nilearn/regions/signal_extraction.py
> Add NiftiMasker ref to signals_to_img_labels

- nilearn/input_data/nifti_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
> FIX: nearest neighbor resampling for mask

- nilearn/plotting/img_plotting.py
> FIX: alpha in plot_prob_atlas

- doc/themes/nilearn/layout.html
- doc/themes/nilearn/static/nature.css_t
This should fix #1071.
I took as example the layout and stylesheet from [scipy-lecture-notes](https://github.com/scipy-lectures/scipy-lecture-notes).
The css changeset also contains a fix for the code example overlapping the sidebar. Thus I'll close #1078.
> [MRG] website navigation improvements

- nilearn/plotting/html_stat_map.py
- nilearn/plotting/tests/test_html_stat_map.py
For #1778 
Opening a new PR for this, the other one was too outdated and problematic.
> [MRG] FutureWarning: view_stats_map() is under active development; may change without warning

- doc/themes/nilearn/layout.html
- doc/themes/nilearn/static/nature.css_t
Following rework by @aabadie of top menu
> DOC: more modern, white layout

- nilearn/surface/surface.py
I closed previous pull request because I messed up with a lot of things to rebase master so I started from a fresh pull request @KamalakerDadi . Thanks for helping me.
> Improve error message of vol_to_surf when input is wrong

- nilearn/plotting/js_plotting_utils.py
see https://github.com/nilearn/nilearn/pull/1766#issuecomment-431546544
> [MRG] fix one deprecation warning

- .travis.yml
Removed 2 of 3 Py2.7 builds (unnecessary), added Py3.6 build
> [MRG] Updating Travis build configs

- .circleci/config.yml
- examples/03_connectivity/plot_adhd_spheres.py
issue #1786 
- master branch and new branches are always built from scratch.
- Existing branches cache their built documentation & reuse that to only
rebuild any differences.
- The cache is purged daily, hence the first push of the day is rebuilt from
scratch.
> Improved: CircleCI builds are more efficient

- doc/whats_new.rst
- nilearn/plotting/html_connectome.py
- nilearn/plotting/tests/test_html_connectome.py
(As per issue #1886 )
Changed params:  
coords -> marker_coords
colors -> marker_color
> [MRG] view_markers() parameters consistent with add_markers()

- nilearn/input_data/nifti_spheres_masker.py
> COSMIT: remove unused imports

- nilearn/regions/region_extractor.py
- nilearn/regions/tests/test_region_extractor.py
> therehold_map_ratio should not change input image

- doc/whats_new.rst
- nilearn/regions/region_extractor.py
- nilearn/regions/tests/test_region_extractor.py
> RegionExtractor mask img

- nilearn/plotting/html_connectome.py
> fix linewidth in view_connectome

- doc/whats_new.rst
- nilearn/__init__.py
- nilearn/version.py
- Updated whats_new.rst changelog.
- Updatd list of contributors for current release.
> Release preparation for Nilearn v0.5.1

- .circleci/config.yml
Fix regressions in CircleCI introduced due to #1967 & #1969
> Fix regressions in CircleCI introduced due to #1967 & #1969 

- .circleci/clean-cache.py
clean-cache.py flushes the both branch & master caches for next CircleCI build
> CircleCI: Enable flushing both branch and master cache

- .circleci/config.yml
- nilearn/decoding/space_net.py
Avoid too long loops when spacenet does not converge
Inspired by #1977, by @KamalakerDadi 
This PR should be "safe", in the sense that the change should be harmless. Iterating 1000 time is too much anyhow.
> MAINT: control SpaceNet convergence

- nilearn/signal.py
> FIXUP: description of low and high pass filter in signal.clean()

- doc/whats_new.rst
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
> [MRG+1] FIX: glass brain plotting to show colorbar when having NaN

- examples/04_manipulating_images/plot_nifti_simple.py
This PR is a follow-up to PR #1953 . Adapting the example to haxby dataset for doing "epi" masking strategy.
> [MRG+1] Update example plot_nifti_simple

- CONTRIBUTING.rst
Pinging @GaelVaroquaux in particular.
Updates the contributing.rst file to include more information, correct "Good First Issue" label.
> [MRG+1] [DOC] Initial update of contributing

- nilearn/plotting/tests/test_surf_plotting.py
- nilearn/surface/testing.py
- nilearn/surface/testing_utils.py
- nilearn/surface/tests/test_surface.py
Moving helper functions in separate file
> organizing functions for testing surface code

- nilearn/decoding/tests/test_searchlight.py
Corrected the definition of the conditions (targets / y) in the searchlight test function so that the classes are balanced
> Minor correction in test_searchlight.py

- doc/connectivity/resting_state_networks.rst
- doc/themes/nilearn/static/nature.css_t
- examples/03_connectivity/plot_compare_decomposition.py
- examples/03_connectivity/plot_probabilistic_atlas_extraction.py
Including CSS, to put the download note of the examples on the side.
> DOC: small doc and formulation changes

- CONTRIBUTING.rst
- doc/contributing.rst
- doc/development.rst
- doc/index.rst
- doc/themes/nilearn/layout.html
Documents the development and decision processes in nilearn. 
Ping @emdupre for review
> DOC: document the development and decisions

- nilearn/_utils/extmath.py
"partition" used to be a backport in fixes, but didn't get clean up fully.
> CLEAN: remove leftover backport

- nilearn/plotting/data/html/connectome_plot_template.html
- nilearn/plotting/data/html/stat_map_template.html
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/tests/test_html_stat_map.py
> [MRG] make html templates valid

- examples/01_plotting/plot_surface_projection_strategies.py
- nilearn/plotting/surf_plotting.py
> [WIP] Don't set aspect of 3d axes: raises NotImplementedError starting from matplotlib 3.1

- doc/manipulating_images/manipulating_images.rst
Fix for #2058 
Also reviewed the rest of the doc and fixed a couple other typos I noticed.
Let me know if you need me to change anything!
> Correct typos and re-word Smoothing step in ROI mask recipe

- .travis.yml
- README.rst
- continuous_integration/install.sh
- doc/whats_new.rst
- nilearn/version.py
#2077
- Conda default channel dropped support for these versions.
- Updated Whats_new.rst
> Bumped up the minimum versions of scikit-learn, scipy to 0.19, mpl to 2.0

- nilearn/plotting/__init__.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/plotting/tests/test_js_plotting_utils.py
> [MRG] allow setting or disabling warning about too many open views

- examples/02_decoding/plot_haxby_stimuli.py
> fix imread import in example

- nilearn/datasets/func.py
> Set verbose=1 to fetchers

- nilearn/plotting/img_plotting.py
> Corrected docstring for bg_img in plot_stat_map

- continuous_integration/install.sh
Temporary stopgap until #2115 is addressed.
> Replaced conda latest version with 4.6.* pending replacement of conda with pip

- doc/whats_new.rst
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/tests/test_matrix_plotting.py
Fixes issues #2049 i.e. `plot_matrix` breaking if an empty list is supplied as the labels argument and `auto_fit=True`.
> Fix matrix plotting labels

- doc/whats_new.rst
- nilearn/datasets/func.py
> fix wrong urls in nki dataset

- appveyor.yml
> change nose to pytest on appveyor

- nilearn/__init__.py
> fix openmp crash

- .travis.yml
- nilearn/signal.py
> Fixing malfunctioning allowed-failure section in Travis

- README.rst
- azure-pipelines.yml
- nilearn/plotting/tests/test_js_plotting_utils.py
> Run tests on local Windows machines & Azure Pipelines

- doc/whats_new.rst
- nilearn/version.py
- setup.cfg
- setup.py
> Installation should fail on Python < 3.5

- nilearn/surface/tests/test_surface.py
> [MRG] fix uniform ball cloud test for sklearn >= 0.22

- appveyor.yml
- azure-pipelines.yml
- continuous_integration/show-python-packages-versions.py
- doc/conf.py
- nilearn/tests/test_package_installation.py
- nilearn/version.py
- setup.py
> [MRG] Add testing for Nilearn setup & install & Fix the broken dependency installation

- doc/whats_new.rst
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/tests/test_nifti_labels_masker.py
- nilearn/regions/signal_extraction.py
The keyword allows changing the extraction function to compute
other measures besides the mean.
Closes #1926
> Add parameter "strategy" to NiftiLabelsMasker to choose function to reduce ROIs

- doc/whats_new.rst
- nilearn/_utils/testing.py
- nilearn/plotting/__init__.py
- setup.cfg
> [MRG] Fix:  Nilearn raises Nose ImportError with no MatPlotLib

- examples/01_plotting/plot_demo_glass_brain_extensive.py
- examples/04_manipulating_images/plot_roi_extraction.py
- examples/plot_3d_and_4d_niimg.py
- examples/plot_nilearn_101.py
Partially addresses #2241.
- Try removing print statements from documentation, as these should now be unnecessary
> [wip, doc] take advantage of new sphinx-gallery features

- CONTRIBUTING.rst
A little detail that was confusing  @koudyk
> More clear CONTRIBUTING.rst

- nilearn/_utils/__init__.py
- nilearn/_utils/helpers.py
- nilearn/plotting/html_connectome.py
- nilearn/plotting/tests/test_html_connectome.py
- nilearn/tests/test_helpers.py
Fixes #2251 
Skipping implementation of pytest. No benefit over existing solution.
> Improve replace parameters

- doc/building_blocks/manual_pipeline.rst
- doc/manipulating_images/manipulating_images.rst
- examples/plot_decoding_tutorial.py
Updating plot_decoding_tutorial tutorial following issue #2242
> typo + changes for plot_decoding_tutorial

- doc/whats_new.rst
- nilearn/plotting/data/html/connectome_plot_template.html
- nilearn/plotting/data/html/stat_map_template.html
- nilearn/plotting/data/html/surface_plot_template.html
- nilearn/plotting/html_connectome.py
- nilearn/plotting/html_stat_map.py
- nilearn/plotting/html_surface.py
- nilearn/plotting/tests/test_html_connectome.py
- nilearn/plotting/tests/test_html_stat_map.py
- nilearn/plotting/tests/test_html_surface.py
- nilearn/plotting/tests/test_js_plotting_utils.py
> [MRG] plot titles in html page titles

- nilearn/_utils/exceptions.py
- nilearn/datasets/func.py
- nilearn/datasets/struct.py
- nilearn/plotting/img_plotting.py
Necessary to fix CI: https://travis-ci.org/nilearn/nilearn/jobs/655871459?utm_medium=notification&utm_source=github_status
> [MRG] BUG: fix non-imported VisibleDeprecationWarning

- .circleci/artifact_path
- .github/workflows/main.yml
This is a test to see if we can generate a link to the artifacts in the PRs
> [MRG] Add link to circleci artifacts

- nilearn/decoding/tests/test_same_api.py
> Remove Empty Test Case

- examples/02_decoding/plot_oasis_vbm.py
- examples/02_decoding/plot_simulated_data.py
- examples/05_advanced/plot_haxby_mass_univariate.py
- examples/05_advanced/plot_localizer_mass_univariate_methods.py
- examples/05_advanced/plot_localizer_simple_analysis.py
- nilearn/decoding/objective_functions.py
- nilearn/image/tests/test_resampling.py
- nilearn/input_data/tests/test_nifti_masker.py
- nilearn/tests/test_niimg_conversions.py
> Fix invalid escape sequences in strings

- doc/modules/reference.rst
this is to check the sphinx documentation.
note: I inadvertently pushed this change to upstream master and reverted that commit right away. sorry about that
> [MRG] list nistats subpackages in reference

- doc/conf.py
this will fix the docs failing to build
> [MRG] fix link to pandas intersphinx objects

- nilearn/plotting/img_plotting.py
Fixes #2430 
Matplotlib 3.2.0 no longer scales colorbars between 0 and 1. `_crop_colorbar` was using `cbar.norm` to scale `cbar_vmin` and `cbar_vmax`, which now leads to broken colorbar values:
Removing the norming behavior leads to expected results:
I don't see any obvious fix that would work for both new and old behavior, so this simply adds a version check for matplotlib.
> Fix colorbar cropping in matplotlib 3.2.0

- nilearn/decoding/decoder.py
> seed fREM default cv generator for stability and reproducibility

- nilearn/signal.py
- nilearn/tests/test_signal.py
> using robust precentile in variance thresholding for high variance confounds

- .github/pull_request_template.md
- AUTHORS.rst
Closes #2453.
Changes proposed:
- Add a pull request template to make auto-closing issues easier.
> Add pull request template

- codecov.yml
Closes #2458.
- Ignore testing related folders and files in CodeCov config file.
> TST: Ignore tests in CodeCov config

- .coveragerc
Closes None. Fixes an oversight in #2463 (see https://github.com/nilearn/nilearn/pull/2463#issuecomment-631768686).
- Add omission patterns to skip testing-related files/folders in .coveragerc, so that tests are not counted toward coverage estimates.
> [TST] Add ignore patterns to .coveragerc

- CONTRIBUTING.rst
- nilearn/datasets/struct.py
> Remove deprecated `fetch_surf_fsaverage5` 

- README.rst
- doc/manipulating_images/manipulating_images.rst
- doc/modules/reference.rst
- doc/whats_new.rst
- nilearn/decomposition/base.py
- nilearn/decomposition/canica.py
- nilearn/decomposition/dict_learning.py
- nilearn/decomposition/multi_pca.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/tests/test_nifti_masker.py
- nilearn/masking.py
- nilearn/regions/parcellations.py
- nilearn/tests/test_masking.py
> FIXUP: rename Nilearn.masking.compute_gray_matter_mask

- doc/index.rst
Openess is the core value of nilearn and its community.
Cc @emdupre for review
> DOC: mission statement

- nilearn/stats/second_level_model/second_level_model.py
- nilearn/stats/tests/test_second_level_model.py
Closes #2408.
- Introduces target_affine and target_shape to Second_Level_Model
> Addressed #2408: Allow to set target_affine in SecondLevelModel

- examples/plot_first_level_model_details.py
- examples/plot_single_subject_single_run.py
- nilearn/reporting/_plot_matrices.py
Closes # 2405.
- Improve display of contrasts by basic matlplolib tweaks. The improvement can only be appreciated by looking at examples, in particular
* plot_single_subject_single_run.py
* plot_first_level_model_details.py
> tweaked contrast matrix display parameters

- doc/Makefile
- doc/conf.py
- doc/modules/reference.rst
- doc/themes/nilearn/static/nature.css_t
- doc/whats_new.rst
- nilearn/connectome/connectivity_matrices.py
- nilearn/datasets/func.py
- nilearn/datasets/neurovault.py
- nilearn/datasets/struct.py
- nilearn/decoding/decoder.py
- nilearn/decoding/space_net.py
- nilearn/image/resampling.py
- nilearn/input_data/nifti_masker.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/regions/rena_clustering.py
- nilearn/reporting/glm_reporter.py
- nilearn/stats/regression.py
- nilearn/stats/second_level_model/second_level_model.py
- nilearn/surface/surface.py
To have better rendering of attributes
Napoleon is a docstring-formatter maintained by sphinx, which is quite robust.
> DOC: Switch to napoleon

- .circleci/config.yml
small change suggested in discussion with circleci support. I will probably change a few details later but avoid non-essential changes while discussion with support is ongoing
> complete cache key

- doc/whats_new.rst
- nilearn/datasets/__init__.py
- nilearn/datasets/struct.py
> remove deprecated fetch_surf_fsaverage5 (announced for 0.7)

- doc/whats_new.rst
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_img_plotting.py
> reorder mni template when loading it in the plotting module

- nilearn/plotting/__init__.py
> BUG: Dont set backend on macOS

- nilearn/plotting/find_cuts.py
triggered some warnings in my code
> don't use is to compare strings

- doc/decoding/estimator_choice.rst
- doc/decoding/frem.rst
- doc/decoding/space_net.rst
- doc/modules/reference.rst
- doc/whats_new.rst
- examples/02_decoding/plot_haxby_frem.py
- examples/02_decoding/plot_mixed_gambles_frem.py
- nilearn/decoding/__init__.py
- nilearn/decoding/decoder.py
- nilearn/decoding/tests/test_decoder.py
Two PRs in one but everything documentation:
- Solving #2494 about FREM method case
- Adding some important things to whats new (Nistats functions in Nilearn, FREM and an example)
Ready for review
> [MRG] Renaming fREM => FREM + improving what's new

- nilearn/decomposition/base.py
Spotted to fix the master. See here: https://app.circleci.com/pipelines/github/nilearn/nilearn/1066/workflows/9aae6623-53f2-496e-ab65-434d41deec5c/jobs/6214
> Minor documentation issues

- doc/whats_new.rst
- nilearn/datasets/atlas.py
Closes #2516  .
- Update README
> FIX readme file of the Destrieux atlas

- nilearn/glm/__init__.py
- nilearn/glm/contrasts.py
- nilearn/glm/first_level/first_level.py
- nilearn/glm/model.py
- nilearn/glm/regression.py
- nilearn/glm/second_level/second_level.py
- nilearn/glm/thresholding.py
- nilearn/plotting/__init__.py
- nilearn/plotting/matrix_plotting.py
- nilearn/reporting/__init__.py
- nilearn/reporting/glm_reporter.py
> [MRG] Added glm-level warning

- .github/workflows/main.yml
Addresses #2508. Basically only revert deletion in #2507 
Not sure this will work.
> restore github workflow

- doc/whats_new.rst
> added highlight in whatsnew

- doc/themes/nilearn/layout.html
- doc/whats_new.rst
- Update news
- Add links to specific versions in `whats_new.html`
> Update news and add links to whats new

- nilearn/glm/tests/test_first_level.py
- nilearn/glm/tests/test_thresholding.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/surf_plotting.py
> use nilearn.image.get_data instead of nibabel.Nifti1Image.get_data

- .travis.yml
- continuous_integration/install.sh
Closes #2592 .
- Add tests for `matplotlib-dev` such as to anticipate upcoming failures (see #2592).
*Note: Not sure this is the best/cleanest way to do it, I'm open to suggestions*
> Add tests matplotlib dev

- doc/whats_new.rst
- nilearn/input_data/tests/test_nifti_labels_masker.py
- nilearn/masking.py
- nilearn/regions/tests/test_region_extractor.py
Closes #2580 .
- NaNs and Infs are represented as zeroes while defining data structures with int type. Converting to float reflects to the real-case scenario.
- Handle tests beyond x86_64 machines like aarch64.
See #2580 for more details.
> FIX testing issues with nans and infs on ARM

- .github/workflows/main.yml
> Remove the check URL step from github workflow

- examples/02_decoding/plot_haxby_different_estimators.py
> Fix example 9.3.12

- doc/decoding/decoding_intro.rst
- doc/whats_new.rst
- examples/02_decoding/plot_haxby_full_analysis.py
- examples/plot_decoding_tutorial.py
- nilearn/decoding/decoder.py
- nilearn/decoding/tests/test_decoder.py
Closes #2471  .
- Implementation of dummy option for classification and regression
- Tests
- Examples
> Dummy option in Decoder and DecoderRegressor

- AUTHORS.rst
- README.rst
Closes #2601  .
I have moved names listed in the README but not AUTHORS in a section "other contributors"; WDYT?
> move list of contributors from readme to authors.rst

- examples/02_decoding/plot_oasis_vbm.py
- examples/07_advanced/plot_haxby_mass_univariate.py
- examples/07_advanced/plot_localizer_mass_univariate_methods.py
- nilearn/decoding/tests/test_searchlight.py
- nilearn/mass_univariate/permuted_least_squares.py
- nilearn/mass_univariate/tests/test_permuted_least_squares.py
> [WIP] Add verbosity and progress to mass-univariate

- nilearn/_utils/niimg.py
- nilearn/image/image.py
- nilearn/input_data/base_masker.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/tests/test_niimg_conversions.py
Fixes #747 
**Description**
function `_repr_niimgs` now accepts a `shorten` boolean parameter to truncate display of niimgs (default is set to True). 
Truncated display was possible before (using `_utils.short_repr`) but not straightforward, and it was truncating on the repr rather than adapting to the type of data provided (see #747 for more details).
**Examples**
See also `test_repr_niimgs`
Previous behavior:
```python
from nilearn import _utils
print(_utils._repr_niimgs('/this/is/a/very/long/name/for/a/nifti/file'))
print("-"*80)
list_of_size_3 = ['/this/is/a/very/long/name/for/a/nifti/file',
'/this/is/another/very/long/name/for/a/nifti/file',
'/this/is/again/another/very/long/name/for/a/nifti/file']
print(_utils._repr_niimgs(list_of_size_3))
list_of_size_4 = …
```
> [ENH] Harmonize short repr of niimgs

- nilearn/plotting/__init__.py
Basic fix for #2465 
Better solution?
> Raise matplotlib import error instead of pytest

- nilearn/_utils/segmentation.py
- nilearn/tests/test_segmentation.py
See #938 
The added tests should fail before patch.
> [MRG] BugFix random walker with isolated seeds

- AUTHORS.rst
> Added some important contributors to the library

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Add a documentation improvement request to the issue templates
- Add a usage question link to *neurostars* in the issue templates (thanks @tsalo for the great idea! :+1: )
See #2629
> Add new issue templates

- nilearn/datasets/__init__.py
> Deprecate numpy arrays and bytes in datasets module

- .github/workflows/testing.yml
- README.rst
Update build badge since we are relying on Travis since #2633
> Enh update badges

- nilearn/datasets/atlas.py
- nilearn/datasets/tests/test_atlas.py
Closes #2665  .
- Post merge corrections in the difumo atlas fetcher as discussed at #2665
> Difumo corrections

- doc/whats_new.rst
Closes None, but references #2674.
- Add a line in `whats_new.rst` about the correction of a bug in 0.7.1.
> Document design matrix baseline fix in What's New

- nilearn/datasets/tests/test_neurovault.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/input_data/tests/test_nifti_maps_masker.py
> [MRG] Fix failures due to numpy 1.20

- nilearn/surface/__init__.py
- nilearn/surface/surface.py
- nilearn/surface/tests/test_surface.py
Following #2474 and as part of #2171, this PR
- adds a `Surface` namedtuple object, composed of a `Mesh` and texture data
- adds the related loading functions
- adds tests for these functions
Note: This is still WIP, any advice or suggestions are welcome! :smiley:
> [MRG] Add Surface object

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- doc/whats_new.rst
- nilearn/datasets/tests/test_neurovault.py
- nilearn/decomposition/tests/test_canica.py
- nilearn/input_data/tests/test_nifti_maps_masker.py
- nilearn/surface/__init__.py
- nilearn/surface/surface.py
- nilearn/surface/tests/test_surface.py
Closes #2629.
- Convert comments in issue templates to sections to be filled out.
- Add a couple of possible fields to the templates.
> Add fields/sections for issue information to templates

- nilearn/_utils/data_gen.py
> fix sampling in generate_fake_fmri_data_and_design

- doc/whats_new.rst
- nilearn/datasets/neurovault.py
- nilearn/datasets/tests/test_neurovault.py
This PR updates what have been done in #1557 by @nicofarr and related to issue #1553
What have been done here in addition to prior work:
- rebase on master and resolve conflicts
- modify the neurovault mock to allow a fake image download (discussed with @jeromedockes in #1557)
- get the test up to date with the neurovault mock and split it into multiple ones
> Resampling functionality for NeuroVault

- examples/02_decoding/plot_simulated_data.py
- nilearn/_utils/ndimage.py
- nilearn/_utils/param_validation.py
- nilearn/connectome/connectivity_matrices.py
- nilearn/datasets/utils.py
- nilearn/decoding/space_net.py
- nilearn/decoding/tests/simulate_graph_net_data.py
- nilearn/decoding/tests/test_fista.py
- nilearn/decoding/tests/test_graph_net.py
- nilearn/decoding/tests/test_same_api.py
- nilearn/decoding/tests/test_searchlight.py
- nilearn/decoding/tests/test_space_net.py
- nilearn/decoding/tests/test_tv.py
- nilearn/image/resampling.py
- nilearn/image/tests/test_image.py
- nilearn/input_data/tests/test_nifti_spheres_masker.py
- nilearn/masking.py
- nilearn/plotting/edge_detect.py
- nilearn/plotting/matrix_plotting.py
- nilearn/plotting/tests/test_matrix_plotting.py
- nilearn/regions/parcellations.py
- nilearn/regions/signal_extraction.py
- nilearn/tests/test_ndimage.py
Update some of the numpy types as to remove part of the deprecation warnings.
> [MAINT] numpy types deprecations

- nilearn/datasets/atlas.py
> [FIX] XML ElementTree iterator

- .github/workflows/testing.yml
- setup.py
Add Python 3.9 to build matrix.
Thanks to @emdupre for catching this! :+1: 
Note: Currently failing as expected. We need to merge #2751 before.
> [MAINT] Test with Python 3.9

- README.rst
I thought this could be useful. We can close this otherwise.
> Add Pypi badge

- doc/whats_new.rst
- nilearn/plotting/data/html/connectome_plot_template.html
- nilearn/plotting/html_connectome.py
- nilearn/plotting/tests/test_html_connectome.py
Closes #2733.
Changes proposed in this pull request: marker labels for the connectome plot.
-
-
> add marker labels to connectome plot

- examples/plot_single_subject_single_run.py
Fix a couple glossary broken references introduced in #2731
> [FIX] Fix glossary broken refs

- .circleci/config.yml
Fixes #2744 
Split the data cache on CircleCI (one per dataset, except very small ones which are combined).
> [MRG][MAINT] Split CircleCI data cache

- .github/workflows/main.yml
> Fix artifact redirect action

- doc/references.bib
- nilearn/decoding/decoder.py
Closes #2781 .
Replace citations with :footcite: tags, add corresponding entry to references.bib
-
-
> Use bibtex in nilearn/decoding #2781

- doc/whats_new.rst
Closes #2797 
- Remove :func: ReST tag
> DOC: fix ref in whats_new

- doc/conf.py
- doc/sphinxext/github_link.py
Closes #2776  .
- copy `github_link.py` from scikit-learn - this wraps the `sphinx.ext.linkcode` extension
- modify `doc/conf.py` to use this extension
> DOC: add links to github using sphinx.ext.linkcode

- examples/01_plotting/plot_3d_map_to_surface_projection.py
Closes #2818  .
- fix sphinx reference
-
> BUG: fix sphinx reference

- nilearn/plotting/surf_plotting.py
Fix the current CircleCI failure on master due to the docstring in `plot_surf` (see #2791)
> [FIX] Fix docstring in plot_surf

- examples/04_glm_first_level/write_events_file.py
Closes #2775  .
- add `plot_events` to example
> DOC: add plot_events to example

- doc/conf.py
Closes #2837.
- Changes call from `add_javascript` to `add_js_file` for latest sphinx 4 release
> [fix] patch add_javascript for sphinx4

- tools/circleci_dependencies.sh
Fixes doc building on CircleCI waiting for the issue to be fixed on sphinx's side. 
See #2842
> Pin sphinx version on circleCI

- nilearn/plotting/surf_plotting.py
> reduce default surf plot width and add the axes to the figure

- .github/workflows/pep8.yml
- .github/workflows/testing.yml
As running them as part of the Python 3.5 workflow was confusing.
> [MAINT] Put pep8 checks in dedicated workflow

- doc/references.bib
- doc/whats_new.rst
- nilearn/signal.py
This PR closes #2788
Adds proposed in this pull request:
- References within the file `signal.py` have been added to the references.bib file, and the docstrings have been updated.
Questions:
- Is [MRG] the right prefix to add if I think the PR can be merged directly?
- Shall I update the `whats_new.rst` file even when the contribution is that small?
Thank you :)
> [MRG] Add references to atlas.py

- nilearn/glm/first_level/experimental_paradigm.py
- nilearn/glm/tests/test_paradigm.py
> Rewrite the modulation warning as a print

- doc/themes/nilearn/layout.html
- doc/whats_new.rst
- nilearn/input_data/base_masker.py
- nilearn/input_data/multi_nifti_masker.py
- nilearn/input_data/nifti_labels_masker.py
- nilearn/input_data/nifti_maps_masker.py
- nilearn/input_data/nifti_masker.py
- nilearn/input_data/nifti_spheres_masker.py
- nilearn/signal.py
- nilearn/version.py
> Release 0.8.0

- nilearn/plotting/img_plotting.py
> Remove threshold from docstring of `plot_epi`

- nilearn/plotting/img_plotting.py
> [FIX] Fix thresholding of MNI152 template when plotting

- doc/whats_new.rst
Fix doc building on CircleCI due to broken link.
> [FIX] fix broken link

- nilearn/datasets/struct.py
Closes #1166  .
- Improve return argument doc string of function `fetch_icbm152_2009`
- Added related loaders and fetchers to See Also
> DOC: Fix return argument readable in ICBM fetcher doc string

- nilearn/glm/first_level/first_level.py
> fix comparison to string

- examples/03_connectivity/plot_multi_subject_connectome.py
- nilearn/_utils/niimg_conversions.py
- nilearn/connectome/group_sparse_cov.py
- nilearn/datasets/func.py
- nilearn/decomposition/base.py
- nilearn/image/image.py
- nilearn/plotting/displays.py
- nilearn/plotting/surf_plotting.py
- nilearn/reporting/html_report.py
Fixes some LGTM recommendations:
https://lgtm.com/projects/g/nilearn/nilearn/?mode=list&severity=recommendation
Please review carefully. Not sure about these, especially unused imports. Unused imports might have undocumented  side effects. If that's the case, they should be documented when importing, as is already the case elsewhere in the source code.
> [FIX] LGTM recommendations

- nilearn/__init__.py
- nilearn/decoding/decoder.py
- nilearn/decomposition/base.py
- nilearn/glm/first_level/first_level.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/matrix_plotting.py
- nilearn/reporting/_visual_testing/_glm_reporter_visual_inspection_suite_.py
- nilearn/tests/test_param_validation.py
Fixes some LGTM errors:
https://lgtm.com/projects/g/nilearn/nilearn/?mode=list&severity=error
> [FIX] LGTM errors

- nilearn/plotting/displays.py
This is a convention, not a requirement, but still...
> [FIX] use "cls" instead of "self" for @classmethod

- nilearn/_utils/niimg.py
Fixes some LGTM warnings:
https://lgtm.com/projects/g/nilearn/nilearn/?mode=list&severity=warning
> [FIX] LGTM warnings

- nilearn/datasets/struct.py
Just adds `stacklevel` to help people more easily find where they need to update their code.
> ENH: Add stacklevel

- doc/whats_new.rst
- nilearn/plotting/surf_plotting.py
- nilearn/plotting/tests/test_surf_plotting.py
> [FIX] Fix missing title in `plot_surf`

- build_tools/circle/dependencies.sh
Closes #2842 
Unpin sphinx now that 4.0.2 has been released.
> [MAINT] unpin sphinx version

- doc/decoding/searchlight.rst
Fixes typo introduced in #2951 making CircleCI fail on master.
> [FIX] Fix typo and full doc build

- CONTRIBUTING.rst
- doc/maintenance.rst
Fix broken doc build on circleCI due to recent merge of #2755
> [FIX] Fix sphinx errors in contributing docs

- nilearn/reporting/_get_clusters_table.py
- nilearn/reporting/tests/test_reporting.py
Closes #2955 
Thanks for reporting the bug @RaphaelMeudec ! :+1:
> [FIX] Fix `get_data` in `get_clusters_table`

- doc/themes/nilearn/layout.html
- doc/whats_new.rst
- nilearn/version.py
> Release `0.8.1`

- .github/workflows/auto-comment.yml
Closes #2962 .
- First draft of auto-commenting to support discussion on what its content should be.
Main hurdles : If we want to include a checklist as @tsalo proposed, it is hard to know which elements should absolutely be included.
> Automatic commenting on new PR

- AUTHORS.rst
Welcome @alexisthual ! :tada: 
PR also fixes the alphabetical order in core-dev list.
> [DOC] Update core-devs list

- .github/workflows/auto-comment.yml
Try a simple fix for the auto-comment action introduced in #2970 (See also #2982 and #2984).
@thomasbazeille : Looking at this [issue](https://github.com/wow-actions/auto-comment/issues/14), it seems like it is the recommended way to fix the issue. If it doesn't work, we can try #2984
> [INFRA] Fix auto-comment action

- doc/connectivity/region_extraction.rst
- doc/connectivity/resting_state_networks.rst
- doc/glossary.rst
- examples/03_connectivity/plot_compare_decomposition.py
- examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
- nilearn/datasets/description/msdl_atlas.rst
- nilearn/decomposition/dict_learning.py
This PR proposes to add `dictionary learning` to the glossary.
> [DOC] Add `dictionary learning` to glossary

- examples/03_connectivity/plot_compare_decomposition.py
Fixes broken reference that I introduced in #2988
> [FIX] Fix broken ref

- examples/01_plotting/plot_surface_projection_strategies.py
- nilearn/_utils/cache_mixin.py
- nilearn/_utils/niimg.py
- nilearn/datasets/func.py
- nilearn/externals/tempita/__init__.py
- nilearn/input_data/base_masker.py
Fix some LGTM.com recommendations:
https://lgtm.com/projects/g/nilearn/nilearn/?severity=recommendation
> [FIX] LGTM.com recommendations

- nilearn/_utils/data_gen.py
- nilearn/plotting/js_plotting_utils.py
- nilearn/reporting/glm_reporter.py
- nilearn/surface/surface.py
> [MAINT] LGTM.com recommendations

- AUTHORS.rst
Welcome @htwangtw ! :tada: 
The PR also proposes to add links to personal pages (I took the one attached to each person's GitHub profile, and the GitHub profile itself when no page was provided).
> [DOC] Update core-dev list

- examples/02_decoding/plot_miyawaki_encoding.py
- examples/02_decoding/plot_miyawaki_reconstruction.py
- examples/02_decoding/plot_simulated_data.py
Small PR fixing some scikit-learn deprecation warnings in a couple examples.
See https://github.com/scikit-learn/scikit-learn/pull/17750 and https://github.com/scikit-learn/scikit-learn/pull/17746
> [MAINT] Address some `scikit-learn` deprecations

- examples/03_connectivity/plot_signal_extraction.py
> [FIX] Fix example `fmriprep_confounds`

- examples/03_connectivity/plot_signal_extraction.py
Fix broken example in #3047 
I should have asked for a full build before merging...
> [FIX] Fix example

- examples/06_manipulating_images/plot_roi_extraction.py
Was supposed to be part of #3051 but I forgot to commit the changes for this example... :sweat:
> [MAINT] Numpy type deprecations

- nilearn/plotting/img_plotting.py
> [DOC] FIX typo

- doc/whats_new.rst
- nilearn/glm/second_level/second_level.py
- nilearn/glm/tests/test_second_level.py
This PR:
- Fixes #3041 
- Does some code refactoring
- Still WIP, probably needs more tests
> [FIX] Allow `DataFrame` as input for `non_parametric_inference`

- doc/decoding/going_further.rst
- examples/02_decoding/plot_haxby_multiclass.py
- examples/06_manipulating_images/plot_affine_transformation.py
- nilearn/datasets/description/adhd.rst
- nilearn/datasets/func.py
- nilearn/decoding/proximal_operators.py
- nilearn/decoding/space_net.py
- nilearn/decoding/tests/test_graph_net.py
- nilearn/glm/tests/test_utils.py
- nilearn/plotting/displays.py
- nilearn/plotting/glass_brain.py
- setup.cfg
- Remove repeated words from the documentation.
- Tell codespell not to look into `.git`.
> [DOC] Repeated words

- CONTRIBUTING.rst
- README.rst
Small PR to fix office hours in README, according to [this announcement on twitter](https://twitter.com/nilearn/status/1460273544353431556?s=20)
> Fix office hours in README

- .circleci/config.yml
- build_tools/circle/dependencies.sh
- doc/conf.py
Monitor memory usage when building docs, as suggested by @larsoner
> [INFRA] Add `memory_profiler`

- doc/connectivity/region_extraction.rst
- examples/03_connectivity/plot_extract_regions_dictlearning_maps.py
Small PR fixing some rendering issues and adding references to API and Glossary.
> [DOC] Fix rendering and add some refs in `region_extraction.rst`

- examples/01_plotting/plot_3d_map_to_surface_projection.py
- nilearn/datasets/func.py
- nilearn/plotting/img_plotting.py
- nilearn/signal.py
See https://lgtm.com/projects/g/nilearn/nilearn/alerts/
> [MAINT] Remove LGTM.com new alerts - mainly unused imports

- nilearn/signal.py
- nilearn/tests/test_signal.py
> [MAINT] Fix new typos found by codespell

- azure-pipelines.yml
> [INFRA] Fix typo in CI job name

- doc/conf.py
- doc/introduction.rst
- nilearn/__init__.py
- nilearn/_utils/cache_mixin.py
- nilearn/_utils/testing.py
- nilearn/conftest.py
- nilearn/image/resampling.py
- nilearn/plotting/displays/_slicers.py
- nilearn/plotting/glass_brain.py
- nilearn/plotting/img_plotting.py
- nilearn/plotting/tests/test_matrix_plotting.py
- nilearn/tests/test_cache_mixin.py
- nilearn/tests/test_masking.py
- nilearn/tests/test_package_installation.py
- nilearn/tests/test_signal.py
- nilearn/tests/test_version.py
- nilearn/version.py
Closes #3108 
Thanks to MNE folks for the fix. :+1: 
I'll add some unit tests for `_compare_version` once the CI is green again.
> [MAINT] `LooseVersion` deprecations

- nilearn/datasets/atlas.py
This PR proposes to improve the documentation for atlas fetchers, especially around their return values.
> [DOC] Improve documentation atlas fetchers

- doc/conf.py
> [MAINT] Fix `matplotlib` intersphinx URL
